### ISSUE TITLE
Author field sometimes displayed as kanji

### ISSUE THREAD

**Issue by Ortham** [wrye-bash/wrye-bash#10]
Bash's encoding checker sometimes displays mod header text (author field) in kanji instead of English. This could be due to slightly incorrect header values causing extra bytes to be interpreted as text, so check offsets.

**Comment by Infernio** [comment]
Feel free to reopen if anyone has a reproducer.

**Comment by Infernio** [comment]
Doesn't look likely, marking as works for me.
