### ISSUE TITLE
First Time Users Wizard Check

### ISSUE THREAD

**Issue by lmstearn** [wrye-bash/wrye-bash#108]
If a user installs a mod for the first time without running the wizard, an alert appears:

"Wizard supplied with mod. Wizard is recommended for first time installation. Do you really want to install? 
<Button Wizard>               Button <Install>
[Checkbox] Don't show me this again"

**Comment by lmstearn** [comment]
Pity, because the UI really doesn't "advertise" or "upsell" the usage of the wizards.

**Comment by Utumno** [comment]
Not now = back burner

**Comment by Infernio** [comment]
Doesn't sound all that difficult (hook the main Install button and add a popup if installer.hasWizard), so added good first issue, but yes this is 308+.

**Comment by Infernio** [comment]
Won't be needed anymore as of 900f991c4952edc41400c6d0b78fac2265562750, which introduces a 'smart' install command that shows any wizards first, then falls back to regular installation if none are available.
