### ISSUE TITLE
Huge lag when switching back to mods tab from another application

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#123]
I meant to post this in a while

Bash is virtually unuseable with my LO and my installers - whenever I switch to another application and back to Bash the lag is about 20 secs - and my machine is _fast_ - 20 seconds on this machine is clearly a bug
This is especially pronounced with my mods tab - 

I distinctly remember Bash was really snappy - the only thing that took time was refreshing the installers tab

Now even ctrl+Up/Down a mod in the LO takes ages.
This needs to be addressed ASAP - ideas ?

**Comment by Utumno** [comment]
@WrinklyNinja what is the state of this ?

Plus I want you to specify me exactly liblo.py API - I need to know exactly which methods/constants is the python side supposed to use, and I need them registered statically in module scope - I will do this but please specify me the API.

**Comment by WrinklyNinja** [comment]
> @WrinklyNinja what is the state of this ?
> 
> Plus I want you to specify me exactly liblo.py API - I need to know exactly which methods/constants is the python side supposed to use, and I need them registered statically in module scope - I will do this but please specify me the API.

`wrinklyninja-liblo-6-support` is ready to be merged, but could do with more testing. As for the API, I'm not sure what you mean. If you're going to be rewriting the Python wrapper, I've uploaded a PDF of libloadorder's API docs [here](https://www.dropbox.com/s/cm1lh8exmp57ovm/libloadorder%20v6.0.3.pdf?dl=0). Otherwise, everything in liblo.py is already in the Python side, so it's already "supposed to be used".

**Comment by Utumno** [comment]
@WrinklyNinja: I would expect to see an API comprised of 4 methods:

GetActive/LoadOrder(reload=False) # just return me the cached value if reload=False
SetActive/LoadOrder(pluginlist)

Am I missing some functionality if the API is reduced to this ?
What in the current liblo.py corresponds to this functionality ? Is there caching ? If not do I have to implement it on the Python side ?

**Comment by WrinklyNinja** [comment]
> Am I missing some functionality if the API is reduced to this ?

Yes.

> What in the current liblo.py corresponds to this functionality ?

`LibloHandle::GetLoadOrder`, `LibloHandle::SetLoadOrder`, `LibloHandle::GetActivePlugins`, `LibloHandle::SetActivePlugins`

> Is there caching ?

On the C++ side, yes. On the Python side, no.

**Comment by Utumno** [comment]
> Yes.

Could you elaborate on this please - I mean functionality used by Bash.

> On the C++ side, yes.

Not exposed on the python side ?

**Comment by WrinklyNinja** [comment]
> Could you elaborate on this please - I mean functionality used by Bash.

I don't know any more about what Bash actually uses than you do: Lojack originally wrote the Python wrapper, I just adapted it afterwards.

Not exposed on the python side ?

No. If nothing has changed, libloadorder will return the same data without any additional computation.

**Comment by Utumno** [comment]
@WrinklyNinja:

- ModInfos.refresh() [calls plugins.refresh()](https://github.com/wrye-bash/wrye-bash/blob/3cde04d7b0e6e9cd0c0fdf469acf10552c36b0a9/Mopy/bash/bosh.py#L4299) which for oblivion always returns True: https://github.com/wrye-bash/wrye-bash/blob/3cde04d7b0e6e9cd0c0fdf469acf10552c36b0a9/Mopy/bash/bosh.py#L3046. That is related with Bash taking ages to refresh even if nothing changed (which is the usual case) - see RefreshData

  So should I check on Bash level (by scanning modification times for the mods) or can Liblo answer if anything changed ? Or would it be enough to change thios line to `if lo.LoadOrderMethod != liblo.LIBLO_METHOD_TEXTFILE: return False` ?

- Is [cleanLoadOrderFiles](https://github.com/wrye-bash/wrye-bash/blob/3cde04d7b0e6e9cd0c0fdf469acf10552c36b0a9/Mopy/bash/bosh.py#L3117-L3130) still needed ?

- I am in the process of rewriting liblo - I want to have a python API that also features caching (as after all I can make educated assumptions as to when a refresh is needed and I don't need the overhead of the C calls at all). I am thinking of splitting the low level part of liblo to a _liblo.py module and leave the Python API (rewritten). Started here: 018c1b9ecc4744ea8f4ae59d6f321b0a1f464c5d. Feedback appreciated

**Comment by WrinklyNinja** [comment]
> So should I check on Bash level (by scanning modification times for the mods) or can Liblo answer if anything changed ? Or would it be enough to change thios line to if lo.LoadOrderMethod != liblo.LIBLO_METHOD_TEXTFILE: return False ?

Libloadorder will scan modification times to check if anything has changed, and return cached data if not.

> Is cleanLoadOrderFiles still needed ?

No, that should be handled by liblo.py's calls to `lo_fix_plugin_lists()`.

> I am in the process of rewriting liblo - I want to have a python API that also features caching (as after all I can make educated assumptions as to when a refresh is needed and I don't need the overhead of the C calls at all). I am thinking of splitting the low level part of liblo to a _liblo.py module and leave the Python API (rewritten). Started here: 018c1b9. Feedback appreciated

I have none to give. On a related note, I'm currently uninterested in contributing to Bash's development, because I find it utterly unrewarding and so I'd much rather do a host of other things with my leisure time. I will of course continue to maintain libloadorder and answer any questions regarding it.

**Comment by Utumno** [comment]
> Libloadorder will scan modification times to check if anything has changed, and return cached data if not.

Still I am not sure why it returns true here: https://github.com/wrye-bash/wrye-bash/blob/3cde04d7b0e6e9cd0c0fdf469acf10552c36b0a9/Mopy/bash/bosh.py#L3046 and why this comment ` return True # Until we find a better way, Oblivion always needs True`. What is the better way you suggest me ?

> On a related note, I'm currently uninterested in contributing to Bash's development, because I find it utterly unrewarding and so I'd much rather do a host of other things with my leisure time

Sorry to hear that

> I will of course continue to maintain libloadorder and answer any questions regarding it.

Glad to hear this

libloadorder fails to detect that the plugins txt is rewritten as detailed in #192 - I would like this fixed for 306 - it is a very useful Bash feature

**Comment by Sharlikran** [comment]
As of f8389b62cc9037754fd5071b6c8fe2bc09c14433 this seems to take 9-10 seconds on my computer with the installers I have in the Skyrim Bash Installers folder.

**Comment by Utumno** [comment]
After six full months I can finally sketch a roadmap:

- [ ] getOrdered should become O(n)
- [ ] tabbing out and back in to Bash should take minimal time 
- [ ] new liblo dll featuring timestamps caching - but see discussion in #187

That's for 306 - the refresh mechanism should be replaced by an event driven one and liblo expose its cache (as as it is now BOTH Bash and liblo _must_ stat the filesystem in case of change, and that's _a serious performance issue_) but those two warrant separate issues - 307+
