### ISSUE TITLE
Program Freeze: Deleting plugin via the interface

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#136]
bluesky404 is having an issue where trying to delete plugins through the interface are causing a program freeze, followed by the window changing to Not Responding, and crash.  Specifically this is happening with the Bashed Patch, I don't know if it happens with other plugins.  The plugin does get deleted, so it's something in the refresh afterwards that is freezing.

I have not been able to reproduce it at all, so maybe someone else can try.

He's tried:
- Delete the Bashed Patch straight away - freeze
- After restarting, a new blank Bashed Patch is generated.  Copy it via the interface, delete the copy - freeze

And other variations on copy and deleting, all leading to a freeze.

**Comment by Utumno** [comment]
I go with @jfpelland and close this - reopen as needed
