### ISSUE TITLE
Reading of Skyrim INI files

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#148]
Bash only reads the Skyrim.ini located in the user's directory.  However, the game will read "along-side" INI files as well.  For example, if there is a Dawnguard.ini, that will be loaded as well and override some settings in Skyrim.ini.
- [x] Determine the order that these along-side INI files are read - Is it alphabetical?  Is it the order their associated plugins are loaded (probably)?  Do inactive plugins still have their INI files read?  Also, these INI files are read if they're in the Data folder, do they also get loaded if they're in the My Games\Skyrim folder too?
- [ ] Implement routines to read the correct overriding INI file when looking for Skyrim.ini settings.

Right now there's one mod I know of that this affects: [Optimized Vanilla Textures](http://www.nexusmods.com/skyrim/mods/57353/?). In that case, there is a much better way for the mod to get its BSAs loaded, but the underlying problem is still there.

**Comment by Utumno** [comment]
What is the state of this ?

**Comment by Sharlikran** [comment]
Should be resolved by this commit https://github.com/wrye-bash/wrye-bash/commit/7e03c1003d0465f6c982c102517916eb07b70fd3

**Comment by Utumno** [comment]
Ok - this and other commits from the skyrim pull that are not directly patcher related I intend to merge before the rest. What about the item @lojack5 left unchecked ?

**Comment by Sharlikran** [comment]
@tony971 Does my current Experimental version still process the INI file for your mod as it did in previous versions?  Probably the best place to get my current version is from the [Fallout 4 Nexus](http://www.nexusmods.com/fallout4/mods/3699/?) as it is the aggregate compilation of all my changes and updates.

**Comment by tony971** [comment]
I released an update for Optimized Vanilla Textures based on this functionality. I wasn't expecting it to still be in an experimental phase.

**Comment by Utumno** [comment]
@tony971, @Sharlikran : does this mean that it is safe to merge ?

I guess the exp version you talk about is based on the 151-skyrim-patchers branch ? @Sharlikran: see comments in a4fa9f3a5d5aeef280bf30f42d96a0468e300d52 - I need the rebased branch to start merging

**Comment by tony971** [comment]
I'd like to have it merged as soon as possible. Until it makes its way into the release version, I'll include loose DLC strings as a workaround.

**Comment by Utumno** [comment]
@tony971: which version you tested with ?

**Comment by tony971** [comment]
I tested an alpha version when the patch was originally introduced but I suggested [this version](http://www.nexusmods.com/fallout4/mods/3699/?) to a user and they seemed happy with it.

**Comment by Utumno** [comment]
Lol - I didn't know this was up - @Sharlikran - what commit is this version based on ? Please from now on link to the commit in those changelogs (I guess the HEAD of  Sharlikran/wrye-bash : 268-fallout4-support ?)

**Comment by Sharlikran** [comment]
All of my versions are based off of https://github.com/Sharlikran/wrye-bash/tree/feature-sharlikran-valda-fallout.  The commit will always be different after I rebase everything.

**Comment by Utumno** [comment]
@Sharlikran: ok thanks - so 307.0.8 is based on https://github.com/Sharlikran/wrye-bash/commit/92f8107680aa489e551b1052ea7aa49e1d99784b upstream dev. Please rebase on current dev - see comments on https://github.com/wrye-bash/wrye-bash/commit/a4fa9f3a5d5aeef280bf30f42d96a0468e300d52

What I need you to do is include a link to the commit in https://github.com/Sharlikran/wrye-bash/tree/feature-sharlikran-valda-fallout your version is compiled from - as in:

307.0.8 (commit: https://github.com/Sharlikran/wrye-bash/commit/8e4ba5bafdddccafa8fe3e1e72dad3d9fc3b94a1)

**Comment by Utumno** [comment]
Just merged the inis stuff from @Sharlikran branch - @lojack5 I would like you to document the reading of skyrim files you said you figured out in the op - hashed up a method here: https://github.com/wrye-bash/wrye-bash/commit/d161022d250be4c0e4fd2a80b448a69c5b79c7e5

**Comment by Utumno** [comment]
@Arthmoor, @Sharlikran, @tony971 - is this working alright in latest 307 nightlies ? https://www.dropbox.com/sh/7b5ily482re0khs/AAD3vAWMVJNIpuS30tsdVte5a?dl=0

**Comment by Utumno** [comment]
@Arthmoor, @Sharlikran, @tony971 - this should be working alright in latest dev - _is it ?_

If you need a standalone try the latest 307 nghtlies: https://www.dropbox.com/sh/7b5ily482re0khs/AAD3vAWMVJNIpuS30tsdVte5a?dl=0

**Comment by Sharlikran** [comment]
Tony and I have already commented on it.  The code from the commits, which I have no Idea where they are now, work.  If it needs to be revised it can be revised.

**Comment by Utumno** [comment]
That code had numerous bugs performance and otherwise and was revised heavily - my question is if this works on current dev ?
