### ISSUE TITLE
Fallout support

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#150]
I am currently working on and testing changes in a test branch [dev-fallout-patcher-update](https://github.com/Sharlikran/wrye-bash/tree/dev-fallout-patcher-update).  Once I have enough code in place to make an organized and clean pull request I will be basing the pull request off of [feature-fallout-support](https://github.com/wrye-bash/wrye-bash/tree/feature-fallout-support).

As refactoring progresses I will update the code to match the new layout and directory structure.

Tasklist
- [x] Update and verify all records for Fallout 3
- [x] Update and verify all records for Fallout New Vegas
- [ ] Update complex records from FO3/FNVEdit to simple records when applicable
- [x] Add additional patcher routines such as `class FidListsMerger`
- [ ] Update Fallout Patcher support

Patchers to update:
- [ ] class ActorImporter
- [ ] class DeathItemPatcher
- [x] class FidListsMerger
- [x] class GraphicsPatcher
- [ ] class ImportActorsSpells
- [x] class ImportFactions
- [x] class ImportInventory
- [x] class ImportRelations
- [ ] class ImportScripts
- [ ] class KFFZPatcher
- [ ] class ListsMerger
- [x] class NamesPatcher
- [ ] class NPCAIPackagePatcher
- [ ] class NpcFacePatcher
- [ ] class PatchFile
- [ ] class PCFaces
- [ ] class RacePatcher
- [x] class SoundPatcher
- [ ] class SpellsPatcher
- [x] class StatsPatcher

Utilities:
- [x] class ActorFactions
- [ ] class ActorLevels
- [ ] class CompleteItemData
- [ ] class EditorIds
- [x] class FactionRelations
- [ ] class FidReplacer
- [x] class FullNames
- [ ] class IngredientDetails
- [x] class ItemStats
- [x] class ItemPrices
- [ ] class ScriptText
- [ ] class SpellRecords
- [ ] class _UsesEffectsMixin

Needs to be clarified or investigated:

Check readClasses, writeClasses
Update for Fallout UOPs
Prevent randomly adding Forms

Branch used in this pull request:

[dev-fallout-patcher-update](https://github.com/Sharlikran/wrye-bash/tree/dev-fallout-patcher-update)

```
dev
   \ dev-skyrim-patcher-update
                              \ dev-fallout-patcher-update
```

**Comment by Sharlikran** [comment]
@Utumno Do you know how to keep PyCharm from opening when you build a test release with the Script?

**Comment by Utumno** [comment]
@Sharlikran: I don't understand - when does it open - which script ?

**Comment by Sharlikran** [comment]
When I run package_for_release.py when I see it say generating comtypes, PyCharm opens.  Now it may be slightly before or after that.  It could also be another file the script accesses because the script is long and complex.  However, that's what I see in the DOS window when it happens.

**Comment by Utumno** [comment]
Yep something in your setup - not happening here - consider reinstalling pycharm and run the script _from_ it ;)

Now back to business

**Comment by Utumno** [comment]
By the way never associate .py files with an editor - I do sympathize though - I still double click once in a while on a .py file expecting to open in the editor and I instead see cmd flush - well...

**Comment by Sharlikran** [comment]
Commit b583e1202f1f0b587ff8856dfdefd809cab84a81 will no longer rebase without resolving changes.  I no longer wish to try and follow the changes.  I'll leave this open as it is something that needs to be done but I won't be working on it.

**Comment by Utumno** [comment]
Point me to the branch you want rebased - I can do it most probably

**Comment by Sharlikran** [comment]
Branch used in this pull request:

[dev-fallout-patcher-update](https://github.com/Sharlikran/wrye-bash/tree/dev-fallout-patcher-update)
```
dev
   \ dev-skyrim-patcher-update
                              \ dev-fallout-patcher-update
```

You don't have to but this branch has changes based off of the dev-skyrim-patcher-update branch.  That way the fallout changes are separate.

**Comment by Utumno** [comment]
Will do later

**Comment by Utumno** [comment]
And done: https://github.com/wrye-bash/wrye-bash/tree/dev-sharl-fallout :)

please pull to your repository ASAP and let me know so I can delete from here

**Comment by Sharlikran** [comment]
How do I do a pull like you are asking?

Normally I do this:

git fetch upstream
git fetch upstream --prune
git checkout dev
git rebase upstream/dev
git push -f origin dev

That gets me dev.  I don't know how to pull those two branches.  I want to comapre the branches before I add them to my branches used in the pull request.  However, I also don't know how to say replace branch dev-fallout-patcher-update with branch dev-sharl-fallout.  How do I do that?

**Comment by Utumno** [comment]
Pull dev as you do then

git fetch upstream dev-sharl-fallout
git checkout -b dev-sharl-fallout FETCH_HEAD

then go to gitk to see the branches

In gitk you can right click on a commit and compare it with selected commit: http://stackoverflow.com/questions/13715710/using-gitk-can-i-see-the-difference-between-2-commits/17549542#17549542

Reset the branch: in gitk, right click in dev-fallout-patcher-update's green dev-fallout-patcher-update tag and choose "checkout this branch". Then right click on the dev-sharl-fallout head commit and choose Reset dev-fallout-patcher-update barnch to here - then in the dialog choose hard. Tip: there is a right click option that reads 'create new branch" - use this to create a tmp branch pointing to the dev-fallout-patcher-update before you reset it to be double sure.

**Comment by Sharlikran** [comment]
delete dev-sharl-fallout

**Comment by Sharlikran** [comment]
'''Python
Wrye Bash startingUsing Wrye Bash Version 306.0.25Python version: 2.7.3wxPython version: 2.8.12.1 (msw-unicode)input encoding: None; output encoding: None; locale: ('pl_PL', 'cp1250')filesystem encoding: mbcsSearching for game to manage:bush.py   84 _supportedGames: Detected the following supported games via Windows Registry:bush.py   86 _supportedGames:  fallout3: F:\install\steam\steamapps\common\Fallout 3 gotybush.py   86 _supportedGames:  falloutnv: F:\install\steam\SteamApps\common\Fallout New Vegas enplczrubush.py   86 _supportedGames:  oblivion: D:\oblivionbush.py   86 _supportedGames:  skyrim: F:\install\steam\steamapps\common\Skyrimbush.py  144 _detectGames: Detecting games via the -o argument, bash.ini and relative path:bush.py  150 _detectGames: Set game mode to falloutnv based on sOblivionPath setting in bash.ini:  F:\install\steam\SteamApps\common\Fallout New Vegas enplczrubush.py  184 setGame: No preferred game specified.bush.py  165 __setGame:  Using falloutnv 
game: F:\install\steam\SteamApps\common\Fallout New Vegas enplczrutesting UACbosh.py 5236 __init__: Using libbsa API version: 2.0.0bosh.py 5242 __init__: Using LOOT API version: 0.7.0load_order.py  253 <module>: Using libloadorder API version: 4.0.1Traceback (most recent call last):  File "bash\balt.py", line 1769, in _conversation_wrapper    return func(*args, **kwargs)  File "bash\basher\__init__.py", line 4069, in RefreshData    self._corruptedWarns()  File "bash\basher\__init__.py", line 4161, in _corruptedWarns    message, liststyle='list', canCancel=False)  File "bash\balt.py", line 1181, in Display    with cls(*args, **kwargs) as dialog:  File "bash\balt.py", line 2763, in __init__    checksCtrl = listBox(self, choices=strings, isHScroll=True)  File "bash\balt.py", line 471, in listBox    gListBox = cls(parent, choices=choices, style=style) if choices else cls(  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line 1290, in __init__    _control
s_.ListBox_swiginit(self,_controls_.new_ListBox(*args, **kwargs))TypeError: String or Unicode type required
'''
I know this is my branch but I don't know what to make of this error.  It's probably a plain old bug. However, it might be because you changed a core routine and these older routines are passing the previously required arguments.

I have a simular with modinfos.ordered because there is no ordered attribute in modinfos anymore. That's why I'm thinking my branch is using older syntax.

Can you take aook please? The user can't use your 306 branch because it doesn't have Fallout support.

**Comment by Utumno** [comment]
Yep it's my changes but I have no time to look at what fails in the fallout code now (pun)

I may have a look - collect a couple more tracebacks, would help

I was thinking lately that the time has come to seriously start thinking of merging the fallout code in - the tracebacks here are just the tip of the iceberg though (and not because they are from latest changes), so that's clearly 307

**Comment by Sharlikran** [comment]
Well then what do we do? I understand it's partially from your changes and that it only happens for Fallout.  However, it's probably not Fallout specific. So once you release 306 however this would happen for Oblivion or Skyrim it's gonna happen.

**Comment by Utumno** [comment]
It's Fallout specific

**Comment by Sharlikran** [comment]
Then I'll have to try and find it thanks.

**Comment by Utumno** [comment]
Not now I'd say - concentrate on the release please - we can't really start looking at fallout support at release time can I ? What I am doing _is not easy_ please remember this

**Comment by Utumno** [comment]
Plus this is rebased on dev - does not even use my dll - I clearly said I want no reports from/rebases on dev

**Comment by Utumno** [comment]
Hey Sharl - now that release is almost out I had a look at this - I fixed the traceback by insane plumber and rebased your work on current dev (which will change soon but I expect no conflicts):

https://github.com/wrye-bash/wrye-bash/compare/sharlikran-fallout-skyrim-rebase-on-dev

Pull it to your fork and test if the traceback here (`TypeError: String or Unicode type required`) is still present (results from corrupted mods, ListBoxes code is further changed since)
Point your feature-sharlikran-valda-fallout to this one - they are identical (apart from my couple commits, and the ones I absorbed to dev - taglists and .manifest skip)

Thanks :)

**Comment by Utumno** [comment]
Added a commit fixing another error introduced by the rebase: https://github.com/wrye-bash/wrye-bash/commit/8d51cdec5809c5da3c2839a75e68b3b2da9fe82f

Coming to speak of one of the first things to address in 307 is the imports policy on those files - we must work close on this together.

Namely I want: star imports in those files (`game/__init__.py`) gone:
https://github.com/wrye-bash/wrye-bash/commit/5cd1c6197ec5e0c061b128b177734782ca04106a

**Comment by Utumno** [comment]
An error in ImportRelations reported here:

http://forums.bethsoft.com/topic/1509287-wipz-wrye-bashexp-skyrim-patcher-update-thread-2/?p=24281296

[quote name="Old Nick" post="24281296" timestamp="1440705733"]
Using the version from that link, I get the following error when trying to build the Bashed Patch for Fallout 3:
[spoiler]
```
Dumping: AndaleResidentFaction 107310 <bash.brec.MelStructs instance at 0x051BD648>
> header: <bash.game.fallout3.records.RecordHeader object at 0x15ADBDB0>
> recType: 'FACT'
> fid: 107310L
> flags1: <bash.bolt.Flags object at 0x15ADBD90>
> size: 74
> flags2: 0
> changed: True
> subrecords: None
> data: None
> inName: bolt.Path(u"Mart's Mutant Mod.esm")
> longFids: False
> eid: u'AndaleResidentFaction'
> full: None
> relations: [<bash.brec.MelObject object at 0x15ADBD10>, <bash.brec.MelObject object at 0x15ADBD50>, <bash.brec.MelObject object at 0x1086E610>]
> flags: <bash.bolt.Flags object at 0x15ADBD30>
> flagsFact: 1
> unknown: '\x00\x00'
> crimeGoldMultiplier: None
> ranks: []
Traceback (most recent call last):
  File "bash\balt.pyo", line 1777, in _conversation_wrapper
  File "bash\basher\patcher_dialog.pyo", line 224, in Execute
  File "bash\bosh.pyo", line 530, in safeSave
  File "bash\bosh.pyo", line 550, in save
  File "bash\record_groups.pyo", line 204, in dump
  File "bash\record_groups.pyo", line 194, in getSize
  File "bash\record_groups.pyo", line 194, in <genexpr>
  File "bash\brec.pyo", line 1595, in getSize
  File "bash\brec.pyo", line 1686, in dumpData
  File "bash\brec.pyo", line 1263, in dumpData
  File "bash\brec.pyo", line 1045, in dumpData
  File "bash\brec.pyo", line 982, in dumpData
AttributeError: 'MelObject' object has no attribute 'groupCombatReaction'
```
[/spoiler]Do you have any idea what's wrong?
 
The Bashed Patch builds without error if I completely deselect "Import Relations" in the left pane of the rebuild patch dialogue box
 
Here's my mod list:[spoiler]
[code=xml:0]00  Fallout3.esm
01  Anchorage.esm
02  ThePitt.esm
03  BrokenSteel.esm
04  PointLookout.esm
05  Zeta.esm
06  Unofficial Fallout 3 Patch.esm  [Version 1.9]
07  CRAFT.esm
08  CALIBR.esm  [Version 1.4]
09  FO3 Wanderers Edition - Main File.esm
0A  Mart's Mutant Mod.esm
0B  Project Beauty.esm
0C  EVE.esm  [Version 0.99]
0D  FO3 Wanderers Edition - Main File.esp
0E  FO3 Wanderers Edition - Optional Restore Tracers.esp
0F  Mart's Mutant Mod - Project Beauty.esp
10  Project Beauty- Point Lookout.esp
11  FO3 Wanderers Edition - Followers Enhanced (BrokenSteel).esp
12  Project Beauty- Broken Steel.esp
13  FO3 Wanderers Edition - DLC Broken Steel.esp
14  FO3 Wanderers Edition - DLC Anchorage.esp
15  FO3 Wanderers Edition - DLC Point Lookout.esp
16  FO3 Wanderers Edition - DLC The Pitt.esp
17  FO3 Wanderers Edition - DLC Mothership Zeta.esp
18  GlowingGhouls-MMM.esp
19  Bashed Patch, 0.esp[/code]
[/spoiler]
 
Mart's Mutant Mod.esm is from the [url=http://www.nexusmods.com/fallout3/mods/16787/]Paradox Ignition Merged[/url] version of [url=http://www.nexusmods.com/fallout3/mods/3211/]Marts Mutant Mod - RC 62[/url], in case that matters
 
Thanks in advance for any help you can give  :smile:
[/quote]

**Comment by Sharlikran** [comment]
I won't be able to resolve that at this time.  He should be using Valda's version no the experimental version.

**Comment by Utumno** [comment]
Yep - no prob Sharl - I am just posting it here so when I turn the eye to Fallout I won't have to dig in the forums

Btw that's what I need you to do also - if something is proven to be a bug carry it here from the forums

Get well soon :)

**Comment by Sharlikran** [comment]
You changed more then what you mentioned in a4fa9f3a5d5aeef280bf30f42d96a0468e300d52.  You changed how links.py calls bass.tooldirs instead of bosh.tooldirs.  I about had another moment.  :laughing: It's all good though I was able to rebase everything.

**Comment by Utumno** [comment]
:+1:

**Comment by Utumno** [comment]
Put to the backburner - fallout3 is post 307

**Comment by Sharlikran** [comment]
@Utumno Which branch should I fork off of for FO3/FNV, feature-sharlikran-valda-fallout?

**Comment by Utumno** [comment]
@Sharlikran https://github.com/wrye-bash/wrye-bash/tree/feature-sharlikran-valda-fallout but needs rebase on dev

**Comment by Sharlikran** [comment]
@Utumno rebased on dev. Both FO3 and FNV versions will start, and go to the mods tab. I didn't test further then being able to run the program.

**Comment by Utumno** [comment]
Hey thanks - where is the rebased branch ?

**Comment by Sharlikran** [comment]
It's the same branch name you had, feature-sharlikran-valda-fallout.

I'm still working on it through. I wanted to import from fallout 3 and when I do some things can't be imported or they error.

**Comment by Utumno** [comment]
There are some of my commits missing ?

**Comment by Sharlikran** [comment]
Nothing is missing. Compare it to your upstream branch.

**Comment by Sharlikran** [comment]
> Squashed several commits which rewrote the history which also included assigning Valda to his commits. You are the git wizard and you will have to pull in the changes.

There it is, I though maybe I didn't explain what I did but my above does explain the changes. I though I wasn't reading correctly for a moment when you asked what happened.

**Comment by Sharlikran** [comment]
There about 2,005 lines of code removed importing Fallout 3 records.

**Comment by Sharlikran** [comment]
If you just want your branch rebased: [dev-sharlikran-valda-fallout](https://github.com/Sharlikran/wrye-bash/tree/dev-sharlikran-valda-fallout) but that has no changes except removing the Fallout 4 files since they are already taken care of in dev.

However, after squashing and rebaseing the [feature-sharlikran-valda-fallout](https://github.com/Sharlikran/wrye-bash/tree/feature-sharlikran-valda-fallout) it's much cleaner, has all your changes, and other changes.

**Comment by Sharlikran** [comment]
just made sure feature-sharlikran-valda-fallout was still rebased on dev

**Comment by Utumno** [comment]
Can you link me to that please. Chopping off dup code is always more than welcome

**Comment by Sharlikran** [comment]
Yes that is the branch. However, again going forward all code for submission into dev will be prefixed with `dev-` and rebased off of dev.  Currently the feature branch and the two pull requests are not named that way.

I understand you will get to this after beta2, that's not a problem. It does however have NSI Installer Info.

**Comment by Utumno** [comment]
@Arthmoor:

- Updates to those games are via steam or is there a patch url like in Oblivion ?
- Archive invalidation applies here ? If so we should enable it via `bsaRedirection = (u'Archive',u'sArchiveList')`
- what are the patch versions we support for those games (to add to the main readme.md) ?

Meanwhile redownload please as me and Ganda threw some more refactoring in there - should be final. Please test in particular that FOSE/NVSE cosaves are treated ok, stats displayed etc

**Comment by Arthmoor** [comment]
New Vegas was released via Steam so all the updates came through there. They haven't patched it in years though as usual for them. It's also available on GoG now but I don't think where it comes from matters much.

Fallout 3 was originally a GFWL title but is also available now via Steam and GoG. Also hasn't been patched in ages so we won't need to worry about that.

Archive Invalidaton still applies for both titles so that needs to get added. Should be done just like it was for Oblivion.

I'll check on specific patch versions and the NVSE/FOSE stuff when I get a chance later. I still haven't set either of those up for these games since I'm not actually playing them anymore.

**Comment by Utumno** [comment]
Thanks @Arthmoor - added AI back waiting for the patch versions

**Comment by Utumno** [comment]
Ok new branch - please use this one:

https://github.com/wrye-bash/wrye-bash/tree/150-fo3-fnv-support

https://github.com/wrye-bash/wrye-bash/archive/150-fo3-fnv-support.zip

**Comment by Arthmoor** [comment]
Last patch versions:

NV: 1.4.0.525
FO3: 1.7.0.3

Both as reported by the in-game UI.

**Comment by Utumno** [comment]
More TODOs - wiki etc

https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=171914

**Comment by Infernio** [comment]
@Utumno Should we reopen this so I have something to reference for the patchers that I'm updating? Or should I make a new 'Update Fallout Patchers' issue for that?

**Comment by Utumno** [comment]
What' easier for you @Infernio - probably a new one you have control over OP?

**Comment by Infernio** [comment]
The 'update patchers' part of this issue is superseded by #468.
