### ISSUE TITLE
CBash_GlobalTweaks are not applied

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#160]
As far as 304.4
- Built a CBash patch
- Select _manually_ (because of #114) the thieves guild, timescale and Crime:Jail tweaks (the globals)
- Build the patch - they are nowhere to be seen in the logs

Workaround:select them manually and change their value

@lojack5 is this related to #114 ?

EDIT: selecting the _defaults_ manually has no effect also...
EDIT2: or is this to be expected because those are the defaults (well no I guess)

Note to self: The global tweakers are here

```
---------- Mopy/bash/patcher/oblivion/patchers/multitweak_settings.py ----------
index 7a7d3c6..2901b6e 100644
@@ -296,2 +296,3 @@ def initPatchFile(cls,patchFile,loadMods):
             if isinstance(tweak,CBash_GlobalsTweak):
+                print tweak
                 tweak.count = 0
```

**Comment by Utumno** [comment]
@Sharlikran can you verify this ?

**Comment by Sharlikran** [comment]
I don't know if I can confirm that.  I can try to just build a patch but I have never played Oblivion.  Let me ask around for help.

**Comment by Utumno** [comment]
Trying to debug this I run across:
```
Traceback (most recent call last):
  File "bash\basher\patcher_dialog.py", line 188, in Execute
  File "bash\patcher\patch_files.py", line 597, in buildPatch
  File "bash\patcher\patchers\multitweak_settings.py", line 63, in apply
  File "bash\cint.py", line 10703, in get_eid
    return IUNICODE(_unicode(retValue)) if retValue else None
  File "bash\cint.py", line 66, in _unicode
    return _uni(text,*args,**kwdargs)
  File "bash\bolt.py", line 106, in _unicode
    try: return unicode(text,encoding)
TypeError: coercing to Unicode: need string or buffer, LP_c_float found
```

Moreover this does not happen consistently...

**Comment by Utumno** [comment]
Well turns out it is expected behavior - the line:

                if record.value != value:

in the pathcher: https://github.com/wrye-bash/wrye-bash/blob/6b63bbb2f1afed8aed2ed43e3efcecb68d9525a2/Mopy/bash/patcher/patchers/multitweak_settings.py#L66 prevents the tweak to be applied if the value is the same as the one in the (Oblivion.esm) record - the defaults are the vanilla values apparently. Closing

**Comment by Infernio** [comment]
This is indeed intended behavior - namely, to prevent ITMs and ITPOs from making their way into the BP.
Since b25727b6ba2210289aa77a6c4ad288af74c55ae5, PBash also behaves this way, so marking as R-invalid for the benefit of anyone wondering about this in the future.
