### ISSUE TITLE
Bash loads an invalid plugins.txt without notifying the user of the error.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#162]
Wrye Bash (presumably all versions) has a somewhat critical bug when the program loads.

If another mod manager (MO or NMM apparently) has allowed a user to select more than 254 plugins as active, Bash does not inform the user of this problem until an attempt is made to build a bashed patch.

Bash should instead validate the contents of plugins.txt to ensure that there are not too many activated mods when starting up. Some kind of notification should be made that this is not a valid state.

The program should then offer to either close down without touching anything, or to deactivate enough plugins to bring it back under the limit.

Also quite possible that bugs need to be filed with the MO and NMM trackers to address this problem as it means those tools are allowing invalid states to be passed to the games they manage which will lead to CTDs on startup.

**Comment by Utumno** [comment]
@WrinklyNinja : taking over - I need to be bale to warn the user and (later) backup the plugins txt, a silent fix is not a solution

@Arthmoor - added the warning in my last commit - should close this - please test 306.201506040253

**Comment by WrinklyNinja** [comment]
> @WrinklyNinja : taking over - I need to be able to warn the user and (later) backup the plugins txt, a silent fix is not a solution

Since you've already forked libloadorder, you can add a return code for when the file has been fixed.

**Comment by Utumno** [comment]
> Since you've already forked libloadorder, you can add a return code for when the file has been fixed.

Yeah thanks - I need to have what was in there - Bash used to display exactly which plugins were deactivated (the commit above addresses a TODO in the code that is 3,5 _years_ old). Plus I would like to backup the plugins file before it was edited.

As for my fork - my C++ is rather rusty, so I would rather we did this together - have a look at my commits in my fork. Alternatively I could just do the whole stuff in Python again, easier for me (still not easy ofc) but not community friendly. I am willing to aid in loadorder - cause I am one of the main and probably the most demanding client. Still I find many things there unsatisfactory: performance (at times Bash just has all the data already and restating the filesystem is simply a nono, or validating existence of the plugins twice etc), the size of the dll (both for downloads and the repository) and most importantly the API (for instance get/set _single_ plugin index should not be part of the API and fix_load_order should be an output parameter - there is more but hey I have my 80k lines of python to feed). Plus the design  decision to give priority to loadorder.txt over the plugins.txt (which is the one the game knows) should be revisited.

I do consider bypassing most of it for 306 cause I want it out and simply I do not have time to debug C++ - took time enough to set it up. My python code then can be ported bacj\k to C++. Meanwhile dropping the boost dependency I think is the only way to reduce the dll size - IIUC.

**Comment by WrinklyNinja** [comment]
> Still I find many things there unsatisfactory

It sounds like libloadorder's design and your own ideas for an API for Bash's use are just plain incompatible.

1. libloadorder is designed to provide a complete solution to load order management, and assumes the client knows nothing of load order, so it has safety (eg. filesystem) checks and loads and caches its own data. Yes, there is a performance hit, but those features are necessary for effective black-boxing.
2. The library is ~ 240 KB when compressed, I doubt users are worried about downloading that. As for storing the DLL in the repository, that's not exactly best practice.
3. I see no reason for disallowing a single plugin's position to be set.
4. That design decision is because loadorder.txt generally offers the most complete load order available, including positions for inactive plugins (which are important for Bash's merging functionality). Libloadorder could merge loadorder.txt and plugins.txt, using the latter's positions for conflicts, but that's more complex and I have yet to see the need for that.

You're effectively asking for a wholesale rewrite of libloadorder, which I'm not going to do, because I haven't had any complaints (aside from bugs which have since been fixed) from the NMM devs, and changing everything would give me more work I don't see as necessary, and make their lives more difficult in having to adapt to that change.

**Comment by Utumno** [comment]
> You're effectively asking for a wholesale rewrite of libloadorder, which I'm not going to do, because I haven't had any complaints

Fair enough.
Black boxing is certainly not for Bash, re: size and repo I know (#199) - 240 k is still big I think.
Re 3 it's a design choice I disagree with, having worked a lot with LO lately (leads to bugs and makes no sense, there is no LO of a single plugin if you come to think about it) - would make your life easier to drop it.
Re 4 - I know the rationale - no, merging loadorder.txt and plugins.txt would be a mistake.

> and make their lives more difficult in having to adapt to that change.

My point would be that it would be easier to change things now than later - do they use the get/set plugin methods ?

Anyway do have a look at my commits, will post more when I get round to it. 

Btw two questions:

- when no loadorder.txt exists there should be one created when Bash runs ?
- what does Oblivion do when two plugins have the exact same mod time (two esps or two esms) ?

**Comment by Arthmoor** [comment]
Wait, what? A 240KB file is too big?

**Comment by Utumno** [comment]
Compared to the Universe ?

**Comment by Arthmoor** [comment]
You've said that the dll file is big. It's 240K. I'm not sure why that's considered "big" by any definition. That's less than half a second's worth of bandwidth or something.

Anyway, for your questions:

Yes, if loadoder.txt doesn't exist it should be generated.

If two plugins have the exact same timestamp, the game will load them in randomly chosen order. Obviously not a good thing if they need to be arranged a certain way.

**Comment by Utumno** [comment]
The 240 kb is technical forget it.

Thanks for answering - I would hope that it was not random, Bash resolves this by ordering alphabetically.

Did you try the newest version with more than 255 plugins (if I get it right it's 255 entries in plugins.txt for  Oblivion and 254 for Skyrim right ?)

**Comment by Sharlikran** [comment]
![image](https://cloud.githubusercontent.com/assets/1912426/8074988/ccbe8e84-0eee-11e5-98e3-d38cb162b22a.png)
Just saw that when I loaded your Wip version.  If that is intentional and something you added please, make sure it does that consistently.  That is very informative and useful.
