### ISSUE TITLE
UnicodeDecodeError on tmp dir creation when username contains non ascii chars

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#180]
Pull request #142 added a force for UTF8.  It might have worked well enough for @valda but unfortunately for [KiraHanato on the Nexus](http://forums.nexusmods.com/index.php?/topic/478460-wrye-bash/page-261#entry21127824) it causes the following error.  I don't think He tried the EXE installer.  When he attempted to use the python version [he had these errors](http://forums.nexusmods.com/index.php?/topic/478460-wrye-bash/?p=21228409).

For 305:

Traceback (most recent call last):
File "bash\bolt.pyo", line 286, in initTranslator
File "gettext.pyo", line 180, in __init__
File "gettext.pyo", line 337, in _parse
LookupError: unknown encoding: CHARSET

For 306:

No Traceback has been provided because there is a limited log file created.

Wrye Bash starting
Using Wrye Bash Version 306
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('ja_JP', 'cp932')
Searching for game to manage:
bush.pyo   81 detectGames: Detected the following supported games via Windows Registry:
bush.pyo   95 detectGames: Detecting games via relative path and the -o argument:
bush.pyo  144 setGame: No preferred game specified.

Screen Shot of his Region and Language settings.
![default](https://cloud.githubusercontent.com/assets/1912426/5592802/a5987636-9198-11e4-9963-be7ceb16fa8d.jpg)

Just getting a link from his for the screen shot gave these three different encodings.
```Python
http://www.mediafire.com/view/kaj3a61xh1ge4nn/%E7%84%A1%E9%A1%8C.png#
http://www.mediafire.com/view/kaj3a61xh1ge4nn/無題.png#
http://www.mediafire.com/view/kaj3a61xh1ge4nn/ç„¡é¡Œ.png#
```

His initial error was:

```Python
Traceback (most recent call last):
File "bash\bash.pyo", line 455, in main
File "bash\bosh.pyo", line 24205, in testUAC
File "bash\bolt.pyo", line 1168, in tempDir
File "tempfile.pyo", line 331, in mkdtemp
File "ntpath.pyo", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7: 
```
He switched to a non unicode English codepage which made wrye bash work after restarting but when he tried to start the game it caused Skyrim to start up in 640x480 windows mode English.

**Comment by Sharlikran** [comment]
@WrinklyNinja @Utumno After looking at the information, especially the log file where it says cp932, I don't think this has anything to do with pull request #142.

What can I change the title to?  Any suggestions?

**Comment by Utumno** [comment]
Thanks for posting this Sharl: the pull request is merged very recently so the user is not having a problem with that

Would be nice if she could install the latest dev version (after solving the dependencies issues) to actually test the pull request

As for her problem it should be some unicode char in the temp directory path - `C:\Users\USERNAME\appdata\local\temp\WryeBash_XXXXXX` should be the error - I bet the USERNAME is the culprit - the first character of it should be the 0x82

**Comment by Sharlikran** [comment]
> Would be nice if she could install the latest dev

That is what HE is using.  I made a standalone to help out so that he didn't have to fight with the python version.

I'll tell him about the temp folder.

**Comment by lojack5** [comment]
Temp folder will have to have a weirdly coded workaround there.  It's failing inside the library function, when already passing the library function a unicode string.  So essentially we'd have to reimpliment the library function `tempdir.mkdtemp`, which is annoying, since it's supposed to work fine with unicode stuff.

Alternatively, you can disable the call to `testUAC`, since I never did fully implement UAC workarounds (since they are a pain), and just require either running as Admin or one of the various other known tricks to get UAC out of the way (especially since this is the current recommendation anyway).  Annoyingly though, the `tempdir` functionality is still needed currently for extracting BAIN archives, so this would only allow it to startup.  You'd either need to recode that to use a different working directory for unpacking/etc, or possibly have a default location (inside the Mopy folder most likely), with an INI option for a specific location (useful for people that have the Mopy folder on a different drive than the actual game).

As for the 305 error: that's error is saying that the translation file it's trying to load is formatted incorrectly.  There's a header in the human-readable versions with something like this:
```"Project-Id-Version: Wrye Bash\n"
"POT-Creation-Date: 2011-12-11 12:53+China Standard Time\n"
"PO-Revision-Date: 2014-08-20 21:46+China Standard Time\n"
"Last-Translator: bluesky404 aka icedream <icedream@tesfans.org>\n"
"Language-Team: Chinese (Simplified) <icedream@tesfans.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=gbk\n"
"Content-Transfer-Encoding: utf8\n"
"Generated-By: pygettext.py 1.5\n"```

The section it'll be choking on is the line saying:
`"Content-Type: text/plain; charset=gbk\n"`

A "freshly" dumped translation file (as in, dumped with all the strings that need to be translated, but are not yet) has that as
`"Content-Type: text/plain; charset=CHARSET\n"`
As in, it's supposed to be filled in by the person that did the translation.  It denotes what encoding the file is using, so when the translation library loads it it knows how to convert the text file to unicode properly.  Whatever translation file their using, this hasn't been done, hence the error: "unknown encoding: CHARSET"

PS: shoot me a PM on the official forums or here (if it's possible) of anything you want me to take a look at, I have about 3 weeks until school starts up again, then another massive load plus tutoring will suck up my time again.

**Comment by Sharlikran** [comment]
```Python
C:\Users\きら\Documents\My Games\Skyrim

C:\Users\ E3 81 8D E3 82 89 \Documents\My Games\Skyrim
```
That is the Users Path to the INI files.

**Comment by Sharlikran** [comment]
![registry](https://cloud.githubusercontent.com/assets/1912426/5594867/bd7c87c4-9215-11e4-8311-7edbba66e70e.png)

Hmmm...  That's weird that the `\` are not escaped and the don't show up as a `\` it's a `¥`.

**Comment by Sharlikran** [comment]
@WrinklyNinja Do you have to do anything special for BOSS or LOOT for other code pages, in this case cp932 so that the BOSS and LOOT can see the users path to the game EXE?

@valda Does your registry look that way?

**Comment by valda** [comment]
![regedit](https://cloud.githubusercontent.com/assets/6148/5595078/817e2402-92ac-11e4-8249-ddcf77363c82.jpg)
This is NV entry because there was not entry of Skyrim.

**Comment by Utumno** [comment]
Hey Lojack what a pleasant surprise :)

You could have a look to issues tagged review (some of them already committed) and to the issues that are tagged 306 and most importantly to the patchers for skyrim: https://github.com/wrye-bash/wrye-bash/commits/dev-skyrim-patcher-update

306 contains a massive refactoring of bosh and basher that needs to reach the userbase soon

Re: the issue at hand: thanks for the CHARSET, that puzzled me.

> He switched to a non unicode English codepage which made wrye bash work after restarting but when he tried to start the game it caused Skyrim to start up in 640x480 windows mode English.

what about this ?

Ands also:

>  So essentially we'd have to reimplement the library function tempdir.mkdtemp, which is annoying, since it's supposed to work fine with unicode stuff.

Well, it is supposed yes - so what is the problem ? That it is using the ascii codec ? Could we instruct it not to ?

**Comment by Sharlikran** [comment]
Steam Settings:
![steam](https://cloud.githubusercontent.com/assets/1912426/5597448/31a34598-9257-11e4-98e1-a2cced93fb19.jpg)

```Auto
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\bethesda softworks\skyrim]
"installed path"="C:\\Program Files (x86)\\Steam\\steamapps\\common\\Skyrim\\"
```
I think that's about all I can get for you guys to work with.

@valda Are your Region and Language settings the same as KiraHanato's are?  Can I get a screen shot of your Region and Language settings?  If yours are different maybe he can try what you are using.

**Comment by Sharlikran** [comment]
@Utumno @lojack5 
I tried all of the following lines:

```Python
"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath="C:\\program files (x86)\\steam\\SteamApps\\common\\Skyrim"

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath='C:\\program files (x86)\\steam\\SteamApps\\common\\Skyrim'

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath="C:\program files (x86)\steam\SteamApps\common\Skyrim"

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath='C:\program files (x86)\steam\SteamApps\common\Skyrim'

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" -g skyrim -o 'C:\program files (x86)\steam\SteamApps\common\Skyrim'

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" -g skyrim -o "C:\program files (x86)\steam\SteamApps\common\Skyrim"
```
None of them worked.  The documentation does not stae that the -g or -o need to be followed by any kind of delimiters.  No `=:;'/"` or space is indicated and when I look at the Python code i don't see what is supposed to be there either.

What is the correct way to specific the game location from the command line?  If one of the above lines should have worked then the routine is bugged.

**Comment by Sharlikran** [comment]
@Utumno @lojack5 
I tried all of the following lines:

```Python
"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath="C:\\Games\\SteamApps\\common\\Skyrim"

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath='C:\\Games\\SteamApps\\common\\Skyrim'

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath="C:\Games\SteamApps\common\Skyrim"

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath='C:\Games\SteamApps\common\Skyrim'

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" -g skyrim -o 'C:\Games\SteamApps\common\Skyrim'

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" -g skyrim -o "C:\Games\SteamApps\common\Skyrim"
```
None of them worked.  The documentation does not state that the -g or -o need to be followed by any kind of delimiters.  No `=:;'/"` or space is indicated and when I look at the Python code I don't see what is supposed to be there either.

What is the correct way to specific the game location from the command line?  If one of the above lines should have worked then the routine is bugged.  It fails when it does not find the registry and completely ignores the command line.

**Comment by Sharlikran** [comment]
I am testing with the --debug and all I get is this:

```Python
Wrye Bash starting
Using Wrye Bash Version 306
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('en_US', 'cp1252')
Searching for game to manage:
bush.pyo   81 detectGames: Detected the following supported games via Windows Registry:
bush.pyo   95 detectGames: Detecting games via relative path and the -o argument:
bush.pyo  146 setGame: Specified game "skyrim" was not found.
```

**Comment by Sharlikran** [comment]
@Utumno @lojack5 

``Python
sOblivionPath=C:\Games\SteamApps\common\Skyrim
```
I added that to my bash.ini and I still have the same error.  A window opens and I am told to use the -o parameter.

**Comment by Sharlikran** [comment]
I deleted the shortcut, reset my windows registry back to what it should be and I still get the error.  Then since i figured it has to be something I am doing I copied the python version from Dev and ran it.  It works fine.  Then I made a standalone version, copied it to the mopy folder, and I get the error to specify the -o command line parameter.

**Comment by Sharlikran** [comment]
Then since I was confused, and getting frustrated because I have been working with him for several days now, I went to my old branch using the old layout not the dev branch but my dev-sarlikran-valda-fallout branch.  I made a standalone EXE and it's working fine.

**Comment by Sharlikran** [comment]
Moved all startup issues related to the 306 Standalone version from the dev branch to new issue #182.

**Comment by Sharlikran** [comment]
Because I was getting issues with the Standalone version of 306 from the dev branch I had him download my EXP version based off of 305.

```Auto
Error! Unable to start Wrye Bash.

Please ensure Wrye Bash is correctly installed.

Traceback (most recent call last):
  File "bash\bash.pyo", line 455, in main
  File "bash\bosh.pyo", line 24829, in testUAC
  File "bash\bolt.pyo", line 1168, in tempDir
  File "tempfile.pyo", line 331, in mkdtemp
  File "ntpath.pyo", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7:
```

And

```Auto
Traceback (most recent call last):
  File "bash\bolt.pyo", line 286, in initTranslator
  File "gettext.pyo", line 180, in __init__
  File "gettext.pyo", line 337, in _parse
UnicodeDecodeError: 'cp932' codec can't decode bytes in position 4-5: illegal multibyte sequence
```
That is the traceback and the BashBugDump.log file.

**Comment by Utumno** [comment]
The strange thing is `UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7:` - position 7 ?

**Comment by Sharlikran** [comment]
I think I caused `UnicodeDecodeError: 'cp932' codec can't decode bytes in position 4-5: illegal multibyte sequence` to occur.  I thought since the game mode and the game folder were not being detected that if he had a standalone that worked then it would be cool if Wrye used an older Japanese.txt file.

**Comment by Sharlikran** [comment]
> The strange thing is UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7: - position 7 ?

Yeah that's why I had asked for a quicky feature request either in the Beth forum or somewhere on GitHub to do a try; except: on folders and print out the being parsed.  With the information Lojack gave I assume it's the users path and the temp folder like he said but it would be nice to have the offending line end up in the log file for future reference and conformation of which sting is not being decoded.

**Comment by Sharlikran** [comment]
```Auto
Wrye Bash starting
Using Wrye Bash Version 305
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('fr_FR', 'cp1252'
Searching for game to manage:
bush.pyo 81 detectGames: Detected the following supported games via Windows Registry:
bush.pyo 83 detectGames: skyrim: B:\TES V Skyrim
bush.pyo 95 detectGames: Detecting games via relative path and the -o argument:
bush.pyo 111 detectGames: skyrim: B:\TES V Skyrim
bush.pyo 144 setGame: No preferred game specified.
bush.pyo 151 setGame: Using skyrim game: B:\TES V Skyrim
testing UAC
bosh.pyo 5536 __init__: Using libbsa API version: 2.0.0
bosh.pyo 5542 __init__: Using libloadorder API version: 4.0.1
bosh.pyo 5548 __init__: Using LOOT API version: 0.6.0
B:\TES V Skyrim
Traceback (most recent call last):
File "Wrye Bash Launcher.pyw", line 87, in <module>
File "bash\bash.pyo", line 574, in main
File "bash\basher.pyo", line 18921, in InitLinks
File "bash\basher.pyo", line 18291, in InitStatusBar
File "bash\bolt.pyo", line 2470, in deprint
File "StringIO.pyo", line 271, in getvalue
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 37: ordinal not in range(128)
```
Another user with a French OS has a slightly different error.

@Lojack I would love to keep providing some of this information to you if you are willing to work on this before school starts.  I don't know how much I can help with my limited programming knowledge but I am willing to try.  If there is some repetitious code that I would need to change I can always do that.  You could contact me on Skype again to go over it.  I have a branch for UTF8 fixes we could work from it if you want or you can create one here and I can fetch it from the upstream.

**Comment by Sharlikran** [comment]
Other information about the French User:

Skyrim Folder: B:\TES V Skyrim
Skyrim Data Folder: B:\TES V Skyrim\Data
Skyrim Strings Folder: B:\TES V Skyrim\Data\Strings
Wrye Bash Folder: B:\TES V Skyrim\Mopy
Users Folder: C:\Users\Centurion
Save Games: D:\My Games\Skyrim\Saves
Temp folder: E:\TEMP

All of those locations are redirected and are set in the registry and in Windows PATH environment.

![french region langue](https://cloud.githubusercontent.com/assets/1912426/5607773/f6e0016c-941d-11e4-86ba-0388a892759b.jpg)

**Comment by Utumno** [comment]
For the mkdtmp:

http://bugs.python.org/issue1681974

Pushed an attempted fix in my branch: 5b6a355d864793b0eac063d7f349ddf9f8a72a7e

not even sure it'll work - I am still looking into it - we need something full proof

The french user is another part of the code - monkey patched that one too: 62988022612cf57360075c83d97364d78e072262

Both are in https://github.com/wrye-bash/wrye-bash/compare/utumno-163-wip

**Comment by Sharlikran** [comment]
```Auto
Wrye Bash starting
Using Wrye Bash Version 306
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('ja_JP', 'cp932')
Searching for game to manage:
bush.pyo   84 _supportedGames: Detected the following supported games via Windows Registry:
bush.pyo   86 _supportedGames:  skyrim: C:\Program Files (x86)\Steam\steamapps\common\Skyrim
bush.pyo  139 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyo  146 _detectGames: Set game mode to skyrim found in parent directory of Mopy. C:\program files (x86)\steam\steamapps\common\Skyrim
bush.pyo  179 setGame: No preferred game specified.
bush.pyo  159 _setGame:  Using skyrim game: C:\program files (x86)\steam\steamapps\common\Skyrim
testing UAC
Error! Unable to start Wrye Bash.

Please ensure Wrye Bash is correctly installed.


Traceback (most recent call last):
  File "bash\bash.pyo", line 382, in main
  File "bash\bosh.pyo", line 10347, in testUAC
  File "bash\bolt.pyo", line 657, in tempDir
  File "tempfile.pyo", line 331, in mkdtemp
  File "ntpath.pyo", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7: ordinal not in range(128)
```
With the latest changes in utumno-163-wip the game is detected, but the username could still be an issue.

**Comment by Utumno** [comment]
What's the deal with standalone traceback ? In line 657 there's a try: https://github.com/wrye-bash/wrye-bash/blob/5b6a355d864793b0eac063d7f349ddf9f8a72a7e/Mopy/bash/bolt.py#L657

Did not write the code and I do not know how it's used - what would happen if I returned None for instance. If all fails I will go with Lo's suggestion and just create the temp dir inside mopy (ini option can wait) but meanwhile try latest of my branch - make sure: 38ba96db7f7f8bf233717e17bf71bdad24a3e4a9 is included

See http://stackoverflow.com/q/28101187/281545

On the + side: I am pleased to see the game detection happen once

**Comment by Sharlikran** [comment]
Let me ask something first before I try that branch.

**Comment by Utumno** [comment]
Any news from the french and japanese users would be welcome - for the japanese maybe creating a japanese named user would be enough to test - I just did not have time to do this myself

Attempted fixes as usual in my dev branch

**Comment by Sharlikran** [comment]
Something I noticed.  In 295.3 `class Path(object):` was rewritten and some interesting lines were removed.  
```Python
class Path(object):
    """A file path. May be just a directory, filename or full path."""
    """Paths are immutable objects that represent file directory paths."""

    #--Class Vars/Methods -------------------------------------------
    norm_path = {} #--Dictionary of paths
    mtimeResets = [] #--Used by getmtime
    ascii = '[\x00-\x7F]'
    japanese_hankana = '[\xA1-\xDF]'
    japanese_zenkaku ='[\x81-\x9F\xE0-\xFC][\x40-\x7E\x80-\xFC]'
    reChar = re.compile('('+ascii+'|'+japanese_hankana+'|'+japanese_zenkaku+')', re.M)
```

```Python
    @staticmethod
    def mbSplit(path):
        """Split path to consider multibyte character boundary."""
        # Should also add Chinese fantizi and zhengtizi, Korean Hangul, etc.
        match = Path.reChar.split(path)
        result = []
        curResult = ''
        resultAppend = result.append
        for c in match:
            if c == '\\':
                resultAppend(curResult)
                curResult = ''
            else:
                curResult += c
        resultAppend(curResult)
        return result
```
Incidentally some users of the Oblivion version swear by older version in the Bethesda threads.  They claim that newer versions don't work right in regards to Unicode.  There normally aren't any details as to what that means.  The Bethesda search option is all wonky and I couldn't easilly find a users post to offer as an example.

**Comment by Sharlikran** [comment]
Another user from the Oblivion Nexus had this error and stated that 302.1 offered a resolution.  The [post is here](http://forums.nexusmods.com/index.php?/topic/100238-wrye-bash/?p=20943294).

As far as testers, I have not heard back from KiraHanato I don't know if he is busy or not.  I have not made a new Standalone for the french user I'll be doing that later today.

**Comment by Utumno** [comment]
Thanks - keep in mind that older versions may work cause for instance testUAC() is not called or anything - without looking at 302.1 it may well be the case - will keep those in mind - nice to have them in this issue - btw keeping issues clean, focused, _dry_ and technical is a huge time saver for me.

The 302.1 user has the same prob as KiraHanato btw - maybe he gives a try to utumno-163-wip ?

Unicode is monkey patched into Bash with good results overall - refactoring Unicode handling is in my TODO list but will wait till 310+ - till then we will be monkey patching, which also will give us insight on what parts of the code need reworking.

**Comment by Sharlikran** [comment]
The french user is trying a version based off of https://github.com/wrye-bash/wrye-bash/commit/cd6d55802021b079e114740644339e4c5ef24b27 but doesn't seem to have much better results.  He is going to do more testing and provide me a log later.

**Comment by Utumno** [comment]
Looking forward - no way the code is failing in the same point - I am very curious (I do hope he is using the right commit though). Thanks for suplying the commit - that's really helpful so I know we are on the same page.

If you can get round to it please create a user in windows named with a Japanese name and try to run 305 then cd6d55802021b079e114740644339e4c5ef24b27 in this profile and see if it fixes the japanese user issues - it would help me to get the unicode commits to dev and off my branch.

Or bug him once more - tell him to test or I will delete his save games ahahaha.

**Comment by Sharlikran** [comment]
That should do it :+1:

**Comment by Sharlikran** [comment]
Did your fix work?  My comment and the :+1: wasn't an acknowledgement that it worked.  The Japanese user isn't responding anymore so I'm not going to bother him.  The french user has other system related issues that is interfering with Wrye Bash.

I know this was a Monkey fix, but did someone in the forum confirm anything?

**Comment by Utumno** [comment]
Yes @psilocide aka lefenger who is of great help. Plus I understand what's going on now. If it resurfaces (unlikely) we can always reopen.

**Comment by Sharlikran** [comment]
Okay thanks for letting me know.

**Comment by Sharlikran** [comment]
The same user mentioned in this issue is still having issues with the current code based off of dev.
```Python
Traceback (most recent call last):
File "bash\bolt.pyo", line 337, in initTranslator
File "gettext.pyo", line 180, in __init__
File "gettext.pyo", line 337, in _parse
File "encodings\utf_8.pyo", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 90-91: invalid continuation byte
```
```Python
Traceback (most recent call last):
File "Wrye Bash Launcher.pyw", line 88, in <module>
File "bash\bash.pyo", line 435, in main
File "bash\basher\__init__.pyo", line 3973, in Init
File "bash\basher\__init__.pyo", line 4025, in InitData
File "bash\bosh\__init__.pyo", line 4153, in generateNextBashedPatch
File "bash\bosh\__init__.pyo", line 4136, in create_new_mod
File "bash\parsers.pyo", line 4112, in safeSave
File "bash\bolt.pyo", line 660, in temp
File "bash\bolt.pyo", line 877, in makedirs
File "os.pyo", line 157, in makedirs
WindowsError: [Error 5] ?????????????: u'c:\\users\\\x82\u0164\x82\xe7\\appdata\\local\\temp\\WryeBash_temp'
```

The section where you see ? are japanese characters which nexus forums cant seem to process but as to what it originally said is access denied.

This is with Skyrim SE and my current code however the files listed in the traceback are unaltered by my version so the line number should match up.  A fix would be nice but I don't expect one any time soon.  Do @valda or @lojack5 have any thoughts?  I know Utumno is writing the current code, I'm asking if anything comes to mind as far as obstacles you experienced in the past.

-------------------
The user shared a wiki entry for a previous version of Wrye Bash.  Probably 306:

Go to python installed folder \Lib\site-packages > make new file called sitecustomize.py > Edit with IDLE > add the code below

import sys
sys.setdefaultencoding('sjis')

OR with this method if the above doesnt work

SteamApps\common\skyrim\Mopy\bash\bolt.py　line 2606

value = unicode(cstrip(value),'cp1252')　with
value = unicode(cstrip(value),'cp1252','ignore')

**Comment by Sharlikran** [comment]
The same user mentioned in this issue is still having issues with the current code based off of dev.
```Python
Traceback (most recent call last):
File "bash\bolt.pyo", line 337, in initTranslator
File "gettext.pyo", line 180, in __init__
File "gettext.pyo", line 337, in _parse
File "encodings\utf_8.pyo", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 90-91: invalid continuation byte
```
```Python
Traceback (most recent call last):
File "Wrye Bash Launcher.pyw", line 88, in <module>
File "bash\bash.pyo", line 435, in main
File "bash\basher\__init__.pyo", line 3973, in Init
File "bash\basher\__init__.pyo", line 4025, in InitData
File "bash\bosh\__init__.pyo", line 4153, in generateNextBashedPatch
File "bash\bosh\__init__.pyo", line 4136, in create_new_mod
File "bash\parsers.pyo", line 4112, in safeSave
File "bash\bolt.pyo", line 660, in temp
File "bash\bolt.pyo", line 877, in makedirs
File "os.pyo", line 157, in makedirs
WindowsError: [Error 5] ?????????????: u'c:\\users\\\x82\u0164\x82\xe7\\appdata\\local\\temp\\WryeBash_temp'
```

The section where you see ? are japanese characters which nexus forums cant seem to process but as to what it originally said is access denied.

This is with Skyrim SE and my current code however the files listed in the traceback are unaltered by my version so the line number should match up.  A fix would be nice but I don't expect one any time soon.  Do @valda or @lojack5 have any thoughts?  I know @Utumno is writing the current code, I'm asking if anything comes to mind as far as obstacles you experienced in the past.

-------------------
The user shared a wiki entry for a previous version of Wrye Bash.  Probably 306:

Go to python installed folder \Lib\site-packages > make new file called sitecustomize.py > Edit with IDLE > add the code below

import sys
sys.setdefaultencoding('sjis')

OR with this method if the above doesnt work

SteamApps\common\skyrim\Mopy\bash\bolt.py　line 2606

value = unicode(cstrip(value),'cp1252')　with
value = unicode(cstrip(value),'cp1252','ignore')

**Comment by Sharlikran** [comment]
Also an update, the above Traceback logs are when using Wrye Bash through or from NMM.  This is the Traceback  without NMM and being run with Admin rights.
```Python
Traceback (most recent call last):
File "Wrye Bash Launcher.pyw", line 88, in <module>
File "bash\bash.pyo", line 435, in main
File "bash\basher\__init__.pyo", line 3973, in Init
File "bash\basher\__init__.pyo", line 4025, in InitData
File "bash\bosh\__init__.pyo", line 4153, in generateNextBashedPatch
File "bash\bosh\__init__.pyo", line 4136, in create_new_mod
File "bash\parsers.pyo", line 4116, in safeSave
File "bash\env.pyo", line 491, in shellMove
File "bash\env.pyo", line 442, in _fileOperation
bash.env._InvalidPathsError
```

**Comment by Utumno** [comment]
The encoding of the paths is mangled up when passed to SHFileOperation - ask the user to post the full bugdumb for future reference

**Comment by Sharlikran** [comment]
NMM doesn't allow you to add the --debug command line parameter at this time.  I can ask for the full bugdump using a shortcut to the EXE but I'm affraid it's not really going to be as accurate as running it from NMM.

I feel that way because from NMM the user has ``````u'c:\\users\\\x82\u0164\x82\xe7\\appdata\\local\\temp\\WryeBash_temp'`````` and from a shortcut the user has ```bash.env._InvalidPathsError```.  Tannin and the nexus team may have made NMM more like Mod Organizer already.  When they announced Tannin was hired to improve NMM the current devs mentioned that NMM has been using links for some time already.

**Comment by Utumno** [comment]
Yep the errors should boil down to the same thing just the bugdump contains precious info - I am tempted to drop the generateNextBashedPatch on start I am tired of patching it.

Will investigate this further when I get done with the other stuff but meanwhile a bugdump would help

**Comment by Sharlikran** [comment]
``````Python
Wrye Bash starting
Using Wrye Bash Version 307 (Standalone)
OS info: Windows-8-6.2.9200
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('ja_JP', 'cp932')
filesystem encoding: mbcs
Searching for game to manage:
bush.pyo 71 _supportedGames: Detected the following supported games via Windows Registry:
bush.pyo 73 _supportedGames: oblivion: C:\Program Files (x86)\Steam\steamapps\common\Oblivion
bush.pyo 73 _supportedGames: skyrim special edition: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition
bush.pyo 131 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyo 137 _detectGames: Set game mode to skyrim special edition found in parent directory of Mopy: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition
bush.pyo 172 setGame: No preferred game specified.
bush.pyo 152 __setGame: Using skyrim special edition game: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition
testing UAC
Traceback (most recent call last):
File "bash\bolt.pyo", line 675, in tempDir
File "tempfile.pyo", line 331, in mkdtemp
File "ntpath.pyo", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7: ordinal not in range(128)
Trying to pass temp dir in...
__init__.pyo 7740 initDirs: Using libbsa API version: 2.0.0
mods_metadata.pyo 223 __init__: Using LOOT API version: 0.10.0
Traceback (most recent call last):
File "Wrye Bash Launcher.pyw", line 88, in <module>
File "bash\bash.pyo", line 435, in main
File "bash\basher\__init__.pyo", line 3973, in Init
File "bash\basher\__init__.pyo", line 4025, in InitData
File "bash\bosh\__init__.pyo", line 4153, in generateNextBashedPatch
File "bash\bosh\__init__.pyo", line 4136, in create_new_mod
File "bash\parsers.pyo", line 4116, in safeSave
File "bash\env.pyo", line 491, in shellMove
File "bash\env.pyo", line 442, in _fileOperation
bash.env._InvalidPathsError 
``````

**Comment by Utumno** [comment]
The user can workaround this by dumping a bashed patch in there, crashes on BP creation - which I should probably give the boot - still worth investigating

**Comment by valda** [comment]
I actually made a Japanese username account and tried it in Virtualbox.
The value returned from tempfile.gettempdir is plain string. need decode MBCS.

```
diff --git a/Mopy/bash/bolt.py b/Mopy/bash/bolt.py
index 6d56393..4489cd3 100644
--- a/Mopy/bash/bolt.py
+++ b/Mopy/bash/bolt.py
@@ -657,7 +657,7 @@ def temp(self,unicodeSafe=True):
         """Temp file path.  If unicodeSafe is True, the returned
         temp file will be a fileName that can be passes through Popen
         (Popen automatically tries to encode the name)"""
-        baseDir = GPath(tempfile.gettempdir()).join(u'WryeBash_temp')
+        baseDir = GPath(unicode(tempfile.gettempdir(), Path.sys_fs_enc)).join(u'WryeBash_temp')
         baseDir.makedirs()
         dirJoin = baseDir.join
         if unicodeSafe:
@@ -694,7 +694,7 @@ def tempDir(prefix=u'WryeBash_'):
 
     @staticmethod
     def baseTempDir():
-        return GPath(tempfile.gettempdir())
+        return GPath(unicode(tempfile.gettempdir(), Path.sys_fs_enc))
 
     @property
     def backup(self):
```

**Comment by Utumno** [comment]
Om my god! thanks a lot @valda !

Sharl try that

**Comment by Sharlikran** [comment]
KiraHanato has reported that this fix worked.

**Comment by valda** [comment]
It’s my pleasure. 😄

**Comment by Utumno** [comment]
@valda: and my pleasure to see you around again :)

Can you provide me a pull request or a commit in your repository I can cherry pick so you get the credit ?
