### ISSUE TITLE
CBash patcher does not import names from csv files

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#181]
Reported by @Tekuromoto here: http://forums.bethsoft.com/topic/1501046-wrye-bash-thread-100/page-7#entry23809107 (standalone) and follow up for Python version: http://forums.bethsoft.com/topic/1510638-wrye-bash-thread-101/#entry23842510

See the post that follow the original report- present in 304.4 so not my changes

[Workaroud](http://forums.bethsoft.com/topic/1510638-wrye-bash-thread-101/#entry23846303) (by Tekuromoto again)

> As for CBash not importing my CSV files, I've worked around it by having two patches:
> - the main CBash patch has everything except tweak names, import names, and import stats
> - the supplementary PBash patch has those three things only

**Comment by Utumno** [comment]
@leandor - if you ever visit python land please have a look at this one - it is most probably an error in binding with CBash from python but who knows. Needs debugger breakpoint set and then see where the nasty critter lies

**Comment by leandor** [comment]
Sure, I added this to the list of issues to check!

**Comment by Utumno** [comment]
@wrye-bash/active @BeermotorWB I think this should be fixed in latest utumno-wip - can anyone check ? Run just the name patcher instructing  it to import some names csv from https://github.com/wrye-bash/wrye-bash/tree/7ac0dbd39f788fa63041f03489adc99c7b54f87c/Mopy/Bash%20Patches/Oblivion as:


Source Mods/Files
•  OOO_Potion_Names.csv

•  Random_NPC_Alternate_Names.csv

•  Random_NPC_Names.csv

•  Rational_Names.csv

**Comment by BeermotorWB** [comment]
@Utumno Just saw this. I've never done this personally. We may try reaching out to @Arthmoor  to see if he could give us some input.

**Comment by Utumno** [comment]
Hey @BeermotorWB - if you have Oblivion it's just a matter of making a BP on python and CBash wityh just import nakmes from the csvs above and checking equal. For now they don't: 

https://www.dropbox.com/sh/znlst37a8kdp9ba/AACHACkBtwuLRoowqR_DSXota?dl=0

**Comment by BeermotorWB** [comment]
@Utumno Just saw your post on AFK mods referring the CSV import.  Just ping me when you're ready for me to test the result.

**Comment by Infernio** [comment]
As far as I understand, this is purely a CBash issue - so closing as `R-wont-fix` (#530).
