### ISSUE TITLE
standalone compiled from dev fails to detect the game when passed by command line or specified in the bash.ini

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#182]
That is my Bash log with the dev branch
```Auto
Wrye Bash starting
Using Wrye Bash Version 306
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('en_US', 'cp1252')
Searching for game to manage:
bush.py   81 detectGames: Detected the following supported games via Windows Registry:
bush.py   83 detectGames:  oblivion: C:\Games\steamapps\common\Oblivion
bush.py   83 detectGames:  skyrim: C:\Games\steamapps\common\Skyrim
bush.py   95 detectGames: Detecting games via relative path and the -o argument:
bush.py  101 detectGames:  skyrim: C:\Games\SteamApps\common\Skyrim
bush.py  144 setGame: No preferred game specified.
bush.py  151 setGame:  Using skyrim game: C:\Games\SteamApps\common\Skyrim
testing UAC
bosh.py 5271 __init__: Using libbsa API version: 2.0.0
bosh.py 5277 __init__: Using libloadorder API version: 4.0.1
bosh.py 5283 __init__: Using LOOT API version: 0.6.0
C:\Games\SteamApps\common\Skyrim
bush.py   81 detectGames: Detected the following supported games via Windows Registry:
bush.py   83 detectGames:  oblivion: C:\Games\steamapps\common\Oblivion
bush.py   83 detectGames:  skyrim: C:\Games\steamapps\common\Skyrim
bush.py   95 detectGames: Detecting games via relative path and the -o argument:
bush.py  101 detectGames:  skyrim: C:\Games\SteamApps\common\Skyrim
```
That is my Bash log from my dev-sharlikran-valda-fallout branch
```Auto
Wrye Bash starting
Using Wrye Bash Version 306.0.14
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('en_US', 'cp1252')
Searching for game to manage:
bush.py   81 detectGames: Detected the following supported games via Windows Registry:
bush.py   83 detectGames:  fallout3: C:\Games\steamapps\common\Fallout 3 goty
bush.py   83 detectGames:  falloutnv: C:\Games\steamapps\common\Fallout New Vegas
bush.py   83 detectGames:  oblivion: C:\Games\steamapps\common\Oblivion
bush.py   83 detectGames:  skyrim: C:\Games\steamapps\common\Skyrim
bush.py   95 detectGames: Detecting games via relative path and the -o argument:
bush.py  101 detectGames:  skyrim: C:\Games\SteamApps\common\Skyrim
bush.py  144 setGame: No preferred game specified.
bush.py  151 setGame:  Using skyrim game: C:\Games\SteamApps\common\Skyrim
testing UAC
bosh.py 5563 __init__: Using libbsa API version: 2.0.0
bosh.py 5569 __init__: Using libloadorder API version: 4.0.1
bosh.py 5575 __init__: Using LOOT API version: 0.6.0
C:\Games\SteamApps\common\Skyrim
```
It's as if the dev branch is detecting the game mode twice.

**Comment by Sharlikran** [comment]
@Utumno @lojack5 
I tried all of the following lines:

```Python
"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath="C:\\Games\\SteamApps\\common\\Skyrim"

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath='C:\\Games\\SteamApps\\common\\Skyrim'

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath="C:\Games\SteamApps\common\Skyrim"

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" --game=skyrim --oblivionPath='C:\Games\SteamApps\common\Skyrim'

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" -g skyrim -o 'C:\Games\SteamApps\common\Skyrim'

"C:\Games\SteamApps\common\Skyrim\Mopy\Wrye Bash.exe" -g skyrim -o "C:\Games\SteamApps\common\Skyrim"
```
None of them worked.  The documentation does not state that the -g or -o need to be followed by any kind of delimiters.  No `=:;'/"` or space is indicated and when I look at the Python code I don't see what is supposed to be there either.

What is the correct way to specify the game location from the command line?  If one of the above lines should have worked then the routine is bugged.  It fails when it does not find the registry and completely ignores the command line.

**Comment by Sharlikran** [comment]
I am testing with the --debug and all I get is this:

```Python
Wrye Bash starting
Using Wrye Bash Version 306
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('en_US', 'cp1252')
Searching for game to manage:
bush.pyo   81 detectGames: Detected the following supported games via Windows Registry:
bush.pyo   95 detectGames: Detecting games via relative path and the -o argument:
bush.pyo  146 setGame: Specified game "skyrim" was not found.
```

**Comment by Sharlikran** [comment]
@Utumno @lojack5 

```Auto
sOblivionPath=C:\Games\SteamApps\common\Skyrim
```
I added that to my bash.ini and I still have the same error.  A window opens and I am told to use the -o parameter.

![wrye error](https://cloud.githubusercontent.com/assets/1912426/5601633/13a3cf52-92c2-11e4-8487-65df3404de67.jpg)

**Comment by Sharlikran** [comment]
I deleted the shortcut, reset my windows registry back to what it should be and I still get the error.  Then since i figured it has to be something I am doing I copied the python version from Dev and ran it.  It works fine.  Then I made a standalone version, copied it to the mopy folder, and I get the error to specify the -o command line parameter.

**Comment by Sharlikran** [comment]
Then since I was confused, and getting frustrated because I have been working with him for several days now, I went to my old branch using the old layout not the dev branch but my dev-sarlikran-valda-fallout branch.  I made a standalone EXE and it's working fine.

**Comment by Sharlikran** [comment]
Confirmed, there are the traceback and BashBugDump.log file from a Standalone EXE from my experimental version.

```Auto
Error! Unable to start Wrye Bash.

Please ensure Wrye Bash is correctly installed.

Traceback (most recent call last):
  File "bash\bash.pyo", line 455, in main
  File "bash\bosh.pyo", line 24829, in testUAC
  File "bash\bolt.pyo", line 1168, in tempDir
  File "tempfile.pyo", line 331, in mkdtemp
  File "ntpath.pyo", line 84, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 7:
```

And

```Auto
Traceback (most recent call last):
  File "bash\bolt.pyo", line 286, in initTranslator
  File "gettext.pyo", line 180, in __init__
  File "gettext.pyo", line 337, in _parse
UnicodeDecodeError: 'cp932' codec can't decode bytes in position 4-5: illegal multibyte sequence
```
That is the traceback and the BashBugDump.log file.

**Comment by Utumno** [comment]
I am aware of this since  a long time: @lojack5 said the command line args did not ever reach perfection.
Anyway the `bush.py   81 detectGames: Detected the following supported games via Windows Registry:` line repeating itself (even three times at times) is a nono clearly - the value should be cached

I just did not have the time to look into this - one must set a breakpoint and step in

**Comment by Sharlikran** [comment]
Makes sense.  You know where you are with your refactoring.  It can just be a reminder before releasing 306, although you are saying you didn't need it really.

**Comment by Utumno** [comment]
I am actually glad someone (you) posted the issue for me :D
But please clean it up a bit: I can't go through it all - it has info related to issue related to 180 - and most importantly _your experimenal branch is the one on pull request 177_ ? In this case i introduced a regression in dev so this must be fixed _now_

**Comment by Sharlikran** [comment]
> But please clean it up a bit: I can't go through it all - it has info related to issue 180

That is all I could think of to remove.  The rest has nothing to do with #180.

> most importantly your experimental branch is the one on pull request 177 ?

No my experimental branch will always by my dev-sharlikran-valda-fallout which is based off of the 305 code base.

> In this case i introduced a regression in dev so this must be fixed now

What?  I made changes to the skyrim patcher folder and the attributes that the patchers look at since they are distinctly different.  I made it off of dev not any of my own branches.  Why on earth would you think that my pull request introduced this error?  I am a little concerned that you reversed the #177 pull request.

In any case, no it is not fixed I just tested it for both Skyrim and Oblivion.  Did you build a standalone EXE and try it?

This is not meant to be mean or disrespectful to you but, no the issue is not created by my pull requests it's created by the much needed refactoring that you are doing.  However, as you stated you are not done yet.  I am sure after you have a better working code base you can figure it out.

Granted it's confusing to me that it works when run as Python and not as standalone but I can't explain that.

**Comment by Utumno** [comment]
@Sharlikran: thanks for cleaning it up:

So there are two bugs:
- cycles in the game detection (the one I referred to)
- standalone compiled from dev at https://github.com/wrye-bash/wrye-bash/commit/5dbf49d0d9bbe5a6ccf3176e32af2084f7e958f4 fails to detect the game when passed by command line

2 questions
1. starting Bash from the launcher and specifying the oblivion folder in the ini works with the standalone ? Or if there is one
2. bad commit on dev:  https://github.com/wrye-bash/wrye-bash/commit/5dbf49d0d9bbe5a6ccf3176e32af2084f7e958f4 - good commit on dev ?

**Comment by Sharlikran** [comment]
1. You can not start the standalone with command line parameters or specify the game path in the bash.ini file.
2. I don't know python to have any valuable input.  However, it looks like optimization for wxPython list boxes.  I say if you have checked it for either Skyrim or Oblivion and your changes are working leave it.

> standalone compiled from dev at 5dbf49d fails to detect the game when passed by command line

I would change that to:

standalone compiled from dev at 5dbf49d fails to detect the game when passed by command line or specified in the bash.ini

**Comment by Utumno** [comment]
Thanks - my 2nd question was what was the last good commit on dev you know standalone worked fine - I guess tag 305 ?

**Comment by Sharlikran** [comment]
Ohhhh no I have no idea when the last working Standalone is other then 305 because I always run it in Python mode.  I can't be of much help there but, I do care and I wish I could provide more insight.

**Comment by Utumno** [comment]
Alright thanks indeed - just edit out the regression part as it is off topic (will do too)
Will see what I can do - come next week I will be busy - but I hope 306 will be for this month
I hope I can squash this in - if @lojack5 jumps in however he may be much faster as he created the standalone and the bush detection algorithm IIRC

**Comment by Utumno** [comment]
Sharl could you checkout e6b2e0e90cfd16e105dbfd3ec1a2e9c49455c1ad and then 7ff57537c149e095eeca390ddf520159a013f7d7 and see if the bug is present there ?
I suspect commit 43e359aa00433aba3ec825f2d782f06e703389a9 is the one that introduced the bug - but the real reason is the mess with the star imports - cf https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/brec.py#L29

How do you build the exe ? `package_for_release.py -e` ?

**Comment by Utumno** [comment]
And here is the bug: https://github.com/wrye-bash/wrye-bash/blob/dev/scripts/package_for_release.py#L246

**Comment by Sharlikran** [comment]
I see you put a strike through on your questions about how I make the EXE.  Yes that's how I do it.

Is it fixed?  Should I try it?  Does it need more work later when you have time?

**Comment by Utumno** [comment]
Havent fixed it yet but I think I know where it is - will post back when I get round to it

**Comment by Utumno** [comment]
I think i fixed it https://github.com/wrye-bash/wrye-bash/tree/utumno-182-standalone

Yey!

**Comment by Sharlikran** [comment]
Not sure what you did but now when I make a standalone exe I can't right click on the Mods tab to do anything.  No contextual menu shows up and i can't rebuild the bash patch.

**Comment by Utumno** [comment]
Try again the branch https://github.com/wrye-bash/wrye-bash/tree/utumno-182-standalone = fixed the mod tabs thing
The installers is the archive invalidation thing I havent looked into - should be an easy fix but I want to see which commit introduced it

**Comment by Utumno** [comment]
The discussion for the game detection algorithm belongs to #184 now

**Comment by Utumno** [comment]
Labeled TODO to not show up on changelogs as it was just a dev regression
