### ISSUE TITLE
External DLL to handle registry and directory detection

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#183]
I was wondering what does the Python Code need to get from Windows?  Does the following cover everything?  This would include command line parameters and bash.ini files.
1. Get location of game exe Oblivion.exe or TESV.exe
2. Get location of INI files
3. Get Location of installer files

Places to look
1. Windows Registry
2. command line parameters
3. bash.ini

Directories to pass to python code
1. Location of game exe Oblivion.exe or TESV.exe
2. Location of installer files
3. Read bash.ini file
   
   3.a Location of Mod Files or the Installer folder (Skyrim Mods\Bash Installers)
   3.b Location of Bash Mod Data  (Skyrim Mods\Bash Mod Data)
   3.c Location of Bash Installer Data (Skyrim Mods\Bash Installers\Bash)
   3.d Location of Game EXE (sOblivionPath)
   3.e Location of User Path (UserPath)
   3.f Location of PersonalPath (PersonalPath) usually My documents folder
   3.g Location of AppDataPath (AppDataPath) Usually where the apps folder is located
   3.h Location of TempDir (TempDir) *NEW Location of the temp folder for BAIN
4. Location of INI files

Games to Detect:

TES3/TES4/TES5/FO3/FNV

The C++ DLL would work through all the Unicode issues that is plaguing Python and pass the folders to Python.  Along with this change make the Temp dir for the BAIN installer in located in the Mopy folder and an entry in the bash.ini.

I would like it to provide Unicode safe folder names.  Which means the follwoing:

``` Auto
C:\Users\きら\Documents\My Games\Skyrim
```

Would become the following

``` Auto
C:\Users\0xE30x810x8D0xE30x820x89\Documents\My Games\Skyrim
OR
C:\Users\%E3%81%8D%E3%82%89\Documents\My Games\Skyrim
```

Whichever is the proper syntax.

**Comment by Utumno** [comment]
Sory sharl not now + I think this should be possible in python - let's see in #180

**Comment by Infernio** [comment]
All done in Python since 307, so obsolete.
