### ISSUE TITLE
Detect conflicts in BSA files

### ISSUE THREAD

**Issue by garthand** [wrye-bash/wrye-bash#188]
This is more applicable for Skyrim than Oblivion, but it would be nice if the Installers tab could detect conflicts between BSA archives the way it does for loose files between mods. I'm not sure how feasible this is, but it would be a fantastic feature.

**Comment by WrinklyNinja** [comment]
IIRC, Lojack implemented this a while ago, though it might be flagged as an
experimental option.

**Comment by garthand** [comment]
I'm using 305 currently, if it was implemented as an experimental feature, how would I go about enabling/testing it?

**Comment by Utumno** [comment]
The menu item is 'Show Bsa Conflicts' and it is on the main (column headers) menu

**Comment by Infernio** [comment]
Enabled by default as of 307 (364da662d0f012f1dfce23051e7adf5a11bc6452).
