### ISSUE TITLE
Wizard GetPluginLoadOrder function addition

### ISSUE THREAD

**Issue by garthand** [wrye-bash/wrye-bash#189]
I'm not super familiar with how wizard syntax is defined, but would it be possible to add a `GetPluginLoadOrder` function that returns the load order of the specified plugin? Most mods aren't load order sensitive but for those that are it would be a real lifesaver when trying to dynamically generate menus or detect a combination of active mods. Otherwise you end up with installers like [this](https://raw.githubusercontent.com/garthand/skyrim-batch/master/wizard.txt) as you try to manually detect every possible placement and combination.

**Comment by Utumno** [comment]
No time for enhancements now sorry - hopefully soon

**Comment by garthand** [comment]
I totally understand, you all have your hands full with the code refactoring, patchers and everything else at the moment haha

**Comment by Infernio** [comment]
Implemented in 14f1f389d9fbc745612971306023e63e7f1489be. Note that I changed `GetEspmLoadOrder` -> `GetPluginLoadOrder`.
