### ISSUE TITLE
Python 3 Support / Upgrade

### ISSUE THREAD

**Issue by DianaNites** [wrye-bash/wrye-bash#194]
I am opening this so there is one, central place to discuss ongoing progress and issues with my conversion of Wrye-bash to Python 3

(i would label this as enhancement)

**Comment by Utumno** [comment]
I will say it once: any mention of python 3, frameworks conversions and prettier colors and scrollbars before 310++ is considered ___trolling___

To come and open an issue in _this_ repo for _your_ project is _unheard of_.

**Comment by Infernio** [comment]
Superseded by #460.
