### ISSUE TITLE
Reboot the repo

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#199]
The repo contains too much cruft - binary files, the chardet library and what not. All these end up in 70 mbytes clone size (which is hell of a lot) and huge rebase etc times - and the situation will only get worse.
I suggest - now that development is not hot - to reboot the repo

Todos:
- discuss what is the better way of doing this - force push to dev/master ? create a different repo ?
  rename this one ? etc - what we loose in terms of commit messages, links etc (github questions) ? ask at SO
- dlls, images etc must be organized in submodules - this must be organized _carefully_. Do some dry runs to see how's going
- rewrite commit policies etc to keep the new born repo clean
- discuss how we will archive history

**Comment by Utumno** [comment]
Move to the backburner till refactoring is at 100% - then we can reboot

**Comment by Utumno** [comment]
> now that development is not hot 

does not refer to present I'm afraid :P - maybe once we are well on py3

**Comment by Infernio** [comment]
Just had a read of https://github.com/newren/git-filter-repo, has some very nice features. In particular:
> 8. [Old commit references] Provide a way for users to use old commit IDs with the new repository (in particular via mapping from old to new hashes with refs/replace/ references).

**Comment by Utumno** [comment]
Looks nice but I grew fond of the old history - if then I can't find something would be very frustrating :P

Will keep in mind however

At the final end we might as well start a fresh repo - in like 4k commits :D

Plus hey - parsers seem to gave broken - pushing a new fix in a min - convert_ids

**Comment by Infernio** [comment]
If I understand what the quote above means correctly, then git has a mechanism called replacement refs that would allow the older commit SHAs to point back to the new ones, so all the links in commit messages and issues would still work.
