### ISSUE TITLE
Run Bash outside game folders

### ISSUE THREAD

**Issue by WrinklyNinja** [wrye-bash/wrye-bash#20]
I've been doing this for *ages*, and I'm surprised that it's not the default setup (it's not what the installer does, and it's not what's instructed in the readme).

I haven't encountered any problems doing so, but is there any reason why dumping Bash in any old place isn't the default setup? Only thing I can think of is `bash.ini` not having setting strings to deal with Oblivion and Skyrim settings at the same time, but then I don't use a `bash.ini`.

Running outside the game folders is preferable, because it means that users don't have several separate versions of Bash installed, leading to possible version fragmentation issues and confusion / invalid bug reports.

(As an aside, why are the BAIN folders not stored in a My Games\game\ subfolder like everything else? Should I open a separate issue for that?)

**Comment by Utumno** [comment]
This actually falls under settings refactoring - I use cranky bat scripts to start different games myself and I feel the pain. However this is in the back burner till the settings internal handling is ripe for refactoring. To quantify a bit now there are at least three aliases (bosh basher settings and balt _settings) and many classes that access them - non exactly ripe.

Under #178.
