### ISSUE TITLE
Bashed Patch tweak options fail to show (Bashed Patch UI)

### ISSUE THREAD

**Issue by leandor** [wrye-bash/wrye-bash#202]
On current 'dev' branch, Bashed Patch window errors out when you right-click a tweak to show the available options:

``` 
Traceback (most recent call last):
  File "bash\basher\gui_patchers.py", line 416, in TweakOnMouse
  File "bash\basher\gui_patchers.py", line 477, in ShowChoiceMenu
TypeError: __init__() takes at most 2 arguments (3 given)
```

Option I used to check:
![image](https://cloud.githubusercontent.com/assets/1095373/7000284/885884f2-dbf4-11e4-801f-85fd7697cd40.png)

Problem seems to come from this line:

``` python
                links.append(_ValueLink(index, label))
```

And seems to be related to this commit: 967b921e0dfe6a6d52cc83939c83374e0e3d6bbd

Nice hunting! :smile:

**Comment by Utumno** [comment]
Thanks for the report - silly me

Try my branch - untested can't test now - but I believe will be ok: https://github.com/wrye-bash/wrye-bash/tree/utumno-163-wip

**Comment by leandor** [comment]
Thanks! Will test again on the evening... I'll edit this post with the results, and I'll close it if it works.

**Comment by Utumno** [comment]
Well just got round to testing it and it has issues - (list index out of range) - will have a closer look tommorow

**Comment by leandor** [comment]
Oops.... Sorry it took me so long, it was a long work day. I was just going to give this a try now! :)

**Comment by Utumno** [comment]
No worries - I will give it a thorough look tomorrow and get back to you :)

**Comment by Utumno** [comment]
Alright pushed new commits - dialog is fixed but please test if also patch is OK - candidates: tweak names, reweight arrows

**Comment by leandor** [comment]
Will test in a few hours, as soon as I get home from work today.

**Comment by Utumno** [comment]
Ok - thanks :)

Just noticed that the reweigh arrows tweaks log reports maximum arrow weight 0.000000000 no matter what option is chosen. Is it ok in game ?

Also could you check the Names tweaker for me ? Like the Spells one ? It should have the same issue in dev.

Go on using my branch - it sits on top of dev - and thanks for the report :)

**Comment by leandor** [comment]
Of course! I'll do those tests after work today.

**Comment by Utumno** [comment]
Well - actually it was not the names patcher - rather the leveled list one - fixed in 306.201504082206

**Comment by leandor** [comment]
Testing the Reweight Tweaks now. For the arrows, it seems to be using 0.00 no matter what was the choice, indeed.

![image](https://cloud.githubusercontent.com/assets/1095373/7060244/c3374016-de53-11e4-8bfa-453a9a256c72.png)

```
Reweigh: Arrows
Arrows set to maximum weight of 0.000000 
Arrows Reweighed: 179
...
```

Just selected a few random ones and did a compare to show (but they're all have weight zero):
![image](https://cloud.githubusercontent.com/assets/1095373/7060258/f37d2538-de53-11e4-9d75-a8c34f2eb6a7.png)

**Comment by Utumno** [comment]
Hmm - in 305 it did also log 0.00000 - so it is not just a log bug ?

If and only if you can test this I would be interested in 304.4 figures (that is before I started committing - so I know if it's my changes)

**Comment by leandor** [comment]
Yeah, I can do that... let me switch quickly and I'll be back in a moment.

**Comment by leandor** [comment]
Now testing again with weight 0.1, so we can compare both tests.

**Comment by Utumno** [comment]
Alright thanks ! So bottom line: reweight arrows and potions pick 0 and 0.1 (which are basically the game defaults IIRC) ?

Will have to look into it

**Comment by Utumno** [comment]
Aaaand fixed :)

Let me handle closing this from the commits

Notes:
- Would it make sense to enable the patcher when selecting an element from the choice menu ?
- What's the deal with potion weight minimum vs maximum ? Which (is supposed) to win ?

@Arthmoor : any ideas on the above ?

**Comment by Utumno** [comment]
Please check the cbash ones too - not anything thorough - all weight patchers preferably

**Comment by leandor** [comment]
Potion min vs max: I believe they're mutually exclusive... and the Min weight option it's there for people that want more realistic items weights (as in, not being able to carry 100 potions around :laughing:)

All my tests were always done using CBash... I can make another Bashed Patch and test both methods, but that'll be a bit later, when I get home from work.

**Comment by leandor** [comment]
Did you commit any new changes? I'm not sure I saw anything new on fetch (got confused because I was switched to another branch.)

I ask because I tried the tests again and they still fail like the ones I reported before.

Here's a sample, just in case:

New bashed patch, python based:
![image](https://cloud.githubusercontent.com/assets/1095373/7083235/a0b6c3e4-df35-11e4-8b12-430751ca5e3e.png)

Arrows:
![image](https://cloud.githubusercontent.com/assets/1095373/7083241/b13f6478-df35-11e4-85d7-e2f55c6f66da.png)

**Comment by Utumno** [comment]
Ooops - forgot to push - sory :(

pushed: 306.201504091341

Should be ok

Consider making a patch with only the weight options - would be much faster :)

Btw - with my load order I noticed some discrepancies between the P and C patches:

```
Bashed Patch, CBash.esp
•  Overview
•  Tweak Assorted
 
Overview
 
Date/Time
•  4/9/2015 1:48:26 PM
•  Elapsed Time: 0:00:01.75
 
Active Mods
•  00 Oblivion.esm
•  01 Jog_X_Mod.esm
•  02 xulAncientYews.esp [Version 1.4.3]
•  03 DLCVileLair.esp
•  04 DLCShiveringIsles.esp
•  05 DLCMehrunesRazor - Unofficial Patch.esp [Version 1.0.6]
•  06 DLCVileLair - Unofficial Patch.esp [Version 1.0.8]
•  07 DLCMehrunesRazor.esp
•  08 DropLPUI.esp
•  09 DLCThievesDen.esp
•  0A DLCSpellTomes.esp
•  0B DLCThievesDen - Unofficial Patch.esp [Version 1.0.11]
•  0C Magus Lost Alteration Spells.esp
•  0D Dungeon.esp
•  0E DLCFrostcrag.esp
•  0F Daedric Shrine Ruins.esp
•  10 Denock Arrows.esp
•  11 Dragons Chamber_Final_1.0.esp
•  12 UOP Vampire Aging & Face Fix.esp [Version 1.0.0]
•  13 ISSUE192Copy.esp
 
Tweak Assorted
 
Reweigh: Arrows
Arrows set to maximum weight of 0.400000 
•  Arrows Reweighed: 5
•  Oblivion.esm: 4
•  Daedric Shrine Ruins.esp: 1
 
Reweigh: Ingredients
Ingredients set to maximum weight of 0.600000 
•  Ingredients Reweighed: 29
•  Oblivion.esm: 28

•  Daedric Shrine Ruins.esp: 1
 
Reweigh: Potions (Maximum)
Potions set to maximum weight of 0.600000 
•  Potions Reweighed: 0
 
Reweigh: Potions (Minimum)
Potions set to minimum weight of 1.000000 
•  Potions Reweighed: 230
•  Oblivion.esm: 222
•  DLCMehrunesRazor.esp: 2
•  DLCThievesDen.esp: 6
 
Reweigh: Staffs/Staves
Staffs/Staves set to maximum weight of 1.000000 
•  Staffs/Staves Reweighed: 228
•  Oblivion.esm: 228
```

and

```
Bashed Patch, PBash.esp
•  Overview
•  Tweak Assorted
 
Overview
 
Date/Time
•  4/9/2015 1:49:41 PM
•  Elapsed Time: 0:00:02.753
 
Active Mods
•  00 Oblivion.esm
•  01 Jog_X_Mod.esm
•  02 xulAncientYews.esp [Version 1.4.3]
•  03 DLCVileLair.esp
•  04 DLCShiveringIsles.esp
•  05 DLCMehrunesRazor - Unofficial Patch.esp [Version 1.0.6]
•  06 DLCVileLair - Unofficial Patch.esp [Version 1.0.8]
•  07 DLCMehrunesRazor.esp
•  08 DropLPUI.esp
•  09 DLCThievesDen.esp
•  0A DLCSpellTomes.esp
•  0B DLCThievesDen - Unofficial Patch.esp [Version 1.0.11]
•  0C Magus Lost Alteration Spells.esp
•  0D Dungeon.esp
•  0E DLCFrostcrag.esp
•  0F Daedric Shrine Ruins.esp
•  10 Denock Arrows.esp
•  11 Dragons Chamber_Final_1.0.esp
•  12 UOP Vampire Aging & Face Fix.esp [Version 1.0.0]
•  13 ISSUE192Copy.esp
 
Tweak Assorted
 
Reweigh: Arrows
Arrows set to maximum weight of 0.400000 
•  Arrows Reweighed: 6
•  Oblivion.esm: 5
•  Daedric Shrine Ruins.esp: 1
 
Reweigh: Ingredients
Ingredients set to maximum weight of 0.600000 
•  Ingredients Reweighed: 32
•  Oblivion.esm: 30
•  DLCMehrunesRazor.esp: 1
•  Daedric Shrine Ruins.esp: 1
 
Reweigh: Potions (Maximum)
Potions set to maximum weight of 0.600000 
•  Potions Reweighed: 0
 
Reweigh: Potions (Minimum)
Potions set to minimum weight of 1.000000 
•  Potions Reweighed: 230
•  Oblivion.esm: 222
•  DLCMehrunesRazor.esp: 2
•  DLCThievesDen.esp: 6
 
Reweigh: Staffs/Staves
Staffs/Staves set to maximum weight of 1.000000 
•  Staffs/Staves Reweighed: 228
•  Oblivion.esm: 228
```

My LO is completely random but yeah - note the reweight arrow and ingredients logs

**Comment by leandor** [comment]
Good idea :) For the python one, as the CBash one is very quick! As always, when I'm back home, I'll repeat the tests.

**Comment by Utumno** [comment]
@leandor: if you get round to it please test my latest iteration (306.201504182238) - should have fixed this issue completely and I also added enabling the patcher on selecting an option I would like some feedback on

**Comment by leandor** [comment]
Yeah, sorry! I'll get to it tomorrow, promise! 
I've got some time consuming stuff on my hands ATM, that is using up all my spare time on weekdays.

**Comment by Utumno** [comment]
Great thanks!

**Comment by Utumno** [comment]
Great thanks! Actually newest version is 306.201504192215 - did some patcher refactoring

**Comment by Utumno** [comment]
Great thanks! Actually newest version is 306.201504202157 - did some patcher refactoring (and some minor cleanup)

**Comment by leandor** [comment]
Ok, testing with these settings in both CBash and Python. They seem to be working perfectly, despite some differences in content between the resulting Bashed Patch esps. 

I could try figuring out why those differences are there, if you want... tried skimming through them and didn't found anything suspicious on the first look.


Here are the results:

![image](https://cloud.githubusercontent.com/assets/1095373/7244240/077452b4-e7af-11e4-8f09-d34b6d97186d.png)

CBash log:
```
Reweigh: Arrows
Arrows set to maximum weight of 0.100000 
•  Arrows Reweighed: 52
•  Oblivion.esm: 21
•  Cobl Main.esm: 7
•  Oscuro's_Oblivion_Overhaul.esm: 3
•  Unofficial Shivering Isles Patch.esp: 1
•  Oscuro's_Oblivion_Overhaul.esp: 14
•  bgBalancingEVCore.esp: 6

Reweigh: Ingredients
Ingredients set to maximum weight of 0.400000 
•  Ingredients Reweighed: 131
•  Oblivion.esm: 30
•  Cobl Main.esm: 70
•  Oscuro's_Oblivion_Overhaul.esm: 26
•  Unofficial Oblivion Patch.esp: 1
•  Oscuro's_Oblivion_Overhaul.esp: 4


Reweigh: Potions (Minimum)
Potions set to minimum weight of 1.000000 
•  Potions Reweighed: 308
•  Oblivion.esm: 4
•  Cobl Main.esm: 15
•  Oscuro's_Oblivion_Overhaul.esm: 42
•  Enhanced Economy.esp: 1
•  Oscuro's_Oblivion_Overhaul.esp: 231
•  RshAlchemy.esp: 4
•  bgBalancingEVCore.esp: 5
•  bgMagicEV.esp: 6

Reweigh: Staffs/Staves
Staffs/Staves set to maximum weight of 2.000000 
•  Staffs/Staves Reweighed: 260
•  Oblivion.esm: 57
•  Cobl Main.esm: 14
•  Oscuro's_Oblivion_Overhaul.esm: 20
•  Unofficial Shivering Isles Patch.esp: 4
•  Enhanced Economy.esp: 2
•  Oscuro's_Oblivion_Overhaul.esp: 163
```

Potions:
![image](https://cloud.githubusercontent.com/assets/1095373/7244307/ef06830e-e7af-11e4-9d6f-45b007664581.png)

Arrows:
![image](https://cloud.githubusercontent.com/assets/1095373/7244319/10366a4e-e7b0-11e4-8193-67f439481816.png)

Ingredients:
![image](https://cloud.githubusercontent.com/assets/1095373/7244323/227e7fac-e7b0-11e4-80ce-868fc6becd1b.png)

Staves:
![image](https://cloud.githubusercontent.com/assets/1095373/7244332/3eff47ec-e7b0-11e4-9406-f98360a11a2d.png)

Python log:
```
Reweigh: Arrows
Arrows set to maximum weight of 0.100000 
•  Arrows Reweighed: 169
•  Oblivion.esm: 128
•  Cobl Main.esm: 16
•  Oscuro's_Oblivion_Overhaul.esm: 19
•  bgBalancingEVCore.esp: 6
 

Reweigh: Ingredients
Ingredients set to maximum weight of 0.400000 
•  Ingredients Reweighed: 140
•  Oblivion.esm: 39
•  Cobl Main.esm: 74
•  Oscuro's_Oblivion_Overhaul.esm: 27

Reweigh: Potions (Minimum)
Potions set to minimum weight of 1.000000 
•  Potions Reweighed: 308
•  Oblivion.esm: 235
•  Cobl Main.esm: 15
•  Oscuro's_Oblivion_Overhaul.esm: 42
•  Enhanced Economy.esp: 1
•  RshAlchemy.esp: 4
•  bgBalancingEVCore.esp: 5
•  bgMagicEV.esp: 6
 
Reweigh: Staffs/Staves
Staffs/Staves set to maximum weight of 2.000000 
•  Staffs/Staves Reweighed: 260
•  Oblivion.esm: 228
•  Cobl Main.esm: 14
•  Oscuro's_Oblivion_Overhaul.esm: 16
•  Enhanced Economy.esp: 2
```

Potions:
![image](https://cloud.githubusercontent.com/assets/1095373/7244369/d753cdb0-e7b0-11e4-92e6-e097542bf314.png)

Arrows:
![image](https://cloud.githubusercontent.com/assets/1095373/7244376/f243bee6-e7b0-11e4-9247-3f1875c3ba10.png)

Ingredients:
![image](https://cloud.githubusercontent.com/assets/1095373/7244383/116d0af2-e7b1-11e4-8b7a-3ee04572e7ad.png)

Staves:
![image](https://cloud.githubusercontent.com/assets/1095373/7244392/25297652-e7b1-11e4-9c2b-2a4149f5c682.png)

**Comment by leandor** [comment]
Whoops... just noticed you committed changes just recently. Didn't picked up those, should I retest this again?

**Comment by Utumno** [comment]
Beauty - let me close this from the commits - the recent changes were on the labels only - so they wont be breaking anything (labels work correctly)

Thank you very much indeed - good catch and excellent work !

Re: differences - won't have any time now but if you spot anything buggy (when/if you get round to it) feel free to open another issue. IIUC there are differences between the patchers that do not affect the game - this may be one of them - there is a long long time I have not played though and my TES4Edit skills are rusty as hell

Please keep using latest of my branch - I make internal code changes all the time - I did some code deduplication changes in the patchers that I did not test thoroughly - they should be harmless but...
(they are in here in the latest five commits in my branch: https://github.com/wrye-bash/wrye-bash/compare/utumno-163-wip)

The more people use it (especially doing patches) the better

If you have time and energy maybe revisit #196 ?

I  am offzzzz

**Comment by leandor** [comment]
Actually, about the face import issue :) 

I was using it extensively a few weeks ago, and found that it's mostly working as intended. 

I was able to edit the face on the CS and after that importing back to the save successfully. 

I'll do a retest of that on the next weekend, since I'm intending to start a play-through of Oblivion and want to keep building my load order for that (man, it's very time consuming!) and that's a perfect opportunity to test these things :)

I'll post my feedback on that ticket when I'm done testing again. Thanks for the reminder!
