### ISSUE TITLE
Wine Compatibility

### ISSUE THREAD

**Issue by dankoB** [wrye-bash/wrye-bash#203]
I port many applications and games to the OSX platform and modded versions of many BethSoft games. Wrye Bash is integral tool for both Oblivion and Skyrim. I have noticed something has changed between the latest stand alone version and the stand alone version I have been using. WryeBash v304.2 works beautifully in Wine with no issues. Although when I try to update to the latest v305 I receive this message and the application will not load.

http://cl.ly/image/002Y0V240u3w/Screen%20Shot%202015-04-08%20at%2010.34.26%20AM.png

Any ideas what could be causing this issue and what I may need to do to rectify it?

**Comment by Utumno** [comment]
Can you python ? If not you can't do much. If yes - well at some point the python ,methods for moving/deleting/copying files were replaced by 'shell' methods  - shell being a windows only library. Start here: https://github.com/wrye-bash/wrye-bash/blob/02a5891c3f1a47e3f3763f772ed5cc767ec93415/Mopy/bash/balt.py#L1044

Unfortunately I have no time to look into this

Btw - please use the latest dev version while on windows: https://github.com/wrye-bash/wrye-bash/tree/utumno-163-wip - I need feedback (and the message on wine should be different)

**Comment by Utumno** [comment]
The `TODO implement this` line was from d4e8d9612618108d63f94773f657adff010184c0 - but the shell methods were plugged in at 35ad8630e0b5dab7cbf1ca425a17102622d0814e

Since v304.2 works we must look the intermediate commits to find out how the shellMove/Delete/Copy were implemented before

**Comment by Utumno** [comment]
@dankoB: could you try https://github.com/wrye-bash/wrye-bash/tree/utumno-wip ? Chances are it's fixed ;)
