### ISSUE TITLE
Windows Error 0xE06D7363

### ISSUE THREAD

**Issue by iliakonnov** [wrye-bash/wrye-bash#204]
I can't start wrye bash, becouse it crash at startup.
The same error on master branch and dev branch.
There is logs:
**BashBugDump_startup**

> Found Python at 'C:\Python27\pythonw.exe' 
> Launching Wrye Bash 306 in debug mode 
> [2015-05-10 14:25:10.539016] [0x000001e0] [trace]   Getting path to %LOCALAPPDATA%.

**BushBugDump**

> Wrye Bash starting
> Using Wrye Bash Version 306
> Python version: 2.7.9
> wxPython version: 2.8.12.1 (msw-unicode)
> input encoding: None; output encoding: None; locale: ('ru_RU', 'cp1251')
> filesystem encoding: mbcs 
> Searching for game to manage:
> bush.py   85 _supportedGames: Detected the following supported games via Windows Registry:
> bush.py   87 _supportedGames:  skyrim: C:\Games\The Elder Scrolls V - Skyrim
> bush.py  145 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
> bush.py  151 _detectGames: Set game mode to skyrim found in parent directory of Mopy:  C:\Games\The Elder Scrolls V - Skyrim
> bush.py  185 setGame: No preferred game specified.
> bush.py  166 __setGame:  Using skyrim game: C:\Games\The Elder Scrolls V - Skyrim
> testing UAC
> bosh.py 5262 __init__: Using libbsa API version: 2.0.0
> bosh.py 5268 __init__: Using libloadorder API version: 4.0.1
> bosh.py 5274 __init__: Using LOOT API version: 0.6.0
> C:\Games\The Elder Scrolls V - Skyrim
> Traceback (most recent call last):
>   File "Wrye Bash Launcher.pyw", line 88, in <module>
>     bash.main()
>   File "bash\bash.py", line 465, in main
>     frame = app.Init() # Link.Frame is set here !
>   File "bash\basher\__init__.py", line 4327, in Init
>     self.InitData(progress)
>   File "bash\basher\__init__.py", line 4358, in InitData
>     bosh.modInfos.refresh()
>   File "bash\bosh.py", line 4288, in refresh
>     if hasChanged: self.plugins.fixLoadOrder()
>   File "bash\bosh.py", line 3098, in fixLoadOrder
>     self.saveLoadOrder()
>   File "bash\bosh.py", line 3009, in saveLoadOrder
>     lo.SetLoadOrder(self.LoadOrder)
>   File "bash\liblo.py", line 414, in SetLoadOrder
>     _Clo_set_load_order(self._DB, plugins, num)
> WindowsError: [Error -529697949] Windows Error 0xE06D7363

P.S. Sorry for my bad English.

**Comment by Utumno** [comment]
Thanks - when you say master you mean 305 ? Or 305 works ok ?

It is failing inside libloadorder.dll - anything unusual with your setup ? Comtypes version ? Operating system ? XP ?

I use python 2.7.8 but I don't think it matters

Can you try my branch: https://github.com/wrye-bash/wrye-bash/tree/utumno-163-wip ?

Note to self: http://stackoverflow.com/questions/13360718/python-ctypes-and-dll-that-uses-a-com-object

**Comment by iliakonnov** [comment]
* When I say master I mean [master branch](https://github.com/wrye-bash/wrye-bash/tree/master)

* I tryed versions forom [sourceforge](http://sourceforge.net/projects/oblivionworks/files/Wrye%20Bash/), only 302 and older worked correctly.

* I'm using comtypes 0.6.2

* I using Win 7.

* Your branch worked correctly.

**Comment by Utumno** [comment]
Aha - thanks - I have a customized build of liblo in my branch - keep using my branch then and report whatever you find - will keep this open till I pin it. Do you have Oblivion_1.1.esm in your list ? When going back from my branch to dev (or master) does it blow again ? Was it because of some peculiar load order ?

The sourceforge versions are also here https://github.com/wrye-bash/wrye-bash/releases (or in git `git checkout v302`)

**Comment by iliakonnov** [comment]
No, I haven't got Oblivion_1.1.esm in my list.
After going back to master, It doesn't crashing anymore.
Thanks for link and your branch.

**Comment by Utumno** [comment]
So it was a one time fix of your load order I guess - lost in Oblivion, or rather Skyrim. I should have asked you to post your load order, damn - can you post it now ?

**Comment by iliakonnov** [comment]
Unofficial Skyrim Patch.esp
Dawnguard.esm
Unofficial Dawnguard Patch.esp
HearthFires.esm
Unofficial HearthFire Patch.esp
Dragonborn.esm
Unofficial Dragonborn Patch.esp
HighResTexturePack01.esp
HighResTexturePack02.esp
HighResTexturePack03.esp
Guard Build (HF) 1.esp
