### ISSUE TITLE
Problems with Cancel function in Wizard

### ISSUE THREAD

**Issue by lmstearn** [wrye-bash/wrye-bash#206]
Wrye Bash 305, Win 8.1
This is the code I run:
<addr>If DataFileExists("OOO 1.32-Cobl.esp")
Cancel ("An older version of COBL is detected. Please uninstall it before running this wizard")
EndIf
If DataFileExists("MMM-Cobl.esp")
Cancel ("An older version of COBL is detected. Please uninstall it before running this wizard")
EndIf </addr>
This works perfectly if the files are present. If they are not present the rest of the wizard selections are all bypassed and the finalize form is reached with no selections made.
Other combinations like "text" ["text"](text) [text] do not work at all.
Edit: I could try and OR those conditions with an ELSE to run the rest of the wizard. Will let you know.
Thanks, Utumno :)

**Comment by lmstearn** [comment]
Putting an Elif and Else for the rest of the code block worked. This can be reduced to an enhancement request perhaps?

**Comment by Infernio** [comment]
Can't reproduce, or I'm misunderstanding the issue. The wizard script I'm using:
```
SelectSubPackage "00 Core"
SelectSubPackage "01 Patch"

If DataFileExists("OOO 1.32-Cobl.esp")
Cancel ("An older version of COBL is detected. Please uninstall it before running this wizard")
EndIf

If DataFileExists("MMM-Cobl.esp")
Cancel ("An older version of COBL is detected. Please uninstall it before running this wizard")
EndIf 
```

The ESPs in question don't exist (obviously, I'm running this on a Skyrim install...), but the `SelectSubPackage` commands work fine:

![Cancel_Problem](https://user-images.githubusercontent.com/2845240/71046547-ead60080-2138-11ea-9fca-c017d7e992f4.png)
