### ISSUE TITLE
Bash Tags and the BOSS API

### ISSUE THREAD

**Issue by lmstearn** [wrye-bash/wrye-bash#208]
It used to be that Bash would take the Bash tag suggestions from the BOSS masterlists and consider them along with those in the plugin header when going through the Bashed Patch process. This functionality was removed, however. Unfortunately, the BOSS API was removed from BOSS and legacy support in LOOT was also removed, so this could complicate matters. After suggesting the mktaglist.py use, this was further investigated and, even though it says it will work with Oblivion's masterlist in the comments, the code for it doesn't seem to be present as it only looks for the YAML masterlist.

Ideally, the BOSS API would be restored and Bash's use of certain aspects of the API would also be restored but that could definitely take some time to do on both ends due to how much the code has changed since the removal.

In recollection there was a regex or a script used to help with the converting of the BOSS masterlist to the LOOT masterlist but it has not been located as yet.

**Comment by Infernio** [comment]
BOSS is definitely not coming back. For Bash Tag suggestions, we now use the bundled LOOT lists or your own LOOT installation.

**Comment by lmstearn** [comment]
Fair enough, as nothing has been done on the ML conversion as yet. However, [BOSS](https://www.afkmods.com/index.php?/files/file/2390-boss-masterlist-for-oblivion/) is very much alive, and in use.
