### ISSUE TITLE
Nested SubPackages in Installers

### ISSUE THREAD

**Issue by lmstearn** [wrye-bash/wrye-bash#211]
Version 3.04 Win 8.1
Suppose an installer has two subpackages a and b
If we then assign a new folder to a and call it c, Bain can currently access the files within, but not the subpackage itself with the SelectSubpackage command.
Logically, we would expect to access this with the command:
SelectSubpackage "a\c"
but given we can access files in c directly with e.g. Selectespm "filename", not  Selectespm "a\c\Filename",  on would infer that SelectSubpackage "c" would also be in the spirit of things.
Unfortunately not, as both fail.
If c is also a nested subpackage of b, then it is not unique.
The enhancement  requested is for SelectSubpackage "c" to work if c is a unique name, if not, the first such encountered in the package. If implemented, the packager might find this detailed in the updated documentation.

**Comment by Utumno** [comment]
I will say this __once__: ___STOP POSTING ONE ISSUE AFTER THE  OTHER___

**Comment by Infernio** [comment]
Wizards can't do anything you can't do in the GUI. That has always been a design goal. Since 'nested subpackages' aren't a thing in BAIN (and this is getting into dangerous, FOMOD-like, package however you want waters), this is a nogo.

**Comment by lmstearn** [comment]
Thanks for again considering what I was going on about.
Utumno: (I WONT BE POSTING ONE ISSUE AFTER THE OTHER)   :triangular_flag_on_post:
