### ISSUE TITLE
Wrye Bash 305 no longer starts

### ISSUE THREAD

**Issue by Sasha-alTherin** [wrye-bash/wrye-bash#212]
I cannot start the program either on its own or thru Mod Organizer.  Yesterday, it opened fine.  Today, it will not.  I have tried a full uninstall and reinstall of Wrye Bash using the installer and going with the standalone version.  I run Windows 7 Home Premium 64-bit with service pack 1.

I get a pop-up with the following text:

Error! Unable to start Wrye Bash.

Please ensure Wrye Bash is correctly installed.

Traceback (most recent call last):
  File "bash\bash.pyo", line 457, in main
  File "bash\bosh.pyo", line 24587, in initBosh
  File "bash\bosh.pyo", line 24359, in initDirs
  File "bash\bosh.pyo", line 5570, in **init**
  File "bash\bosh.pyo", line 5591, in refresh
  File "bash\loot.pyo", line 344, in Load
WindowsError: [Error -529697949] Windows Error 0xE06D7363

**Comment by Sasha-alTherin** [comment]
More information: the same 305 standalone executable works just fine when ran within Oblivion.  But running within Skyrim produces the aforementioned error report.

**Comment by Utumno** [comment]
https://www.google.be/search?hl=en&q=WindowsError:+[Error+-529697949]+Windows+Error+0xE06D7363&gws_rd=cr,ssl&ei=MR93VYTxIIO7swHYw4DoBA

What did you change since yesterday - something has to do with LOOT ?

**Comment by Sasha-alTherin** [comment]
Loot was updated a couple days ago before this happened.  I did create a couple rules for some mods to load in certain positions yesterday.  But that shouldn't cause WB to stop working.

**Comment by Sasha-alTherin** [comment]
Rolled back to a previous restore point, WB still had the aforementioned error.  Cleared the edited metadata in LOOT and WB loaded fine.  Re-did the metadata edits using Load After specific esp file(s) rather than assigning priority numbers and WB still loaded fine. Re-did the metadata edits using priority numbers and again WB loaded.

I am at a loss.  I do not see how LOOT's edits could affect whether or not WB runs.

**Comment by Utumno** [comment]
I do not see it either - but then I have never used loot (grumbles) - well I do, but I do not like it - anyway I did not write that code...

Please install latest 306 and see if the problem persists:

https://www.dropbox.com/s/ledb3ef3iaalp4p/Wrye%20Bash%20306.201506091707%20-%20Standalone%20Executable.7z?dl=0

and python https://github.com/wrye-bash/wrye-bash/archive/utumno-163-wip.zip

**Comment by Sasha-alTherin** [comment]
306 is fine.  Since wiping out the metadata edits in LOOT, 305 was working fine too.  All I can guess is that I may have made some mistake in LOOT that wasn't replicated this time around.

**Comment by Utumno** [comment]
yep which made loot.Load crash - please keep using 306, I need all the feedback I can get :)
