### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#220]
- [ ] Eliminate all `except: pass` in the code. _ALL_
- [ ] Unswallow tracebacks - __BAD__:

 ```
try:...
except SomeError: raise AnotherError('you should burn in hell')
 ```
 __GOOD__:

 ```
try:...
except SomeError: raise AnotherError, 'you belong to paradise', syc.exc_info[2]
 ```
 Check: http://stackoverflow.com/a/16414892/281545

**Comment by Arthmoor** [comment]
What exactly does "except: pass" do and why are they all bad?

**Comment by Utumno** [comment]
That's technical :D

**Comment by Utumno** [comment]
Another Code quality issue for the backburner
