### ISSUE TITLE
Remove the messages tab

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#221]
It's not doing anything anymore and stands in the way of finalizing #163 - I simply have to edit completely useless code. _Nevertheless_ I want this to be done with chirurgical precision - that is carefully extract all messages related code to new modules from bosh and basher (in a dedicated branch) and then in a single commit cut it off.

I actually like the idea of the messages tab - I just can't bear the maintenance overhead at this time. One of the first things to be done for 307, I got plans it stands on their way.

**Comment by Arthmoor** [comment]
Do you mean the "PM Archive" tab or the "People" tab? IMO, they've both been useless from the start but every time I've ever suggested ditching them, someone says they want to keep them :P

**Comment by Utumno** [comment]
:D The PM

The People's one is useful for technical reasons - namely it makes me keep the UILists and associated data stores general enough - plus is related to the Tank classes hierarchy and must go with them

Yes I know you want them gone - first the PM though :)

**Comment by alt3rn1ty** [comment]
@Utumno - The work on the ReadMe HTMLs, and associated screenshots is done as of two days ago

http://forums.bethsoft.com/topic/1536340-wrye-bash-thread-105/page-5#entry24407922

^^ Link for download is in that post

**Comment by Utumno** [comment]
Thanks @alt3rn1ty much appreciated - I am traveling at the moment and need a couple days - I will go through it ASAP.
