### ISSUE TITLE
Apply BCF fails when the converted installer is present

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#223]
~~To the eternal bewilderment of the current maintainer.~~

Pinned it (does not mean it is an easy fix though !)

Simply the converted and original (non BAIN) files may very well have the same CRC - the crc being the crc of all their files

The broken data structure is `crc_installer` - simply does not have a crc for all installers - this may be the root of other bugs - #93 comes to mind.

This particular issue:
create a converter for a simple archive, add all files to the converted BAIN'ed archive then try to apply the converter - boom - is unpacking the bain'ed archive (I guess if the bained archive sorts after the non bained): reproducer: https://www.dropbox.com/s/8unx35ig396f5xo/WryeBash%23223.zip?dl=0

blows at the call `self.arrangeFiles(SubProgress(progress,lastStep,0.7))`

Happily the uses of crc_installer are few

**Comment by BeermotorWB** [comment]
Tested BCF apply this morning with no error. Structure was created properly and wizard was added. I've reached out for some more testers to apply some of the  BCFs I created.

**Comment by Utumno** [comment]
Thanks !
