### ISSUE TITLE
[Skyrim] SKSE cosaves are not deleted when save files get deleted.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#224]
As the title says. If you delete a save file using Bash's saves tab, the SKSE cosaves that go with them are not removed.

Functionality to delete OBSE cosaves when an Oblivon save should already exist to make this easy to port over.

May also be necessary to check FOSE and NVSE cosaves when the time comes to integrate the Fallout games into Bash.

**Comment by Utumno** [comment]
Thanks - did it work back in 305 ?

**Comment by Arthmoor** [comment]
Yep, looks like that still works in 305.

**Comment by Utumno** [comment]
Good catch there @Arthmoor ! Fixed in my branch (along with cosave backups never being deleted)
