### ISSUE TITLE
BAIN Wizards - Back button confuses selections

### ISSUE THREAD

**Issue by ghost** [wrye-bash/wrye-bash#225]
Bug Reproducible in 305, and 306 development builds - Reported in this post http://forums.bethsoft.com/topic/1525110-wrye-bash-thread-104/page-2#entry24180058 on BGS Forum.

After advancing through a wizards selection pages, then using the Back button to go back in the selection pages, make different selections to the previous choices, and then proceed with the wizard advancing forward again

Selections can be confused after the wizard is applied, noticeable by compairing the sub-packages box on the Installers Tab with what you would expect to now be selected and installed.

Mod file to reproduce with BAIN Wizard : http://www.nexusmods.com/skyrim/mods/13268/?
( To fully test the Wizard - Needs Dawnguard.esm, Hearthfires.esm and Dragonborn.esm dlc plugins installed - If you dont have them just use a text file as a dummy plugin with the same name )

**Comment by Metallicow** [comment]
I have noticed this behavior myself with the WizBAIN DEMO and a couple of other issues with it or my scripting.
I think the issue may revolve around when the events take place, (indentation helps with this) and how they are parsed not only when in action(running a wizard), but maybe also a first parsing of the code(right before the wizard is actually *shown*)...

I'll try to look into this more now that I am back modding again. Consult Lojack for deeper issues within wiz script.

**Comment by Utumno** [comment]
See: https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=168369 and ex

**Comment by Infernio** [comment]
Can't be both `works for me` - which means it couldn't be reproduced - and `bug` - which means we were able to reproduce it and acknowledge it's a bug.
