### ISSUE TITLE
Option to list dependencies on a particular mod

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#227]
An option added to the right click menu when right clicking on a mod that will show you what other mods in the load order use it as a master would be pretty handy.

Similar to how we seem to have an option to "List Masters", "List Dependencies" would be great.

**Comment by Utumno** [comment]
>  what other mods in the load order use it as a master

Other active mods or any mods ?

**Comment by Arthmoor** [comment]
I would lean toward any mods in the folder at the time. Marking the active ones if possible, though I don't know how hard that might be.

**Comment by Utumno** [comment]
Implemented in 306.201509150914, mod menu, List Dependent 

Review (including my english, I do not like  _Dependent Mods of Oblivion.esm_ very much - Mods dependent on Oblivion.esm ?)

Of course we also need to edit the readme

And that's _really_ the very last piece of code for 306 ;)

**Comment by Arthmoor** [comment]
Works good, though you labeled it "List Dependent" when it should be "List Dependencies" :P 

The UI box should probably say:

"Mods dependent on modname.esp"

**Comment by Utumno** [comment]
Thansk ! Will do - I mark non active mods with `__` - is this ok ?

**Comment by Arthmoor** [comment]
Yeah, marking inactive ones that way is fine.
