### ISSUE TITLE
MustBeActiveIfImported tag appears to do nothing

### ISSUE THREAD

**Issue by Supierce** [wrye-bash/wrye-bash#229]
The "MustBeActiveIfImported" tag appears to do nothing, at least in my case. To reproduce:

1) Install Better Cities Primary Resources-16513-6-0-3, which contains BetterCities.esp with only a MustBeActiveIfImported Bash tag.

2) Activate the esp and create a Bashed Patch.

3) Note that the tag is ignored and the esp is inactivated and merged into the Bashed Patch.

Vorians, the Better Cities author, says the tag works for him, but another user reported the same failure I'm seeing. I've confirmed that 305 behaves the same way.

Users are prompted to "Deactivate before merging" which they can choose to ignore, but again that's exactly the same behavior as not having the "MustBeActiveIfImported" tag at all.

**Comment by Utumno** [comment]
See: http://forums.bethsoft.com/topic/1525110-wrye-bash-thread-104/page-4#entry24269144 for the report
- this seems broken in 305 too

**Comment by D4id4los** [comment]
@Utumno I think I have a fix for this bug in commit 183eda1f0cf8e3e83fc8c27084d0dfc24a7305bf. 

Does this follow the new contributing guidelines correctly?

**Comment by Utumno** [comment]
@D4id4los wouldn't the change in 2c701b9fb6d7b48f69849f5e505e4e3840f766e4


```
@@ -996,5 +996,8 @@ def _ask_deactivate_mergeable(self, active_prior_to_patch):
         for mod in active_prior_to_patch:
-            tags = bosh.modInfos[mod].getBashTags()
+            mod_inf = bosh.modInfos[mod]
+            tags = mod_inf.getBashTags()
             if u'Filter' in tags: unfiltered.append(mod)
             elif mod in bosh.modInfos.mergeable:
+                if u'MustBeActiveIfImported' in tags:
+                    continue
                 if u'NoMerge' in tags: noMerge.append(mod)
```

suffice ?

**Comment by D4id4los** [comment]
Ah sorry, I didn't have a look at your utumno_wip branch and just worked of dev. 

https://github.com/wrye-bash/wrye-bash/commit/2c701b9fb6d7b48f69849f5e505e4e3840f766e4 would fix one part of the issue, probably in a nicer way then my code, namely incorrectly disabling the plugin prior to building a patch. It would however not activate an imported plugin marked with MustBeActiveIfImported if it was for some reason not active before building the patch.

For this reason I put my activate imported plugins marked with the tag code after the code that activates the bashed patch after it has been completed. I do think such a function is consistent with the description of the tag given in the documentation

> Must be active to function correctly even if it is imported into the Bashed Patch.

**Comment by Utumno** [comment]
I wouldn't activate mods - needs careful thought (plugin limit could throw a BoltError for instance etc etc) _and_ docs. Maybe patch the description of the tag given in the documentation I the lines "the only function of this is that Bash won't ask to deactivate" - we could of course go into detecting muxt be active mods (including resource ones) but this goes far - 310 far

**Comment by D4id4los** [comment]
Alright then I'll see about making the change to the docs and I'd say scrap my branch and use your fix for incorrectly disabling plugins.

**Comment by D4id4los** [comment]
Ok, I figured out how to revert the old commit on my branch. It now contains only https://github.com/wrye-bash/wrye-bash/commit/57d03824abc383fd69b6ee095204335e08ea1615 which is the discussed change to documentation.

**Comment by Utumno** [comment]
Thanks will squash it into my branch when I get round to merging
