### ISSUE TITLE
Consider a Automatic Builds Repo?

### ISSUE THREAD

**Issue by Metallicow** [wrye-bash/wrye-bash#23]
I see other projects do something like
BuildBot or TravisCI for builds.

I guess something like this would be nice further down the line after refactoring.
For example bash could have a seperate repo it dumps daily builds into.
Or triggered manually when needing a build.

Not sure how much work this would be to setup...?
Just opening this for Comments/Ideas/Suggestions on an automated build process.
Does anyone involved have any experience with this sort of thing?

**Comment by Utumno** [comment]
This is being addressed in #474 and co
