### ISSUE TITLE
App Launcher Changes

### ISSUE THREAD

**Issue by Metallicow** [wrye-bash/wrye-bash#230]
To Whom It May Concern:

The GIMPShop software has been corrupted evilly by a apparently mean programmer.
The known installer has added malware, and since the original author has dropped away from the project, this other programmer has corrupted the installer.
This leads me to one conclusion: He/She liked GIMP's UI Interface more than GIMPShop's "Photoshop-like" UI and has took it out on the installer source code.
This also means that the GIMPShop source **CANNOT be trusted AT ALL**.
**This has been verified by me in a virtual machine.**
Therefore GIMPShop should be removed from the supported App Launchers. Users of Wrye bash should not be led to install now known bogus/crapware. -The Monkeys.
What this means is if users still have a copy of the software installer that is not corrupted(A Offline backup), then they can add it to the one of the 18 Custom Launchers in bash.ini or provide a Shortcut link with newer bash at thier own risk.

On the flip-side, There has been a project over the years that has finally came into the light of Professional Graphic Artists as a usable Open Source alternative 'like-Photoshop-like'.
That app is called Krita [https://krita.org/]. It has my full support and recommendation, and a few Kickstarter bucks to employ the full time programmers to try and make it as fast as Photoshop by Krita version 3.1 with a new app code base for rendering/etc.
Add in that built-in App Launcher to replace the GIMPShop one.

I'll review the other Open Source Apps supported for mal-ity also as a stone would.

**Comment by Utumno** [comment]
Hi!
You may set up a branch removing GIMPShop and adding Krita and let me merge it

**Comment by alt3rn1ty** [comment]
Hi Moo, good to see you again

Didnt know about GIMPShop, but also reference anything on sourceforge .. Dont go there. Its been known for a while that installers get piggyback ad/malware
Use original sites where possible such as ..
http://www.gimp.org/
( Have a read of their statement "GIMP PROJECT'S OFFICIAL STATEMENT ON SOURCEFORGE'S ACTIONS" )

Original GIMP is fine

**Comment by Metallicow** [comment]
Hey alt3y, long time no talk. thanks for the looking-into effort.

Anyway, GitHub GUI apparently updated to a new codebase(GitHub Desktop)(AGAIN) now I have to delete my fork as to GUI update problems. The new GUI shows both the orgs branches and my forks branches in the same dropdown/tree which is undesirable for me...

..Adding GitHub GUI Icon to launcher links priority also... as well as other desired must have apps.

Deleted my fork and may refork again at a later date to see if GitHub Desktop has its bugs fixed...
They fixed at least one from my complaint long ago and did a few enhancements also. :)(

**Comment by Metallicow** [comment]
Metallicow-App-Launcher branch created successfully.
Can start work again.

BTW, what are the "randomish" dict numbers for? (with the gimpshop16/24/32.png code)

**Comment by lojack5** [comment]
16/24/32 means the icon size. Ex: gimpshop16.png means it's the png file for the 16x16 icon for gimpshop.

**Comment by Metallicow** [comment]
@lojack5 I mean the code like this in bosh 305

        u'gimpshop16.png' : 1135,
        u'gimpshop24.png' : 2435,
        u'gimpshop32.png' : 2895,

I forked off dev. What was the randomish dict numbers for in 305 and are they still needed somewhere or in the process of moving?

**Comment by Utumno** [comment]
That's not an issue that needs any code _at all_ . It needs just _removing_ the ini entries and the respective gifs and adding the new ones - which I am reluctant to do as it means more binary cruft. 
I will close this as backburner. If you are sure it's worth the hassle just submit me a patch removing the ini doing those. And Respect my time - I am releasing, and have more serious issues that adding/removing App launchers.

**Comment by Metallicow** [comment]
See #237
Should be ready.

**Comment by Arthmoor** [comment]
Is this even an issue that needs to be addressed given the official position from the Gimp authors is basically that Sourceforge are now scumware dealers and they had nothing to do with this? I think this kind of thing unfairly casts Gimp as the bad guy when this isn't the case.

**Comment by Metallicow** [comment]
The original gimpshop was a fork of gimp and eventually dropped off. It is no longer supported anyway.
I have nothing against gimp, just that we shouldn't be pointing users to known infected installers/code.
It really would be great if the original gimpshop dev finished work on the project. I didn't remove gimp, just gimpshop launcher in favor of a more supported app, which is more photoshop-like anyway. And yeah, I read the Sourceforge articles... sad that developers are dropping it because of these instances.

**Comment by Arthmoor** [comment]
Oh. Gotcha. I guess I thought Gimpshop and Gimp were the same thing. :P

**Comment by Infernio** [comment]
Superseded by #237, as mentioned above.
