### ISSUE TITLE
Masterless blank esps

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#231]
Triggered by https://github.com/wrye-bash/wrye-bash/pull/165/

See [post by Lojack](http://forums.bethsoft.com/topic/1525110-wrye-bash-thread-104/page-5#entry24298604):

[quote name="Lojack" post="24298604" timestamp="1441414506"]
As far as I can tell, Bash still generates new mods files, and does not copy paste via the template (edit: except what I found below): [Blank mod creation function](https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/basher/mods_links.py#L221)

As for getting rid of the template, I never liked the templates anyway, :tongue:
But anyway, looks like the only reference to the template blank esps is [here](https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/basher/mods_links.py#L221), so just replace that bit with generating the file and you should be good.
[/quote]

and [my reply](http://forums.bethsoft.com/topic/1525110-wrye-bash-thread-104/#entry24299168) - edit: and lo's instructions: http://forums.bethsoft.com/topic/1525110-wrye-bash-thread-104/?p=24299220

Goals:

- [ ] bin the templates - generate the esps on the fly always (make sure this works for fallout etc)
- [ ] remove masters (or just don't add them ?) on the fly
- [ ] menu items in mods - new mod without masters
- [ ] option for new projects (with or without masterless esp)
- [ ] readme updates

**Comment by Utumno** [comment]
@Arthmoor @Sharlikran: the new Mod created by the mods tab File > New Mod... command is diffrent from the template in Mopy/templates/game/Blank Mod.esp. Can you tell what the differences are and which one to keep ?

**Comment by Arthmoor** [comment]
Both files in Skyrim produced an 87 byte file with Skyrim.esm listed as a master and nothing more. As far as I can tell in xEdit, these files are identical.

For Oblivion, the one from File->New Mod should be kept. It produces a file with nothing but Oblivion.esm set as a master. The blank template has an extra string added to the author field that it doesn't need.

**Comment by Utumno** [comment]
Excellent thanks. Is the format of these records documented somewhere ?

The Blank template  is 84 bytes vs 85 bytes in New Mod.esp - which is generated by the code and I would like to keep. Seems though that it contains the author field - or do I get it wrong ?

**Comment by Arthmoor** [comment]
Yep, for Skyrim, it's here: http://www.uesp.net/wiki/Tes5Mod:Mod_File_Format
For Oblivion: http://www.uesp.net/wiki/Tes4Mod:Mod_File_Format

They may be somewhat outdated, but the TES4 header record information is all correct.

The blank template file for Oblivion doesn't really need to have an author set. The one the UI makes works just fine without it.

**Comment by Utumno** [comment]
>  For Oblivion: http://www.uesp.net/wiki/Tes4Mod:Mod_File_Format

I have seen that but still I miss info - anyway digging a bit I realized that the Blank template has indeed a string in author's field (CNAM) and no SNAM record. So I just keep the New Mod (which is the one the code generates, yey)

Note to self - 0.8 in binary is `CD CC 4C 3F` (little endian representation in the files ! - note the size of the record is given as `41 00 00 00` == 65 + 20 the size of the [record's header](http://www.uesp.net/wiki/Tes4Mod:Mod_File_Format#Records) = 85 bytes.

**Comment by Utumno** [comment]
Did not remove the templates - should I (yes) ?
