### ISSUE TITLE
Bash Tag List Not Populated

### ISSUE THREAD

**Issue by TheHermit-OrmrSnaethorsen** [wrye-bash/wrye-bash#234]
Hello, I'm a complete neophyte to github, so I apologise if I've posted this issue in the wrong place or fashion.

I've been using Wrye Bash for some time. I currently use Wrye Flash for FNV and it all works fine.
But I've just installed the Standalone version (via installer) for Skyrim as directed in the S.T.E.P. guide and I've run into an issue.
I'm not sure whether this is normal behaviour for the Wrye Bash for Skyrim or not.
Basically, the Bash Tags list isn't populated with all known bash tags, whereas in Wrye Flash it is.

Wrye Flash:
<a href="http://imgbox.com/w4qMxGCp"><img src="http://5.t.imgbox.com/w4qMxGCp.jpg" alt="w4qMxGCp.jpg" /></a>

Wrye Bash:
<a href="http://imgbox.com/jQ6ka4tw"><img src="http://3.t.imgbox.com/jQ6ka4tw.jpg" alt="jQ6ka4tw.jpg" /></a>

Without the list I'm unable to add the necessary Bash Tags to my Skyrim mods.
I [i]could[/i] do it manually, I suppose, but I get the feeling that that wasn't meant to be the case.
If somebody could help me I would really appreciate it. I've already tried uninstalling and reinstalling -- No difference.

**Comment by Utumno** [comment]
Dunno what the STEP project is

Try the Standalone from this post: http://forums.bethsoft.com/topic/1525110-wrye-bash-thread-104/?p=24121794

**Comment by TheHermit-OrmrSnaethorsen** [comment]
I assumed everybody knew of the S.T.E.P. project. It's a comprehensive community driven Skyrim installation guide. It also has a section for Wrye Bash installation; one that has worked for me in the past: http://wiki.step-project.com/Guide:Wrye_Bash

I tried the Standalone version from the thread you linked. Everything loaded up fine, but I still have same limited number of Bash Tags in the list. Is there any way for me to populate that list manually?

**Comment by Utumno** [comment]
Aha - now I get what you mean. You mean the tags are not _many_. Supporting all the Bash tags for skyrim is not yet done, sorry to disappoint you - help needed ;)

See #151 and the experimental thread here; forums.bethsoft.com/topic/1534516-wipz-wrye-bashexp-skyrim-patcher-update-thread-3

Good news is the version you are using should be much faster/bug free than the 305 - so stick with it till 306 is released.

**Comment by TheHermit-OrmrSnaethorsen** [comment]
Ahh! Okay, a part of me did wonder if that was the case, but I recall an older version of Wrye Bash for Skyrim that I was using [around this time last year] *did* have all of the tags. I'm close to finalizing my load order and sorting my plugins with LOOT, naturally. LOOT provides bash tag suggestions. I'm probably stating the obvious, but are you saying that those tags cannot be added in any way until 306 is released? In other words, is it ineffectual for me to create a bashed patch for my game at this point in time if it won't be able to use all required tags?

**Comment by Utumno** [comment]
You were probably using the Sharlikran experimental version from the thread linked to. 306 will have no more tags I am afraid but you can use Sharls version which contains most of 306 fixes/improvements.

Once 306 is out I hope I will find some time to invest on that version and merge it to official - _but_ I am the only one coding for Bash - so help is needed. You can help by using the version from Sharl and posting bugs etc in his thread. Closing this for now.

Thanks :)
