### ISSUE TITLE
Package script and installer fixups

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#235]
The installer creation keeps failing on me: https://www.dropbox.com/s/2ywhmvdszhmwpag/build%20-%20235.log?dl=0

On the other hand I would like the script to:
- [x] instead of relocating non repo files to just copy the repo files needed to /scripst/temp/mopy and package them from there - reasons:
  - I have hard links/junctions etc in my repo which are messed up
  - code is complicated (as the error linked to shows)
  - if I get a crash in middle operation (I had a BSOD recently but I was lucky) non repo files (which in my case are numerous) would end up in temp
  - keep in mind that we may set up tests packages etc in the repo

@lojack5: could you have a look as you know your way around there ?

Other issues:
- [x] Bash automaton is not working
- [x] version number should be made more flexible - at list major, minor, patch should be supported
- [x] COPY option does not work for installer - files from my repo get bundled along Apps/some_link.lnk.
- [x] Apps/some_link.lnk gets bundled in python and standalone too - not sure about 306

Bugs (reach the users):
- [x] game.template is included in the standalone (present in 306)
- [x] standalone created by the installer adds a bunch of empty Bash subfolders: basher, chardet, game (has the tempalte σo not empty technically), patcher (present in 306 but of course 307 adds bosh, game/fallout4)
- [x] we were missing to delete files that we absolutely must like `Mopy/bash//game/game.__init__py`

**Comment by lojack5** [comment]
When I designed the relocating thingy I went with moving non-repo files instead of moving repo files simply because that would be less files to move overall.  It could be rewritten to copy repo files, though that will increase build times (since copying takes time, but moves are essentially free).

Anyway, I don't know if I'd even have time to do that until I get a short break, school/work has me drained mostly of my time.

**Comment by Utumno** [comment]
I see - thanks - still in school ? Grab Pycharm and get the professional edition with your school email. If you don't fall in love with it I will do you a homework :ice_cream:

See the guide in the wiki

In my case non repo files are a lot - plus it is really cleaner this way (think hard links, crashes and whatnot). Better avoiding relocating completely. And the files are a couple megabytes so not really a problem in modern machines

I can get away with a fresh clone but I would like to see this fixed - it does not work for me in my repo (some file is not closed apparently so not moved so the traceback I see ?)

**Comment by lojack5** [comment]
Well, I don't think I'll be able to fix @wrye-bash-automoton directly.  It'll need to be replaced.  I created it with 2-factor authentication so that when storing its user info, that info cannot be used to hijack the account (the token has read-only privileges on its account).

However, for the same reason I can no longer log into that account:
 - I don't remember the email I used to create it (I believe it was a brand new gmail account, but I have no idea what it was)
 - I don't have the authenticator for the account anyway, as I lost it when I got a new phone.

So options are:
 1. repeat the initial process with a new user to perform the same role. We then have the same potential issue again: If the information is lost, there's no way to fix it.
 2. create a new user, but do not use 2 factor authentication. Drawbacks here are: either we need to secretly all know the login info for it (how to securely pass that info on to new people as needed?), or we store that info in plaintext in the `globals.py` file, like the token is currently.  That of course, opens up the new account to a malicious attack.  Granted, the automaton cannot actually do anything in the wrye-bash repositories, but it will be a hassel if someone decides to take over the read-only account so we can no longer use it.

What are your thoughts? I like the 2 factor authentication route, but we'll need some way to ensure if it breaks / someone needs to edit it, they can get in (recovery codes would work), but so only trusted people have that info.

**Comment by lojack5** [comment]
Turned out to be easier than I thought to get this working.  No need for @wrye-bash-automoton anymore.  I'll wait for your merge before I do mine, since it messes around with quite a few things.

**Comment by Utumno** [comment]
Thanks I can do the merge for you (it's just a cherry pick actually). I should have created an issue for the automoton to meta - this issue is for the package script in wrye Bash, blame it on the 306 release dizziness - frankly the 306 release was a huge headache - but now everything should be pretty much smoothed out for 307 (wikis, readmes, meta repo, release procedure and so on)

Meanwhile if you could address the issue here for the package script it would be much much appreciated. I expect it would greatly simplify the script so I can then make it more flexible to easily roll betas out

**Comment by lojack5** [comment]
Ok, branch `lojack-package-script-improvements` has some fixups, etc.  If you can think of any other requests there, please let me know so I can do it all in one branch.  The option you're looking for to make it not move the files but copy a clean repo instead is `--non-repo=COPY`.  It's still defaulted to `MOVE` since that's quicker than copying (especially all those image files).

**Comment by Utumno** [comment]
Thanks lo - will have a look tommorowishzzzzz

**Comment by Utumno** [comment]
@lojack5: would like to have this in the beta - rebased on dev and added a fixup commit: https://github.com/wrye-bash/wrye-bash/commits/utumno-lojack-package-script-improvements

One snag is that I learned about scandir and want to have this in for the beta also - I plugged it alright in the python version: b58e95127bc127052635cb59d14eb925df20ae5a but the standalone exe is built but does not startup. I am on a crappy laptop with a crippled setup but I suspect has something to do with scandir requiring some msvc libraries - try installing it via pip.

scandir.walk offers a quite solid performance over os.walk, and that's very important for BAIN performance - basically the getmtime(True) and refreshCrcDate performance sink is precisely os.walk

Having also some thoughts on version names - maybe a way to allow a string version that will be displayed on the download archives and bugdumps while having a 30X.X.X.X version for the exe anyway ? Not terribly important - I just may give that a shot

I liked the enum :)

**Comment by Utumno** [comment]
Getting this:

```
[package_for_release]: Creating installer distributable...
[package_for_release]:  WARNING: Non-repository files are present in your source directory.
[package_for_release]:           You have chosen to move the non-repository files out of the source directry temporarily.
[package_for_release]:  Relocating non-repository files:
[package_for_release]:   macro\py
[package_for_release]:   macro\macro
[package_for_release]:   bash\patcher\oblivion
[package_for_release]:   _inis
[package_for_release]:   macro
[package_for_release]:  Restoring non-repository files
[package_for_release]:  Error calling creating installer, aborting creation.
Traceback (most recent call last):
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\scripts\package_for_release.py", line 516, in BuildInstallerVersion
    RelocateNonRepoFiles(non_repo)
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\scripts\package_for_release.py", line 387, in RelocateNonRepoFiles
    shutil.move(src, dst)
  File "C:\_\Python27\lib\shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
Error: Destination path 'scripts\temp\macro\macro' already exists

```
which I was getting before in my main machine with MOVE option

**Comment by Utumno** [comment]
And a couple details - detect fast invalid version numbers:
```
C:\Dropbox\eclipse_workspaces\python\wrye-bash\scripts>package_for_release.py
No release version specified, please enter it now.
>y
2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
ERROR: Could not locate git.  Try adding the path to your git directory to the PATH environment variable.
GitPython is not set up correctly, aborting.
```

Display a success error message on success:

```
C:\Dropbox\eclipse_workspaces\python\wrye-bash\scripts>package_for_release.py -g"C:\_\Git\bin" --non-repo COPY
No release version specified, please enter it now.
>306.1
2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
WARNING: Your wrye-bash repository is dirty (you have uncommitted changes).
WARNING: You are building off branch "utumno-lojack-package-script-improvements", which does not appear to be a release branch for 306.1.
Using file version: 306.1.0.0
Creating Python archive distributable...
Building standalone exe...
 Generating comtypes...
 Calling py2exe...
 Adding icon...
 Compressing with UPX...
Creating standalone distributable...
Creating installer distributable...
 WARNING: Non-repository files are present in your source directory.
          You have chosen to make a temporary clean copy  of the repository to build with.
 Copying repository files to temporary location...
 Calling makensis.exe...
```

**Comment by Utumno** [comment]
Finally I still can't make it get scandir in the standalone:

> Unhandled exception at 0x740B8FAC (msvcr90.dll) in Wrye Bash.exe: 0xC0000005: Access violation reading location 0x0023FFFF.

I suspect that is because I have teh 64 dlls ? Installed scandir from:

https://pypi.python.org/packages/2.7/s/scandir/scandir-1.2.win-amd64-py2.7.exe#md5=896625409dc758be28ce52e27abeeb27

**Comment by Metallicow** [comment]
I'd guess ya its the 64 and 32 bit mixing. you will need 32bit for your python.
Try uninstalling the exe installer and install with pip.
pip normally tries to build a binary .whl for the platform.
...Other than that you could use setuptools and the zip package.
It might also be a problem with py2exe as it is not updated anymore.
You might try PyInstaller if that doesn't work.
PyInstaller now supports python 3 and normally snakes all imports without having to place extra hacks in the code sometimes as with py2exe. 
I recall PIL(not pillow) always had problems when using Image you would have to import all the format Plugins to get it to work right with py2exe. might be some strange issue like that also.

**Comment by Utumno** [comment]
And another occasional traceback
```

C:\_\Python27\python.exe C:/Dropbox/eclipse_workspaces/python/wrye-bash/scripts/package_for_release.py -w -g c:\\_\\Git\\bin --non-repo COPY
No release version specified, please enter it now.
>307.2016.0314.1631
2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
WARNING: You are building off branch "utumno-wip", which does not appear to be a release branch for 307.2016.0314.1631.
Using file version: 307.2016.0314.1631
Building standalone exe...
 Generating comtypes...
 Calling py2exe...
 Adding icon...
 Compressing with UPX...
Error: [Error 145] The directory is not empty: u'C:\\Dropbox\\eclipse_workspaces\\python\\wrye-bash\\Mopy\\build\\bdist.win32\\winexe\\collect-2.7\\encodings'
Traceback (most recent call last):
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/scripts/package_for_release.py", line 903, in main
    exe_made = CreateStandaloneExe(args, file_version)
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/scripts/package_for_release.py", line 339, in CreateStandaloneExe
    rm(os.path.join(mopy, u'build'))
  File "C:/Dropbox/eclipse_workspaces/python/wrye-bash/scripts/package_for_release.py", line 145, in rm
    elif os.path.isdir(node): shutil.rmtree(node)
  File "C:\_\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\_\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\_\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\_\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\_\Python27\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\_\Python27\lib\shutil.py", line 254, in rmtree
    os.rmdir(path)
WindowsError: [Error 145] The directory is not empty: u'C:\\Dropbox\\eclipse_workspaces\\python\\wrye-bash\\Mopy\\build\\bdist.win32\\winexe\\collect-2.7\\encodings'

Process finished with exit code 0

```

**Comment by Utumno** [comment]
@lojack - been debugging this but can't get it to work - for one COPY somehow still uses the old Mopy. For two I realized there arew some bugs - mentioned in the OP - namely the standalone has some empty folders created - present in 306.

Fixed a couple of bugs though here: https://github.com/wrye-bash/wrye-bash/commits/utumno-lojack-package-script-improvements

**Comment by Utumno** [comment]
Ok closed but left review label on cause I would like a second pair of eyes @lojack5. Thanks :)
