### ISSUE TITLE
Windows XP Support

### ISSUE THREAD

**Issue by Ortham** [wrye-bash/wrye-bash#24]
@Wrye-Bashers: Should we support Windows XP users?

I've decided not to in BOSS because in a few months XP will become a security risk, and by supporting it I'd be encouraging the same complacency in XP users that has kept them with it since Windows 7 was released.

However, I acknowledge that Bash is a separate project with separate goals, and if need be I'll rebuild the DLLs I provided so that they support XP (I can't remember if they already do, so I've PMed someone who would be able to test).

**Comment by Infernio** [comment]
@Utumno What do we do with this issue? I have no clue if WB still supports XP (I would assume not, CBash or some other dependency probably broke it).

**Comment by Utumno** [comment]
XP? :P

Nothing broke it but XP is right out

**Comment by Metallicow** [comment]
It should with python 2 but when bash moves to py 3 it will be obsolete.

**Comment by Utumno** [comment]
Actually it's loot that broke XP support but that must have been already since for ever

**Comment by Metallicow** [comment]
You could actually make it work again, but it would be a biggest pain in the ass to deal with even the smallest of changes. The difference here is that there are differences in not only python, but all the other tools that bash uses that may or may not use python. You must remeber that python is a programming language first and a scripting language second(some call it glue).

**Comment by Metallicow** [comment]
Another problem is that MS never fixed the 64bit problem, so yea its a matrix problem with a real small file and plenty of people will spend a lot of time looking at it, hence its security issues.

**Comment by Infernio** [comment]
Definitely obsolete as of 310 (the py3 version we're using doesn't even support Windows *7* anymore lol).
