### ISSUE TITLE
File operations should be case-insensitive

### ISSUE THREAD

**Issue by grv87** [wrye-bash/wrye-bash#242]
I try to install mod from .7z file. It has directories `Data\textures`, `Data\meshes` etc. However, directories in my game have capitalized names: `Data\Textures`, `Data\Meshes`.
1. Instead of putting files from mod into existing directories Wrye Bash creates new directories with non-capitalized names. 
2. Depending on situation Wrye Bash and the game see either one or another directory. I tried several times and got the following cases:
   - Wrye Bash after installation reports that the mod still has missing files
   - The game sees new directories only and loses all main graphics.
3. When I move all files from `textures` to `Textures` then Wrye Bash reports that the mod has missing files.

Also, note that I have `obcaseinsensitive` registry key set to 0 (for other applications such as Cygwin).

**Comment by Utumno** [comment]
Wrye Bash is not prepared to handle a case insensitive file system (and I doubt by your resulst that Oblivion can either) - this would need a rewrite that is simply out of the question now, so closing as won't fix. However see the first post in the forums thread for reporting: http://forums.bethsoft.com/topic/1536340-wrye-bash-thread-105/#entry24321878 a bug and post the required information, I may have a look sometime in the future

**Comment by grv87** [comment]
Did you mean case sensitive?

**Comment by Utumno** [comment]
Yep - please post me your bugdump and the rest of info needed as detailed in the link above - I need a wiki page on this @wrye-bash/bashers anyone ? - name it "[github] Reporting issues" and carry the info from the forums first posts there
