### ISSUE TITLE
Additional Screenshot Path for Oblivion Reloaded

### ISSUE THREAD

**Issue by Supierce** [wrye-bash/wrye-bash#246]
Oblivion Reloaded now provides an alternative screenshot method, with a path of Oblivion\Screenshots and a default file format of jpg. I wonder if WB should add that location and file format to WB's screenshot tab. I'm not suggesting that this be a user option - just that the path could be scanned by default, along with the default Oblivion screenshot path.

**Comment by lojack5** [comment]
I know this is not what you're requesting, but for the time being, it's something you can do if *all* of your screensshots are stored in this special directory.

In **Oblivion.ini** / **Skyrim.ini**, there's a line under the `[Display]` sections that reads:
```sScreenShotBaseName=ScreenShot```

That's what Bash reads to determine where to look for screenshots.  If you change that, then Bash will look in the correct spot.  Note that changing it will also change the default location of screenshots , so non-OR screenshots will also end up in that location, which maybe you don't want, let me know if that's the case.

@utumno: will double checking on the code for the above information, I noticed your "cache?" [comment](https://github.com/wrye-bash/wrye-bash/blob/ab640cd822b0827796a22c5df4abdf2e8d60a952/Mopy/bash/bosh.py#L5784) here.  I'd say only if you also put in size/modification time detection so it'll reload it on file changes.  That is, we want to not have to relaunch Bash in order for it to pick up if the user changes the INI setting.  Of course that would probably be best implemented in the base class (`INIFile`), so all INI settings are cached for any INI file, and only re-read when a file modification is detected.

**Comment by Utumno** [comment]
Yes ofc - thanks for commenting. The ini tab needs caching definitely though - it's one of the remaining big performance issues - haven't profiled yet but something there takes ages - it's in my local TODOs since I rewrote the RefeshUI API. Note that it kicks in in BAIN too via the RefrehUIMods beast. Caches are notoriously tricky to implement correctly - an interesting problem there - yes in INIFile

Could you enligthen me as to what `ALL, TWEAKS, TARGET` mean here: https://github.com/wrye-bash/wrye-bash/blob/ab640cd822b0827796a22c5df4abdf2e8d60a952/Mopy/bash/basher/__init__.py#L1575-L1593

In the same code note for instance that in the `ALL` path RefreshUI is called twice on the iniList in the same call of RefreshPanel - but the real performance hit comes exactly from not caching the ini settings IIRC -

**Comment by Utumno** [comment]
@Supierce - sorry for hijacking your issue - I think this would best be solved by indeed adding extra locations for screenshots - the code is not just ready yet - technical: `.dir` has ~140 occurrences and adding extra dirs involves hacking the `ScreenshotsData.dir` attribute. The XXXData.dir attribute I already tried to encapsulate but was not trivial. Once encapsulated we may either have it treated like a list of dirs to cater for the screenshot multiple dirs or move this mechanism inside the subclass. To decide we must first encapsulate (so we visit all usages) and put some thought on how it might be generalized. Probably File_Open should become UIList_Open (not really a file command and one I use a lot - never liked it being buried in the File menu)

**Comment by Supierce** [comment]
It hadn't occurred to me to just change the path for Oblivion's screenshots to agree with OR's. Maybe a readme addition is all that's needed. For that matter, OR's screenshot path is configurable too, so maybe this is a non-issue. How about the ,jpg format? Is that a problem for WB?

**Comment by lojack5** [comment]
@supierce: yep,  most normal image extensions are supported: bmp, jpg, jpeg, png, tif, gif

@utumno: ALL, TWEAKS, TARGETS - `TWEAKS` means only re-read the tweak files, `TARGETS` means reread the target INI files (like the ones that tweaks work on), and `ALL` means both.  Also, if you're interested in making Bash scan two folders at once, you may want to look at `PathUnion` [here](https://github.com/lojack5/Wrye-Bash-Python-3/blob/76cac7db8e58fe35d69319a85e323462114b9407/src/bolt/Path.py#L688), it basically makes a filesystem consisting of multiple source folder.

**Comment by Utumno** [comment]
@Supierce : could you phrase the readme addition for me and tell me where to stick it ? As it seems this will go to backburner fro a while, but I do not abandon the idea (and certainly not the refactoring idea)

@lojack5: Thanks - I may come for more re: the ini tab. Re: path union nice - though I think I will keep simple in this case. From a 10 miles high view maybe consider changing `list` to something else ( `ls` ?)

**Comment by Supierce** [comment]
In Oblivion.ini / Skyrim.ini, there's a line under the  [Display]  sections that reads:
 sScreenShotBaseName=ScreenShot 

I can't find a way to change that so that screenshots are stored in Oblivion\Screenshots. Anyone know the proper entry?

**Comment by Utumno** [comment]
Can't try now but is this just for the name - Like ScreenShot 1,2,3 etc ? Maybe there is another setting for the directory ?

**Comment by InsanePlumber** [comment]
[url=http://afkmods.iguanadons.net/index.php?/topic/4246-screenshot-directory-can-it-be-changed/]Maybe this will help.[/url]

**Comment by Supierce** [comment]
Thanks guys. Since the oblivion.ini path needs to include the base filename, it won't work as a common solution for Oblivion Reloaded screenshots, which use a different filename structure. The best solution will be to edit OblivionReloaded.ini to dump its screenshots in the root directory like Oblivion does. To me, it's not an ideal solution, but I'll come up with some readme text for it.

**Comment by Supierce** [comment]
Here it is. Let me know if you need something different. Thanks!
_________________
Oblivion Reloaded Screenshots

By default, Oblivion stores its screenshots in Oblivion's root folder, while OBlivion Reloaded uses Oblivion\Screenshots. To have all screenshots appear under Wrye Bash's Screenshots tab, find the following line under the [Display] heading in Oblivion.ini:

SScreenShotBaseName=ScreenShot

...and add the path to the Oblivion\Screenshots folder, i.e.:

SScreenShotBaseName=C:\Bethesda Softworks\Oblivion\ScreenShots\Screenshot

Note that the base filename ("Screenshot" or any other base name you like) must be included in the path or Oblivion's native screenshots will not work.

**Comment by Utumno** [comment]
Well I went ahead and added the info only to realize that Bash has a menu item for that:
http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#screenshots-commands

Next Shot

Two devs + 2 power users vs Bash: 0-1

So if you could just rephrase this a bit :)

Then I will edit the readme (editing the readme takes ages for me) and temp close this - but I am not satisfied. As far as I can tell enabling this alternate directory results in Bash not seeing the screenshots in base dir - also I am not sure what "Oblivion's native screenshots will not work." means

**Comment by Supierce** [comment]
Utumno, unless you add a "Change Path" or "Additional Path" command, I don't see a way to do what we're after with those menu options. We need to either change the storage location of Oblivion's native screenshots or have WB check both locations. I suppose we could tell people to change the OR path to "Oblivion\", but I don't like the idea of dumping OR's screenshots into OB's root folder.

"Oblivion's native screenshots will not work." means that when you press the PrntScr key, nothing happens.

**Comment by Supierce** [comment]
Utumno, here's a slightly reworded version of my earlier readme suggestion. Since the screenshot section already exists, maybe this could just be added as a note:
___________________________________________________

NOTE for users of Oblivion Reloaded

By default, Oblivion stores its screenshots in Oblivion's root folder, while Obivion Reloaded uses Oblivion\Screenshots. To have all screenshots appear under Wrye Bash's Screenshots tab, find the following line under the [Display] heading in Oblivion.ini:

SScreenShotBaseName=ScreenShot

...and add the path to the Oblivion\Screenshots folder, i.e.:

SScreenShotBaseName=C:\Bethesda Softworks\Oblivion\ScreenShots\Screenshot

IMPORTANT: The base filename "Screenshot" (or any other base name you like) must be included in the path or Oblivion's native screenshots will not work. Pressing the PrntScr key will do nothing.

**Comment by Utumno** [comment]
I am sure I had posted this:

> Thanks @Supierce - I will edit the readme accordingly and will consider adding additional paths when the code is ready (as explained in my notes above) .

My (non) connection apparently...
