### ISSUE TITLE
GitHub Desktop GUI walkthoughs

### ISSUE THREAD

**Issue by Metallicow** [wrye-bash/wrye-bash#248]
Everything is housed on GitHub, so use GitHub GUI as default.

Coming back and forth between Git Desktop GUI's and using/learning them can be more time spent than coding the new fix or whatever.

I suggest a wiki page and/or a old-school screenshot developer walkthough tutorial, like alt3rn1ty's pic tuts.

As sometimes different git actions in different gitApps can not only seem confusing as to what they do compared to the other.

Ex: compare GitHub GUI against GitTortoise/etc..
TODO: Add links to the issue leading to the wiki page/etc specifically dealing with Wrye Bash.

**Comment by Utumno** [comment]
No - I only support msysgit - I explicitly removed tortoise gui instructions from here: https://github.com/wrye-bash/wrye-bash/wiki/%5Bgit%5D-Syncing-a-Fork-with-the-main-repository

where I say first thing:

> NB: We only support the msysgit suite - any support requests should be for that platform.

@Metallicow: when I say something like this and you go and post an issue like that you are just spamming me and wasting my time - take this as a friendly warning. From now on _expect posts like this to be deleted without notice_
