### ISSUE TITLE
OR file extension issue

### ISSUE THREAD

**Issue by Supierce** [wrye-bash/wrye-bash#249]
Oblivion Reloaded now adds an additional save file, just like the .obse file, but with a .or extension. Currently, WB isn't aware of this when doing file operations, leading to orphaned and misnamed saves. Since OR is a popular extension of Oblivion that appears to be here to stay, I recommend that WB include the .or files when doing file operations.

**Comment by Utumno** [comment]
No longer needed: http://forums.bethsoft.com/topic/1614408-wrye-bash-thread-113/page-7#entry25309018
