### ISSUE TITLE
List Script Extender Plugins

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#254]
> Got a feature request unless I'm somehow overlooking it: could Bash generate a list of script extender plugins similar to how it does the mod list with the BBCode formatting and version numbers? 

On behalf of deaths_soul via BGS forum.

**Comment by Infernio** [comment]
Superseded by #456:
>  Offer functionality to dump a list of all SE plugins, their versions, compatibility status, etc.
