### ISSUE TITLE
Renaming saves/screens/installers fixups

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#259]
- Checking for valid filenames and catching failures should be revisited. Renaming a screenshot with a filename containing `:` in windows results in the files being deleted _forever_. Renaming with `filename<` results just in broken UI (file displays `filename<` but is not ofc renamed).
 EDIT: the `:` weirdness was due to ADS: http://stackoverflow.com/q/34097936/281545. So:
 - [ ] common _bolt ~~or env~~_ code for validating filenames
 - [x] refresh the ui in case of failure so it does not display the wrong filename -> https://github.com/wrye-bash/wrye-bash/commit/9a20d7fc5366b414faa555e4135794b83c4ad5a5 TODO: saves (edit: done: 20b66f1962050bf2f023e29850e481aa68a14ff4)
- [x] when a file is open (in 7z for instance) in installers the file is copied with the new name and then unlinking fails of course resulting in duplicating the file. Yak -> done: https://github.com/wrye-bash/wrye-bash/commit/cffd0985a0b22f3cd0104d6aaf92694d7fae32ee TODO: saves (edit: done: 20b66f1962050bf2f023e29850e481aa68a14ff4)
- [ ] renaming auto/quicksaves.bak is broken - cofiles are not moved along (heck they are not detected to begin with)
- [x] when renaming fails if user had hit enter it will open the files (in screens and installers...). ~~wx bug - added in #197~~ - edit:solved: https://github.com/wrye-bash/wrye-bash/commit/fdbc802aadc6ae354fb9b31b565c6c4a8e720772 - YEY!
- [x] markers - see http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/page-3#entry25188212 - done: https://github.com/wrye-bash/wrye-bash/commit/4a5c1ddaf35bd8abcb12cbdb4f5ec35e67bd819c
- [ ] common rename link (see Installers/Saves/screen etc rename links) -> 1f99a8582a355e35d57465342c3c8e6cd6bc6118
- [ ] save details - validate !
- [ ] mods details - validate !
- [ ] Incremental renames (file, file (1), file (2),...) should have a common pattern in all of bash
- [ ] BAIN renaming detects if filename ends in a number and adds to that - remove this ? -> kept for scrreenshots - need to ask
- [ ] consider using shellMove instead of Path.moveTo -> done

Backburner - see 20b66f1962050bf2f023e29850e481aa68a14ff4 for todos:

- [ ] screenshots/installers reselect (and details) !
- [ ] factor out common code in OnLabelEdited

**Comment by Metallicow** [comment]
I am guessing maybe this should best be handled with a simple RegEx?

regex = ???TODO???

Ex: myfile.ext
 1. (re.search)GetFilePath-->CheckIfAlreadyExists -->
 2. (OPTIONAL AskForOverWrite) -->
 3. LoopUntilFileName(Num)+1.ext -->
 4. SuggestFileName(Num#).ext in Dialog -->
 5. If answer == OK: then write file to disk

 #. Loop AskDialog if: if user suggests saving as a file that already exists.

... What all cases should Wrye Bash handle? 
... Just generally or more in depth...?

**Comment by Metallicow** [comment]
@Utumno Could you provide a code example of the ``< or : or etc`` being deleted forever on MSWindows?...
Certain chars are not allowed in filenames specifically on certain OS's.
Maybe there is a better answer to the dilemma...

**Comment by Utumno** [comment]
@Metallicow : your posts are here: https://www.dropbox.com/sh/83nkrwjjavfkzwp/AAD2xvJnFvJRKJ5n0HVt4gAoa?dl=0. Instead of posting here without having carefully read the OP _go ahead and rebase and clean up your branches as I said a million times and specifically commented_. I am tempted to just revoke your write rights in this repo.

This post will self destruct - I expect to see your branches rebased ASAP - or I am taking over.

https://github.com/wrye-bash/wrye-bash/compare/metallicow-installer-details
https://github.com/wrye-bash/wrye-bash/compare/metallicow-wx3-wxphoenix-compatibility
https://github.com/wrye-bash/wrye-bash/compare/metallicow-306beta-fixes
https://github.com/wrye-bash/wrye-bash/compare/metallicow-app-launcher

**Comment by Utumno** [comment]
@lojack: the `:` is really puzzling me - moreover when I try to reproduce in the debugger it disappears - a "heisenbug". It is related to the `:` being the drive separator and actually moveTo fails here: https://github.com/wrye-bash/wrye-bash/blob/98c729f4bb62345365ed28d932420e4c2ceaebdf/Mopy/bash/bolt.py#L967

But why it is deleting the file is beyond me - actually the file is replaced with a zero bytes `filename` if I try to rename it to `filename:`. I know of course how to prevent this a(and will do) but I 'd like to unserstand what goes on here.

**Comment by lojack5** [comment]
Not sure how to deal with this.  Probably need some sort of "is valid name" check, disallowing things that windows rename dialog would normally disallow (even if `:` does have meaning, Windows Explorer forbids you from using it.)

**Comment by Utumno** [comment]
@lojack5: i've already dealt - for what was going on see: http://stackoverflow.com/q/34097936/281545.
