### ISSUE TITLE
Wrye Flash Save Game profile issue

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#261]
In a [Fallout 4 post](http://forums.bethsoft.com/topic/1558694-wipz-wrye-flashexp-fallout-4-installer-update/?p=24670284) a user is reporting that the profiles are not working 

Game mode Tested

Fallout 4

Wrye Bash GitHub Branch

https://github.com/Sharlikran/wrye-bash

Current Behavior:

When in Fallout 4 available save games does not appear to change.

Expected Behavior:

Saves from current profile should be the only files showing in the list of available save games.

**Comment by Sharlikran** [comment]
@lojack5 I know you are busy and @Utumno has been doing a fantastic job on refactoring.  However, a 2nd pair of eyes on this would be appreciated to restore this much used and much needed functionality.  I didn't even know it was gone until someone reported it in my experimental branch.  At first i thought it was me until I tested it with Skyrim using files from the dev branch.

**Comment by Utumno** [comment]
I don't understand what is the problem or when it came about - was it not present in 306 ?

**Comment by lojack5** [comment]
I saw this post on the FO4 forums, is this happenning in all games, or just Fallout 4?  Also, from the sound of the post on Fallout 4, it sounded like the profile was setup properly, but the *game* didn't see them, which leads me to think that the Fallout4.ini setting we use doesn't apply to Fallout 4 like it did the previous games.

**Comment by Utumno** [comment]
Please link to that post

**Comment by Sharlikran** [comment]
Are you sure you want the [Fallout 4 post](http://forums.bethsoft.com/topic/1558694-wipz-wrye-flashexp-fallout-4-installer-update/?p=24670284) linked?  To eliminate confusion I tested with Skyrim and the dev branch.  So this not only has nothing to do with Fallout 4 but nothing to do with my branch or Fallout in general.

@Lojack After reading what you said I deleted my Oblivion and Skyrim INI files.  I see that only Oblivion has a SLocalSavePath in it by default.  So is it that the intended functionality?  Am I wrong and Wrye Bash doesn't copy the files and simply changes the SLocalSavePath variable in the INI file?  Can you clarify that for me?

I reset all of the INI files for Skyrim, Fallout 3, Fallout NV, and Fallout 4.  Fallout 4 and Skyrim do not have SLocalSavePath in the INI file.  Which leads me to believe that only Oblivion, Fallout 3, Fallout NV use that.  I will test this later with Skyrim and Fallout 4 just to be sure.  As long as I know that the functionality is to change the INI file and not actually copy the files.  

I would test more but I have had one hour sleep.  A friend of the family called me and I had to take him to the hospital.  I haven't had time to do any more testing.  I had no idea that's what was happening.  It has always been my understanding that the files are copied because it takes a long time depending on how many file are in the saves folder to refresh the list.  Which affirmed what I had been told and that the files were being moved rather then simply changing an INI variable and then refreshing the list.  I must have been misinformed.

**Comment by Utumno** [comment]
>  Am I wrong and Wrye Bash doesn't copy the files and simply changes the SLocalSavePath variable in the INI file

Yes - since forever. Why on earth would it copy files around ? Where was this in the readme ?

Well probably time for a readme patch ?

But we need to see if this is true for Fallout4 as well - that's why I wanted the fallout post

**Comment by Sharlikran** [comment]
I changed my ticket.  @lojack5 can I get confirmation.  I think there is more going on here.  Rather then me retyping what I posted here is [my response on the Beth forums](http://forums.bethsoft.com/topic/1558694-wipz-wrye-flashexp-fallout-4-installer-update/?p=24680328).

**Comment by Utumno** [comment]
Closing this as works for me - reopen as needed
