### ISSUE TITLE
Reduce Installers tab memory usage

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#263]
Just loading the Installers tab kicks memory usage of Bash up by ~340 MB in my setup (290 installers, 20 projects). That's clearly a bug - labeling as TODO so it does not show up on second post yet. Off hand profiling suggest that we are creating a huge number of 'unicode' objects - see profiling of ShowPanel in: https://github.com/wrye-bash/wrye-bash/commit/0de07ee3f12fbd853a9a0992ada45f241d323648

```
                                 types |   # objects |   total size
====================================== | =========== | ============
                               unicode |     1585016 |    193.05 MB
                <class 'bash.bolt.Path |      186374 |     11.38 MB
                                  dict |         367 |     10.80 MB
                                   set |        2410 |      1.07 MB
                                  list |       10335 |      1.01 MB
                                   str |        7998 |    360.01 KB
               collections.defaultdict |         290 |     56.52 KB
    <class 'bash.bosh.InstallerArchive |         246 |     46.12 KB
                                  long |        1710 |     27.60 KB
                                   int |         990 |     11.60 KB
    <class 'bash.bosh.InstallerProject |          22 |      4.12 KB
     <class 'bash.bosh.InstallerMarker |          22 |      4.12 KB
  <class 'bash.bosh.InstallerConverter |          89 |      2.78 KB
                    wrapper_descriptor |          29 |      1.13 KB
                                 float |          44 |    704     B
```

Opening this to start investigating - NB this triggers errors in bashed patch creation that are probably memory errors - see report: http://forums.bethsoft.com/topic/1570906-wrye-bash-thread-106/#entry24717040

> any scan of the installed packages, followed by an attempt to create a bashed patch (CBASHO, fails with the following traceback:
> 
> ```
> CBash encountered an error LoadCollection Check the log.
> Traceback (most recent call last):
> File "bash\balt.py", line 413, in <lambda>
> File "bash\balt.py", line 1575, in _conversation_wrapper
> File "bash\basher\patcher_dialog.py", line 191, in PatchExecute
> File "bash\patcher\patch_files.py", line 469, in buildPatch
> File "bash\cint.py", line 15414, in load
> File "bash\cint.py", line 144, in NegativeIsErrorCheck
> bash.cint.CBashError: 'Function returned an error code.'
> ```

_'Function returned an error code.'_ - duh

@lojack5: when you come to it any ideas on where those ~200 mb of unicode strings come from would be appreciated

Under #219.
- [ ] refershDataScrDate is the culprit - creates an inordinate number of path instances.
- [ ] `src_sizeCrcDate` used in method above duplicates the info in fileSizeCrcs which is the data structure we use - rewrite refershDataScrDate  so it uses the latter

**Comment by leandor** [comment]
I've got that traceback above on my install just now... the message has two extra lines above that weren't included in the above dump, here's the complete text:

```
ModFile: Error - Unable to open "Oblivion.esm" as read only via memory mapping.
LoadCollection: Error - Unknown exception


CBash encountered an error LoadCollection Check the log.
Traceback (most recent call last):
  File "bash\balt.py", line 413, in <lambda>
  File "bash\balt.py", line 1802, in _conversation_wrapper
  File "bash\basher\patcher_dialog.py", line 191, in PatchExecute
  File "bash\patcher\patch_files.py", line 469, in buildPatch
  File "bash\cint.py", line 15414, in load
  File "bash\cint.py", line 144, in NegativeIsErrorCheck
bash.cint.CBashError: 'Function returned an error code.'
```

Can I provide any help in debugging this one?

**Comment by Utumno** [comment]
I am afraid no, I think it's just buried deep in refreshDataSizeCrc - cyclic references. Just memory error. 'Function returned an error code' is, well, grotesque. What we would need is getting a map of the CBash error codes in cint so we are at least sure.

**Comment by Utumno** [comment]
Closed but still we need more work in phase II of BAIN refactoring.
