### ISSUE TITLE
Rework docs detection and display by BAIN 

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#266]
Docs handling by BAIN never appealed to me:
- [ ] we lack a specification of how docs are handled by BAIN - see #219 ~~for docs strange behavior on complex packages~~ that was because of package layout rules for complex packages, still there is some strange exceptions allowed in the code (like readmes in the root folder)
- [ ] docs for a mod that are installed should be displayed by the docs folder instead of having the archive unpacked (duh)
- [ ] doc detection should be reworked to detect a list of docs and display this to the user as a menu if more than one are present (the Open Readme item should become a TransLink)
- [ ] consider mirroring the installers structure to docs folder
- [ ] docs for a BAIN installed esp should be registered in the doc browser
- [ ] ability to set a main doc if many are detected

Happily there is a persistent currently unused Installer attribute (readMe) that could serve as the list of docs and a hasReadme which could be used as the main one - or vice versa.

SEE also svn: https://sourceforge.net/p/oblivionworks/enhancements/64/

**Comment by Utumno** [comment]
@Arthmoor: specification time: where does BAIN expect to find docs - in complex vs simple packages ? 

- should Bash look for readmes at the top level of a complex package or only inside the subpackages ?
- should we treat specially a docs folder ? a screenshots folder ?
- what are the rules inside a subpackage (therefore IIUC inside a simple package) ? what should we do with:

           Data\
           readme.txt

 or:

           textures\
           some.esp
           readme.txt

It's really important I have a concrete (and complete) specification but an answer to the above will do for now.

**Comment by Sharlikran** [comment]
The Fallout 4 cosave is `.f4se`

**Comment by Utumno** [comment]
I mean the header magic :) Ooops I put #266 while I meant #236

**Comment by Sharlikran** [comment]
It's always the name of the Script Extender. So the 4 letters for Fallout 4 is F4SE because the script extender is F4SE.

As a reference this is already in constants.py for each game. This is the section for [Fallout 4](https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/game/fallout4/__init__.py#L95-L102).

```python
#--Script Extender information
class se:
    ## TODO: verify filenames once F4SE is released
    shortName = u'F4SE'                      # Abbreviated name
    longName = u'Fallout 4 Script Extender'  # Full name
    exe = u'f4se_loader.exe'                 # Exe to run
    steamExe = u'f4se_steam_loader.dll'      # Exe to run if a steam install
    url = u'http://f4se.silverlock.org/'     # URL to download from
    urlTip = u'http://f4se.silverlock.org/'  # Tooltip for mouse over the URL
```
Also as a quick note, the TODO: isn't needed, those are the names.
