### ISSUE TITLE
Update Fallout 4 Support

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#268]
I have made some changes to Lojack's Fallout 4 support.  I will begin to detail the changes here.  All changes will be in [268-fallout4-support](https://github.com/Sharlikran/wrye-bash/tree/268-fallout4-support) on my fork [Sharlikran/wrye-bash](https://github.com/Sharlikran/wrye-bash)

Branch Structure:

In order to maintain an aggregate collection of changes for testing I have rebased this in the following manner.

wrye-bash : dev
wrye-bash : dev-skyrim-patcher-update <<-- placeholder for new changes
Sharlikran/wrye-bash : dev-skyrim-patcher-loot-update
Sharlikran/wrye-bash : dev-fallout-patcher-update
Sharlikran/wrye-bash : 268-fallout4-support

Current changes:

I have made some miscellaneous tweaks to the Fallout 4 support files.  The following are the more notable changes.

- [x] Added check for Fallout4.esm : libloadorder doesn't bother adding game's master because it always loads first and does not write it to plugins.txt.  However, it must be there since you can't activate or deactivate it in Wrye Flash.
- [x] Added FO4Edit App Button
- [x] Updated F4SE Steam DLL

This issue is currently a WIP

**Comment by Sharlikran** [comment]
@Utumno 

```Python
Wrye Bash starting
Using Wrye Bash Version 307.0.6
Python version: 2.7.8
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('en_US', 'cp1252')
filesystem encoding: mbcs 
Searching for game to manage:
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 310, in main
    ret = bush.setGame(opts.gameName, opts.oblivionPath, bashIni)
  File "bash\bush.py", line 159, in setGame
    foundGames_, name = _detectGames(workingDir, bashIni)
  File "bash\bush.py", line 94, in _detectGames
    foundGames_ = _supportedGames() # sets _allGames if not set
  File "bash\bush.py", line 65, in _supportedGames
    game_path = get_game_path(submod)
  File "bash\env.py", line 44, in get_game_path
    subkey, entry = submod.regInstallKeys
ValueError: need more than 1 value to unpack
```

I'm causing an error somewhere now that I have rebased all my branches.  151-skyrim-patchers works for Skyrim and starts just fine.  I looked in #151 and #177 but I don't see any additional changes you made that would break something in bash\game.  You probably told me in a commit but I missed it.  I have an install registry key for Fallout 4 that should be in __init__.py.  Is that where I need to start?

**Comment by Sharlikran** [comment]
I'm gonna have my work cut out for me because of the refactoring.

```
fail bash\basher\gui_patchers.py
fail bash\basher.py
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 380, in main
    import basher
  File "Wrye Bash Launcher.pyw", line 76, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\basher\__init__.py", line 4299, in <module>
    from .gui_patchers import initPatchers
  File "Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\basher\gui_patchers.py", line 714, in <module>
    class DestructiblePatcher(importers.DestructiblePatcher,ListPatcher): pass
ImportError: caused by ImportError(u'caused by NameError("name \'ListPatcher\' is not defined",)',)
```

There needs to be a knives stabbing me in the eyes emoji like WrinklyNinja's icon.

**Comment by Sharlikran** [comment]
@Utumno You have ```_ListPatcherPanel``` in gui_patchers.py but not in ```patchers\special.py``` am I reading that correctly?  No need to explain python programming it's way over my head.

**Comment by Utumno** [comment]
> EDIT1: I'm just going to compare my 307.0.6 version from the Nexus with 151-skyrim-patchers. I'll have to merge the changes slowly into a test branch until I find the change.

Or just wait for me - it will be 5 mins for me usually - but see rebase tip below

> EDIT1: I changed it to _ListPatcherPanel since it's basically like Relev/Delev.

Yep - so rebase often ! this way you review the changes that are made in dev and you can easily pinpoint tracebacks like this one

> You have _ListPatcherPanel in gui_patchers.py but not in patchers\special.py am I reading that correctly? No need to explain python programming it's way over my head.

Yes that's why I changed the name - basically there are two different classes. Underscore marks the class as private to the file it's in - this _ListpatcherPanel should (and is) only used in the gui_patchers file

**Comment by Sharlikran** [comment]
> Or just wait for me - it will be 5 mins for me usually - but see rebase tip below

Ehh I have to learn more anyway.  It's not an annoyance or anything.  I just have to push myself a little more to understand it all.  It's fine.

**Comment by Sharlikran** [comment]
In regards to : Updated save file extension for class CoSaves - b7d5a42a6655183c89a907a587ae769f9fe1229f

The original regex was looking for save games ending in .ess which is Oblivion.  My comment also asks why there is an (f?) and is very specific.  If it's not updated I would think Wrye won't see Fallout's save files.

If multi game support that was started about what, 5 years ago--is to continue and new games like Skyrim/Fallout 4/FO3/FNV support are going to be added lots of little things like this will have to change.  I'm not always going to feel comfortable justifying and explaining my changes.  When you look at my changes if the change doesn't make sense then don't add it.  However, I can't guarantee what will and won't work outside of Oblivion.

You are the only person working on this project other then Diana.  But Diana's only just started looking at things recently.  However, Bethesda enthusiasts like myself play more then just Oblivion.  Since this version is basically the "Oblivion" version and since Skyrim was the previous game that was never fully integrated and since Fallout 4 is the current game it might be a good idea to own a copy of at least those three games.  Sticking with what you are familiar with, which seems to be Oblivion, sets the tone that Wrye is for Oblivion only which I know isn't your end goal.

**Comment by Utumno** [comment]
Yeah no worries I see the point - I have already commented on that on a commit comment expalining the f is for the first backup - will try to adapt

**Comment by Sharlikran** [comment]
I had surgery 3/25/16 so can't talk after this for a while.

All commits for the Fallout 4 changes should be in dev and I have already explained why above or in the commit.  If you don't want to add something that's fine but you might get users stating that something doesn't work the same as Sharlikran's version and you will have to track it down when I have already taken care of it.  I don't see the point in causing yourself any extra work.

As for fallout4\records.py there is no reason not to include the file as is since Fallout 4 is bassed off of Skyrim.  I'm pretty sure I have explained this elsewhere.

**Comment by Utumno** [comment]
All the best with your health !

Adding those several hundred lines of code adds several hundred _warnings_ among others and I would prefer having those split up, reviewed then added. Will get back with specific comments but for now I tried to split up a my self so I will need you to tell me if I missed anything. Will post this ASAP

In short, changes that are user visible should definitely be in dev - placeholder code that is not plugged to anything should _absolutely not_ be on dev - that's a general principle in SCM not specific to our discussion or indeed to bash

**Comment by Sharlikran** [comment]
In reference to the comments in 1e45218894836558d7b8e3c7c43d28f4fb3c225a

Not feeling that the FO4 changes are safe when some things are placeholders is a bit senseless.  Until the release of the Fallout 4 CK no modding tool will be accurately updated or be stable or safe.  All the Nexus mods should be updated with the FO4CK but that didn't happen with Skyrim so I'm not holding my breath that it will happen for Fallout 4.

We are all just doing our best at this point to enjoy mods prior to the FO4CK.  Obviously we don't know what the EXE will be named.  Thousands of people have downloaded the Fallout 4 version from the Nexus and it works fine.

Also there may be warnings in fda29cf89f0e5b0cb423da8ffd833dcae57f95af because I copied that a while back to use as a starting point for Fallout 4.  It is much easier to update an existing record with the definitions from FO4Edit then to just add the record from scratch.  I may not know python but I have become quite familiar with the record format between xEdit and Wrye.  Wrye just needs updates to make the patchers work better.

Also it's a good idea to have the Skyrim record there because since Bethesda uses the previous game and CK there may be some records in Fallout4.esm that will have the Skyrim format.  It has happened with all the previous games FO3/FNV/TES4 so no reason for it not to happen now.  But to be honest since they want this on consoles they may be more diligent.

Sometimes Bethesda updates the record so there may be one version from a previous game that they didn't update and two versions from the current game because they made changes and released a patch.  This might even happen with the release of survival mode for Fallout 4.  Bethesda doesn't care about making their record structure compatible with our tools or use standard update logic when making changes to the records.  They do what they want.  Typically a custom unpacker is required for the truncated records.  They are all over the place in the code if you look for it.

```
Utumno:
-    def loadData(self,record,ins,type,size,readId):
+    def loadData(self, record, ins, rec_type, size, readId):
         """Reads data from ins into record attribute."""
-        if type == 'CTDA':
+        if rec_type == 'CTDA':
```
I noticed this in the commit and that's probably all that needs to happen to commit fda29cf89f0e5b0cb423da8ffd833dcae57f95af.  Changes that have happened since Nov 2015 just need to be included.  However, Wrye doesn't have access to any of the records yet since they are all disabled and basically placeholders.  

The only ones I want enabled are in __init__.py in the imports section because those have already been confirmed as unchanged between Skyrim and Fallout 4.  However, there is no point in enabling the Merge Patch Patcher since most mods won't qualify to be merged and it will just cause confusion.

**Comment by Sharlikran** [comment]
I didn't know there was a #245.  However, I have added what I have changed so far in the OP.  I haven't changed anything else because it's not needed yet.

**Comment by Sharlikran** [comment]
@iaz3 any help with Fallout 4 would be appreciated.  I'm not doing much really until the release of the Fallout 4 CK.

**Comment by Utumno** [comment]
Ok @iaz3 too - lets use this issue for fallout 4 for 307.

> Not feeling that the FO4 changes are safe when some things are placeholders is a bit senseless.

Yes but they add _commit noise_ - and I was right that some of those changes _were needed for Bash to function_. SO I would like this work to be carried in the bottom of your branch and split up in manageable commits so when the time comes we can merge immediately as opposed to the skyrim case.

Also keep in mind I take your word for the commits (as I cant test). So please run Bash for fallout and note all that is not working - beta time soon with official support and we don't want people flooding the forums with small glitches here and there. Given that I will be helpless this would slow development to a crawl.

>  Thousands of people have downloaded the Fallout 4 version from the Nexus and it works fine.

Link ? We need to shut this down for 307 beta and have an official page as for the other games as this is officially supported. Need work in meta repo too

> Changes that have happened since Nov 2015 just need to be included

Yep - in splitting up the huge fda29cf in small, a few records commits - going from verified to non verified - once this is started I can check the warnings and show you how to fix them. This goes double for fallout3/nv work which adds a gazillion warnings too.

Let's work together in this - heed to my call cause I know the program and I do know what is a priority - you do understand it's not my egoism, and given that refactoring succeeded that I do know what I am doing ;)

Sincerely hope you are better with your health :)

**Comment by Utumno** [comment]
Also you checked in the OP some items - I need to know what to merge - especially for LO @Arthmoor raised a point about the DLC's

Random point: Ini tweaks are about to be overhauled and Mopy/Ini tweaks go bye bye. Not sure this will make it for the beta though (too much work). Please always keep an eye on utumno-wip - that's what is currently going on and so you need to be aware

**Comment by Sharlikran** [comment]
I'm probably able to sit longer but not able to work on anything.

> it's not my egoism

I don't feel it is either.  I just can't constantly amend all the commits so safe changes are in one place and placeholders in another.

> I do know what I am doing ;)

After all the work you have done in the last year, I bet you do know the code and what you are doing quite well.  I'm not trying to be ignorant of that or inconsiderate.

**Comment by Sharlikran** [comment]
I don't have the DLC yet but I would think that libloadorder will only omit Fallout4.esm.  Wrinkly didn't have libloadorder omit the DLC for Skyrim so it shouldn't be a problem.  If the two commits I have for LOOT are added to dev that should be sufficient.

If anyone with the DLC has the new file version I appreciate knowing what it is.  The old version was 0.95 but DLCRobot.esm seems to have a new version number.

@iaz3 or @Arthmoor I can't get the DLC yet so do either of you have time to do something for me to help with the Clean Data procedure?  Don't do this if you don't have the DLC though.

------------------------

Basically I need a list of all the files in the Data folder.  I don't know of any programs out there that can make a text file but I stumbled across a program that does.  [FilesearchEx](http://goffconcepts.com/products/filesearchex/) lets you make a text file of the search results.  It has a free trial version so you don't have to buy it.  After installing it go to the Fallout 4 Data folder and right click it.  You get an option to search the folder with FilesearchEx.  Once it's done you will see this.

![filesearch](https://cloud.githubusercontent.com/assets/1912426/14183408/146df28c-f725-11e5-9585-a359c438cff6.jpg)

Then under tools is a small piece of paper with a green down arrow and it will save it as a text file.

NAME|INFOLDER|EXT|SIZE|DATEMODIFIED|DATECREATED|DATEACCESSED|ATTRIBUTES
360WalkandRunPlus-RunBackwardSpeedAdjust.esp|F:\Games\SteamApps\common\Skyrim\Data\|.ESP|303 B|4/13/2013 12:01 PM|6/9/2015 8:29 AM|6/9/2015 8:29 AM|32
3DNPC.bsa|F:\Games\SteamApps\common\Skyrim\Data\|.BSA|2.8 GB|5/23/2015 9:25 AM|6/9/2015 8:32 AM|6/9/2015 8:33 AM|32
3DNPC.esp|F:\Games\SteamApps\common\Skyrim\Data\|.ESP|21 MB|5/21/2015 4:43 PM|6/9/2015 8:32 AM|6/9/2015 8:34 AM|32
3DNPC_Updated.7z|F:\Games\SteamApps\common\Skyrim\Data\|.7Z|5 MB|5/18/2015 2:26 PM|5/25/2015 10:09 PM|5/25/2015 10:09 PM|32
AMMOTest Numbered Files.7z|F:\Games\SteamApps\common\Skyrim\Data\|.7Z|752 B|6/7/2015 11:06 AM|6/7/2015 11:06 AM|6/7/2015 11:06 AM|32
ApachiiHair.esm|F:\Games\SteamApps\common\Skyrim\Data\|.ESM|55 KB|9/12/2013 5:17 PM|6/9/2015 6:28 AM|6/9/2015 6:28 AM|32

That's a sample of the text file and I have REGEX lines to straighten it all out so i can use it for Wrye Flash.  If anyone with the DLC could help me with that I'd appreciate it.  I just need a zip file of the results and I can do the rest.  You can attach the zip file to this issue.

**Comment by Utumno** [comment]
> I need a list of all the files in the Data folder.

Haha - navigate to data folder from a cmd and issue `dir /b /s` or some variation

**Comment by Sharlikran** [comment]
LOL okay, you know I don't use DOS anymore so....  :tongue: :smile:

That would work as well I guess.  Just output it into a text ```dir /b /s > results.txt```

**Comment by Utumno** [comment]
Notepadd ++ has column editing mode - but I guess you know that

**Comment by Utumno** [comment]
@wrye-bash/fo4 - I leave this up to you. Cooperate among you as you see fit to verify that current support is bug free then proceed to split the record commits as I mentioned above. Do _not_ notify me until done, or from commits that I need to merge due to fixing current suport

Thanks

**Comment by Sharlikran** [comment]
Since there is still a lot of refactoring my next wip will probably be just whatever is in dev, with the Clean Data feature updated, and the new version number from DLCRobot.esm.  That's about it.  I don't want to make the feature-sharlikran-valda-fallout on my fork not work by adding too many changes.

**Comment by Sharlikran** [comment]
You know where my [Fallout 4](http://www.nexusmods.com/fallout4/mods/3699/?) version is Utumno, I posted it before.  Also the name of the file or mod can be changed from "Wrye Flash PsychoExperiMental" to "Wrye Flash" at any time.  It's not set in stone.

**Comment by Utumno** [comment]
@Sharlikran https://github.com/wrye-bash/wrye-bash/issues/297 shows confusion started. Since we officially support fallout4 in the dev branch this page (which the OP did not link to) should be made in par with the Oblivion and skyrim ones. I have hashed up a description here: https://www.dropbox.com/s/zrxofv0awzzrwdt/Nexus%20-%20Fallout%204%20Wrye%20Bash.txt?dl=0 - can you tell me if it is adequate (I do not want big differences so I can automate the coding) ? Then pack up a version based on my latest beta and post that so we know who is using what.

Thanks

**Comment by Utumno** [comment]
Closing this as its items are done (not sure about the F4SE dll?) - please all fallout 4 discussion should be in #245 - discuss there and I will open issues if it proves not an easy fix.

It would be very helpful if your fallout 4 specific work was on a branch right on dev - fallout 4 is officially supported so anything you have that's needed and not in dev must be merged asap. When the dust settles from my merges please cleanup your fallout4 work and point me to it in #245
