### ISSUE TITLE
Skip Bash Installers Folders

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#269]
Some users configure NMM to download files directly to the Bash Installers folder.  This allows users to interface with the Nexus and check for updates with NMM since Wrye Bash isn't able to do that at this time.  However, when doing so the NMM folders show up on the Installers tab.

It would be nice if you could specify a list of folders to skip in `__init__.py`. So the following folders were hidden.

![skipfolders](https://cloud.githubusercontent.com/assets/1912426/12378716/d1a934ec-bcfb-11e5-8af3-9c9338a7ad73.jpg)

**Comment by Utumno** [comment]
My last commit in my wip branch fixes this - nice opportunity to stress test my work on BAIN refresh, but I would not advertised it as it may lead to weird reports on forums - new ini setting where you can specify dirs to skip: https://github.com/wrye-bash/wrye-bash/commit/9174ec07a6160100a26a43c6747328724d19728f

**Comment by Sharlikran** [comment]
Yeah it works fine.  Thanks for adding that.

**Comment by Utumno** [comment]
Thanks sharl - will merge ASAP - I had to go through the installer - good news is I managed to bend NSIS to my will - bad news is I had to understand it lol
