### ISSUE TITLE
Installer nsis script improvements

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#286]
- [ ] write a log and offer to show it
- [ ] offer to open installation locations instead of running the program(s)
- [ ] remember that the python version was installed in an extra location (bugsie)
- [ ] remember choice on start menu shortcuts
- [ ] add docs telling the user what they should and should not touch in Mopy (related to below)
- [x] drop deleting most of the files we delete (especially those in Data - bugsie - done: https://github.com/wrye-bash/wrye-bash/commit/b36d7f86a958541e74e09e81d0dab68d479a3cac )
- [ ] add  DO NOT MANUALLY EDIT CONTENTS OF THIS FOLDER files in ~~INI Tweaks/~~, bash/ etc
- [x] Packing the standalone warns - Are those above used in special ? May they point to import cycles and whatnot? - Infernio: nope, just py2exe/pyinstaller getting confused about attr access vs. module access, nothing to worry about.
  > The following modules appear to be missing
  > ['Carbon', 'Carbon.Files', '_scproxy', '_sysconfigdata', 'basher.appRestart', 'basher.uacRestart', 'bosh.LoadFactory', 'bosh.MasterSet', 'bosh.ModFile', 'bosh.ModInfo', 'bosh.dirs', 'bosh.getPatchesList', 'bosh.getPatchesPath', 'bosh.inisettings', 'bosh.reCsvExt', 'bosh.reModExt', 'comtypes.gen.MSHTML', 'fintl', 'patcher.PatcherInfo', 'patcher.configIsCBash', 'patcher.exportConfig', 'win32com.shell', 'win32com.shell.shellcon']

**Comment by Sharlikran** [comment]
> drop deleting most of the files we delete especially those in Data

Those are there specifically for anyone upgrading form an earlier version.  Most people that use the Oblivion versions swear by 292 to 295 as the only real stable versions and won't use newer versions of the 300+ (305, 306) series for Oblivion.  I know you would like to see them upgrade to the new versions.  If they do and they check the box to delete old files it's not going to do it correctly and that will require them to manually delete the Mopy folder and reinstall everything anyway.  Which doesn't make much sense.  You could state you have done it and explain why nobody should be using anything that old but most people don't read change logs, or description pages, or sticky posts on the nexus, or documentation.

**Comment by Sharlikran** [comment]
> Packing the standalone warns

I believe @Lojack said those are unavoidable.

**Comment by fireundubh** [comment]
Do we care about these improvements anymore?

**Comment by Utumno** [comment]
Dunno really - depends on if the work on the new installer is really rock solid and if it's worth while switching - about which I have no clue, cause I didn't follow the work by @iaz3 and I need to do a lot of reading / stackoverflow digging and user polling to be sure.

If you feel like tackling the first few you might as well as we probably keep nsis for 307, and digging in there you will spot more bugs I am sure - one obvious is that if one has 4 games the extra locations are not even displayed I think. Although some help wit the python code would be certainly needed - will post some easy refactoring soonish you could help with if you have some time.

**Comment by Infernio** [comment]
Better to replace it, see #477.
