### ISSUE TITLE
Record Structure

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#288]
@Utumno I'd just ask your questions here about the record definitions.  I'd hate to see your head explode after looking at all the code.  Most of it is a custom API so there won't be any Delphi documentation.  XEdit has a lot of back end code to handle everything that could get confusing.  If I can't tell you then I can ask @Zilav or @Hugues92.

So far Hugues92 has said that byte order is not utilized in xEdit so we don't need to do that for Wrye.  Maybe not now but at some point most of that should probably be removed.  It's working fine for now so I'd leave it.  It ain't broke so don't fix it.

**Comment by Utumno** [comment]
Yes and please refrain from opening discussion issues - I have enough of them already - PM me for that kind of stuff please.

**Comment by Sharlikran** [comment]
I'm sorry because I can't use Zilav and Hlp as a reference if I PM you or use other methods of communication.  So skip it.  Thanks for letting me know.
