### ISSUE TITLE
Split Screens/Inis/Installers/People details panels into dedicated classes

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#293]
Stands in the way of finalizing #163 and thus UI refactoring. Also at the root of bugs such as #271.

Hard

Also general details handling - in RefreshUI
- [x] screens (done : 12dfe1e1c0eecb01695cfd04d6e5399598d2a937, https://github.com/wrye-bash/wrye-bash/commit/3d36634fd01bfe159006d34c257f480087488463)
- [x] people (https://github.com/wrye-bash/wrye-bash/commit/593653068462e3267d5996aa8d6bd5016ea96f5d)
- [x] installers (https://github.com/wrye-bash/wrye-bash/commit/49df166b3c0c2a52a58d5c6e481147746597a540)
- [x] move _DetailsViewMixin only where needed (not in SashPanel) (https://github.com/wrye-bash/wrye-bash/commit/20c5384a8eb37c369d69039215cb8dbdb9805cc9)
- [ ] inis

**Comment by Utumno** [comment]
@iaz3 - here is another that really stands on my way (not related to the patcher). You could try the tabs in the order of the OP, people first which should be easy - then installers which should be trickier

**Comment by Utumno** [comment]
Closing this - only remaining tab is the ini one but this needs a general overhaul first - see #326

**Comment by m0lz** [comment]
@Utumno was this issue anything to do with a problem alt3rn1ty mentions on AFK mods site ? ( He answered a question you asked in the BSAs and you topic )

Your bleeding edge version of Wrye Bash when first loading has a bug where you see the information boxes stretched across the majority of Wrye Bash, and then they quickly reduce to normal size on the right again.

**Comment by Utumno** [comment]
@m0lz thanks for the heads up - which version exactly - the python or standalone ? Does it have a version number ?

**Comment by m0lz** [comment]
He mentions 307.201610020028 - Installed Standalone

**Comment by Utumno** [comment]
Thanks - yes - inertia I looked at the topic - should be cured now, will pack a new one soonish :)

**Comment by m0lz** [comment]
@Utumno No problem, but looks like you have another problem with the latest .. See alt3rn1ty again

**Comment by Utumno** [comment]
@Metallicow: I actually used your code form your branches - if your are curious for the final solution have a look  at https://github.com/wrye-bash/wrye-bash/commit/49df166b3c0c2a52a58d5c6e481147746597a540

I need to delete those branches from here to cleanup a bit please let me know if you have backups.

Meanwhile the code is ready fro switching to the wx 3.02 now - and there are other wx issues I could use your help. If still around now is the time to get involved back in :)

**Comment by Metallicow** [comment]
I'm not worried about the backups provided everything works now.
I'll try to look at the wx 3.0.2 stuff again here soon. Thanks.
