### ISSUE TITLE
Wrye for Fallout 4 v 1.5

### ISSUE THREAD

**Issue by bitdman** [wrye-bash/wrye-bash#297]
Nexus has an optional wrye flash beta 
Wrye Bash 307.10 - Standalone Executable for Fallout 4 Beta v1.5.157 ONLY!

When I downloaded it I get   Wrye Bash 307.003 stand alone executable.....Is this right?

**Comment by Utumno** [comment]
Please do not open issues to ask questions like that - the discussion is going on here:
http://forums.bethsoft.com/index.php?/topic/1599816-relz-wrye-bash/page__view__getnewpost

**Comment by Sharlikran** [comment]
I stated on the nexus page to ignore file names.

**Comment by Sharlikran** [comment]
No more confusion.  I locked the comments section and removed the files.  People will have to wait until Utumno is done and merges things into dev.

**Comment by Utumno** [comment]
We are still talking about that : http://www.nexusmods.com/fallout4/mods/3699/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Ffallout4%2Fajax%2Fmodfiles%2F%3Fid%3D3699&pUp=1

ain't we ?

**Comment by Sharlikran** [comment]
Yeah.  However, confusion eliminated.  No need to worry about what name of the file is or what version it is or what everything is or isn't titled.  In fact if it gets any more confusing I'll just hide the page entirely.

**Comment by Utumno** [comment]
Well don't get me wrong - the 307 beta will support fallout 4 and this page should be there cause hey we need to spread the word - but wait a couple days till I hash up a new nightly (I am away from my main machine now) and you can push that there - no support for the rest of fallout games - just plain old Wrye Bash (so the title should change accordingly and the description should match the other pages redirecting to the oblivion thread etc with possibly some additions for fallout 4 as we do for skyrim). But let's continue this discussion to #268 (see links there).
