### ISSUE TITLE
Duplicate FormID from patcher in Skyrim

### ISSUE THREAD

**Issue by Kelmych** [wrye-bash/wrye-bash#298]
I had a duplicate formID problem when I was using DynDOLOD and I traced it back to a problem with the bashed patch. Two Tamriel Worldspace entries (00009389 and 00009344) are supposed to be in Block -1,0 Subblock -3,2 but the bashed patch puts them in Block 0,-1 Subblock 2, -3. There are other entries in the bashed patch in the same block and subblock with have correct block/subblock, but these 2 entries have reversed identifiers.

I used the bleeding edge python version of WB 307 dated March 28, 2016 for the test ; I also tried several recent and older 306 versions of the standalone WB and got the same error. I created a bashed patch after eliminating all the plugins that didn't affect these entries to see if the error was still there, and it was. Replicating the error requires only the following plugins (this is also the load order I used).
Skyrim, Update, and the DLC esms
Unofficial Skyrim Legendary Edition Patch.esp, Cutting Room floor.esp, FloraRespawnFix.esp, and RealisticWaterTwo.esp

**Comment by Sharlikran** [comment]
When I enabled the CELL patcher I did not think there would be any issues.  This has been reported in the Bethesda threads before.  The report did include the use of DynDOLOD.  Zilav doesn't work on Wrye Bash and it's written in Python so he really couldn't suggest possible code.  

I also have no way to know what it's related to.  For example, if you were to make a brand new plugin in the CK itself make as many of these changes as you can.  Change the ImageSpace (C.ImageSpace) then the lighting (C.Light), the Music (C.Music), the Name (C.Name), and the Water height (C.Water) and then add say a rock to each of those two Tamriel Worldspace entries, without any LOD stuff as a factor.  Make sure only Skyrim.esm is a master.  Then build a bash patch without any other plugins active except Skyrim.esm and the test plugin does that still occur?

Unfortunately until the issue can be more accurately identified and until the Skyrim patchers are updated this can't be fixed.  If you can provide the extra information that would be helpful.  

However, understand that it could be quite some time before this is addressed.  The current volunteer is willing to work on the patchers but doesn't have intimate knowledge of them.  I can't write in Python so I rely on volunteers to make changes to Wrye.

**Comment by Infernio** [comment]
Please comment / reopen if this can be reproduced again.
