### ISSUE TITLE
Refactoring Backburner

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#300]
Random Personal TODOs:

https://github.com/wrye-bash/wrye-bash/commit/318e66a9ad3a096c316decc751bc76d6c3b5b858

f = open(r'C:\Users\MrD\AppData\Local\Oblivion\plugins.txt', 'r')

add SPELL to fallout 3/nv type_name dictionary ?

a0325d266f60a97d55d9d11f760988dd22aff9e5 breaks copy or move icon - why ?

---

failure to install meshes 0 kb - http://www.nexusmods.com/oblivion/mods/46028/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Foblivion%2Fajax%2Fmodfiles%2F%3Fid%3D46028&pUp=1

see http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/page-4#entry25208218

see also http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/page-4#entry25205282

> I'm having a problem with the "Import Face" feature. When I attempt to import a face of the same race and gender (female Breton) I get this message: "Uncertain about position of face data, probably because player character name is too short. Try renaming player character in save game."

---

http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/#entry25186608

h/vspace(pixels):

http://stackoverflow.com/q/38044167/281545

FFFFFFFF     FFF - EEE autoRe in importers patchers

patchFile,loadMods

Common code in Mopy/bash/patcher/patchers/importers.py - WIP: getpatchesPath()

IniInfos not masters:

```
+        status = 30 if any( # if self.masterNames is empty returns False
+            (m not in modInfos) for m in self.masterNames) else 0
+            (m not in self) for m in self.masterNames) else 0

```

Also check what happens with desync and flip esm in skyrim

```
    self._rebuild_mtimes_cache() ##: will need that tweaked for lock load order
```

NEW ISSUES:

Override skips should override Skip Beth content too
Rearange mods by save masters' order 

make counter in archives optional !!

ini setting to control click on installers tab to switch to it

---

MEMORY:

```
                    # for v,val in selfTops[label]:
                    try:
                        import sys
                        print label, sys.getrefcount(selfTops[label].records[0])
                    except Exception as e:
                        print label, e
```

**Prints 2 always**

---

Test in 306the elsweyr stuff.....

Haha - thanks for chiming in. Also another option would be to select Override Skips from the mod menu - less intrusive and won't scan the Oblivion.esm on every boot ---> Override skips does not work with beth files !!!!

DOCS ! refreshInstallers = wrapper around refresh basic

u'The McMiller Chronicles\Data\The McMiller Chronicles.esp' -- type 2 !

---

```
@@ -4699,2 +4699,3 @@ def __setstate__(self,values):
         dest_scr = self.refreshDataSizeCrc()
+        # if self.fileRootIdex: print self.archive, self.fileRootIdex
         if self.overrideSkips:
```

---

http://forums.bethsoft.com/topic/1589330-wrye-bash-thread-107/page-2#entry24963242

Generally speaking, it feels like the way WryeBash loads third party apps is just a little weird.  I still get errors whenever I attempt to launch Oblivion or Construction Set extender.  And it's still weird to me that if I launch BOSS separately from Wrye Bash, I don't need to close it before I see the updated date changes vs. what happens if I launch Boss from WryeBash.

---

Inis

Default ini tweak - to edit right click and select Copy --- mouse tip

[Window Title]
Warning

[Content]
C:\Users\MrD\Documents\My Games\Oblivion\Oblivion.ini does not exist yet.  Oblivion will create this file on first run.  INI tweaks will not be usable until then.

[OK]

---

getmtime

Test a bunch of modification times for change in python:

I want to be able to test if any of the modification times in a folder has changed without having to store the (potentially large) individual files and subdirectories modification times. I came up with:

---

 eliminate Link.Frame uses in bosh: see 6452bcb # 163

---

Use self.dir here:

progress(0, (_(u"%s: Skips overrides...") % dirs['mods'].stail)+ u'\n')
Installer.calc_crcs(pending, pending_size, bass.dirs['mods'].stail,
-                            new_sizeCrcDate, progress)

---

self.config = config = data[project].getOmodConfig(project)

Note irefresh('I') is needed for archives due to crc_installer update -> drop if changed check and always have this done -> simplify _get_refreshed

_skips_in_data_dir --> SKIP MOST OF IT ON A FULL REFRESH - add in docs on refresh !!!

When you enable skipping files for an installer the files that were installed and now skipped will show as dirty till a BAIN restart. Then BAIN may loose the track of those files (depends on the file type). This is intentional (avoid refreshing some directories such as distantlod etc). If you want to uninstall files like those enable the Override Skips option on the installer.

clear read only takes time !!! in installers !!!!! rm tmp dir

 ##: BLOWS !! in non shellUI path ---> ΝΟΤ TRUE

```

Traceback (most recent call last):
  File "bash\balt.py", line 2331, in __Execute
    self.Execute()
  File "bash\balt.py", line 1575, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\installer_links.py", line 749, in Execute
    self.iPanel.RefreshUIMods(*ui_refresh)
  File "bash\basher\__init__.py", line 2761, in RefreshUIMods
    BashFrame.iniList.panel.RefreshPanel('ALL')
  File "bash\basher\__init__.py", line 1588, in RefreshPanel
    self.SetBaseIni(self.GetChoice())
  File "bash\basher\__init__.py", line 1626, in SetBaseIni
    self.tweakContents.RefreshTweakLineCtrl(selected)
  File "bash\basher\__init__.py", line 686, in RefreshTweakLineCtrl
    tweakPath = bosh.iniInfos[tweakPath].dir.join(tweakPath)
  File "bash\bolt.py", line 1224, in __getitem__
    return self.data[key]
KeyError: bolt.Path(u'Tutorials, Disabled [Skyrim].ini')

```

---

 isUpdated = oldInfo is not None and not isAdded and not \
                fileInfo.sameAs(
                    oldInfo)oldInfo is not None

CORRUPTED DOES NOT WARN ON MODS IF KNOWN CORRUPTED WHILE WARNS ON SAVES

BAIN:

IT DOES ! DEBUG !! Current refresh mechanism wont detect file changes in the project that leave file size the same - cause does not use in those checks `getmtime(true)`.

PLUS WHY WHEN I MAKE MY CHANGES @balt.conversation IS NEEDED

---

Inform BAIN tracked files  when flipping esm state

backup should not mess with first backup - another ghosting effect ???
change description save and peek F:\Oblivion Mods3\BASH\Bash Mod Data\Backups

setGhost GHOOOOST
TODO what happens if I manually name a file to .ghost - on refresh ModInfos

Closing tabs - LEAKS (screensData, IniInfos etc)

SAVING SETTINGS SHOULD ALWAYS SAVE SAVE INFO AND INI INFO EVEN IF THE TABS ARE NOT THERE

---

restore from backup does not reorder by LOad order:
1. Sort by LO
2. Backup a file
3. Reorder it (oblivion)
4. Restore backup
5. The file is not reordered
   if refresh.data(): RefreshUI(file=file)
   else: refreshFile (?)
   - but RefershData does ! (tab out/in bash)

Same problem when installing from BAIN - mod time is not taken into account !
Need refershUIMods, duhhhh

---

2.
PopulateItems() pass self.selected in when I have them (avoid GetSelected call!!)

4.
groups check none
DOCS: groups current is checked TODO UNCHECK

**Comment by Utumno** [comment]
Various:

- [ ] enabling disabling tabs was hacked in, to eternal chaos - deserves an issue 
  - [ ] Saving settings should always save save info and ini info even if the tabs are not there
  - [ ] Closing tabs - LEAKS (screensData, IniInfos etc)
- hide:
  - [ ] _unhide_wildcard(): add disabled saves
  - [ ] open a file then try to hide it:
    
    ```
    Traceback (most recent call last):
    File "bash\basher\installer_links.py", line 466, in Execute
    file.moveTo(newName)
    File "bash\bolt.py", line 951, in moveTo
    shutil.move(self._s,destPath._s)
    File "C:\_\Python27\lib\shutil.py", line 303, in move
    os.unlink(src)
    WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\Dropbox\\skyrim\\Skyrim Mods\\Bash Installers\\BAIN-Skip_Bethesda_intro-100.7z'
    ```
    
- [ ] ess.bak files are not handled - deserves another issue
  - [x] CoSaves must be edited to cater for obse.bak
  - [ ] rename, duplicate etc

---

BAIN leftovers
- [x] Installer.archive should be a Path - backwards compatibility
- [ ] Projects first breaks drag and drop
- [ ] Copy to conflicts - don't use tmp dir ?
- [ ] Monitor External Install -> createFromData -> use shellMove ?---

Override skips should override Skip Beth content too:
> another option would be to select Override Skips from the mod menu - less intrusive and won't scan the Oblivion.esm on every boot ---> Override skips does not work with beth files !!!!


_skips_in_data_dir --> skip most of it on a full refresh - mention in docs on refresh !!!

When you enable skipping files for an installer the files that were installed and now skipped will show as dirty till a BAIN restart. Then BAIN may loose the track of those files (depends on the file type). This is intentional (avoid refreshing some directories such as distantlod etc). If you want to uninstall files like those enable the Override Skips option on the installer.

clear read only takes time !!! in installers !!!!! rm tmp dir

test created inis:

```
tweaksCreated = {set} set([(bolt.Path(u"C:\\GAMES\\TESIV\\Oblivion\\Data\\INI Tweaks\\Automagic Bags, ~Old Settings [Automagic_Bags_v4-02--BAIN'ed-22414.7z].ini"), bolt.Path(u'C:\\GAMES\\TESIV\\Oblivion\\Data\\Automagic Bags.ini'))])
 __len__ = {int} 1
 256866344 = {tuple} <type 'tuple'>: (bolt.Path(u"C:\\GAMES\\TESIV\\Oblivion\\Data\\INI Tweaks\\Automagic Bags, ~Old Settings [Automagic_Bags_v4-02--BAIN'ed-22414.7z].ini"), bolt.Path(u'C:\\GAMES\\TESIV\\Oblivion\\Data\\Automagic Bags.ini'))
  __len__ = {int} 2
  0 = {Path} C:\GAMES\TESIV\Oblivion\Data\INI Tweaks\Automagic Bags, ~Old Settings [Automagic_Bags_v4-02--BAIN'ed-22414.7z].ini
  1 = {Path} C:\GAMES\TESIV\Oblivion\Data\Automagic Bags.ini
```

---

#163 leftovers:
- [x] Many calls like :  
  ```
        self.window.RefreshUI(refreshSaves=True)
        self.window.SelectItemsNoCallback(to_select)
        self.window.SelectAndShowItem(to_select[-1])
  ```  
  time for a new to_select param in RefreshUI -> transfered in #353
- [x] drop sashgravity as we explicitly always set the sash (test)
- [ ] More visible splitters
- [ ] OnClosePanel Show - masters list autosize columns
- [ ] _DetailsMixin -> _DetailsPanel
- [ ] slight difference in initial sizes of mods vs saves details initial sizes.
- [ ] revisit ShowPanel - do the details have _firstShow False ?
- [ ] espmMenu move to InstallerDetails

------------------------------------------------------------------------

INISsssss

- [ ] update parameter is needed as if we get any setting form target before
the iniInfos refresh its size and modtime checks will not show it as
changed - a better way?
- [ ] IniInfos.factory reads the file twice - collect settings while parsing file?

------------------------------------------------------------------------

Load Order - https://github.com/wrye-bash/wrye-bash/issues?q=sort%3Aupdated-desc%20state%3Aclosed%20label%3AC-internal%20label%3AA-load-order

- [ ] the ideas in https://github.com/wrye-bash/wrye-bash/issues/578#issuecomment-2476293079
- [ ] the `_lo_op` decorated methods should be melded
- [ ] refreshLoadOrder needs be encapsulated in ModInfos

**Comment by Utumno** [comment]
Notes:



------------------------------------------------------------------------

import numpy as np

x= np.zeros((5,1))
y= np.zeros((5,1))
print x
x[0]=[1]
y[0]=1
print x

print x==y


------------------------------------------------------------------------
Pycharm

```
    @staticmethod
    def _is_ini_tweak(ci_relPath):
        return ci_relPath[-4:].lower() == u'.ini' and ci_relPath[
                                                      :11].lower() == u'ini ' \
                                                                      u'tweaks/' and not os.path.sep in ci_relPath[
                                                                                                        11:]
```

Dunno where  I got this static method fromkeys/...

@@ -535,2 +536,7 @@ def copy(self):

    @staticmethod
    def fromkeys(keys, v=None):
        return super(LowerDict, DefaultLowerDict).fromkeys(
            (_ci_str(k) for k in keys), v)

That's the way to implement it as a static method - escapes me !

**Comment by Utumno** [comment]
Let's hijack this @nycz (which is just a glimpse in the chaos of my todo files) to define some refactoring tasks that I would like you to take over:

- #174:

- [ ] Rename ItemLink.help attribute to `_help` - add a note to the coding style that this is a forbidden name
- [ ] use commit above to define `link_help` property that by default returns `_self._help`
- [ ] use commit above to prune `_initData` overrides that only define custom help

Needed to proceed with final phase of patcher API refactoring

**Comment by Utumno** [comment]
@nycz : And another large scale but focused refactoring - we need to have a GameInfo class that defines sensible defaults for all constants in `game/__init__.py`. This would then need bush.game uses be traced down and replaced with calls to GameInfo class, but the current situation is super messy and will only get  worse as games multiply - we copy paste and edit the same set of constants on every game - yak. Under  #358

**Comment by Utumno** [comment]
@D4id4los - encapsulate game constants in a class is the goal - first step would be eliminating esp (unfortunately named) class, move class variables in module scope prepend `esp_`, ugly prefix for ugly var - probably `recordTypes` and `topIgTypes` belong to `RecordHeader`

**Comment by D4id4los** [comment]
We might want to improve exception handling further than in #373 by replacing or defining our own wx excepthook. Relevant links are:

https://stackoverflow.com/questions/6234405/logging-uncaught-exceptions-in-python
https://pymotw.com/2/sys/exceptions.html
https://wiki.wxpython.org/CustomExceptionHandling

**Comment by Utumno** [comment]
Thanks @Infernio - I should probably clean up this issue and use it as our refactoring discussion hub

**Comment by Utumno** [comment]
Keeping this as refactoring backburner - will go through open and backburner issues one of these days to move items here. Feel free to edit the posts oh you with admin rights
