### ISSUE TITLE
Invalid function value imported to patch by a merged mod

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#307]
This one might need the xEdit guys to help out on. Basically when merging the attached file (you'll also need Helgen Reborn handy for this) the function listed in the pic is given an incorrect value in the patch. I'm not sure if it's the patcher that did it or if it's just referencing a value the rest of the Skyrim specific code hasn't got listed. The game does not seem to mind though.

https://i.imgur.com/ghhu8zJ.jpg

[HRFixes.zip](https://github.com/wrye-bash/wrye-bash/files/264381/HRFixes.zip)

**Comment by Arthmoor** [comment]
As of 307.201610020028 this issue is still present.

**Comment by Utumno** [comment]
reared its ugly head again: https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=171947

@Arthmoor  could you please post a minimal load order and minimal patch config to reproduce ? As in _mininininimal_ Aslo a bugdump please - is this current utumno-wip ?

@wrye-bash/devs  anyone can take this up ? Looking at you @warmfrost85 !

**Comment by warmfrost85** [comment]
@Arthmoor , is HRFixes your own creation? I don't see it on the Nexus. Are those mods all vanilla from Nexus? 

After I'm given a minimal LO that recreates it I'll look but at this point almost everything is above my pay-grade.

**Comment by Utumno** [comment]
Yep minimal LO and BP options are the only chance things like those get fixed

**Comment by Arthmoor** [comment]
At minimum you'd need the plugin I linked here along with Helgen Reborn for SSE https://www.nexusmods.com/skyrimspecialedition/mods/5673

Set it up to merge the HRFixes.esp file into the patch.

I'll grab a bug dump but I'm not sure what that's going to tell us since the issue only manifests once the game loads.

**Comment by Utumno** [comment]
Thanks @Arthmoor 

> I'll grab a bug dump but I'm not sure what that's going to tell us since the issue only manifests once the game loads.

Info on your setup - I must find a way to include the commit sha for python builds - ideas welcome (probably a silly file with the sha)

**Comment by Arthmoor** [comment]
Tried running in debug to get a dump, but no data is sent to the file past the LOOT api error which I expect to see since I don't have LOOT installed.

**Comment by Infernio** [comment]
Can't reproduce with the linked plugin, merges fine and the CTDA does not get corrupted:

![CTDA-Fine](https://user-images.githubusercontent.com/2845240/68551343-47dce900-040c-11ea-8575-feccbe672e67.png)

**Comment by Infernio** [comment]
Please comment / reopen if this can be reproduced again.
