### ISSUE TITLE
Warn when a mod is ordered before its masters

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#308]
See no warn in 305 oblivion

![out_of_order_masters-oblivion-esp-305](https://cloud.githubusercontent.com/assets/1365079/15406438/d35dac66-1e06-11e6-831a-0000da67669c.jpg)

@Arthmoor:

What should be done you think ? Paint the checkbox orange as I do in my current wip branch ? (I still have to edit the mouse tooltip on the status bar to read "Mod ordered after its masters")

**Comment by Arthmoor** [comment]
Yeah, I think that would be enough.
