### ISSUE TITLE
Add patcher support fo XCLR subrecords of CELL

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#31]
I'm surprised nobody asked for this before but it would be nice to have support to be able to import regions from a CELL record into the patch so that mods that need to change region data don't get stomped by later loading ones.

**Comment by Infernio** [comment]
So, this was implemented in 9c162e71e7baef4bb439006d1c8cd4c0d3e1b5dc without anyone noticing that there was an issue open for it :P
Closed as of that commit.
