### ISSUE TITLE
Various patcher-related bugs

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#314]
Catch all issue to dump bug reports from the forums that may or may not need separate issues.

From http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/#entry25181994

> On to Oblivion, then. I checked the bashed patch to see if it was reverting any vanilla values. The only one was from Knights. The heavy Boots of the Crusader have a flag, "calculate from all levels <= player's level." The Unofficial Knights Patch removes this flag, the bashed patch restores it. I'm guessing that removing it was the unofficial fix for the level glitch with this item.  

---

from: http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/#entry25185082

>  Note that the bashed patch chooses to revert the value back to the same value as Oblivion.esm uses. Example: AdrienneBerene has a faction rank of 3 in Oblivion.esm, UOP then changes it to 7 and then bashed patch changes it back to 3 again.

First report is here: http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/page-7#entry25178766

---

Supierce on NVIDIA fog fix: http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/page-6#entry25174562

---

Import Inventory http://forums.bethsoft.com/topic/1606578-wrye-bash-thread-111/#entry25219520:

> Found a strange bug with inventories importing. Look at these screenshots: 
> 
> http://imgur.com/a/QxHSP 
> 
> In one case MTC's entry has overwritten FCOM's change, in second everything was imported perfectly, and in third Bashed Patch has just ignored MTC's changes. Is there any way to fix it without a manual patch? 
> 
> P.S. Also, many village/quest mods need Actors.AIPackages, Invent and Factions tags. Here is one example from MTC: http://imgur.com/a/K9sqj

---

http://forums.bethsoft.com/topic/1606578-wrye-bash-thread-111/#entry25222880

> Cbash crashes when I import names from this plugin (Oblivion Content Restoration Project): http://www.nexusmods.com/oblivion/mods/45909/?tab=1&navtag=http%3A%2F%2Fwww.nexusmods.com%2Foblivion%2Fajax%2Fmoddescription%2F%3Fid%3D45909%26preview%3D&pUp=1
> 
> ```
> Traceback (most recent call last):
>   File "bash\balt.pyo", line 416, in <lambda>
>   File "bash\balt.pyo", line 1573, in _conversation_wrapper
>   File "bash\basher\patcher_dialog.pyo", line 201, in PatchExecute
>   File "bash\basher\patcher_dialog.pyo", line 302, in _save_cbash
>   File "bash\cint.pyo", line 14259, in save
> WindowsError: exception: access violation reading 0x1280B40F
> ```
> 
> If WB is launched with administrator privileges, WB just CTDs.
> Not a serious problem for me, but I couldn't find anything unusual in the esp, so it is strange.

---

CBash:
- [x] Mod_CreateDummyMasters -> investigate why CBash blows - dropped in 964a0a93e1b60151a9743c79241b4a2f837aafc3

**Comment by m0lz** [comment]
Would this be of any use ..
http://afkmods.iguanadons.net/index.php?/topic/4706-wip-xedit-lib-dll-wrapper-for-xedit/

"Use Cases
I envision a number of use cases for this project, including patching, automation, resolving plugin errors, and building new mods.  This project is, in many ways, a spring board from which many other projects can be made"

Now that Wrye Bash is supporting multiple games, the first thing to develop when a new game comes along is the list of records definitions for xEdit ..
.. If the above will auto adopt the same then future patchers updating could just be a case of playing catchup to xEdits records, which are always seriously investigated so that the community can be 100% confident in its operation.
Right now only a short while after Skyrim SE was launched, SSEEdit is already at a pretty dependable state

**Comment by m0lz** [comment]
More discussion on the same here ..
http://forums.bethsoft.com/topic/1611022-wip-xedit-lib-dll-wrapper-for-xedit/
Supports Python and C++ and by the looks of it anything else that matters

**Comment by Utumno** [comment]
Well maybe - let's see how it goes. Those dll wrappers i don't really trust judging from my experience with Bash - note that current Bash does not anymore feature _any_ of those.

**Comment by BeermotorWB** [comment]
More info on the Nvidia Fog Fix:
From the main himself at wryemusings.com:

> Nvidia Fog Fix
> 
> •  Systems with Nvidia cards can suffer a black screen bug when the player enters interior cells where near fog, far fog and fog clipping distance are all equal to 0. To avoid this, this function scans the mod and sets near fog to 0.001 in problem cells.
> 
> •  This feature is based on [Quarn's Nvidia Black Screen Fix](https://www.nexusmods.com/oblivion/mods/11167/?tab=description)
> 
> •  It is advised that modders run this function on their mods before releasing. 
> 

According to posts on the mod page for this fix, people were still experiencing issues with this as late as 2017 on Windows 10, so this is likely a quirk of the Oblivion engine that is exacerbated on Nvidia cards for some reason. I haven't personally used this on my Nvidia card on Windows 10 and haven't encountered a problem, but this may still affect older cards.

**Comment by Infernio** [comment]
As of 9697b64abc00beaed04e950af20c8116db15151a and 6436024eb06cd80dbfbb34a6d538af6b4aa71e04 the affected patchers have basically been rewritten. The CBash part of the issue was fixed by just dropping the pointless CBash path: 964a0a93e1b60151a9743c79241b4a2f837aafc3

**Comment by Utumno** [comment]
thanks inf - those ancient patcher issues finally closed :)
