### ISSUE TITLE
Standalone version 307.201607061835 - Bug

### ISSUE THREAD

**Issue by m0lz** [wrye-bash/wrye-bash#316]
Traceback (most recent call last):
  File "bash\basher__init__.pyo", line 971, in OnLeftDown
AttributeError: 'MouseEvent' object has no attribute 'Veto'

Just after adding a newly generated DynDOLOD Output files BAIN, right click and install the same
Then go to the Mods tab, DynDOLOD.esp is last in the load order and unchecked
Click to activate the plugin ( put a tick in the box )
You should get the above error

**Comment by m0lz** [comment]
Wrye Bash starting
Using Wrye Bash Version 307.201607061835
Python version: 2.7.10
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('en_GB', 'cp1252')
filesystem encoding: mbcs 
Searching for game to manage:
bush.pyo   71 _supportedGames: Detected the following supported games via Windows Registry:
bush.pyo   73 _supportedGames:  skyrim: D:\Steam\steamapps\common\Skyrim
bush.pyo   73 _supportedGames:  fallout4: D:\Steam\steamapps\common\Fallout 4
bush.pyo  131 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyo  137 _detectGames: Set game mode to skyrim found in parent directory of Mopy:  D:\Steam\steamapps\Common\Skyrim
bush.pyo  172 setGame: No preferred game specified.
bush.pyo  152 __setGame:  Using skyrim game: D:\Steam\steamapps\Common\Skyrim
testing UAC
__init__.pyo 7463 initDirs: Using libbsa API version: 2.0.0
mods_metadata.pyo  219 __init__: Using LOOT API version: 0.6.0
mods_metadata.pyo  267 refreshBashTags: An error occurred while parsing files C:\Users\m0l3y\AppData\Local\LOOT\Skyrim\masterlist.yaml, C:\Users\m0l3y\AppData\Local\LOOT\Skyrim\userlist.yaml:
Traceback (most recent call last):
  File "bash\bosh\mods_metadata.pyo", line 261, in refreshBashTags
  File "bash\loot.pyo", line 342, in Load
  File "bash\loot.pyo", line 346, in PlainLoad
  File "bash\loot.pyo", line 234, in LootErrorCheck
LootError: LootError: LOOT_ERROR_PARSE_FAIL:yaml-cpp: error at line 608, column 9: bad conversion

Traceback (most recent call last):
  File "bash\basher\__init__.pyo", line 971, in OnLeftDown
AttributeError: 'MouseEvent' object has no attribute 'Veto'
Traceback (most recent call last):
  File "bash\basher\__init__.pyo", line 971, in OnLeftDown
AttributeError: 'MouseEvent' object has no attribute 'Veto'
Traceback (most recent call last):
  File "bash\basher\__init__.pyo", line 971, in OnLeftDown
AttributeError: 'MouseEvent' object has no attribute 'Veto'
Traceback (most recent call last):
  File "bash\basher\__init__.pyo", line 971, in OnLeftDown
AttributeError: 'MouseEvent' object has no attribute 'Veto'

**Comment by m0lz** [comment]
I think this problem is reproducible no matter what you select or deselect on the mods tab in this version of Wrye Bash

**Comment by Utumno** [comment]
Please do not post issues for problems in **wip** builds. Those builds sure contain small issues like this one. These are discussed in the forums - always check there first:

http://forums.bethsoft.com/index.php?/topic/1604190-relz-wrye-bash/page__view__getnewpost

 This was already reported there and fixed in my latest wip branch so we just wasted an issue slot.

**Comment by m0lz** [comment]
My fault then, I do not understand this "wasted an issue slot" or how important that is .. But will remember in future if I am not a member of a forum where you would like bug reports, then I will just not bother.

I see now that a member Supierce has raised the issue in this post ..
http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/#entry25184676

Isnt that forum just about dead though ???, Bethesda are supposed to be moving everyone to a new forum which is supposed to be crap site software based on Jive.
I certainly do not feel like joining a soon to be extinct forum.

Glad you already fixed the problem though, will you be posting a new WIP Standalone, or are they only done periodically and less often than those Python files ?

**Comment by Utumno** [comment]
Did not mean to be harsh - that's the way people contribute - discuss in that forum and then post here to avoid noise in the tracker - trust me maintaining a tracker (and not a real good one) is _another_ thing I have to do, one too many.

In that forum we discuss alternatives to that forum.

**Comment by m0lz** [comment]
@Utumno - I understand, and thank you for your continued dedication to this amazing project.
