### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#317]
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

https://github.com/blog/1184-contributing-guidelines

**Comment by Utumno** [comment]
This needs to contain the info from:

[github] Reporting a bug · wrye-bash/wrye-bash Wiki
https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Reporting-a-bug

but also from the contributing pages - see the readme contributing section https://github.com/wrye-bash/wrye-bash#contributing - for instance :

[github] Branching Model & Using The Repository · wrye-bash/wrye-bash Wiki
https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Branching-Model-&-Using-The-Repository
[git] Syncing a Fork with the main repository · wrye-bash/wrye-bash Wiki
https://github.com/wrye-bash/wrye-bash/wiki/%5Bgit%5D-Syncing-a-Fork-with-the-main-repository

And also contact info - see for instance: https://github.com/wrye-bash/wrye-bash#questions--feedback-

**Comment by Sharlikran** [comment]
With my schedule I may not get to this at all.  Not being rude I just want to spend more time playing FO3, revisit Morrowind, play FO4, Skyrim, and although that's a long list of games I want to spend more time with my family.

**Comment by Utumno** [comment]
Ok - but if you just get me started it would be enough - and you do have the experience to get this right :)

**Comment by Utumno** [comment]
[Dubiousness hashed up one](http://forums.bethsoft.com/topic/1615914-wrye-bash-thread-114/page-2#entry25313326) which I attach and will proceed to edit

[Wrye Bash - Contributing MD file.txt - original by Dubious](https://github.com/wrye-bash/wrye-bash/files/779738/Wrye.Bash.-.Contributing.MD.file.txt)

**Comment by Utumno** [comment]
Notes:

Link to exemplary report
Use this: https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines
And this: http://stackoverflow.com/help/how-to-ask
And that: http://www.chiark.greenend.org.uk/%7Esgtatham/bugs.html?

**Comment by Utumno** [comment]
Some omitted stuff:
[ommited.txt](https://github.com/wrye-bash/wrye-bash/files/922986/ommited.txt)
