### ISSUE TITLE
Uninstalling Package Causes Wrye Bash to Minimize

### ISSUE THREAD

**Issue by garthand** [wrye-bash/wrye-bash#319]
Using the standalone version of Wrye Bash, whenever I uninstall a package it minimizes Wrye Bash. I don't think this is expected behavior.

**Comment by Utumno** [comment]
More info please - 306 ?

**Comment by Utumno** [comment]
Please give me more info (see https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug) otherwise I will need to close this - works for me
