### ISSUE TITLE
Wrye Bash won't lauch. Log shows nothing.

### ISSUE THREAD

**Issue by Laitdark** [wrye-bash/wrye-bash#320]
Alright. My operating system is Windows 10 64bit
After reinstalling Skyrim, I have installed the Wrye Bash standalone 306. Now when i am trying to launch Wrye Bash it quickly shows a Wrye Bash logo, then some kind of a text window (Looks like a log, but it stays for like half a second, so it's impossible to read what's on it). and disappears.

**Comment by Utumno** [comment]
See https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug - produce a bugdumb

**Comment by Laitdark** [comment]
Oh. Nevermind. Found a reason by going through the log (It actually appeared through using a .bat file). It was the Read-Only status of loadorder file in AppData. Issue resolved

**Comment by Utumno** [comment]
Glad it did - please try and use latest beta from the forums here: http://forums.bethsoft.com/index.php?/topic/1604190-relz-wrye-bash/page__view__getnewpost
