### ISSUE TITLE
Rework the Ini Edits tab

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#326]
The Ini tab needs a complete refactoring for performance, refresh glitches, code readability and whatnot.
- [x] IniInfos should take care of refreshing the target ini - it is taken care off by the panel making the logic of the code very convoluted
- [x] tweak status should be set in IniInfos refresh iff the target ini changed or the ini tweak changed
- [x] We should not refresh the ini on boot if the ini tab is not enabled. In general enabling/disabling tabs is very badly implemented and although I fixed most bugs, code quality suffers.
- [x] when non current ini is deleted outside Bash change is not detected
- [x] default tweaks should be harcoded - bin the folder  Mopy\Ini Tweaks that only serves to confuse (I came across a BAIN package packaging inis as in Mopy\Ini tweaks - see #219) and create a DefaultINIFile(INIFile) class
- [x] the panel should have a details view like the others and its ShowPanel API match the people's/screens etc - this surelly leads to other issues like:
  - [x] refresh glitch - deleted ini changes are not reflected if we fall back into default init
- [x] IniInfos should feature IniFiles - IniInfo should directly inherit IniFile and _AfileInfo (https://github.com/wrye-bash/wrye-bash/commit/b0e4c7fd31f5dc93854b0bfc4e6e49648bb6d6b6)
- [x] read_ini_content(as_unicode=True) should return stripped lines - get rid of whole line handling in `bosh.ini_files.OBSEIniFile#saveSettings`
- [x] SortChoices() and rest of targets handling (move rest of logic in the data model (clean_targets method...) should be moved to the data model that should wrap settings[bash.ini.choices'] accesses.
- [x] `oblivionIniMissing` should be set on booting and we should warn on boot also - it's a mess I warn you

- [ ] applying an ini tweak by BAIN is complicated to no end

----
- [ ] **add a corrupted data structure to IniInfos** see Monkey patch for undecodable inis commit

----
- [ ] use [ConfigParser](https://docs.python.org/2/library/configparser.html) to read write/inis instead of reinventing the wheel (except if there is a reason to reinvent - **investigate!**) - see also: [Writing comments to files with ConfigParser](http://stackoverflow.com/q/6620637/281545), [ConfigParser with Unicode items](http://stackoverflow.com/q/1648517/281545), [Python 2, ConfigParser: retrieving the line number of a section/option](http://stackoverflow.com/q/28675565/281545)
- [ ] multiline values are not read correctly:
  ```
   _settings_cache_linenum:
   SMasterMismatchWarning (190933648) <type 'tuple'>: (u'One of the files that "%s" is dependent on has changed since the last save.', 701)
  ```
----
- [ ] drop syscalls from get_ci_settings - patch SaveSettings to update the cache. This will take care of:
  - [x] cache also language in oblivionIni (75ba2f7)
    - [ ]  drop it again when system calls are pruned from get_ci_settings
  - [ ] getSetting should become get_settings_cached - always load cache on start. Not called in a loop anywhere but still..
  - [ ] cache the target ini settings for the getStatus calls
  - [ ] follow with the debugger updating the ini - you will see a busload of getting modification times etc (for the target ini for instance)- cache!
- [ ] simplify bosh.ini_files.IniFile#needs_update -> move it to OblivionIni ?
- [ ] ini_line_info named tuple
- [ ] drop Browse from targets - add a button

See also: 1d4c23a037f6845f5dfebaf1e5e005f8f121a63b

Tweaks:
Tweaklines control rework deletion 63cc29cd1461ea0d0c529a5867d63a00f5c58e27

Tracking uses of getTweakFileSettings - WIP, TODOs:
TODO: We should avoid copying the cache in getSetting - factor out
_cache updating code.

**Comment by Utumno** [comment]
This should have been closed in https://github.com/wrye-bash/wrye-bash/commit/bb6c8bd2e7ac22d1218cbad90e404b9739dba7bc

**Comment by Infernio** [comment]
After trying to use `ConfigParser` to do the `INIGame` work for Morrowind, I can safely say why we're reinventing the wheel: because ConfigParser works great for reading, but is utterly unsuitable for writing. It strips comments, which is a no-no for mod and game INIs that often contain explanations for settings. Trying to read OBSE INIs with it would probably consist of a whole bunch of hacks too...

Really, our INI reading/writing framework needs to be able to do *minimal* edits to the INI to achieve the desired effect. This is something that IniFile is quite good at, but ConfigParser absolutely fails at due to it forcibly rewriting the entire file every time.

On another note - the INI viewer on the right-hand side of the INI Edits tab does not seem to refresh in response to file changes? May be a regression, I'm not sure if that's worked before or not.

**Comment by Utumno** [comment]
> May be a regression, I'm not sure if that's worked before or not.

hmm seems to work on nightly - thanks for the ConfigParser - checked!
