### ISSUE TITLE
FileInfo(s) APIs refactoring

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#336]
It is not a terrible API per se but:

- [x] IniInfo have no backups, headers and masters (https://github.com/wrye-bash/wrye-bash/commit/81746fbfee4f8e6017f4435a556d1b072b7209e0, https://github.com/wrye-bash/wrye-bash/commit/b0e4c7fd31f5dc93854b0bfc4e6e49648bb6d6b6#diff-9cce2419e77947d069ca14ed8543066bR2096)
- [x] those two should subclass their files directly (https://github.com/wrye-bash/wrye-bash/commit/b0e4c7fd31f5dc93854b0bfc4e6e49648bb6d6b6, https://github.com/wrye-bash/wrye-bash/commit/b199a7bd5eec69ec0852f86d6e3629784e6b90ce#diff-9cce2419e77947d069ca14ed8543066bR2936)
- [x] sameAs is not a bad idea but needs_update may be better (https://github.com/wrye-bash/wrye-bash/commit/ad79e70632c2eca473abe923277d6db069246ff9)
- [x] refresh ! needs rewrite to be more granular and the different kinds of infos complicate this a lot (ghosts, default tweaks...) -> #353 (for this issue specific see for instance https://github.com/wrye-bash/wrye-bash/commit/ad79e70632c2eca473abe923277d6db069246ff9, https://github.com/wrye-bash/wrye-bash/commit/25a20555b1c611ba560af8a71fc84d18adffc06e)
- [x] bosh.ModInfos#refreshFile <--- revisit
- [x] needs_update refreshFile rename (_cache_updated, add_info)
- [x] CorruptedFile(AFile) class to further optimize refresh (now it always recheck corrupted, plus we do not have an easy way to mark BSAs as corrupted when their cache is read) See: [_reset_cache rewrite to unify refresh](https://github.com/wrye-bash/wrye-bash/commit/25a20555b1c611ba560af8a71fc84d18adffc06e) ~~-> actually no - just add a corrupted attribute~~ -> a1c5a36bce7184e66f2fe9455ca718900608b665
  - [ ] Corrupt files don't get refreshed properly when deleted: create empty TXT file, change extension to ESP, refresh WB, delete it, refresh WB -> traceback
- [ ] cachedCrc/setmtime - crc is not correctly updated in some cases - see [Reworking AFile API - keeping ctime - WIP](https://github.com/wrye-bash/wrye-bash/commit/b7586dfb90bb45bf0200c2fe58d02f96954602a6) commit
- self.abs_path -> use sparingly, don't want a new getPath (moving logic into ListInfos helps)
- [x] incorporate Installers and screens to this AFile API - see e007a5308d509fcd5e123d566b2b3c24e228edaa / beef63c79c52af80cdbf7c9ba953e408680df6a3
- [ ] remove table - use it only to load/save the 'persistent' (see Installer) attributes - then get/set attributes to the infos accordingly
  - [ ] BSAInfo no masters - but table first this is nit
- [ ] use the persistent/volatile ListInfo attributes to properly implement rename! (again see Installer copy_to)
- [ ] use Afile for load_order files
-----

File operations - we need to mark_unchanged if using the python methods but SHFileOperation will preserve c/mtime - all this part of the API needs rewrite, it's system's programming after all, generally a hard subject. See Slight optimizations in rename:

-----

Rename/Hide/Backup and co fall into two categories: copying and moving files. We should rethink our internal APIs for copying/moving and then rewrite those operations as thin wrappers (passing the right paths in) around a copy/move API. Those operations should be as atomic as the filesystem permits. Moreover, when renaming/hiding/backing up/moving in save profiles etc multiple files we should construct all the source/paths _at once_ and issue _one_ system call - see for instance _try_rename that does this per file...

----

I created an AFile class to represent a file with a cache check for mod times and size but it's difficult to plug it in. Opening this to document/coordinate the refactoring.

**Comment by Infernio** [comment]
I know this is probably fixed in your 336 work already(?), but I just got this with a corrupted save (or rather, save that WB does not yet know how to read) in Starfield:

```
Traceback (most recent call last):
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/gui/events.py", line 181, in _post
    result = listener(*listener_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/balt.py", line 515, in _conversation_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/basher/__init__.py", line 4006, in RefreshData
    store.unique_store_key: not booting and bool(store.refresh()) # todo add the refr object here
                                                 ^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 3412, in refresh
    return super().refresh(booting=booting) if refresh_infos else \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 1589, in refresh
    new_or_present, del_infos = self._list_store_dir()
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 1643, in _list_store_dir
    return self._diff_dir(FNDict(((x, {}) for x in inodes)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bosh/__init__.py", line 1651, in _diff_dir
    if inf.fn_key not in inodes}
       ^^^^^^^^^^
AttributeError: 'Corrupted' object has no attribute 'fn_key'
```

**Comment by Utumno** [comment]
Thanks Inf and thanks for merging that ton of commits and fo4 refactoring and for investigating the heisenbugs - let's see if this one is really fixed.
