### ISSUE TITLE
Remove/Hide custom plugin timestamping

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#34]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/235/)

Now that Bash uses BAPI for load ordering, and Skyrim doesn't use timestamps for load ordering, the ability to set custom timestamps through Bash is useless (correct me if I'm wrong), as changing the load order through drag 'n' drop or the arrow keys would cause timestamps to be overwritten by BAPI on Oblivion, and timestamps are ignored in Skyrim.
Removal of the custom timestamping features involves the removal of the File->Sort (which should never have existed...) and File->Redate plugin context menu commands, and the Timestamp field in the Modified panel. The Modified column in the main list in the Mods tab could also be removed, but I'd argue that it's still got some informational use for Oblivion. Perhaps it could be hidden by default for Skyrim.

**Comment by Infernio** [comment]
Using redating to move files around is pointless since d67f621278ffddaafcb4d55b735bb5a075bd9c92, but as mentioned above, redating still has other use cases.

**Comment by Infernio** [comment]
As for 'Sort', 92691409567ce020c6958325ee8c4bd8c9e820cc renamed it to 'Order By Name', so I don't think there's any more issue with it ('Sort' was definitely terrible as a name for it though, agreed).
