### ISSUE TITLE
Include updated 7z.exe and 7z.dll

### ISSUE THREAD

**Issue by HylianSteel** [wrye-bash/wrye-bash#341]
As it stands right now, the bundled 7z.exe and 7z.dll are version 9.20 (from 2010). The newest version is 16.04 (just updated last month) and includes quite a bit of improvements.

**Comment by Gr3yStar** [comment]
I see that this is actually a duplicate issue. closing.

**Comment by Utumno** [comment]
Yep duplicates #313 but still thanks for the heads up for 16.04
