### ISSUE TITLE
Installer Directories Containing Solely BA2 Files Not Showing Up

### ISSUE THREAD

**Issue by nephatrine** [wrye-bash/wrye-bash#343]
I've got a mod folder laid out like this:

\00 ESP Option A\
\00 ESP Option A\example.esp
\00 ESP Option B\
\00 ESP Option B\example.esp
\01 Assets\
\01 Assets\example.ba2

Installers only shows the first two options as sub-packages and has no way to install the "01 Assets" folder. If I put in a loose asset as well, then it is able to pick up the folder and it does install the BA2 files just fine afterwards. I don't really think I should have to put dummy files in there though for Sub-Packages to see it and allow it to be installed.

**Comment by Utumno** [comment]
Yep, I have addressed this in my wip branch - you can use the python version of utumno-wip from here or wait for me to pack a standalone (check the oblivion thread link in Readme.md here)

**Comment by Utumno** [comment]
Current dev code contains the fix for this if you want to test
