### ISSUE TITLE
Rework Mod Groups - remove BALO

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#35]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/234/)

BALO allows users to put plugins into arbitrary groups for load ordering purposes. These groups are also handy for selectively enabling/disabling groups of plugins, as you can deactivate or activate all the plugins in a group at once. However, BALO is deprecated and will shortly be removed.
Exclusion groups are a way for Bash to warn players if they have more than one plugin of an arbitrary group of plugins active at once. This is neat, but it requires renaming the plugins to put them in a group, which is a Bad Idea (TM). Exclusion groups are independent of BALO.
The idea of groups is a good one though, and is a useful feature for Bash. Groups would also be useful for BAIN, where they already have a semi-parallel in the form of marker packages. However, having an abstract definition that can then be made specific to plugins and packages would be neater. Within this abstract group concept, a group could be one of two types: exclusive or inclusive. Exclusive groups only allow at most one item to be active at once (one plugin or package), while inclusive groups allow many items to be active at once (but not necessary all of them). The members of a group could be activated or deactivated with one action, and trying to activate more than one exclusive group item could result in a warning from Bash.
To differentiate the group concept from that of a load order list as found in the mods tab, a load order list is ordered, whereas a group is not, and activation of a load order list deactivates all plugins not in the list. Neither groups nor load order lists are necessarily cohesive (ie. if A and B are in the group/list one after another, then C, which is not in the group/list, could be between them).
These features would replicate the current functionality with better "focus" than is currently present, giving it firmer foundations.

**Comment by Utumno** [comment]
Balo is (hopefully completely) uprooted, groups function and have couple more edit actions added and exclusion groups seem to serve their dubious purpose - so I am calling this a day. I am leaving the check items just as a reminder - if you have lots of free time try implementing some of it - better wait for bosh refactoring has started though.
