### ISSUE TITLE
Reporting a Bug - Clarifying

### ISSUE THREAD

**Issue by m0lz** [wrye-bash/wrye-bash#357]
I dont know where to report documentation so opening an issue.

Reporting a bug documentation
https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Reporting-a-bug

Could that be changed a little ?, I tried following it ( I was going to report a bug but turned out I was overlooking something so its no longer necessary ).

The 1st problem I see is in a users point of view reading it. 
To anyone unfamiliar looking for the word Standalone, WBSA does not leap out at you. It took me a while to realise it stands for Wrye Bash StandAlone ( and only because looking carefully I saw the exe mentioned in the code box after it )

The 2nd problem is probably only obvious to anyone not so familiar with command lines
For a long while I was trying different methods of typing "Wrye Bash.exe" -d into the command line and not producing a bugdumplog in mopy.
Then I noticed the word navigate, and that your command line prompt included the path to mopy

Only then did it dawn on me that I somehow had to change where the command line prompt was sourced / directed to

How are typical users expected to decipher all this to give you a bugdump if they are not familiar with the command line and what you mean by navigate, or that there is any other kind of command involved in "navigating"

So I propose the Reporting a Bugdump instructions are buggy, and need changing to read something like the following to make it clearer -

Change

WBSA version
Fire up a command prompt, navigate to Mopy and issue:
C:\path\to\Mopy>"Wrye Bash.exe" -d
This way the output will be redirected to Mopy/bashbugdump.log and no more stdout/stderr windows will pop up.

To something like

Standalone version
Fire up a Command Prompt, which will look similar to this
C:\Users\Username>
ensure you know the full path to your game installation, and type ( changing path\to\game ) :
chdir /D "C:\path\to\gamefolder\Mopy"
Your command prompt should now read 
C:\path\to\gamefolder\Mopy>
Type 
"Wrye Bash.exe" -d
Wrye Bash should now launch, and any error output will be redirected to Mopy/bashbugdump.log
The bashbugdump.log is a text file, and the contents can be pasted into forum posts.

**Comment by Utumno** [comment]
Go ahead and edit the wiki

**Comment by Utumno** [comment]
BUt actually the correct _is_ path/to/mopy - Bash can be anywhere it's not required to be in the game folder

**Comment by Utumno** [comment]
And do not edit out the "and no more stdout/stderr windows will pop up." - that's needed info

**Comment by m0lz** [comment]
@Utumno
Done
Done
and Done preserving the quoted part of the original
This issue is also .. done - CloseMe

**Comment by Utumno** [comment]
Reopen as needed - please keep wiki line length short (most of the wiki's I wrote/edited are like that) so I can compare revisions. Thanks!
