### ISSUE TITLE
Rework game handling

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#358]
- [x] move save files to a bosh/save_files.py module and mimic bsa_files.py - exceptions, header etc. Drop the `game/__init__.py` ess class and the convoluted saves handling hierarchy (see #349 -> done: https://github.com/wrye-bash/wrye-bash/commit/a824289a265d461ec6b3d310bf885cea2f422868)
- [x] create a GameInfo class for maximum typing and easier override of only changed options
- [x] Import reworking - see #360 - avoid importing constants.py files for all games
- [x] bush - defaultEyes etc are oblivion specific! - see 6f5f8ec0ebefcbd44adfe63858d91b5bb2d86b04, cc840a0dcb83a37eeb4983f956bfb64b77e17deb and 0eb4d7287658b4db00f2a0462196cabe72a419c6
- [ ] revisit splitting of constants in files and probably create some new ones/GameInfo variables based on uses of `bush.game.fsName`

Supersedes #65 

Backburner:

- [ ] Mopy/bash/basher/app_buttons.py - messy and muddy

**Comment by Utumno** [comment]
@GandaG - bush.game is a module loaded dynamically in bush detect_game and co. This has several flaws - first step to correct this would be:

- define a GameInfo class in game.`__init__` and push all constants in its namespace (as in indent all the file one level)
- repeat for other game files, making them inherit
- modify the loading mechanism so it sets bush.game to the respective class for that game
- test everything works (hunt up bush.game uses)
- as a final step eliminate duplicate code in GamInfo classes - defining common values in super class

GameInfo classes should be static. A probable design would be

in game.init

```
class GameInfo(object):
   fsName = ...
   
  def init ():
     ...

GameType = GameInfo
```

then in others say `oblivion.__init__`

```
from .. import GameInfo

class OblivionGameInfo(GameInfo):
   fsName = ...
   
  def init ():
     ...

GameType = OblivionGameInfo
```

and then set the bush.game to <game module>.GameType. That's just a suggested solution may have wrinkles

I expect this  to chop off hundreds of lines of duplicate definitions and open the way to fix up import garbage and other issues.

**Comment by GandaG** [comment]
Just a couple of thoughts:
- Should `game` be kept purely static or can I put some logic there? (Like splitting `_supportedGames`, having the game dicts be built via metaclasses in `game` and `_registryGames` be built at import in `bush`);
- Since everything in `game` is static data, how about config (json/yaml/toml) files to store that info in? With a common one to provide defaults. Doing the same with classes and importing all attributes to the `GameInfo` class in each game's `__init__` is also easily doable but config files seem cleaner.

**Comment by Utumno** [comment]
- Purely static as it is now
- No, they break the IDE code insight and it would introduce a new python dependency to parse the yaml and more code - a nono

Net result should be a net decrease in code ;)

**Comment by Utumno** [comment]
As a general note

> simpler is better than complex

That's so so true. People new to the code will have to grok metaclasses, be aware of import dependencies (actually import should be a noop, there is rarely an exception and most import statements that do something are downright wrong and in Bash had led to very subtle bugs) and game handling is really complex - we don't need it made more complex. I don't think David Beazley will be in Bash development any time soon so KISS

There is room for clever stuff, lots of room - but start simple.

Please make separate commits more or less as in my checklist - each commit must of course compile and not break anything - but should be easy to review also. So probably changing the first 3(4) points should be in one commit and last point (eliminate code duplication) in another commit.

Comments should be cleaned up too along with deduplicating code - so comments in base class and just sections of static fields in derived ones

Thanks :)

**Comment by GandaG** [comment]
Right, will do. One last thing, should game.constants et al. be placed in classes as well? 

The code everywhere expects those modules to be in the same namespace as the future GameInfo class, so should I put each of those under a variable in GameInfo and change access everywhere else? The only alternative that I can see and doesn't involve a bit of logic would be to duplicate all those variables in GameInfo (which would be horribly inefficient)

**Comment by Utumno** [comment]
> should I put each of those under a variable in GameInfo and change access everywhere else

I'd say yes - well there's always a little catch when refactoring. I haven't looked at it - care to give an example ?

> duplicate all those variables in GameInfo (which would be horribly inefficient)

And horrible in general - they _used_ to be in the same file mind you

---

Actually this is related to step two in game handling which is import refactoring - I would hope that this step would involve minimal changes outside `game/`

**Comment by Utumno** [comment]
Btw @GandaG I have set up some links in contributing.md as in https://github.com/wrye-bash/wrye-bash/blob/caefbb968a9c4cc2796ad67e77ce2b62048abf6c/Contributing.md#set-up - have you went through them ? Feedback/questions appreciated. I would recommend you install PyCharm, makes working with Bash code much easier. Plus there is another refactoring I would like done after this one ;)

**Comment by GandaG** [comment]
`game.<game>.constants` as an example. Right now, it's fully imported into `game.<game>.__init__` and other modules access it as `bush.game.<constant>` (see `basher.mods_links@44`). 

It could be changed to having a class `<game>Constants` in `game.<game>.constants`, that is imported and used in `game.<game>.__init__` as such:

```
from .constants import <game>Constants
from . import GameInfo

Class <game>Info(GameInfo):
    constants = <game>Constants
```

And it would be accessed as `bush.game.constants.<constant>`.

---

I'm still downloading Windows to dual-boot it, will read after! I have installed PyCharm but it slows down my crappy laptop too much :/ I'm sticking with vim until I get back to my proper desktop.

Sure, I'm up for it, since you're not letting me do any cool stuff here (;p) this one should be simple enough

**Comment by Utumno** [comment]
Haha you can always fix an issue - well 1% inspiration, 99% perspiration. I ahve performed countless such tasks - have a look at my wip - renaming stuff and the like, all the time. Now actually I am doing a much needed refactoring in core data apis - not exactly cool.

You do need PyCharm, yes it's slow on me too. If you have a uni account grab the professional. But the refactorings I need are most easily done on pycharm

----

(should be first)

Well, this means we have to address the import issue: the problem is that we load all constants (and records) for all games always. That's more intricate to solve correctly.

Can we somehow (temporarily) inject the constants into the game namespace in `init()` ? They should not be used before `game/<game>. init` is called

**Comment by GandaG** [comment]
Something like this?

```
from .constants import <game>Constants
from .. import GameInfo

class <game>Info(GameInfo):
    @classmethod
    def init(cls):
        for key, value in <game>Constants.__dict__.items():
            if key not in cls.__dict__:
                cls.__dict__[key] = value
```

A bit hacky but it does inject everything into the GameInfo namespace and provides lazy loading.

**Comment by Utumno** [comment]
Hmmm - to be honest I would prefer a solution where we avoid all that and instead we have two globals in bush - one for the GameInfo class and one for the <game>.__init__ module (as it is now) and keep constants referenced from the module. Then we can investigate what is the best ~~hack~~ way to lazy load. Keep in mind some game modules import from other game modules _ see skyrimSe for instance. It's not an easy problem ;)

To lazy load one should import locally btw:

```
class <game>Info(GameInfo):
    @classmethod
    def init(cls):
        from . import constants
        for key,value inspect.getmembers(constants): # is this the best way ?
            if key not in cls.__dict__:
                setattr(cls, key, value)
```

**Comment by GandaG** [comment]
Oh, I was assuming constants and such would also be placed in classes (so SSE would inherit from Skyrim). Would one of those variables be injected into the other? If not we'd run into the same problem as before, the rest of the code would have to be modified.

About the code, yes you're right about the lazy loading :p, inspect is the best to go about injecting from a module (afaik) but the issue with grabbing everything from a module is that you'll inject everything that module imported unless you do some specific logic for each injection (need to check if imports actually change)

So the current idea is to keep everything the same way except for making the GameInfo classes out of \_\_init\_\_ and putting them in a separate variable. Is that it?

**Comment by GandaG** [comment]
Well, if some more extreme lazy loading is required, __getattr__ could be overridden and constants et al. only imported whenever something tries to access them.

**Comment by Utumno** [comment]
Actually I think that the _module_ should be put in another variable - most bush.game accesses access the constants that will become static fields of the GameInfo class, so less code modifications if we make 'game' point to the GameInfo type

**Comment by GandaG** [comment]
Mostly done, just waiting those 15 hours for Skyrim to finish downloading to test.

Just to recap, your requirements are:
* `game` should be kept purely static
* no hacks
* modules/variables in `game` should be loaded as selectively as possible
* `bush.game` access should change as little as possible

And since we're breaking point 4 already, let me propose properties (surprisingly not hacky):
```
class <game>Info(GameInfo):
    @classproperty  # read-only
    def constants(cls):
        import constants
        return constants
```

Again, breaks 4, but I haven't been able to find a solution that fits all those points :/

**Comment by Utumno** [comment]
That's neat but I would like to avoid local imports - meanwhile where is da code ? :)

**Comment by GandaG** [comment]
I was waiting to test (3 hours still to go) before committing but [here you go](https://github.com/GandaG/wrye-bash/tree/ganda-358) (I'll improve the commit msgs on rebase)

**Comment by Utumno** [comment]
Thanks indeed - looks nice, nicer than I thought. Note that now we can much more easily track what comes from where - https://github.com/GandaG/wrye-bash/commit/073245583a543a5ca1aae7efdc39be0f05e39693?w=1. 'game' was a rather bad choice

Well be informed that like all tasks I assign people there's more than meets the eye - even in this first phase I am curious to see if the BP is built - there are very arcane import cycles in there.

But I like it and it opens the way to more interesting refactorings, thanks!

**Comment by Utumno** [comment]
Be aware that the same procedure must be repeated in fallout3/NV branch! more on that later

**Comment by GandaG** [comment]
It had a few mistakes (init() should be static), fixed them, bashed patch builds for Skyrim. There is something I wanted to test for SE (the se class inherits from oldrim, skips importing all those things) but I've tripled checked and it should work. Will test when it finished downloading. There are a couple of bugs but they're there in dev as well.

Anything else before I start moving defaults to base class?

**Comment by Utumno** [comment]
> There are a couple of bugs but they're there in dev as well.

Ooops - bugs, where ? :looks:

Hmm- I'd say let's wait till tested - will cherry pick to the utumno-wip branch and have more people test it. Of course you can go ahead and start chopping off that duplicate code, but we may have bugs that will cause us to rework it

**Comment by GandaG** [comment]
Well, it may be that I screwed up the setup (I'm not used to Windows), but in the patcher dialog for oldrim I can't change the tweak values (it shows up as `Timescale [[20]]`) and this shows up after:
```
Traceback (most recent call last):
  File "bash\balt.py", line 436, in <lambda>
    if onButClick: self.Bind(wx.EVT_BUTTON, lambda __event: onButClick())
  File "bash\balt.py", line 1605, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\patcher_dialog.py", line 264, in PatchExecute
    bosh.modInfos.refreshFile(patch_name)
  File "bash\bosh\__init__.py", line 1331, in refreshFile
    self._notify_bain(changed={info.abs_path})
AttributeError: 'NoneType' object has no attribute 'abs_path'
```
Let me rebase then!

**Comment by Utumno** [comment]
No it's a regression in the head of dev commit! Rebase over utumno-336-new_info branch - it's just fixed in there. Sorry about that!

**Comment by Utumno** [comment]
>  but in the patcher dialog for oldrim I can't change the tweak values (it shows up as Timescale [[20]]) 

Hmm don't know about that - timescale is pretty useless in oldrim

**Comment by GandaG** [comment]
Refactored GandaG/wrye-bash@3470b80bb

The timescale was just an example, it appears like that for all of them (will re-check when back on Windows with the 336 branch)

**Comment by Utumno** [comment]
Hey thanks will have a look - ended up working on Bash 8 hours a day those last 3 days - will take a break. I wanted to do some refactoring that I wanted in since a while - proved a full time job. Merged in dev, along with the regression fix. Will take down the 336 branch if I don't have any bad news. Use dev from now as normal :)

**Comment by GandaG** [comment]
Sure, tomorrow I'll re-rebase and re-push :stuck_out_tongue_closed_eyes:

**Comment by Utumno** [comment]
Hi @GandaG and a happy new year :)

In discussion in #390 I realized that to decouple bosh from bush we probably need to turn init into a class method and perform some common init tasks in there - like setting the _bsa_type. Could you turn it to a class method in next rebase ?

**Comment by GandaG** [comment]
Happy new year! I had actually forgotten to rebase on dev so I'll get on it right away. Anything else that is needed?

**Comment by Utumno** [comment]
Thanks @GandaG 

Two things - start working on moving common code to base GameInfo and apply those changes to the fallout3 branch - see #400

**Comment by GandaG** [comment]
After the common code refactor, should I diff both commits and apply them to the [fallout branch](https://github.com/wrye-bash/wrye-bash/tree/feature-sharlikran-valda-fallout)? Or diff/apply only `game.__init__.py`?

**Comment by Utumno** [comment]
You should ideally rebase the fallout branch on your branch and make a clean commit touching only the fallout3/nv files - that will be squashed in there later. Maybe there are some usages of game_mod in there to hunt down still.

**Comment by GandaG** [comment]
May I delete the duplicate comments on each `<game>.__init__` explaining what the variables are? It's already in GameInfo and I won't touch any game-specific ones.

**Comment by Utumno** [comment]
Definitely

> Comments should be cleaned up too along with deduplicating code - so comments in base class and just sections of static fields in derived ones

;)

**Comment by GandaG** [comment]
Done GandaG/wrye-bash@d052d3a

Will do fallout tomorrow!

**Comment by Utumno** [comment]
Excellent - left some comments for you

>  207 additions and 704 deletions

Better than I thought and there's room for more - so 500 lines of unneeded duplicate code, duh
Glad you took care of those internal classes overrides too !

**Comment by Utumno** [comment]
@GandaG would like to merge - are we ready ?

**Comment by GandaG** [comment]
Fallout branch isn't finished and all that is missing in the "regular" one are those little formatting changes that also aren't finished. I can finish both after my exam on tuesday, sorry.

**Comment by Utumno** [comment]
Thanks @GandaG - fallout would need also the RecordHeader and editMore changes applied from the dev branch. Good luck with your exam !

**Comment by GandaG** [comment]
The formatting changes are done GandaG/wrye-bash@2467c8e2 let me know if something else is needed on this branch.

**Comment by Utumno** [comment]
Thanks @GandaG, good job - for some reason you put `stringsFiles = []` into Fallout4 but I will correct that on merge. Btw (@wrye-bash/devs) when changes are requested it's better to commit those in a separate commit so I can review them separately from the initial commit which I have already reviewed.

Could you take up the sync of the fallout3 branch with dev (recordHeader and canEditMore commits - hope I am not missing something) - in separate commits over your fork of that branch ?

**Comment by Utumno** [comment]
Will proceed merging - alea jacta est!

What is important is we carry those to the fallout3/nv branch. Afterwards we should address:

- [ ] saveProfilesKey move to SaveInfos
- [ ] drop laa and the button - this will cascade - remove images, add to readme etc etc
- [ ] rework constants.py - remove short constants and move them to `game.__init__.py` and import locally in game.init as with records

**Comment by Utumno** [comment]
@GandaG I corrected the fallout3 branch - now what's left to do is only apply the GameInfo refactoring there - please do (or let me know if you can't)

**Comment by GandaG** [comment]
Should I leave these comments? [1](https://github.com/wrye-bash/wrye-bash/blob/0265fc2d3ea66576a3f0630728cc340577dac8cc/Mopy/bash/game/fallout3/__init__.py#L265-L274), [2](https://github.com/wrye-bash/wrye-bash/blob/0265fc2d3ea66576a3f0630728cc340577dac8cc/Mopy/bash/game/fallout3/__init__.py#L283-L289), [3](https://github.com/wrye-bash/wrye-bash/blob/0265fc2d3ea66576a3f0630728cc340577dac8cc/Mopy/bash/game/fallout3/__init__.py#L463-L472)

**Comment by Utumno** [comment]
Yep - those are probably the full patcher support offered in valda's version. As I commented in one of your commits, minimal _code-only_ edits - so it is easier for me to review.

Replying to you here for your PM:

>  Forgot to ask, how should the commit msg be for fix commits? "Fixup into XXXXXX - fixes problem a, b and c"? 

Up to you basically as long as a person reading this one year after can understand what's going on.

Those particular fixup commits will be squashed with initial commit of `__init__` files - iron rule is we do not allow broken commits on dev if we can avoid it. Just waiting for this to rewrite that branch.

An interesting coding problem - have a look at the comment in  Mopy/bash/game/falloutnv/records.py at 57334e12bea7ee919cabf3ca5ade8b94fae937ff

> """ Can't import MelConditions, MelEffects, MreAlch,

> +    MreCpth, MreIdle, MreMesg, MrePack, MrePerk, MreQust, MreSpel, MreTerm,
> +    Because once the imported Fallout 3 record is used it will use Fallout 3
> +    constants.py regardless of imports in falloutnv.records.py."""
> 

Could we do better than that now with the GameInfo machinery ?

Of course for your changes to work you should rebase the branch on dev - and have a look at my additions, namely importing the records in init etc (had left comment for you on older comit versions see above)

Have also a look at checklist aboveespecially `rework constants.py` - smaller ones should be moved inside GameInfo - give this some thought.

And in case you run out of work - there is always #342 where there is ongoing understanding we should rewrite SSE records.

Thanks!

**Comment by GandaG** [comment]
> minimal code-only edits

Right, this time I sort of did it all in one commit - GandaG/wrye-bash@83ae72b. I can split easily, let me know if it's better.

> namely importing the records in init etc (had left comment for you on older comit versions see above)

Will apply the same to the fallout branch. Both of them have no merge/read/write classes so it's only the imported records really.

> An interesting coding problem - have a look at the comment in Mopy/bash/game/falloutnv/records.py at 57334e1

Sorry, I'm not understanding what they mean with the comment. Is it that the import from fallout3.records will override the local definition at falloutnv.records?

Please review my last commit and the one I'm about to push (and test since I can't really) and we'll get to the checklist after!

**Comment by Utumno** [comment]
Thanks @GandaG - I pushed corrections as commits in fallout3 branch here - have a look at last few. No need for splitting actually everything will be squashed to initial commit of these files, as we want no broken commits on dev and half of this branch is broken as we apply fixes in separate commits. Did it that way to review easily but will get to rewriting the history of the branch asap

Meanwhile a nice side issue that people have been requesting since for ever is https://github.com/wrye-bash/wrye-bash/issues/273

**Comment by Utumno** [comment]
@Infernio @GandaG 

I finally came round to revisiting some old branches (some of it before the GameInfo refactoring) addressing loading the constants.py for all games. We don't want to do that especially as we support more and more games - it's ugly and p[erformance nowadays depends very much on memory pressure.

I had attacked this problem in various ways:

- rewriting the importer in Wrye Bash launcher: https://github.com/wrye-bash/wrye-bash/tree/utumno-358-fake_importer-XXX - this is rejected (I am not even sure it does the trick, plus anyway it's not used for the Standalone, don't ask me why) but I posted it here for your reference (it does not even launch). Btw the Importer code was there cause python could not launch Bash if there were unicode chars at the Mopy path - maybe not needed anymore (and it's definitely hacky). See http://stackoverflow.com/a/43700205/281545 for a detailed analysis of my hack
- doing some `locals()` hacks - that's ugly, had to be repeated in every GameInfo.init we had to explicitly import the constants etc etc - rejected (and untested) - see: https://github.com/wrye-bash/wrye-bash/tree/utumno-358-locals-hack-XXX
- my preferred solution: https://github.com/wrye-bash/wrye-bash/tree/utumno-358-dynamic-import-hack . This has many advantages:

		Cons:
		- Hack, we should find a way to call super cls init see:
		https://stackoverflow.com/a/1269224/281545

		Pros:
		- get us rid of constants.template and instead enhances IDE's static
		analysis (now constant.py members are offered for autocomplete)
		- gets us rid of from constants import * (star imports are evil)
		- gets us rid of duplicate code - we only need to define in constants
		what is actually used or else fallback to GameInfo empty class
		variables (see for instance cleanup in bash/game/fallout4/constants.py)
		- helps us trace down bush.game_mod real (and hacky) uses
		- and of course, reduces RAM usage as we only load constants module for
		running game

  still needs some love (revisit bush cleanup code (_allModules and co), test in the nightly, remove prints and possibly revisit constants comments/layout) but I am rather satisfied. Infernio you have been working with the constants module lately, I believe this will make things much more elegant (no need to define constants for every game, static IDE analysis/code completion etc)

----

Meanwhile, could you guys review the first few commits in my branch - namely the bush rip: https://github.com/wrye-bash/wrye-bash/commit/203974120445776998e994fa64d45e08ad943c4f and the next few renaming `flags`. I think we should push those to dev along with some of @Infernio 's fixes and then publish a new nightly containing this constants-handling rewrite and fixups from Infernio's wip - push a nightly to Nexus too

Thanks! :)

**Comment by Utumno** [comment]
@Infernio I pushed your branch and included some of it in the nightly branch https://github.com/wrye-bash/wrye-bash/tree/inf-wip-on-nightly - feel free to review and delete as needed. I will pack a nightly and if all goes well those patcher fixups here: https://github.com/wrye-bash/wrye-bash/compare/cf5927d6316fa420f2599fd6e8d46da200aab843...67fa856dfb639527996d1c2884e7b0409bfff10c should land on dev

I count on you to keep an eye on the forum for possible regressions - but we should merge and post a nightly on nexus ASAP

Thanks!

**Comment by Utumno** [comment]
At long last indeed - thanks!
