### ISSUE TITLE
Update Help File

### ISSUE THREAD

**Issue by ghost** [wrye-bash/wrye-bash#359]
In Wrye Bash 307, right-clicking the column headers only allows users to select which colomn to be displayed. "List Mods" is not available and "List Bash Tags" only avalable in contextual menu when right-cliking on of the listed mods.

In Help file:
"If the issue is related to the Bashed Patch, please include the following:

    Your load order. Get this by right clicking on a column header in the Mods tab, and selecting List Mods....
    Your Bash Tags. Get this by right clicking on a column header in the Mods tab, and selecting List Bash Tags...."

**Comment by Utumno** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/1365079/21964063/3ddd1a6c-db45-11e6-9e1b-e3dc8d024130.jpg)

**Comment by SinbadStackpole** [comment]
Sorry, my mistake. I read it too fast. I thought it was  right clicking on the Mods tab.Thank you and sorry for the trouble.

 
      De : Utumno <notifications@github.com>
 À : wrye-bash/wrye-bash <wrye-bash@noreply.github.com> 
Cc : SinbadStackpole <rommel30@rocketmail.com>; Author <author@noreply.github.com>
 Envoyé le : Dimanche 15 janvier 2017 11h09
 Objet : Re: [wrye-bash/wrye-bash] Update Help File (#359)
