### ISSUE TITLE
Refactor generic launchers

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#36]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/232/)

Many of Bash's launchers are to utilities for which it provides no special icon, and no special options. The few that are specially handled include TES4Gecko, TES4Edit, TES4LODGen, BOSS and perhaps some of the other modding utilities also get special icons.
For the utilities without special handling, it would be neater if support for them was not hardcoded into the ini file and the Python, but instead was handled via shortcuts to these utilities in Mopy\Apps. Bash could ship with shortcuts to their default locations, and this would work just as well as it does with the current system, but would involve less code (which is IMHO a good thing).

**Comment by Infernio** [comment]
Related to #250 and #479 - needed to mirror Polemos' fork.

**Comment by Utumno** [comment]
Yep! a lot of cruft (and windows specific cruft) in there - for one buttons need a static factory and subclasses like JaveButton etc instead of setting 100 attributes in AppButton init based on if checks

308 proper

**Comment by Utumno** [comment]
Closing in favor of  #570
