### ISSUE TITLE
Clean up imports

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#360]
Apparently - due to the dirty dynamic imports of the game modules etc most probably ~~and our dear hacky launcher~~ nope it's not the launcher - disabling it results in exactly same `sys.modules` - we import modules twice or thrice or several times under different namespaces. YAK!

Look at the attached bugdump

[BashBugDump - OBLIVION IMPORTS.txt](https://github.com/wrye-bash/wrye-bash/files/724192/BashBugDump.-.OBLIVION.IMPORTS.txt)

`bash.basher.re` ??

EDIT: turns out those are not a problem:

http://stackoverflow.com/a/1958474/281545 -> [Dummy Entries in sys.modules](http://www.python.org/doc/essays/packages/)

But there is another issue - we never delete the imported modules for other games

    def readHeader(self,__once=[]):
        """Read header from file and set self.header attribute."""
        if not __once:
            __once.append(True)
            deprint("sys.modules", '\n'.join(x for x, v in sys.modules.items() if v is not None))
        from .save_files import get_save_header_type, SaveHeaderError

[BashBugDump - OBLIVION IMPORTS WITHOUT DUMMIES.txt](https://github.com/wrye-bash/wrye-bash/files/724488/BashBugDump.-.OBLIVION.IMPORTS.WITHOUT.DUMMIES.txt)

EDIT: this proves harder than I thought ->http://stackoverflow.com/questions/3105801/unload-a-module-in-python -> http://web.archive.org/web/20080926094551/http://mail.python.org/pipermail/python-list/2003-December/241654.html, http://bugs.python.org/issue9072

This basically means we must load the records and the rest inside game.game.init.... _**OR**_ _probably not import all game modules ?_ - see: http://stackoverflow.com/a/41848229/281545
Under #244 and #358 too

**Comment by Utumno** [comment]
related: debugging the crash reported:

http://forums.bethsoft.com/index.php?app=forums&module=forums&section=findpost&pid=25304464

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 441, in main
  File "bash\basher\__init__.py", line 4033, in Init
  File "bash\basher\__init__.py", line 4083, in InitData
  File "bash\bosh\__init__.py", line 3702, in refresh
  File "bash\bosh\__init__.py", line 2424, in refresh
  File "bash\bosh\__init__.py", line 1591, in getHeaderError
  File "bash\bosh\__init__.py", line 2156, in readHeader
ImportError: No module named save_files

People were launching by shortcut: http://forums.bethsoft.com/topic/1614408-wrye-bash-thread-113/page-7#entry25308638

![supierce_shortcut](https://cloud.githubusercontent.com/assets/1365079/22846928/4e973cfc-efea-11e6-8642-60fa327e1de8.jpg)

See: [What is a window's shortcut equivalent command on cmd?](http://superuser.com/q/1172136/35020)

last piece of the puzzle: assoc prints ( Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Susan>assoc .py
.py=Python.File

C:\Users\Susan>assoc .pyw
.pyw=Python.NoConFile) :

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Susan>assoc .py
.py=Python.File

C:\Users\Susan>assoc .pyw
.pyw=Python.NoConFile

So having save_files imported locally crashes Oblivion 9but not Fallout 4)

**Comment by Sharlikran** [comment]
Using ``from module import xxxxxxxx`` still [imports they entire module](https://stackoverflow.com/questions/3591962/python-import-x-or-from-x-import-y-performance).

**Comment by Infernio** [comment]
Is there anything left to do here now that we dynamically import all but `game/*/__init__.py`? That's still a hack, sure, but it's a pretty well-worn and functional hack by now.

**Comment by Utumno** [comment]
No - this was meant for an investigation of imports (several issues over the years where we would import say brec and bash.brec or smth). I used to be schizophrenic but we are both ok now :P

**Comment by Utumno** [comment]
Reopen if you want to further dig into imports
