### ISSUE TITLE
[FO4] DLCUltraHighResolution.esm needs special handling

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#365]
With the inclusion of the new hi-res texture pack for Fallout 4, a new master file gets installed. That file, DLCUltraHighResolution.esm, needs to have the same handling applied to it as the other 6 DLCs do. The game will not write it to plugins.txt and thus Bash ends up listing it disabled and becomes confused just like it did with the other files.

I have confirmed via a save that it needs to be positioned after DLCNukaWorld.esm.

**Comment by Utumno** [comment]
Addressed in current python wip - now that all the pieces are in place that's as simple as one line. Removed the bug as we don't want it to appear on posts - it's just a tiny little TODO

**Comment by Utumno** [comment]
That being said please test it does work alright
