### ISSUE TITLE
Wrye Bash Python Error Message

### ISSUE THREAD

**Issue by aba42** [wrye-bash/wrye-bash#367]
Win10Pro, Wrye Bash 3.06,  Skyrim Classic.  Out of the blue, Wrye Bash will not complete a "Rebuild Patch" without generating the following error, then stopping:

wwPython:stdout/stderr

```
Traceback (most recent call last):
  File "bash\balt.pyo", line 1796, in _conversation_wrapper
  File "bash\basher\patcher_dialog.pyo", line 209, in Execute
  File "bash\patcher\patch_files.pyo", line 305, in buildPatch
  File "bash\patcher\patchers\multitweak_settings.pyo", line 259, in buildPatch
  File "bash\patcher\patchers\multitweak_settings.pyo", line 44, in buildPatch
AttributeError: 'NoneType' object has no attribute 'lower'
```

Searching for a solution, I was advised to back up to an earlier version of Wrye Bash.  I tried 3.05, 3.04-4, and finally 3.07, Beta 1.  ALL of them generate a version of the Error.  I reloaded 3.06, and created a logged dump.  It's fairly short, and follows (and I don't understand programming or what this dump means)...can anyone point me in the direction of how to resolve this?  I cannot continue Skyrim without fixing this error, as Wrye Bash is telling me it needs to be rebuilt.  Here's the Log Dump:

------------------------------------------------------
```
Wrye Bash starting
Using Wrye Bash Version 306
Python version: 2.7.10
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('en_US', 'cp1252')
filesystem encoding: mbcs
Searching for game to manage:
bush.pyo 87 _supportedGames: Detected the following supported games via Windows Registry:
bush.pyo 89 _supportedGames: skyrim: D:\Steam\steamapps\common\Skyrim
bush.pyo 147 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyo 153 _detectGames: Set game mode to skyrim found in parent directory of Mopy: D:\Steam\steamapps\common\Skyrim
bush.pyo 187 setGame: No preferred game specified.
bush.pyo 168 __setGame: Using skyrim game: D:\Steam\steamapps\common\Skyrim
testing UAC
bosh.pyo 5224 __init__: Using libbsa API version: 2.0.0
bosh.pyo 5230 __init__: Using LOOT API version: 0.6.0
bosh.pyo 5268 refreshBashTags: An error occurred while using the LOOT API:
Traceback (most recent call last):
File "bash\bosh.pyo", line 5259, in refreshBashTags
File "bash\loot.pyo", line 334, in Load
File "bash\loot.pyo", line 231, in LootErrorCheck
LootError: LootError: loot_error_parse_fail:yaml-cpp: error at line 322, column 9: bad conversion

load_order.pyo 321 : Using libloadorder API version: 7.6.0
bosh.pyo 5268 refreshBashTags: An error occurred while using the LOOT API:
Traceback (most recent call last):
File "bash\bosh.pyo", line 5259, in refreshBashTags
File "bash\loot.pyo", line 334, in Load
File "bash\loot.pyo", line 231, in LootErrorCheck
LootError: LootError: loot_error_parse_fail:yaml-cpp: error at line 322, column 9: bad conversion

Traceback (most recent call last):
File "bash\balt.pyo", line 1796, in _conversation_wrapper
File "bash\basher\patcher_dialog.pyo", line 209, in Execute
File "bash\patcher\patch_files.pyo", line 305, in buildPatch
File "bash\patcher\patchers\multitweak_settings.pyo", line 259, in buildPatch
File "bash\patcher\patchers\multitweak_settings.pyo", line 44, in buildPatch
AttributeError: 'NoneType' object has no attribute 'lower'
bosh.pyo 5268 refreshBashTags: An error occurred while using the LOOT API:
Traceback (most recent call last):
File "bash\bosh.pyo", line 5259, in refreshBashTags
File "bash\loot.pyo", line 334, in Load
File "bash\loot.pyo", line 231, in LootErrorCheck
LootError: LootError: loot_error_parse_fail:yaml-cpp: error at line 322, column 9: bad conversion

```
--------------------------------------------------------------------

THANK YOU!!!

Allen

**Comment by aba42** [comment]
I have NO idea why that text jumped in size and got bolded.  I did NOT do that, it appeared that way when I sent the error!  Allen

**Comment by Utumno** [comment]
Ok edited to remove bold - please use 307 latest code and post to the Oblivion thread for help (see https://github.com/wrye-bash/wrye-bash for links)

**Comment by aba42** [comment]
I apologize, but I don't understand that instruction.  I went to github, found the Questions-Feedback.  That took me to an Oblivion Thread, I followed three different topics all the way to the end, then found "Topic Locked", with no more "time to start a new thread".  I am totally new to these forums, so have no idea where I'm supposed to pose this puppy.  Wait a minute, I finally found this page:
http://forums.bethsoft.com/topic/1617476-wrye-bash-thread-115/...now I just need to figure out how the hell to login and post something.  We're havin' fun now, huh?  So much for retirement!  Ugh!!

**Comment by Utumno** [comment]
http://forums.bethsoft.com/topic/1617476-wrye-bash-thread-115/#entry25333128

http://forums.bethsoft.com/topic/1617476-wrye-bash-thread-115/#entry25333362

Just the tweak settings blows - needs someone to follow with the debugger.

> EDIT: it is the Globals/GMST tweaks patcher that fails
> Please make a patch with only game tweaks and try to find which one is failing

**Comment by Sharlikran** [comment]
@aba42 you are not following common practices for reporting a bug.  The first rule is to always upgrade to the latest version. This error doesn't happen in 307 beta1 from the version you can download form the Nexus.

Once you have the version from the Nexus be sure to get LOOT 10.1 or higher as you will need it since the Syntax for the masterlist changed.

**Comment by aba42** [comment]
If I had any idea how what "common practices for reporting a bug" are, I'd follow them . I'm not a modder, I'm just trying to get my Skyrim to work. And, thanks for your E-mail response, but I have the identical issue with both 306 and 307. I'll be happy to try it again, perhaps 307's been updated since I last tried. But, neither has worked correctly for me for a couple of months now. 

----- Original Message -----

**Comment by Sharlikran** [comment]
The 307 Beta1 is the same version that has been there since Dec 2016 so it has not changed.  Please install it anyway as nobody can troubleshoot older versions.  If you continue to get the error once 307 is installed, post here but don't revert. Keep 307 installed.

**Comment by aba42** [comment]
Will do, thank you! 

Allen 

----- Original Message -----

**Comment by Utumno** [comment]
Latest version is in the main readme here - on the second posts of forum threads - use that one (will be more or less the next beta)

**Comment by Sharlikran** [comment]
@aba42 Utumno is making the changes so his suggestion should take precedence.  However, sometimes I help him by doing some complex git bisect techo geek stuff that he taught me. To do that you and I have to test with the same version. So if you do as he asks, please let me know otherwise I can't help him or you properly.

Since I see you have the Standalone EXE you probably don't have the Python components installed. To get the version he is talking about (307.201708021813) please go to the post. The link is at the bottom under [307 WB wip standalone](https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=166863)

**Comment by aba42** [comment]
Sharlikran, 

Yes, I did download and install the non-Python executable following the link in Utumno's message. And, for the first time in MANY MANY MONTHS, it APPEARS to have worked 100% CORRECTLY!!!! I have NO idea (of course) what you guys have fixed, but (and I have not yet started Skyrim to see if anything blows up) the process was 100% smooth. I had to "Sort Masters" on 22 Files first (using TES5Edit). I got an error on two of the files (which are Merged Files), but the Sort appears to have taken. Then I ran Wrye Bash (the most recent version, Executable). It took just over 2-1/2 minutes (and I have a FAST machine). BUT, my total .esp count dropped from 244 to 223!!! Simply Amazing!! 

I can't believe that you guys have actually stuck with me and my issue for all these months. I hadn't heard a thing for many months, then all of a sudden, this week, you guys are all over it. 

Thank you, again!!!! I truly appreciate it. Now, to go see if Skyrim blows up. 

Allen 

----- Original Message -----

**Comment by Sharlikran** [comment]
I am not an official team member, just a fan, supporter, and contributor.  Mainly my interest in this issue is because I port the records from xEdit to Wrye Bash. I fully support the record definitions that I have made. If there is an error I'm happy to make the required changes.  Which again, I don't believe there is an issue with Wrye Bash either the utumno-wip version or the current 307 Beta1 that I used to test with.  However, without you doing some further testing we won't know what needs to be done.

**Comment by Utumno** [comment]
Thanks @Sharlikran, issue closed

**Comment by Infernio** [comment]
Can't be both `works for me` - which means it couldn't be reproduced - and `bug` - which means we were able to reproduce it and acknowledge it's a bug.

**Comment by Utumno** [comment]
Yep correct - thanks for cleaning up @Infernio. In my TODOs to clean up too (projects, code quality issues and co) - hope will get round asap

**Comment by Utumno** [comment]
By the way patcher and skyrim could have stayed but again don't spend too much brain power on old issues, it used to be a mess
