### ISSUE TITLE
Virtual BSAs - BAIN packaging of projected files into a BSA

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#37]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/227/)

Original request:
> This will be more useful for Skyrim than Oblivion, but it would be nice if one day BAIN could be used to package loose files in a project folder into a BSA for distribution since the Creation Kit's native handler for this is bugged to the point of nearly being unusable.
> Where "package for release" exists, a new option below that reading "package for release using BSA" should be added.
Obviously will require Bash/BAIN to support BSA handling to begin with, but perhaps there's a way to make this work by routing the request silently to BSAOpt if it's installed?

My idea would be much more far-reaching, similar to this MO2 plugin: https://github.com/ModOrganizer2/modorganizer-bsapacker
Basically, there would be two different configurations - one global, and one per installer. If you enable this feature, then you can configure 'rules' for which files will be packed into BSAs/BA2s.
This would be based on folder names and wildcards, with a hierarchical system where the per-installer config overrides the global one. Obviously we should provide a sane default (e.g. excluding FNIS files from the `meshes` folder).

BAIN would then take those files and write out one or more BSAs (remember, BSAs have a ~2GB size limit) if possible (e.g. in Skyrim, splitting is not possible, since it can only load one BSA per plugin).
That BSA should obviously be cached - our entire 'BSA cache' folder needs rethinking no matter what, this would be a good opportunity.

Blocked on #519.

**Comment by Infernio** [comment]
Ref #233, this basically depends on the same things (being able to write BSAs).

**Comment by Infernio** [comment]
On the backburner, BAIN is currently too much of a mess for this.
