### ISSUE TITLE
Skyrim OG Tera Armors Level List plugin not being merged into Bashed Patch

### ISSUE THREAD

**Issue by Drakonas** [wrye-bash/wrye-bash#370]
The Tera Armors Leveled List plugin for Skyrim Legendary Edition by asianboy345 is not being merged into the Bashed Patch. I'm shocked because it's been out for 2 and a half years, so I guess it was missed somehow. I'm pretty sure it's supposed to be merged into the patch.

[Mod Page](http://www.nexusmods.com/skyrim/mods/25846/)
The plugin is in an optional download.

**Comment by Utumno** [comment]
Please give me the info on your install required - also right click on it and select "mark mergeable" > what's the output ?

**Comment by Drakonas** [comment]
Sorry, wasn't sure what info you needed since this isn't a bugfix or feature request. None of the requested info in the wiki seemed to me like it was needed, so I apologize.

FYI, I'm not sure what you mean by "install required", but I'm assuming you mean mod list and load order. Let me know if I'm wrong and you need something else specifically.

[MO Profile Details (Modwatch)](https://modwat.ch/u/XenoDrakeMV5)

![Screenshot of result of attempted Merge Marking](http://genesis.whatbox.ca:42424/img/Wrye%20Bash_2017-04-20_22-33-41.png)

        Python Mergeability
        -----------------------
        Not Mergeable
        •  Tera Armor Level List.esp:
        
           New record(s) in block(s): LVLI.

**Comment by Utumno** [comment]
Well apparently this mod adds new records to the game therefore it can't be merged - in general as noted in the contributing.md please ask at the forum before posting here: https://bethesda.net/community/topic/38798/relz-wrye-bash-oblivion-skyrim-skyrim-se-fallout-4

People there may help you find which are those new records exactly

Rerquired info is a bugdump - Bash version for one...

Closing this except if someone has any ideas ?

**Comment by Drakonas** [comment]
Apologies... I'll close it. I take it it's a bad idea to use a bashed patch with this plugin then?
