### ISSUE TITLE
Top level exceptions module

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#372]
I read that some place (will find the link), and it makes more and more sense to me. A lot of coupling with bolt/bosh occurs because of exceptions. A top level `exceptions.py` module will allow us to decouple, plus having all exceptions in one place we can correct code style (python 3 like chaining, new style classes etc) and remove cruft. Another thing (that's from Alex Martelli presentation on error handling) - MI for exceptions https://www.youtube.com/watch?v=frZrBgWHJdY

**Comment by Utumno** [comment]
backburner for now

**Comment by Infernio** [comment]
Oh yeah, that fun github nonsense... assigning to Utumno so at least *someone* is assigned :P
