### ISSUE TITLE
Norwegian locale time & date format error : Oblivion

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#381]
Bug Reported on Oblivion Nexus: [Reference Post](https://forums.nexusmods.com/index.php?/topic/100238-wrye-bash/?p=52588658)

User Traceback from 307 beta1:
```Python
Wrye Bash starting
Using Wrye Bash Version 307.201612302300 (Standalone)
OS info: Windows-10-10.0.14393
Python version: 2.7.12
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('nb_NO', 'cp1252' )
filesystem encoding: mbcs
Searching for game to manage:
bush.pyo 71 _supportedGames: Detected the following supported games via Windows Registry:
bush.pyo 73 _supportedGames: oblivion: c:\games\gog\oblivion
bush.pyo 131 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyo 137 _detectGames: Set game mode to oblivion found in parent directory of Mopy: C:\Games\GOG\Oblivion
bush.pyo 172 setGame: No preferred game specified.
bush.pyo 152 __setGame: Using oblivion game: C:\Games\GOG\Oblivion
testing UAC
mods_metadata.pyo 224 __init__: Using LOOT API version: 0.10.2
__init__.pyo 3463 __init__: Fatal error constructing 'Mods' panel.
Traceback (most recent call last):
File "Wrye Bash Launcher.pyw", line 88, in <module>
File "bash\bash.pyo", line 439, in main
File "bash\basher\__init__.pyo", line 4037, in Init
File "bash\basher\__init__.pyo", line 3679, in __init__
File "bash\basher\__init__.pyo", line 3458, in __init__
File "bash\basher\__init__.pyo", line 1768, in __init__
File "bash\basher\__init__.pyo", line 268, in __init__
File "bash\basher\__init__.pyo", line 228, in __init__
File "bash\balt.pyo", line 1660, in __init__
File "bash\balt.pyo", line 1773, in PopulateItems
File "bash\balt.pyo", line 1718, in PopulateItem
File "bash\basher\__init__.pyo", line 769, in <lambda>
File "bash\bolt.pyo", line 163, in formatDate
ValueError: (22, 'Invalid argument' )
```

Code Block where error occurs in dev: [L175-L185](https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/bolt.py#L175-L185)

Observation:

While attempting to resolve the issue by asking the user to change the time date format to something close to English I noticed that several languages use similar time date formats. German, Norwegian, Russian all use dots for the Date. Japanese, French, Italian, Spanish, and English use slashes.

![english](https://user-images.githubusercontent.com/1912426/29176842-de8fdf22-7da1-11e7-88b1-a8d7ee060b42.jpg)
![russian](https://user-images.githubusercontent.com/1912426/29176841-de8f3504-7da1-11e7-8ffa-28f80d127ec9.jpg)
![norwegian](https://user-images.githubusercontent.com/1912426/29176844-deb60c88-7da1-11e7-88a9-9ecfc2184630.jpg)
![japanese](https://user-images.githubusercontent.com/1912426/29176840-de8c47ea-7da1-11e7-8fbd-9590f711a4f4.jpg)
![french](https://user-images.githubusercontent.com/1912426/29176843-de90989a-7da1-11e7-8300-384a324d5452.jpg)

Question:

Is there a better way to break up the Date and Time for the different formats?

I have suggested to try the utumno-wip branch since the code is slightly different. However, as mentioned the traceback is from 307 Beta1 not a wip.

**Comment by Sharlikran** [comment]
Seems to have been fixed by the latest wip, will wait for more info. Honestly didn't think there would be a difference because of region differences and date time formats. Sorry for the trouble.

**Comment by Utumno** [comment]
No prob sharl - yes fixed in latest - I general always ask users to test latest.

**Comment by Sharlikran** [comment]
Yeah but I was making an attempt to use the release version and not the wip since you prefer that people don't make bug reports for wip versions.  I didn't know the code was different until I made the bug report and diffed the files.  Once I saw the code changes, then I figured it was worth a try. Thanks for being understanding.

**Comment by Utumno** [comment]
I do want people to make bug reports for wip - just not here but in the forums (they should end up here if it proves a serious/difficult bug but not if it's just a small regression). On the other hand wip builds should be better than the released ones, bugs fixed, features added etc No use to test but those - if the bug is fixed in wip, the bug is fixed. Moreover this last one should be next beta
