### ISSUE TITLE
Update LOOT API integration to v3.0.0

### ISSUE THREAD

**Issue by D4id4los** [wrye-bash/wrye-bash#388]
LOOT API v2.0.0 had some changes to the API that need to be integrated in Wrye Bash. [According to WrinklyNinja](https://github.com/wrye-bash/wrye-bash/issues/371#issuecomment-325320468) it should shouldn't be too much work.

The change-log can be found [here](https://loot-api.readthedocs.io/en/latest/api/changelog.html#id2) and Wrinkly summarized the changes in [this commit](https://github.com/loot/loot-api-python/commit/a94fb19bdebb4dced3c9dcc0ac6af7e47d10a150)

**Comment by D4id4los** [comment]
@Utumno Should this be targeted for 307 beta or 308?

**Comment by Utumno** [comment]
Thanks ! 307 hands down, we will have one post every other day. If you can take this up go ahead ! we should update the readme and release guide also.

**Comment by Utumno** [comment]
Links https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=169248

**Comment by D4id4los** [comment]
As seen in https://github.com/loot/loot-api-python/issues/9 I can't get the newer versions of loot to work for me. Wrinkly suspects that it might have something to do with my local environment. 

I tried to get it to work for some 6 hours yesterday and am no closer to a solution. I would appreciate it if someone could take the time to see if they also face this issue. To make it easier to test I created a zip file with all the necessary files to test it (you need to change `game_path` in `test_loot_api.py` to the path to your oblivion install).

[loot_api_v3_test.zip](https://github.com/wrye-bash/wrye-bash/files/1593949/loot_api_v3_test.zip)

When I run it I get the following output:

```
E:\software\Python27\python.exe E:/wrye_bash/main_repo/wrye-bash/scripts/test_loot_api.py
Traceback (most recent call last):
  File "E:/wrye_bash/main_repo/wrye-bash/scripts/test_loot_api.py", line 11, in <module>
    db.load_lists(masterlist_path)
RuntimeError: bad cast

Process finished with exit code 1

```

**Comment by Utumno** [comment]
```
C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy>test_loot_api.py
Traceback (most recent call last):
  File "C:\Dropbox\eclipse_workspaces\python\wrye-bash\Mopy\test_loot_api.py", line 11, in <module>
    db.load_lists(masterlist_path)
RuntimeError: bad cast
```

**Comment by D4id4los** [comment]
Alright, WrinlyNinja found the problem. The new versions of loot api require one to call `loot_api.initialise_locale('')` before any other commands. I'll now start working on actually updating the bash code for the breaking changes.

**Comment by D4id4los** [comment]
Alright this was surprisingly simple once everything started to work^^. I tested the update for Oldrim and Fallout4, don't have SSE installed and my Oblivion install is messed up and crashes Wrye Bash on startup.

Also fixed the install_loot_api and mktaglist scripts.

**Comment by BeermotorWB** [comment]
Do you need me to help you test with SSE & Oblivion @D4id4los ?

**Comment by Utumno** [comment]
Good job @D4id4los ! Well will pack into the new nightly then. Could you also edit the release wiki so we know what to do everytime we want to update the loot API ? Probably we should generate new taglists too ?

**Comment by D4id4los** [comment]
@BeermotorWB Since I really only changed the initialisation, I think it will be fine to test it once Utumno has packed the new nighly, thank you.

@Utumno Alright, will update the wiki. I think we should update the taglists? Though as far as I understand it they would only be used if no loot api is found so I'm not quite sure how important they are right now. Still, I'll add instructions for doing it to the wiki for now.

**Comment by Utumno** [comment]
Thanks @D4id4los ! Yes we should compile new taglists - as long as we keep them. It's not a bad idea after all to have a fallback source of tags.

**Comment by Utumno** [comment]
```
Wrye Bash starting
Using Wrye Bash Version 307.201801021732
OS info: Windows-7-6.1.7601-SP1
Python version: 2.7.12
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: UTF8; output encoding: None; locale: ('en_US', 'cp1253')
filesystem encoding: mbcs
command line: ['Wrye Bash Launcher.pyw', '--debug']
Using scandir 1.5
bash.py  288 _main: Searching for game to manage:
bush.py   80 _supportedGames: Detected the following supported games via Windows Registry:
bush.py   82 _supportedGames:  Oblivion: C:\GAMES\TESIV\Oblivion
bush.py   82 _supportedGames:  Skyrim Special Edition: F:\GAMES\SteamLibrary\steamapps\common\Skyrim Special Edition
bush.py   82 _supportedGames:  Skyrim: C:\GAMES\Skyrim
bush.py  140 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  146 _detectGames: Set game mode to Fallout4 based on sOblivionPath setting in bash.ini:  F:\Games\Fallout 4
bush.py  161 __setGame:  Using Fallout4 game: F:\Games\Fallout 4
testing UAC
mods_metadata.py  227 __init__: Using LOOT API version: 0.12.0
mods_metadata.py  285 refreshBashTags: An error occurred while parsing file C:\Users\MrD\AppData\Local\LOOT\Fallout4\masterlist.yaml:
Traceback (most recent call last):
  File "bash\bosh\mods_metadata.py", line 278, in refreshBashTags
    lootDb.load_lists(path.s)
RuntimeError: yaml-cpp: error at line 11, column 9: bad conversion: 'text' key missing from 'message content' object

mods_metadata.py  300 refreshBashTags: An error occurred while parsing taglist.yaml:
Traceback (most recent call last):
  File "bash\bosh\mods_metadata.py", line 297, in refreshBashTags
    lootDb.eval_lists()
AttributeError: 'loot_api.DatabaseInterface' object has no attribute 'eval_lists'

```

Taglists failure - should update backend code too apart from the tag lists

**Comment by D4id4los** [comment]
https://github.com/wrye-bash/wrye-bash/commit/affa7c8bbab7c2123d58ec93fbace7db96e389d3 is a fix for the second error, also raised by [alt3rn1ty](https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=171197). That one should not actually impact functionality, since it is the last function called in the try-catch blocks and I did update the back-end functions to use the new way of evaluating conditions but missed removing the old function calls.

I forgot to check the error logs during the last test for functionality. At some point I'm going to rewrite Bash error logging to also output into stdout so I can see debug output on the fly in PyCharm. There have now been multiple times I missed stuff like that during my tests because I forget to switch to my notpad++ instance to see if there have been some errors.

I can't reproduce the first error you see. But it is a RutimeError so it's probably coming from the loot API directly. Given that it says yaml-cpp my first suspect would be an incompatible master list format. Back in v0.8 the message content had an attribute `str` but v0.10 has replaced it with `text`.

**Comment by Utumno** [comment]
Thanks! yes my first error is a loot one - discard it

**Comment by Utumno** [comment]
Well the standalone I packed here: https://www.dropbox.com/sh/7b5ily482re0khs/AAD3vAWMVJNIpuS30tsdVte5a?dl=0 hard crashes - deleting the packed loot_api dll (version 0.12) allows Bash to start

**Comment by Utumno** [comment]
Hey @D4id4los - some new tracebacks with new loot : https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=171795

We should also redo the packed taglists (for fallout 3 on its branch too) and check standalone works alright

Hope you can give this some love - it's basically what's left for next and final I hope beta - apart from some other stuff I have been busy with (including this damn restore settings)

**Comment by Utumno** [comment]
We need to update the taglists (see mktaglist.py) and also update the release guide with this step

**Comment by Utumno** [comment]
I did update the taglists but packaging to standalone Bash won't start - deleting the loot_api.dll starts ok but ofc no loot support:


```
Wrye Bash starting
Using Wrye Bash Version 307.201803041642 (Standalone)
OS info: Windows-7-6.1.7601-SP1
Python version: 2.7.12
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('en_US', 'cp1253')
filesystem encoding: mbcs
command line: ['Wrye Bash.exe', '--debug']
Using scandir 1.5
bash.pyo  286 _main: Searching for game to manage:
bush.pyo   80 _supportedGames: Detected the following supported games via Windows Registry:
bush.pyo   82 _supportedGames:  Oblivion: C:\GAMES\TESIV\Oblivion
bush.pyo   82 _supportedGames:  Skyrim Special Edition: F:\GAMES\SteamLibrary\steamapps\common\Skyrim Special Edition
bush.pyo   82 _supportedGames:  Skyrim: C:\GAMES\Skyrim
bush.pyo  140 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyo  146 _detectGames: Set game mode to Skyrim Special Edition based on sOblivionPath setting in bash.ini:  F:\GAMES\The Elder Scrolls V Skyrim Special Edition
bush.pyo  161 __setGame:  Using Skyrim Special Edition game: F:\GAMES\The Elder Scrolls V Skyrim Special Edition
mods_metadata.pyo   39 <module>: Failed to import the loot_api module: (MemoryLoadLibrary failed loading loot_api.pyd)
testing UAC
```

**Comment by Utumno** [comment]
I need some help with this @D4id4los @WrinklyNinja - packing the standalone does not work for me - won't start

**Comment by WrinklyNinja** [comment]
I tried replicating the issue, but can't even get the `package_for_release.py` script to work. It's been a long time since I touched Bash, but I checked out the latest `dev` code, ran the `install_loot_api.py` script, then installed everything `package_for_release.py -t` told me to. When I run it with `package_for_release.py -r 4` this is the log that is produced:

```
[package_for_release]: WARNING: You are building off branch "dev", which does not appear to be a release branch for 4.
[package_for_release]: Using file version: 4.0.0.0
[package_for_release]: Creating Python archive distributable...

7-Zip [32] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Scanning the drive:
1 folder, 724 files, 23605520 bytes (23 MiB)

Creating archive: C:\Users\Oliver\Documents\Code\wrye-bash\scripts\dist\Wrye Bash 4 - Python Source.7z

Items to compress: 725


Files read from disk: 724
Archive size: 9344688 bytes (9126 KiB)
Everything is Ok
[package_for_release]: Building standalone exe...
[package_for_release]:  Generating comtypes...
[package_for_release]:  Calling py2exe...
[package_for_release]:  Adding icon...
[05 Mar 2018, 18:12:06]

C:\Users\Oliver\Documents\Code\wrye-bash\scripts\build\standalone\Reshacker.exe -addoverwrite "C:\Users\Oliver\Documents\Code\wrye-bash\Mopy\Wrye Bash.exe," "C:\Users\Oliver\Documents\Code\wrye-bash\Mopy\Wrye Bash.exe," C:\Users\Oliver\Documents\Code\wrye-bash\scripts\build\standalone\bash.ico, ICONGROUP, MAINICON, 0

Error: "C:\Users\Oliver\Documents\Code\wrye-bash\Mopy\Wrye Bash.exe" does not exist

[package_for_release]:  Compressing with UPX...
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2010
UPX 3.07w       Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 08th 2010

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: C:\Users\Oliver\Documents\Code\wrye-bash\Mopy\Wrye Bash.exe: FileNotFoundException: C:\Users\Oliver\Documents\Code\wrye-bash\Mopy\Wrye Bash.exe

Packed 0 files.
[package_for_release]: Creating standalone distributable...

7-Zip [32] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Scanning the drive:

WARNING: The system cannot find the file specified.
Mopy\Wrye Bash.exe

1 folder, 600 files, 17992705 bytes (18 MiB)

Creating archive: C:\Users\Oliver\Documents\Code\wrye-bash\scripts\dist\Wrye Bash 4 - Standalone Executable.7z

Items to compress: 601


Files read from disk: 600
Archive size: 8600758 bytes (8400 KiB)

Scan WARNINGS for files and folders:

Mopy\Wrye Bash.exe : The system cannot find the file specified.
----------------
Scan WARNINGS: 1
[package_for_release]: Creating installer distributable...
[package_for_release]:  Calling makensis.exe...
Command line defined: "WB_NAME=Wrye Bash 4"
Command line defined: "WB_FILEVERSION=4.0.0.0"
Command line defined: "WB_CLEAN_MOPY=Mopy"
Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
Processing script file: "C:\Users\Oliver\Documents\Code\wrye-bash\scripts\build\installer\main.nsi" (ACP)
File: "Mopy\Wrye Bash.exe" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in macro InstallBashFiles on macroline 41
!include: error in script: "scripts\build\installer\install.nsi" on line 195
Error in script "C:\Users\Oliver\Documents\Code\wrye-bash\scripts\build\installer\main.nsi" on line 390 -- aborting creation process
[package_for_release]:  makensis exited with error code 1.  Check the output log for errors in the NSIS script.
```

Sure enough, the `Wrye Bash.exe` doesn't exist, but I don't know why.

**Comment by Utumno** [comment]
Thanks for looking at it @Wrinklyninja!

The instructions given by `-t` are outdated (had no idea they existed will fix) - for sure the zipextimporter.py is not needed anymore
The other thing is py2exe 32 bit is needed - better follow the [1. Setup Your Python Environment
](https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Making-A-Release#1-setup-your-python-environment)

You also need to install the WB requirements (see main readme.md on repo) - comtypes, pywin, wx 2.8 scandir - https://github.com/wrye-bash/wrye-bash#installation

Something goes amiss and the exe is not built

**Comment by Utumno** [comment]
Forgot to add - use utumno-wip or better https://github.com/wrye-bash/wrye-bash/tree/150-fo3-fnv-support - those contain the corrections in py files for newest loot api

**Comment by WrinklyNinja** [comment]
I reinstalled all the development dependencies just to be sure, checked out the `150-fo3-fnv-support` branch, but no change. I still can't get the executable to build, it's like it doesn't even try to call py2exe or something.

**Comment by Utumno** [comment]
Not sure @WrinklyNinja - I can build just fine, could you post a list of the versions of the python/build dependencies in case I spot something?

**Comment by Utumno** [comment]
@WrinklyNinja nallar had some issues too building and solved them as discusses here: https://github.com/wrye-bash/wrye-bash/pull/407#issuecomment-381161528
 Maybe have a look ? Some python versions conflict apparently - we need python 2 32 bits

**Comment by WrinklyNinja** [comment]
I released a new version of the LOOT API module last weekend, I've been meaning to have another go at this but haven't found the time yet. The new version updates the LOOT API and the bindings generator library, which apparently fixes some regressions, which may be relevant.

**Comment by WrinklyNinja** [comment]
> we need python 2 32 bits

I think I've just spotted what was causing me problems: Inkscape has a bundled Python that's 64-bit and it was added to my PATH. I only noticed because I was still getting python.exe --version reporting 2.7.13 after uninstalling Python 2.7...

**Comment by WrinklyNinja** [comment]
Still no luck, I ensured I only had 32-bit Python 2.7.14 installed and all the WB and packaging dependencies installed, and I still see the same issue as before.

I also tried running the generated setup.py manually, but didn't get very far with that. I'm not sure if the errors I encountered were down to user error or related to my issue though, I may investigate that more later.

**Comment by WrinklyNinja** [comment]
Fixed my issue, sent the PR above with my fix. I don't have any trouble launching WB with the latest LOOT API.

**Comment by Utumno** [comment]
Excellent - re: python3 it's tricky - porting to wx 3.02 however is nearly done - see relevant issue. Would like to do this step by step - so wx 302 classic then phoenix and python 3. Python 3 porting is kinda 309 as I see in the code
