### ISSUE TITLE
Preview of 'Clean Data'

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#39]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/220/)

It would be nice to have a preview of the files that will be removed from the data folder when 'Clean Data' is executed from the Installers tab.
Possibly with an option to either once or permanently exclude some files from cleaning.

**Comment by Utumno** [comment]
Superseded by https://github.com/wrye-bash/wrye-bash/issues/273
