### ISSUE TITLE
Add meta.ini to global skips

### ISSUE THREAD

**Issue by BeermotorWB** [wrye-bash/wrye-bash#392]
Meta.ini is a metadata file created and used exclusively by Mod Organizer. They are always in the root of the mod package or archive and can be skipped outright.

Occasionally you will encounter one in a mod package and it is treated like a normal \.ini file. 

I'll confirm all file name variants and update.

**Comment by BeermotorWB** [comment]
Research done.  I grepped through the MO source code and it will always write the file as the lowercase "meta\.ini".  Confirmed this with a shell script I found for editing meta.ini files on Linux. The script has no regex considerations for variances in case.

**Comment by BeermotorWB** [comment]
This probably can fit under the umbrella of #270

**Comment by BeermotorWB** [comment]
In my initial testing in my fork I have the skip working. Holding for now.

**Comment by Utumno** [comment]
Hey @BeermotorWB - sorry it took ages - I am very very pressed for time. Please link me to relevant commit. I also have some easy tasks for you (like renames or such) that stand on my way for other more complicated stuff. Will come back to that as soon as I merge to dev some of my wip branch so you can work on it on stable code

**Comment by BeermotorWB** [comment]
@Utumno No worries at all, I completely understand. 

Here's the link to my first wobbly attempt at editing the silent skips list. The [first commit](https://github.com/BeermotorWB/wrye-bash/commit/aef72ba28c429486bd037934601a85f7ac1c4032) I did in PyCharm at work on my Mac, and the [fix for that commit](https://github.com/BeermotorWB/wrye-bash/commit/f594bf94c1f6d666e22cdfd394f939af7279babb) that I did at home after testing it with actual mods containing meta.ini files. 

If it seems ham-fisted, it was, but I learned many things.

**Comment by Utumno** [comment]
Ok - never commit on dev directly - always commit on a new branch, named beermotorwb-392 in this case - see https://github.com/wrye-bash/wrye-bash/blob/dev/Contributing.md andf in particular https://github.com/wrye-bash/wrye-bash/wiki/%5Bgithub%5D-Branching-and-merging-to-dev-using-rebase

**Comment by BeermotorWB** [comment]
Yep, that's exactly what I meant by ham-fisted. :)

**Comment by Utumno** [comment]
Feel free to edit those wiki pages btw - I see glitches in there ;)

**Comment by BeermotorWB** [comment]
Heh I'm a quick study. I already found something in the [coding guidelines](https://github.com/wrye-bash/wrye-bash/wiki/[dev]-Coding-Style) that may need to be updated per #372. 

Alas I digress, I'm going to branch and redo those edits + retest,  then I'll do a proper submission for review. Shouldn't take long.

**Comment by BeermotorWB** [comment]
Forked, branched, and committed the change per the guidelines.  

I've been fighting with macOS idiosyncrasies (text=auto in .gitattributes throws a wrench into things) so I'll verify everything on my Windows machine once I get home.

**Comment by Utumno** [comment]
Have a look at https://github.com/wrye-bash/wrye-bash/wiki/[git]-Issues-with-line-endings-preventing-checking,-merge,-etc and https://stackoverflow.com/q/21122094/281545

**Comment by BeermotorWB** [comment]
Thank you for saving what's left of my sanity. :)
