### ISSUE TITLE
Additional Tool Dirs:  DynDOLOD & FNIS

### ISSUE THREAD

**Issue by BeermotorWB** [wrye-bash/wrye-bash#393]
Per @Sharlikran 's [suggestion in the official AFK Mods thread.](https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=169002). 

DynDOLOD and Fores New Idles (FNIS) are common tools used with Skyrim and Skyrim SE.

Much like we did for BodySlide, I propose adding the "DynDOLOD" and "Tools" directories as recognized directories for the Skyrims.

Will branch and test. I have test data handy and have some time.

**Comment by Utumno** [comment]
Ok - basically I was going to suggest you took care of this :)
But please refrain from posting issues for such small fixups - too much overhead - just notify me from the commit or another issue. If it does prove hard we can then open an issue.

Thanks!

**Comment by BeermotorWB** [comment]
@Utumno will do.  I considered bumping/reopening #379 but I was unsure which would be preferable.

**Comment by BeermotorWB** [comment]
Bumping back to post-Beta 2.

**Comment by Utumno** [comment]
Well it should be a very easy change - in that case we could have it in - or no?

**Comment by Arthmoor** [comment]
As I mentioned on AFK, the "Tools" folder under Data appears to be a vanilla folder the CK, not something FNIS installs on its own. It's in my vanilla-only SSE install that hasn't been modified by anything. Only the CK was installed to it. Data\Tools is there with the expected tool folders below that.

**Comment by Utumno** [comment]
I leave this up to you guys - anyway it's a couple lines in `game/__init__` files - see #379. I would like this closed however ASAP - I have 100 open issues I scroll through every day ;)

**Comment by BeermotorWB** [comment]
@Utumno  I spoke to Arthmoor offline and we're good with this one regarding CK dirs. I've tested this one and unlike the BodySlide situation in #379 no additional documentation is needed as the DynDOLOD data is almost always .ini files.  This issue can be closed if no more discussion is needed.

**Comment by Utumno** [comment]
Hmm - readme must be updated for this _and_ #379 - didn't do that - search for "skyproc patchers" in readme - add the changes to that commit and squash it with the other one on Add meta.ini to global skips. Will then take this over to my wip so I publish on next build

Thanks!

**Comment by BeermotorWB** [comment]
Roger. I'll see what I can do on the readme. It may be tomorrow since I'm running out of daylight today.

**Comment by Utumno** [comment]
No prob - anyway I won't be able to do anything the next few days

**Comment by BeermotorWB** [comment]
@Utumno General Readme has been updated in vim and I fixed my crlf issue. These last two can be closed if there's nothing more that needs to be done.

**Comment by Utumno** [comment]
Thanks @BeermotorWB - taking over - gimme couple days
