### ISSUE TITLE
UnicodeDecodeError on initializing wrye bash

### ISSUE THREAD

**Issue by Luskain** [wrye-bash/wrye-bash#394]
Hello. I've been running into an error on Wrye Bash initialization since I formatted my PC, from windows 10 to the same OS. After doing some search on the internet, I failed to find anyone with a similar problem.

The error happens when I try to launch Wrye Bash, whereas the typical logo appears on the middle of the screen, but a windows pop out behind it, containing the last lines of the dump log. After that, both windows close and the program doesn't initialize. The problem seen to be only affecting Skyrim, since I also have Fallout 4 and New Vegas, and Wrye Bash works normally for then. I'd also like to state that I've been using your amazing program since Oblivion, and never had any problem at all.

I've already tried the following, to no success:
- Clean reinstall of Wrye bash;
- Installing older versions of Wrye Bash after uninstalling the current version completely;
- Alternating between stand-alone executable and python one installation after clean uninstall;
- Installing Wrye Bash outside Skyrim's folder;
- Executing Wrye Bash with administrator privileges;
- Executing Wrye Bash in compatibility modes;
- Executing Wrye Bash in high priority;
- Downloading the latest python version and all other requirements listed on Wrye Bash page;
- Deactivating/uninstalling all mods;

Here's the dumb log (Sorry, I didn't find out how to put on spoilers, I never entered this site before).
[BashBugDump.log](https://github.com/wrye-bash/wrye-bash/files/1356950/BashBugDump.log)

PS: My Skyrim's installation directory is not the same than the OS.

**Comment by Utumno** [comment]
Please use the version from the second post in the AFK mods forums (see frontpage readme) - should be fixed there

You couldn't find the spoilers cause there aren't any - I should fix the issue template

**Comment by Luskain** [comment]
Hello, thanks for the quick reply. 
You mean the one in this post? 
[https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/](url)
Doesn't seen to be working either, just installed it. :(

**Comment by Utumno** [comment]
It's your skyrim.ini that's corrupted - please backup/delete it and try again

**Comment by Utumno** [comment]
TODO: add more meaningful error (catch the UnicodeDecodeError on first ini read - maybe allow for default language instead of crashing ?

**Comment by Luskain** [comment]
Wow, that worked like a charm. I deleted the skyrim.ini in the "My Games" folder and it all came back to normal. That's so very odd, I totally remember trying that before. 
Thank you so very much!

**Comment by Utumno** [comment]
Welcome - thanks for trying to submit a good bug report.
