### ISSUE TITLE
Skyrim can stop loading on startup after bashed patch creation in v307b1

### ISSUE THREAD

**Issue by TokcDK** [wrye-bash/wrye-bash#396]
After bashed patch was created game stop loading on stuptup. I already encountered with same problem and checked ARMA records in bashed patch.esp and changed texture hashes and game start normal loading after this with activated bashes patch esp.

Here I encountered with this problem in first time when was changing ARMA records in Tes5Edit:
https://github.com/TES5Edit/TES5Edit/issues/426

As I may suppose it is because I used Graphics tag for bashed patch and was merged ARMA records.

**Comment by BeermotorWB** [comment]
@TokcDK  Please try the latest Beta 2 release candidate [from the official thread](https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=166863)  and see if the issue persists in the new version.

**Comment by TokcDK** [comment]
Found "Wrye Bash 307.201711250133" but unfortunately cant check it because cant run with next error:
> Traceback (most recent call last):
>   File "bash\bash.pyo", line 260, in main
>   File "bash\bash.pyo", line 425, in _main
>   File "bash\basher\__init__.pyo", line 3989, in Init
>   File "bash\basher\__init__.pyo", line 4031, in InitData
>   File "bash\bosh\__init__.pyo", line 1598, in __init__
>   File "bash\bosh\__init__.pyo", line 1608, in ini
>   File "bash\bosh\__init__.pyo", line 959, in BestIniFile
>   File "bash\bosh\ini_files.pyo", line 61, in formatMatch
>   File "bash\bolt.pyo", line 908, in open
>   File "os.pyo", line 150, in makedirs
>   File "os.pyo", line 150, in makedirs
>   File "os.pyo", line 150, in makedirs
>   File "os.pyo", line 157, in makedirs
> WindowsError: [Error 3] : u'T:\\'

**Comment by Utumno** [comment]
Please post about your issues in the official thread - before you post here you are supposed to ask there first
