### ISSUE TITLE
Wrye Bash could not find a game to manage.

### ISSUE THREAD

**Issue by aminomancer** [wrye-bash/wrye-bash#398]
"Wrye Bash could not find a game to manage. Please use -o command line argument to specify the game path"

Have tried installing several different ways. The game path (skyrim special edition) is exactly as defined by the installer, but it was installed on an external drive. So I assumed that was the issue, but I just don't have enough disk space on the internal drive to find out.

edit: never mind, i retried the python build with scandir this time and got past the loading splash. sorry for the bump

**Comment by BeermotorWB** [comment]
No worries. Glad to hear you were able to get the issue sorted out!
