### ISSUE TITLE
Fallout 4 VR Support

### ISSUE THREAD

**Issue by nephatrine** [wrye-bash/wrye-bash#401]
I don't expect you guys to go out any buy headsets or the game to work on this yourselves, but I tried to implement Fallout 4 VR support myself in a clone of utumno-wip by copying the `bash/game/fallout4` directory to `bash/game/fallout4vr` and making the necessary changes to the `__init__.py` in there. These are the things I changed in there:

```
displayName = u'Fallout 4 Vr'
fsName = u'Fallout4VR'
altName = u'VRye Flash'

exe = u'Fallout4VR.exe'

regInstallKeys = (u'Bethesda Softworks\\Fallout 4 VR', u'Installed Path')

vanilla_string_bsas = {
    u'fallout4.esm': [u'Fallout4 - Interface.ba2'],
    u'fallout4_vr.esm': [u'Fallout4_VR - Main.ba2'],
}

iniFiles = [
    u'Fallout4.ini',
    u'Fallout4Prefs.ini',
    u'Fallout4Custom.ini',
    u'Fallout4VrCustom.ini',
    ]

masterFiles = [
    u'Fallout4.esm',
    u'Fallout4_VR.esm',
    ]
```

I changed the file lists in `constants.py` as well since there are different vanilla files in the VR install. I'm not going to paste those here because I can't really see how I'd have screwed that up.

I also added another AsteriskGame override in `bash/games.py`:

```
class Fallout4VR(AsteriskGame):

    must_be_active_if_present = (bolt.GPath(u'Fallout4_VR.esm'),)
    _ccc_filename = u''

    @property
    def remove_from_plugins_txt(self):
        return {bolt.GPath(u'Fallout4.esm')} | set(
            self.must_be_active_if_present)
```

and the check to use it in the same file:

```
    elif name == u'Fallout4VR':
        return Fallout4VR(mod_infos, plugins_txt_path)
```

This is sufficient for Fallout 4 Vr to show up as an option to select when starting up Wrye Bash, but upon selecting it I get this cryptic (maybe just cryptic because I'm not familiar with Python) error:

```
bush.py  156 __setGame:  Using Fallout4VR game: C:\Games\Steam\steamapps\common\Fallout 4 VR
mods_metadata.py   39 <module>: Failed to import the loot_api module: (No module named loot_api)
fail bash\bosh.py
Error! Unable to start Wrye Bash.

Please ensure Wrye Bash is correctly installed.

Traceback (most recent call last):
  File "bash\bash.py", line 351, in _main
    import bosh # this imports balt (DUH) which imports wx
  File "Wrye Bash Launcher.pyw", line 76, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\bosh\__init__.py", line 1188, in <module>
    class BSAInfo(FileInfo, _bsa_type):
ImportError: caused by TypeError('Error when calling the metaclass bases\n    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases',)
```

I can still select other games like Skyrim Special Edition and Wrye Bash seems to work just fine with them so I guess the problem is specifically with the fallout4vr folder and I have no idea where I goofed up. I've looked all over the BSAInfo class and don't see anything remotely relevant to anything I did.

Sub-issues:
 - [ ] #635

**Comment by Utumno** [comment]
Edit the bsa_files.py accordingly

**Comment by BeermotorWB** [comment]
This is very cool. While finances prevent me from getting a headset at the moment (my wife and I would fight over it so I would have to buy two) I would love to see Bash working with the VR versions of FO4 and SSE.

**Comment by BeermotorWB** [comment]
You're right, I went back and did my homework and FO4VR does not have any DLC, any CC content, nor is there any official modding support.

Skyrim VR is going to be a PS4 exclusive apparently.

**Comment by nephatrine** [comment]
Sorry, was gone for the holidays so couldn't really respond. While the mod support isn't "official", FO4VR does support them just the same as the vanilla game and you can even enable the in-game mod menu. There's even a dedicated VR category on the Nexus now. There are a couple of issues with the official DLC since they weren't built for VR, but most mods that don't rely on F4SE work just fine in VR. You can even move save games between the 2D and VR game without issue. It's mostly just a different executable and a couple of extra BA2 files.

**Comment by nephatrine** [comment]
@Utumno I added a check in get_bsa_type to treat Fallout4 and Fallout4VR ba2s the same way. Must have missed that when I first grepped though for game-specific code. I also had to duplicate the png icons since it looks for them based on the fsName. Seems to have at least got me past that issue. Thanks.

**Comment by Utumno** [comment]
Well - assigning this to 308 - not sure if it will end up in but still worth investigating. Meanwhile I need help in #150 and #358 which are related - have a look especially to the latter, we are changing game loading logic

**Comment by nephatrine** [comment]
Your contributing.md says not to issue a pull request, but I have forked and [my changes are here](https://github.com/nephatrine/wrye-bash/commit/98588a5770ddc4342f722fbf9f8a4f3fcd70371a) if you want to review them or use them in any way you want.

**Comment by Utumno** [comment]
Thanks ! feel free to pack it and offer it to people in AFK forums for testing

**Comment by nephatrine** [comment]
It installs mods and correctly formats the plugins.txt as far as I can determine after testing. I installed the LOOT API which flagged a couple of checks I missed for the mod metadata and loot game type (load order should be the same as normal Fallout 4 so LOOT itself doesn't need an update for support afaict).

I think packaging a release is going to be difficult since I'm using MSYS2 for git but using a normal Windows install of Python.

**Comment by nephatrine** [comment]
Did not mean to close fyi. Clicked wrong button.

**Comment by Infernio** [comment]
Nightlies now include experimental support for Fallout 4 VR (no installer edits right now though - they were a pain for Enderal, so I'm putting them off for as long as possible).
