### ISSUE TITLE
Wrye Bash not working in MO2

### ISSUE THREAD

**Issue by FuzFuzFuz** [wrye-bash/wrye-bash#402]
[BashBugDump.log](https://github.com/wrye-bash/wrye-bash/files/1565418/BashBugDump.log)

Here is the BashBugDump using the latest version of WryeBash. The 307 beta 1 version works fine.

**Setup**

- Wrye Bash v307.201711250133 (Standalone Executable)
- Microsoft Windows 10 Home v10.016299 Build 16299
- FO4 installed & detected via registry

**Repro**

1. Launch Wrye Bash through Mod Organizer 2 v2.0.8.3
2. MO2 launches WB, but WB abruptly closes.

**Noticed Behaviors:**

- Wrye Bash launches fine outside of MO2.
- All other programmes (eg. LOOT) runs fine, bringing me to the conclusion the problem is due to WB and not MO2.
- WB worked fine in MO2 before the latest Windows update.

**Comment by Utumno** [comment]
Sorry we do not support MO - please ask at the forums for help
