### ISSUE TITLE
Wrye bash not responding when completing bashed patch

### ISSUE THREAD

**Issue by lotrg54** [wrye-bash/wrye-bash#412]
Wrye bash is crashes after completing bashed patch how to fix that ? ı use it with mod organizer 2

**Comment by RapthorneLightweaver** [comment]
I'm having the exact same issue. using MO2 building patch, the dialogue box closes on the message "saving patch" and then the entire thing freezes up. no popup with a summary, no anything. There's not even any bug log to post

**Comment by m0lz** [comment]
Guys ask the developers of MO2

Wrye Bash developers do not use or understand MO2, so can not help

Wrye Bash is meant to be used as a Mod Manager on its own, not through another tool.

This is not an issue with Wrye Bash and should be closed.
Please do not make bogus issues taking up Wrye Bash development time.

**Comment by Arthmoor** [comment]
I'm not Utumno but this issue is definitely one we should close so I'll go ahead and close it now.
