### ISSUE TITLE
Rewrite copyright lines for 2019

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#416]

**Comment by FelesNoctis** [comment]
What all needs to be changed? Just the year, or are we changing any names?

**Comment by FelesNoctis** [comment]
Hmmm. In the python files I'll probably leave that to you guys to pick up. For the documentation apparently that isn't in there at all, so I'll add a footnote to the bottom with it. Don't know why it wasn't in the first place. :P

**Comment by Arthmoor** [comment]
One assumes it would now be set to 2019? :P

**Comment by Utumno** [comment]
Not sure what the proper thing is - well yes probably @Arthmoor

**Comment by Infernio** [comment]
Whelp, I *didn't* do that, that was github :P

**Comment by Utumno** [comment]
That's not really an enhancement (user visible) rather a TODO (so excluded from changelog) - re-adding
