### ISSUE TITLE
xEdit support - read expert settings from Bash.ini

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#419]
Currently the xEdit "expert mode" settings are hardcoded somewhere in the Python files.

What I'd like to see instead is a line in the Bash.ini file that controls what parameters get sent to the launch icon when expert mode is enabled. xEdit has had some recent development on it which adds some new flags that are useful for doing certain operations considered dangerous.

**Comment by Utumno** [comment]
Could you give me an example command line and add the info to the readme in the respective menu description?

**Comment by Utumno** [comment]
Use the readme from my branch!

**Comment by Utumno** [comment]
Pushed some commits in utumno-wip ( https://github.com/wrye-bash/wrye-bash/commit/67f8c82965d2d8d55bd647c34ad3fe1d6e9f33fb ) - new setting `sxEditCommandLineArguments` - very hasty but test if you can.

**Comment by Arthmoor** [comment]
Ok, tested. It's working, but the arguments being passed should only be doing so if the expert mode toggle in the UI has been enabled. Otherwise it's fine. I'd change the comment in the ini file though to be more clear:

;--sxEditCommandLineArguments: additional command line arguments to pass to xEdit when
; launched via Bash with xEdit expert mode enabled.

Right now it's simply adding the arguments to the hardcoded list, but that's actually fine since toggling expert mode by itself should not be enough to enable more dangerous options anyway.

**Comment by Utumno** [comment]
Ok done - could you provide me with an example command line ?

**Comment by Arthmoor** [comment]
The default that's passed by the expert mode toggle to SSE would have these arguments:

-SSE -edit -IKnowWhatImDoing

An example of a line to add would include the argument to enable editing of the master files header:

sxEditCommandLineArguments=-AllowMasterFilesEdit

I know there are others but I'm not sure what any of them are besides that one.
