### ISSUE TITLE
Spaces in Windows Temp folder path causes 7z extraction error.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#428]
When installing mods through BAIN, Wrye Bash will return an extraction error in 7-zip if there is a space in the user's temporary file paths in Windows. People have mentioned it on forums and chat servers for some time now but only a few people seem to have hinted at the cause.

The other night on Discord the situation came up again and we were able to verify that having a space in the file path to a user's Temp folders in Windows is the root cause of the problem. Wrye Bash must be passing a command line out to 7z that doesn't put quotes around the file path being referenced.

The error message: https://cdn.discordapp.com/attachments/496820407580622871/523988028784508928/unknown.png

User's Windows paths: https://cdn.discordapp.com/attachments/496820407580622871/523994871971708938/unknown.png

Confirmation of workaround: https://i.imgur.com/Cvd2f0h.png

Other hits for the same problem:

https://bethesda.net/community/post/502649

https://forums.nexusmods.com/index.php?/topic/6758552-wrye-bash-error-code-extraction-failed-7zexe-return-value7/

https://www.reddit.com/r/skyrimmods/comments/7mg9q5/wyre_bash_extraction_error_7_help/

**Comment by Utumno** [comment]
Pushed a commit on my wip branch that may fix that - untested, no windows machine available atm
