### ISSUE TITLE
Hide some "always recommended" Bashed Patch options

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#43]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/214/)

Suggested by wrinklyninja, my comments below:
Some Bashed Patch options should always be selected when building a patch for the end user. These options shouldn't necessarily be enforced, but to improve the interface (information overload), they should be hidden, and only accessible for advanced users that have opted to do so. These patchers are:
Contents Checker
SEWorld Tests
Cobl Catalogs - only performed if Cobl.esm is present
Cobl Exhaustion - only performed if Cobl.esm is present
Additionally, I (Lojack) would recommend considering other "Always recommended" options to be put under this hidden category of patchers, like the Leveled Lists patcher, which for 99% of end users should be left on Automatic.

**Comment by Utumno** [comment]
I am not a real fun of this - explicit is better than implicit for one. For two, adding some docs on the enabled by default patchers - even adding to the patcher text something like " Recommended to leave enabled" - would be much more maintainable and easier for users to understand than hiding some of the UI, etc, etc

**Comment by Infernio** [comment]
Yeah, I agree. As I said in https://github.com/wrye-bash/wrye-bash/issues/485#issuecomment-578537391, this will probably just confuse users - specifically, I think it will to lead to users asking 'Why did you remove X patcher?'. Explaining that we simply hid that patcher will become *really* tiring really quickly.

**Comment by Infernio** [comment]
Rejected, as per the discussion above.
