### ISSUE TITLE
Automate Dev Environment Setup

### ISSUE THREAD

**Issue by GandaG** [wrye-bash/wrye-bash#430]
Setting up the proper environment for using/developing Wrye Bash from a git clone is a lengthy process in Windows and can be a turn off for potential new developers.

This should be a seamless process requiring little to no user interaction and optionally provide support for use in a virtualenv.

TODO:
- [x] Automate wxPython 2.8.12.1 Unicode installation
  - [x] Maybe host a wheel/ready-to-install archive ourselves?
- [x] Automate py2exe 0.6.9 installation
  - [x] ~~Check if newer versions can be used - pip-able packages would be the best~~
         newer versions are py3 only.
  - [x] ~~Host wheel, same as for wxPython~~
         ~~Christoph Gohlke generously hosts [pre-built wheels](https://www.lfd.uci.edu/~gohlke/pythonlibs/#py2exe) for python. No wx 2.8 wheels though.~~
         `package_for_release` complains about `zipextimporter.py` so I'll just build and host the wheel.
- [x] Automate NSIS + lnetc installation
  - [x] If portable NSIS is installed, redo package_for_release with this as fallback
- [x] Move NSIS download to `package_for_release`
- [x] Move all packages to `requirements.txt`
- [ ] Edit readme and release wiki to reflect changes

**Comment by GandaG** [comment]
@Utumno since both wxPython and py2exe now have built wheels in repo, the script has become a glorified requirements file, with a nsis download.

My proposal is that we:
- Move the packages to a requirements.txt file:
  - No extra step needed, `pip install -r requirements.txt` is still a one-liner
  - No extra packages
  - Pipenv has legacy support for requirements files for whoever wants to use it
  - More pythonic (although outdated)
  - Splitting packages for running and building WB would require adding a second file
    - There are so few packages that I don't think installing all right away is a problem, especially since it's automated
- Move the NSIS download to `packages_for_release`:
  - It would check for the cli argument, the winreg key and only then would it resort to auto downloading nsis + inetc
  - It's a small download (2mb)
  - Requires no extra input by the user

**Comment by Utumno** [comment]
Thanks!
Well probably the only thing that is still useful there is the script for generating the changelog - probably move this to dev repo also and then bin that repo?

**Comment by Utumno** [comment]
I am getting some errors on the forums that may be related to comtypes - maybe - I do remember recently that comtypes version did make a difference: https://github.com/wrye-bash/wrye-bash/issues/425#issuecomment-449187350

Could you pin the comtypes version to 0.6.2 - till we get round to dropping it completerly hopefully soon - see: nycz-wx-begone-DEV
 branch

**Comment by GandaG** [comment]
@Utumno does 0.6.4 work?
```
$ py -2 -m pip install comtypes==0.6.2
Collecting comtypes==0.6.2
  Could not find a version that satisfies the requirement comtypes==0.6.2 (from versions: 0.6.4, 1.0.0, 1.1.0, 1.1.1, 1.1.3.post2, 1.1.4, 1.1.5, 1.1.6, 1.1.7)
No matching distribution found for comtypes==0.6.2
```
I could built a comtypes wheel but since it's marked for disposal...

**Comment by Utumno** [comment]
Hmmm - not sure really, and not sure what happens with windows 10. But reports are piling up - see also: https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=174876

**Comment by Utumno** [comment]
Thanks @Infernio - I have windows 7 so I can do later today or tomorrow (:P) but @GandaG would be great if you did pack a nightly with comtypes 0.6.2 (or maybe 0.6.4 to test) and post that to AFK so we get up to speed (plus there are lots of bugfixes and the work on patchers/records)

comtypes dependency must go but that depends on upgrading wx - so to me after all the dust settles this would be a priority

Infernio I would say that priority for now is finalizing the esl support - that is the `is_esl_capable()`. Could you do this on a clear commit over my branch?
