### ISSUE TITLE
Links to AFK Mods need to be updated

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#434]
I am finalizing a switch over to a new domain for the AFK Mods site. I know there are some URLs within the Wrye Bash files that refer to links at afkmods.iguanadons.net. These will all need to change to www.afkmods.com instead. Only the domain portion will need to change, the rest of the URL should still work fine.

**Comment by Utumno** [comment]
Nice opportunity to remove the link to beth forums and add discord

**Comment by Infernio** [comment]
Done on [inf-afkmods-update](https://github.com/wrye-bash/wrye-bash/tree/inf-afkmods-update). Took this opportunity to update some other ancient links as well (forums.bethsoft.com and the old nexusmods link format).

**Comment by Arthmoor** [comment]
If you're also updating Nexus links on this branch you should note that they're now using HTTPS links and the ones I saw changes are still using the old HTTP ones.

**Comment by Infernio** [comment]
> If you're also updating Nexus links on this branch you should note that they're now using HTTPS links and the ones I saw changes are still using the old HTTP ones.

Done in ed11b45728c1ecfd6428d237ebf703dbe50cde56. I skipped the taglists, because that would be an unreadable mess of 3000+ lines of changes.

**Comment by Utumno** [comment]
Excellent job @Infernio - feel free to merge to dev when ready (could use some squashing, like the https with the nexus ones). The taglists someone should probably mention to LOOT so next time we generate them they are ok?
