### ISSUE TITLE
Revamping the cosaves API

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#437]
The main problem with `cosaves.py` is that it's pretty hard to read and understand, owing to it being fairly unstructured. Additionally, it includes ~150 lines of halfhearted support for Pluggy cosaves, with the rest being in `_saves.py`.

In terms of functionality, it does just enough to remap the first chunk - and nothing beyond that. This turns out to not be a problem in most cases, since we can't edit SSE saves anyways and most cosaves only include a plugin list in the first chunk. However, problems are starting to surface - see #426 for an example.

## Basic Refactoring:
- [x] Rip pluggy code out of `_saves.py` and stick it into `cosaves.py` - see https://github.com/wrye-bash/wrye-bash/commit/014ee123d0eab0f76c906f222b6aababa08e3a2c
- [x] Refactor the cosaves hierarchy to allow the pluggy code to export the same API as the xSE code.
- [x] Refactor and improve code until an entire xSE cosave can be loaded.
- [x] Keep a consistent structure in mind: `__init__` loads every part of the chunk, `write_chunk` writes the entire chunk. Don't load things in the middle of dumping the cosave, for example.
- [x] Add code for 'intelligent' writing of cosaves - for example, the length of strings or entire chunks can be auto-calculated when writing.
- [x] Use the 'intelligent' writing to greatly simplify the remapping procedure. The final result should just be 2-3 lines:
```python
def remap_plugins(self, plugin_renames):
    self.mod_names = [plugin_renames.get(x, x) for x in self.mod_names]
```
- [x] Use `__slots__` as part of the design phase to make sure we have the lowest possible memory usage.
- [x] Utilize mixins to factor out common functionality (e.g. dumping and remapping).
- [x] During all this, make sure that remapping xSE and Pluggy cosaves does not break.

## New Features:
- [x] Support for dumping .pluggy contents - some (unused) code previously existed, but I had to rewrite most of it anyways.
- [x] Support for the xSE LIMD, LMOD and PLGN chunks. All of these can now be remapped.
- [x] Retrieving the master list from the cosave. Cosaves should export a `get_master_list` method that can then be used to display the correct load order for SSE.
- [x] Use the above method to show the correct save master order in SSE when possible. 

## Improved Features:
- [x] Improve remapping performance by keeping a list of 'remappable' chunks and only remapping those.
- [x] Tidy up some xSE dumping output to make it easier to read.
- [x] Create a 'light load' procedure that will only load the first chunk, which we can then use to reduce memory usage for SSE.

## Long-Term Goals (308+):
- [ ] Investigate adding support for pluggy chunks inside xSE cosaves. From my limited testing, Pluggy v132 seems to just create a new xSE plugin entry inside the cosave, so my code should process that correctly - even if remapping probably won't work.
- [ ] Decode all remaining vanilla xSE chunks.
- [ ] Decode relevant third-party xSE chunks (e.g. DATA)
- [ ] Investigate splitting out the chunk definitions per game (as in `game/*/cosave_chunks.py` or something similar).

**Comment by Infernio** [comment]
One small fix in 8ce92cc324297cf80add2392c558a65ce9398953 and some minor changes in 814656453c435da94a7f1981cfa60c138905338c.

**Comment by Infernio** [comment]
Note to self: Need to edit all occurrences of SKSE64 in the cosaves code now to also mention F4SE, since that's been updated with PLGN support since then.

**Comment by Infernio** [comment]
Idea for avoiding the unnecessary syscall that gets issued for every cosave when we refresh (The `isfile`s in `SaveInfo.do_update` and the `size_mtime` in each cosave's `do_update`):
```patch
diff --git a/Mopy/bash/bosh/__init__.py b/Mopy/bash/bosh/__init__.py
index d8df3bf10..f298d4a56 100644
--- a/Mopy/bash/bosh/__init__.py
+++ b/Mopy/bash/bosh/__init__.py
@@ -1070,19 +1070,23 @@ def do_update(self):
         cosaves_changed = False
         for co_type in SaveInfo.cosave_types:
             co_path = co_type.get_cosave_path(self.abs_path)
-            if co_path.isfile():
+            co_exists = co_type in self._co_saves
+            try:
+                co_stat = co_path.size_mtime()
                 if co_type in self._co_saves:
                     # Existing cosave could have changed, check if it did
-                    cosaves_changed |= self._co_saves[co_type].do_update()
+                    cosaves_changed |= self._co_saves[co_type].do_update(
+                        cached_stat=co_stat)
                 else:
                     # New cosave attached, add it to cache
                     self._co_saves[co_type] = self.make_cosave(co_type,
-                                                               co_path)
+                        co_path, co_stat)
+                    cosaves_changed = True
+            except OSError:
+                if co_exists:
+                    # Old cosave deleted, remove it from cache
+                    del self._co_saves[co_type]
                     cosaves_changed = True
-            elif co_type in self._co_saves:
-                # Old cosave deleted, remove it from cache
-                del self._co_saves[co_type]
-                cosaves_changed = True
         # If the cosaves have changed, the cached masters can no longer be
         # trusted since they may have been retrieved from the cosaves
         if cosaves_changed:
```

Would need some edits to AFile to allow passing in cached `size_mtime`s to both its initializer and `do_update`. Which might be leaking the abstraction too much?

**Comment by Utumno** [comment]
> Would need some edits to AFile to allow passing in cached size_mtimes to both its initializer and do_update. Which might be leaking the abstraction too much?

Might (I already added that raise on error param) - on the other hand maybe the try can stay (usually the cosave will be there) and omit the `co_stat = co_path.size_mtime()` as anyway it will be performed in the  if/else branches

Will have a closer look
