### ISSUE TITLE
'BoltError: Active mods with no load order' when manually deleting a mod

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#438]
This error seems to be showing up for a lot of people. A typical traceback:
```
Traceback (most recent call last):
  File "bash\bash.py", line 184, in main
    _main(opts)
  File "bash\bash.py", line 361, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4018, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4055, in InitData
    bosh.modInfos.refresh(booting=True)
  File "bash\bosh\__init__.py", line 1855, in refresh
    forceRefresh=hasChanged or _modTimesChange, forceActive=deleted)
  File "bash\bosh\__init__.py", line 1602, in _modinfos_cache_wrapper
    lord_func(self, *args, **kwargs)
  File "bash\bosh\__init__.py", line 1710, in refreshLoadOrder
    cached_active=not forceActive)
  File "bash\load_order.py", line 303, in refresh_lo
    _update_cache(lo, active)
  File "bash\load_order.py", line 255, in _update_cache
    cached_lord = LoadOrder(lord, acti_sorted)
  File "bash\load_order.py", line 97, in __init__
    [x.s for x in (set(active) - set(loadOrder))]))
BoltError: Active mods with no load order: HighResTexturePack03.esp, HighResTexturePack02.esp, Dawnguard.esm, HearthFires.esm, Dragonborn.esm, HighResTexturePack01.esp
```

Steps to reproduce:
1. Launch Wrye Bash for Skyrim (LE or SE, doesn't seem to matter)
2. Make sure the Mods tab is selected (this step may not actually be necessary)
3. Manually delete an _enabled_ mod from the Data folder for Skyrim (**not through Wrye Bash!**)
4. Tab back into Wrye Bash
5. Look at the BashBugDump.log. Additionally, after closing and reopening WB, you should now crash on each launch.

Collection of tracebacks that all seem to belong to this issue: https://gist.github.com/Infernio/d560c8a6bfef95502efd3ac3087d4f46

**Comment by Infernio** [comment]
`regression` since it allegedly used to work properly. Again, I don't have instructions on how to reproduce this, so I can't find out when it used to work and bisect it

**Comment by Infernio** [comment]
BashBugDump by @Sharlikran: https://gist.github.com/Infernio/f7daa9efdc3275111086c4d29abeb151

**Comment by Infernio** [comment]
Steps to reproduce seem to be:
1. Launch Wrye Bash for Skyrim (LE or SE, doesn't seem to matter)
2. Make sure the Mods tab is selected (this step may not actually be necessary)
3. Manually delete a file from the Data folder for Skyrim (**not through Wrye Bash!**)
4. Tab back into Wrye Bash
5. Look at the BashBugDump.log. Additionally, after closing and reopening WB, you should now crash with the error on each launch.

**Comment by Infernio** [comment]
Bisection result:
```
$ git bisect good
3214e6962093e770ec36dec43b315e05944f1bf6 is the first bad commit
commit 3214e6962093e770ec36dec43b315e05944f1bf6
Author: MrD <the.ubik@gmail.com>
Date:   Sat Dec 29 21:59:39 2018 -0500

    Revise active mods limits for esls - hard limit of 4096 for now:

    From @Infernio at acc80eb9214e2e18206282e323829f3e4fb9dd0a

    So, the current knowledge on this is:

    4096 is the theoretical limit on ESLs - that's how much space there
    is in the FormID for them (8^4 = 4096).
    However, testing shows that the vanilla game gives up at a much lower
    limit. That limit can be raised to around 1800 ESLs with Engine
    Fixes. At that point, the game runs out of stdio handles to use for
    plugin files.
    As for how Wrye Bash should handle this - not sure yet. I don't know
    the exact number, but my suspicion is 2048 stdio handles - 254
    regular plugins = 1794 ESLs, but I'm not sure if anyone has done
    proper testing with that. For now, it's probably alright if WB just
    sticks to the theoretical limit - but we should keep this in mind
    once more testing is done.

    For more information, see:

    https://afkmods.iguanadons.net/index.php?/topic/5079-plugin-files-and-you-esmeslesp/
    https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=vs-2017

:040000 040000 345d9beb0dcb44a7d51516eb50669f17582d6ad7 e0c44c87826849c80c9d0cffd90e11f5b93f86d3 M      Mopy
```

I've manually verified that it works in the commit before that (a78c4f0b6377115a234f64e7566ed485eb50200d) and breaks from that commit onwards (done on LE so that the half-reverted ESL support doesn't kill my load order :P).

**Comment by Infernio** [comment]
Should be fixed in https://github.com/wrye-bash/wrye-bash/commit/07a81aa6002651a81ba31b04832969f70b67f6cc.

Guess this issue was pointless after all :P

**Comment by Utumno** [comment]
Great job @Infernio !

**Comment by Infernio** [comment]
@Utumno There are quite a few fixes piling up on [inf-fixes](https://github.com/wrye-bash/wrye-bash/tree/inf-fixes) now, should I squash those and push them to dev?

**Comment by Utumno** [comment]
Oh missed this - go ahead!
