### ISSUE TITLE
Import quest icons

### ISSUE THREAD

**Issue by puddydoo** [wrye-bash/wrye-bash#440]
Quest icons aren't included in Import Graphics. There are some Oblivion mods that only change the icons of quests and so it should be able to import that without overwriting the entire quest.

Maybe this could also apply to faction rank insignias.

**Comment by Infernio** [comment]
Should be done as of https://github.com/wrye-bash/wrye-bash/commit/769f0046097093a3d2cd0b4dddf84af13791cd29. That said, I have next to no experience with Oblivion, so @puddydoo if you could test with this build (both PBash and CBash), that would be helpful:
[Wrye Bash 307.201905021146 - Standalone Executable.zip](https://github.com/wrye-bash/wrye-bash/files/3137869/Wrye.Bash.307.201905021146.-.Standalone.Executable.zip)

**Comment by puddydoo** [comment]
Applied NoMerge and Graphics tags to the mod "Colored Quests" and the quest icons make it into a PBash, but not a CBash.

**Comment by Infernio** [comment]
I didn't have high hopes for the CBash edits, so that's not too surprising. I'll leave this issue open in case I do figure out how to get CBash to patch this.

**Comment by Sharlikran** [comment]
@puddydoo @leandor Leandor would have to update and compile a new version of CBash to include that kind of update.
