### ISSUE TITLE
Multi-Game menu is partially squashed

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#441]
Version 307.201905311918 has a slight problem when Wrye Bash is installed for managing multiple games from a single install. The initial menu is cropped off and the game up there can't be accessed.

![MenuCropped](https://user-images.githubusercontent.com/1762652/60401020-f278fd00-9b38-11e9-851f-52c667eb5f72.png)

**Comment by Infernio** [comment]
Should be improved as of https://github.com/wrye-bash/wrye-bash/commit/c102ba6e7ad9525f293e35b93f05f24605727a58:

![GameSelect](https://user-images.githubusercontent.com/2845240/61673537-22f32780-acf0-11e9-8ba2-6952b40d68bf.png)

That said, wx is extremely fickle, so I have no idea how well this will work (especially for non-1080p resolution).

**Comment by Infernio** [comment]
Closed in fe7cbe398bba8e9137183c3d30ba7a4ab1767b49.
