### ISSUE TITLE
Auto Wizard doesn't resolve SelectOne if default is third option or beyond

### ISSUE THREAD

**Issue by alphaniner** [wrye-bash/wrye-bash#444]
SelectOne is not automatically resolved by Auto Wizard if the specified default is the third option or beyond, e.g.:
```
SelectOne "Test0", \
    "One", "", "", \
    "Two", "", "", \
    "|Three", "", ""
EndSelect

SelectOne "Test1", \
    "One", "", "", \
    "Two", "", "", \
    "Three", "", "", \
    "|Four", "", ""
EndSelect
```
etc.

The problem is line 1429 of Mopy/bash/belt.py:
```
                if defaultMap[i]:
```
which should be:
```
                if i:
```

That said, the following produces the same results as the `if` block beginning on 1435 but is more straightforward IMO:
```
        # auto wizard will resolve SelectOne/SelectMany only if default(s) were specified.
        if self.bAuto and defaultMap.count(True) > 0:
            temp = []
            for index in range(len(titles)):
                if defaultMap[index]:
                    temp.append(titles[index])
                    if not bMany:
                        break
            self.PushFlow(u'Select', False, [u'SelectOne', u'SelectMany', u'Case', u'Default', u'EndSelect'], values=temp, hitCase=False)
```
(Note: original line 1437 `default = False` appears to serve no purpose so I left it out)

[BashBugDump.log](https://github.com/wrye-bash/wrye-bash/files/3388817/BashBugDump.log)

**Comment by Metallicow** [comment]
I am not the author of Wizard Script or WizBAIN syntax. Please see the code or demo.

**Comment by Metallicow** [comment]
If you have a problem that CAN be resolved. Please update the demo and hook into main:

**Comment by Metallicow** [comment]
I do not have time for p2.7-3.7+ or wx2.8-wx4.1 etc,..

**Comment by Metallicow** [comment]
It is python based, that is all I can tell you

**Comment by Utumno** [comment]
Thanks @alphaniner for the bug report complete with fix - I will push a fix
on the nightly branch based on your code. Btw instead of
`defaultMap.count(True)`
would be faster to use `any(default Count)` here. Ignore the spam above plz

**Comment by alphaniner** [comment]
Thanks @Utumno for the tip, I wasn't aware of any().
