### ISSUE TITLE
BAIN Wizards: General Improvements

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#446]
While looking through `belt.py` and the BAIN Wizard documentation for investigating issues 444 and 445, I noticed that two functions were missing documentation. Opening this issue as a TODO list for me as I go through and fix all the problems I found (and so I can nicely refer to this issue in commit messages).

## Constants
- [x] The documentation lies when it says that wizards only define two constants, `True` and `False`, they also define a constant called `SubPackages`. It's even used in many examples further down the page.

## Functions
- [x] `DisableINILine` - disables a setting by commenting out the line in the INI file. These tweaks don't seem to work in WB right now though.
- [x] `EndExec` - internal function, marks the ending of an `Exec` function's contents. Calling `EndExec` manually is an error (should still have documentation to this effect though).

## Operators
- [x] Did you know that wizards support incrementing or decrementing variables? I didn't either, because the documentation never mentions it.
  - [x] Turns out that the increment / decrement operators were supposed to act as postfix ones, but someone made a mistake and they actually act as prefix operators. I'll just change the specification to keep backwards compatibility.
- [x] The operators need some better documentation. When I see `^=` I assume bitwise negation, but looking at the source code, it's actually exponentiation.
- [x] The `in` operator needs an actual explanation of what it does (with an example).
- [x] The dot operator basically assumes that you're familiar with OO to understand it. An example would help (starting to notice a pattern here? :stuck_out_tongue: ).
- [ ] An implementation of `%=` and `%` for modulo exists, but is commented out. Might be worth reviving?

## Random Notes
- [ ] Everything mentioning `Espm` should probably be deprecated in favor of new keywords / functions with `Plugin` instead, since `.esl` files are a thing now - and there may be other types in the future (obviously we'll keep the old versions around indefinitely, similar to how `CompareOblivionVersion` was handled, since an absolute ton of wizards would break otherwise).
- [x] The `string[start:stop:step]` syntax in Python isn't called indexing, it's called [slicing](https://docs.python.org/2/glossary.html#term-slice). Indexing is only when you use a single number in the brackets (e.g. `string[target]`).

**Comment by Utumno** [comment]
> DisableINILine - seems to set a setting in an INI file to an empty string?

should probably just prepend a `;`.

Historically @lojack5 said that this (or the Scriptparser) was the first python he wrote so there are many not-so-pythonic idioms. That being said if you really want to dig in there that's ok. I am busy lately but if I do find some time would like to look into the wx3/p3 switch as p2 is going out of service soon.

**Comment by Infernio** [comment]
@Utumno That seems to be exactly what it does. However, it looks like WB can't actually apply those tweaks :P
Try executing this wizard, and then try applying the resulting tweaks:
```
; test BAIN Wizard Installation Script
DisableINILine("Skyrim.ini", "General", "iPresentInterval")
DisableINILine("Skyrim.ini", "General", "iMadeUpSetting")
```

**Comment by Infernio** [comment]
So, fun fact, BAIN wizards are Turing-complete.
Here's an emulator that doubles as a proof, because why the hell not: https://github.com/Infernio/bainwiz-turing

**Comment by Utumno** [comment]
> Try executing this wizard, and then try applying the resulting tweaks:

Away from windoz machine - so the _theory_ is that there is a "deleted line" concept in wrye bash ini handling - that's basically half-broken, I am sure. Lo was the wizard/ini guy, but the ini part has been rewritten since. I never tested "deleted" though - let me see... start from here: https://github.com/wrye-bash/wrye-bash/blob/6ff2eb61097ded9e33d78bbfad6031e8dc64a47f/Mopy/bash/bosh/ini_files.py#L68

Avoid renames till the very end while refactoring, does help reviewing - the ini code uses mixed style, PEP8 one is mine, `ci` prefix stands for case insensitive, AFile api is nearing beta.

**Comment by Infernio** [comment]
Documentation updates are done on [inf-wiz-docs](https://github.com/wrye-bash/wrye-bash/tree/inf-wiz-docs) now. I'm splitting any refactoring etc. into a different branch since the documentation changes are harmless (i.e. they can't possibly break dev).

**Comment by Utumno** [comment]
excellent! basically if you could (squash?) move it on top of nightly would
be grand - just a bit worried there might be conflicts with feles rewrite

**Comment by Utumno** [comment]
Had a very brief look in your branch - great work. Some random points:

- plugin is ok but better not float around outside of an element of other keywords, as it used to be a bane (not sure if anymore though).
- one of the most annoying things with belt is that is imported in `bash/bash.py` as it sets a `codebox` static to WryeParser. Well if don't deprecate all this maybe it's time to move this out of there, it's super ugly (plus files doing stuff on import is always a smell). Be warned that I kind of tried but it was far from simple IIRC.
- maybe (up to you) not add the newline between one liner functions? Really appreciated you zapped the ones inside the code :)

**Comment by alphaniner** [comment]
> That seems to be exactly what it does. However, it looks like WB can't actually apply those tweaks :P

And if used to disable lines of an OBSE-type .ini without also editing the .ini, `get_ini_type_and_decoding` (in bosh/ini_files.py) raises `BoltError` because the resulting tweak contains only comments (which are effectively ignored by the function).

**Comment by Utumno** [comment]
@alphaniner can you python? Maybe hash up some unit tests? :P

**Comment by alphaniner** [comment]
I would if I could. I know enough python to troubleshoot some bugs. I have only a basic understanding of unit testing and no idea how to apply it to a project like this.

**Comment by alphaniner** [comment]
Back on topic, it would be nice if the example version string for `CompareWBVersion` were appropriate for WB instead of SE.

If possible for `CompareGEVersion` too, but that's probably not practical if there are GEs for multiple games (I only know of OBGE).
