### ISSUE TITLE
Crash on open if oblivion.ini exists in install directory

### ISSUE THREAD

**Issue by alphaniner** [wrye-bash/wrye-bash#447]
If oblivion.ini exists in the install directory, it's read into a `ConfigParser.ConfigParser` object (Mopy/initialization.py 157-158). By default the `read()` method raises `ParsingError` if the file contains "options without values". To prevent this the `ConfigParser` object has to be created with `allow_no_value=True`.

PS. I'm not actually trying to use a local oblivion.ini; I'm working on a wizard function for proposal (to get the value of an ini setting) and created the local ini to verify that my function followed the rule indicated on [uesp](https://en.uesp.net/wiki/Oblivion:Ini_Settings):

> Oblivion reads the Oblivion.ini in the directory where it exists first, and only if bUseMyGames is non-existent or set to 1 does it then look for My Documents\My Games\Oblivion.ini. In other words, both can exist simultaneously, and only the value of bUseMyGames in the Oblivion.ini directory where Oblivion.exe is run from will actually matter.
-----
Edit: initialization.py looks for the wrong setting too:
```
        if get_ini_option(oblivionIni, u'bUseMyGamesDirectory') == u'0':
```
Should be
```
        if get_ini_option(oblivionIni, u'bUseMyGames') == u'0':
```

**Comment by Infernio** [comment]
I waded through logic this once before and got really confused, because there are several sources that use `bUseMyGames` and several that use `bUseMyGamesDirectory`:

## bUseMyGamesDirectory
UESP: https://en.uesp.net/wiki/Oblivion:Directories
STEP: https://wiki.step-project.com/Guide:Oblivion_INI/General#bUseMyGamesDirectory
MO2: https://github.com/ModOrganizer2/modorganizer/issues/799

## bUseMyGames
UESP: https://en.uesp.net/wiki/Oblivion:Ini_Settings

Might have to do some testing to see what Oblivion accepts.

**Comment by alphaniner** [comment]
I did a bit of testing. I made a copy of the .ini with HDR enabled, used the launcher to enable Bloom, then moved the copied .ini to the install directory.

With `bUseMyGames=0` in the install .ini, Bloom was enabled in-game. With `bUseMyGamesDirectory=0` in the install .ini, HDR was enabled in-game.

With that and the fact that only one source mentions `bUseMyGames` (aside from the comments in `initialization.py`), I'd say it's safe to assume it was a typo.

**Comment by Infernio** [comment]
Fixed in 6f20ebf01f95c573156cfe7d136804897d22b82d.

**Comment by alphaniner** [comment]
Maybe also replace the references to `bUseMyGames` in the comments (lines 147 & 149) with `bUseMyGamesDirectory` to avoid confusion in the future?

**Comment by Infernio** [comment]
Done in f419cb128e6e57fe29d91fbf91388d5e0cce45a4.
