### ISSUE TITLE
Issue with Ampersand in Select description.

### ISSUE THREAD

**Issue by alphaniner** [wrye-bash/wrye-bash#448]
If there is an ampersand in the main description of a SelectOne or SelectMany block e.g.
```
SelectMany "This & that and those.", \
	"A", "This & that and those.", "", \
	"B", "", ""
EndSelect
```
The ampersand does not appear in the wizard and the last word is broken off to a new line e.g.
```
This  that and
those.
```
Additional ampersands also fail to appear but don't have any other consequences AFAICT.

**Comment by alphaniner** [comment]
Looks like this may be a wx issue, because the description is used in a call to `balt.StaticText` which is a subclass of `wx.StaticText`...

**Comment by Metallicow** [comment]
yes & is an escape in wx for various things.

**Comment by alphaniner** [comment]
A new function (`SetLabelText`) was added somewhere along the line (probably in 3.0; it exists in 3.0.2.0 anyway) which is like `SetLabel` but doesn't interpret ampersands. Maybe something to consider for the wx3/p3 switch.

I don't really see any point in keeping this open, but I'll let @Infernio decide since he's been assigned.

**Comment by Infernio** [comment]
Everything I've found online just suggests escaping ampersands by replacing them with two ampersands:
http://wxpython-users.1045709.n5.nabble.com/wx-StaticText-and-ampersand-amp-td2359503.html
https://stackoverflow.com/questions/4667881/how-to-write-a-in-button-text-in-wxpython

So, I've done that in a99ff8514e0ee07e91ac7669c1590c9906f2e3c7 now. It seems to work and only shows a single ampersand, but at least on my Linux machine with wine, the line break also still appears. I don't have a Windows machine to test this right now, so I can't say if it's just a wine issue.

**Comment by alphaniner** [comment]
Yeah, I had also tested that and the line break still appears on Windows too. I forgot to mention after I went looking for better solutions.
