### ISSUE TITLE
GE version detection

### ISSUE THREAD

**Issue by alphaniner** [wrye-bash/wrye-bash#449]
The tuples in the list for GE version detection (`game/oblivion/__init__.py` lines 76-78)
```
exe = [(u'Data',u'obse',u'plugins',u'obge.dll'),
       (u'Data',u'obse',u'plugins',u'obgev2.dll'),
       ]
```
contain 'Data' as part of the path, but in belt.py these get joined with `[bass.dirs['mods']` which itself represents the 'Data' folder. As a result the files are not found, so GE detection for `CompareGEVersion` and `RequireVersions` doesn't work. Removing 'Data' from the paths fixes the issue.

On a related note, maybe the plugin for Oblivion Reloaded (obse/plugins/OblivionReloaded.dll) could be added to the list since it is the current "incarnation" of OBGE. I tested this and the version is correctly detected as '7.0.0.0'.

**Comment by Infernio** [comment]
Should be fixed as of 89731c1de802c021d7592b45c48ba879d34b31e9. I also removed the need to do the `7.0.0.0` thing in df930c354a8f4da07763ea408644fd77bc3b2f58, you can now just specify `CompareGEVersion "7" >= 0`.
