### ISSUE TITLE
SEFF icon tweaker

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#45]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/212/)

~~TODO: See if this is applicable for Fallout 3 / Fallout : New Vegas~~ - not applicable, the whole MGEF system got reworked after Oblivion

Gratis_monsta, on 29 December 2011 - 09:09 PM, said:
Like the Script Effect silencer, how about a script effect icon changer tweak? [This mod](https://www.nexusmods.com/oblivion/mods/20395) has a nice selection (or you could use the basic vanilla spell icons)

**Comment by Infernio** [comment]
Going to use this as an opportunity to show off how easy making a tweak with the new implementation is :)
