### ISSUE TITLE
Installer General tab: Change 'Conflicts' to 'Mismatched'

### ISSUE THREAD

**Issue by alphaniner** [wrye-bash/wrye-bash#450]
The General tab for an installer indicates the number of matched, missing, and conflicted files e.g.:
```
Configured: 2 (9 KB)
  Matched: 1
  Missing: 0
  Conflicts: 1
```
But the indicated number of Conflicts is actually the number of mismatches, which is not necessarily the number of conflicts (for example a modified .ini is a mismatch, not a conflict).

So the text should be modified to indicate mismatches rather than conflicts:
```
Configured: 2 (9 KB)
  Matched: 1
  Missing: 0
  Mismatched: 1
```

Going beyond this, IMO it would be valuable if a sub-entry were added to indicate overridden files:
```
Configured: 2 (9 KB)
  Matched: 0
  Missing: 0
  Mismatched: 2
    Overridden: 1
```

I [implemented this and more](https://gist.github.com/alphaniner/3ebf42f39f9ba4a43a8a00d6adc48bd3) (maybe too much more) to show the following:
```
Configured: 2 (9 KB)
  Matched: 0
  Missing: 0
  Mismatched: 2
    Overridden: 1
  Overrides: 1
  Underrides: 0

Dirty: 1
```
"Overridden" refers to files in this package which are overridden by other packages ("Higher" conflicts). "Overrides" refers to files of other packages this package overrides ("Lower" conflicts). The terms could maybe use some work.

"Dirty" is hidden if it is 0. If "Mismatched" is 0 then "Overridden" is hidden, and if "Configured" is 0 then everything underneath it is hidden.

**Comment by Utumno** [comment]
Putting in the bugburner for now let's revisit in 308 (with fomods we must revisit BAINpackage display anyway)

ref #380
