### ISSUE TITLE
Skyrim VR Support

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#454]
Continuing from #407, since we prefer issues over PRs.

Adding Skyrim VR support should be fairly easy - it's basically Skyrim SE but without ESLs - but if issues arise, testing and reproducing is going to be difficult to impossible, since none of us own VR headsets.

### Sub-issues:
 - [x] #534
 - [x] #549 
 - [ ] #635

**Comment by Infernio** [comment]
Nightlies now include experimental support for Skyrim VR (no installer edits right now though - they were a pain for Enderal, so I'm putting them off for as long as possible).

**Comment by Infernio** [comment]
*(Can't assign @nallar because they never commented on this issue - github weirdness again)*

**Comment by nallar** [comment]
Unfortunately, don't currently have access to a VR setup to test. Stuck out of country during this coronavirus mess for longer than expected.
