### ISSUE TITLE
Avoiding 'iCCP: known incorrect sRGB profile' warning in wizards and FOMODs

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#458]
People on Discord are getting scared at these warnings:
![iccp](https://user-images.githubusercontent.com/2845240/64474728-e7fe6380-d178-11e9-8c3b-551f37808f25.png)

As mentioned in the wxPython 3 commit on nightly, wx3 uses libpng1.6+, which is much stricter when it comes to iCCP profiles in PNGs.
I've fixed the warnings for WB's images by running ImageMagick on them, but users can still encounter it when running wizards and FOMOD installers with such images.

There doesn't seem to be any easy way to disable this warning, so we'll have to build in an ImageMagick / pngcrush pass after extracting wizard / FOMOD files.
That obviously means bundling something like ImageMagick or pngcrush. Some stats:

|   Processor    |  Binary Size (all 32 bit) |             Relevant Command            | License |
| -------------- | ------------------------- | --------------------------------------- | ------- |
| ImageMagick    | 25.8 MB (Q8, dynamic)     | `magick mogrify <file>`                 | [Apache 2.0-like](https://imagemagick.org/script/license.php) | 
| GraphicsMagick | 5.4 MB (Q8)               | `gm mogrify <file>`*                    | [MIT-like](http://www.graphicsmagick.org/Copyright.html) | 
| pngcrush       | 388.6 KB                  | `pngcrush -ow -rem allb -reduce <file>` | libpng/zlib-like | 

*: might need to be `gm mogrify -strip <file>`, haven't played around with this yet

`pngcrush` seems like the obvious choice since it's much smaller than the others.

**Comment by Utumno** [comment]
Snag - any idea if needed in phoenix? If we are to bundle smth probably smaller wins

**Comment by Utumno** [comment]
> when running wizards and FOMOD installers with such images

Another fix could be to ask modders o do tthe Roght Thong with their images - or is it very frequent?

**Comment by Infernio** [comment]
It seems to be *very* frequent, that's the problem. If it was only one or two rare wizards, I'd stamp a 'not a bug' flair on this and tell the modders responsible to fix their images :P

**Comment by Infernio** [comment]
See 27e1d59009bde68533d2e0da23620ace642c1a9f  and 809037ef397f54c303476039c3b216ec731c8ecc for a working solution.

**Comment by Arthmoor** [comment]
Is this primarily old mods for Oblivion doing this or are some of the newer ones doing it too? Maybe this is the result of some ancient version of an image editor nobody uses anymore.

**Comment by Infernio** [comment]
Even new ones do this. I've observed a simple 'Save As' in Photoshop (CS6, not sure about newer versions) spitting out 'invalid' sRGB profiles (invalid as in proprietary and therefore unsupported by libpng). Save For Web seem to work though.

**Comment by Arthmoor** [comment]
I see. So this is some kind of license purity issue then?

**Comment by Infernio** [comment]
Some sRGB profiles are legitimately just wrong, and some are unsupported by libpng.

**Comment by Utumno** [comment]
Posting for reference: 

https://github.com/wxWidgets/wxWidgets/commit/a016e6b896a3d22ccd7a5257154fa80622622048 - this commit in wxWidgets adds support for suppressing the warnings - this would be the optimal solution (avoid adding the binary, avoid processing overhead). On the other hand adding the binary would offer yet another menu in the swiss army knife ("Clean up pngs...")

Re: 64-bit , I used to know why - I don't remember but may be comtypes or wx 2.8? If yes we're lucky

**Comment by Utumno** [comment]
As noted here: https://github.com/ContinuumIO/anaconda-issues/issues/1868#issuecomment-401612221 probably wxpython3 still uses the so-called `WX_3_0_BRANCH` meaning this commit is not in, but if we go phoenix all the way maybe `SetLoadFlags` it's part of the API

**Comment by Utumno** [comment]
> Re: 64-bit , I used to know why - I don't remember but may be comtypes or wx 2.8? If yes we're lucky

Although I am affraid itt might be CBash

**Comment by Infernio** [comment]
> On the other hand adding the binary would offer yet another menu in the swiss army knife ("Clean up pngs...")

Good point, we could actually go even further and offer an 'Optimize PNGs' option on projects that doesn't just fix the warnings but actually applies pngcrush's optimizations as well (left those out of fix_png since that would obviously make it even slower).

**Comment by Metallicow** [comment]
This is the easiest way to hack around it. just toggle this when doing wizards, tho this isn't the best option because there might be other issues besides the sRGB Profile issue...
wx.Log.EnableLogging(enable=False)

attached iCCP_known_incorrect_sRGB_profile.png
![iCCP_known_incorrect_sRGB_profile](https://user-images.githubusercontent.com/4668356/71535790-530daa80-28ce-11ea-8626-aebf46dbfd11.png)

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

""""""

# Imports.--------------------------------------------------------------------
# -Python Imports.
import os
import sys

# -wxPython Imports.
import wx

class MyPanel(wx.Panel):
    """"""
    def __init__(self, parent, id=wx.ID_ANY,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.BORDER_SUNKEN, name='panel'):
        """"""
        wx.Panel.__init__(self, parent, id, pos, size, style, name)

        wx.StaticBitmap(self, -1, wx.Bitmap('iCCP_known_incorrect_sRGB_profile.png'))

class MyFrame(wx.Frame):
    """"""
    def __init__(self, parent, id=wx.ID_ANY, title=wx.EmptyString,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.DEFAULT_FRAME_STYLE, name='frame'):
        """"""
        wx.Frame.__init__(self, parent, id, title, pos, size, style, name)
        global gMainWin
        gMainWin = self
        wxVER = 'wxPython %s' % wx.version()
        pyVER = 'python %d.%d.%d.%s' % sys.version_info[0:4]
        versionInfos = '%s %s' % (wxVER, pyVER)
        self.CreateStatusBar().SetStatusText(versionInfos)
        panel = MyPanel(self)
        self.Bind(wx.EVT_CLOSE, self.OnDestroy)

    def OnDestroy(self, event):
        """"""
        self.Destroy()

class MyApp(wx.App):
    """"""
    def OnInit(self):
        """"""
        # wx.Log.EnableLogging(enable=False)
        self.SetClassName('MyApp')
        self.SetAppName('MyApp')
        gMainWin = MyFrame(None)
        gMainWin.SetTitle('MyFrame')
        self.SetTopWindow(gMainWin)
        gMainWin.Center()
        gMainWin.Show()
        return True

if __name__ == '__main__':
    gApp = MyApp(redirect=False,
            filename=None,
            useBestVisual=False,
            clearSigInt=True)
    gApp.MainLoop()

```

**Comment by Metallicow** [comment]
There is no easy way around this issue other than to tell everyone on the net to fix their images or by optimizing them. This is a libpng issue. Maybe someday when they figure out what is standard, then wx and every other library can incorporate a real fix. until then, just workaround it....

**Comment by Metallicow** [comment]
@Utumno @Infernio 
I think disabling the warnings for projects might be best as a menu option on the BAIN tab(yet another menu item to clog things up), tho it would something to think about if you want that enabled by default... 
Weighing in users wrath vs developers(well thats the way it is)

**Comment by Metallicow** [comment]
As far as optimizing PNGs, https://nikkhokkho.sourceforge.io/static.php?page=FileOptimizer is a GUI frontend for a lot of png optimizers, and if you look at all the included ones and the settings in the sourcecode, this might help. 
I thought about bundling all the png optimizers myself at one time and applying the settings in a python GUI so that it would be portable across OS, tho the author is still active and updates his app, tho his GUI kit is only good for MSWindows(GUI he uses)

**Comment by Infernio** [comment]
Closed in 050391ca22d7c8451390cbff6fd150ab0b9bcabd for now - as mentioned in that commit, our current solution is pretty ugly and slow. However, wx4.1 [will offer better ways around this](https://wxpython.org/Phoenix/docs/html/wx.Image.html#wx.Image.SetDefaultLoadFlags) - so a better solution will require #190 and a bit of waiting.

**Comment by Metallicow** [comment]
@Infernio That is essentially the same code I wrote above, but it deals directly with wx.Image only. ... So im not sure why you didn't implement a solution like I got below. It adds 2 lines to the code for a switch. Turn off logging before doing a installer and turn it back on after installer has been installed.

```python
class MyApp(wx.App):
    """"""
    def OnInit(self):
        """"""
        # wx.Log.EnableLogging(enable=False)  wxPy 4.0 and before
        wx.Image.SetDefaultLoadFlags(0)  # wxPy 4.1
```

This works with wxPy4.1

```python
class MyPanel(wx.Panel):
    """"""
    def __init__(self, parent, id=wx.ID_ANY,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.BORDER_SUNKEN, name='panel'):
        """"""
        wx.Panel.__init__(self, parent, id, pos, size, style, name)

        image = wx.Image()
        image.SetLoadFlags(0)
        image.LoadFile('iCCP_known_incorrect_sRGB_profile.png')
        wx.StaticBitmap(self, -1, wx.Bitmap(image))
```

but in order to do that with the installer problem your code should basically look like this until you get to wxPy4.1

```python 
wx.Log.EnableLogging(enable=False)
#... Unpack and Load and/or install Mod from archive might contain unoptimized images.
wx.Log.EnableLogging(enable=True)
```

**Comment by Infernio** [comment]
Doing it like this:
```python
wx.Log.EnableLogging(enable=False)
#... Unpack and Load and/or install Mod from archive might contain unoptimized images.
wx.Log.EnableLogging(enable=True)
```
would mean adding a wx import into bain, which is a nono - there is a balt import, so I could add a wrapper to balt to do this, but that balt import shouldn't be there either:
```python
 from .. import balt # YAK!
```
Note the `YAK!` - bain shouldn't be coupled with balt, and further coupling is a nono. So the only other option would be to hunt down all usages of `balt.Image`/`wx.Bitmap` and surround them with something like this:
```python
with balt.SuppressWarnings():
    my_bitmap = balt.Image(u'foo.png').GetBitmap()
```
where `balt.SuppressWarnings` would be a context manager that can enable and disable logging. Problem is that there are ~33 usages of `balt.Image` and who knows how many implicit usages of `wx.Bitmap`, so finding all the spots to surround with that context manager would be more effort than I am willing to exert right now :P
#190 will make this much simpler once it's done, because we'll have centralized image handling so we can just put the logging toggle/SetLoadFlags call in that one central place.
