### ISSUE TITLE
Feature Suggestion: External configuration file per plugin for Bash tags

### ISSUE THREAD

**Issue by FelesNoctis** [wrye-bash/wrye-bash#463]
Summary:
Modify the default behavior of reading/saving custom tags for plugins from the plugin header description to read an external file of the same name.

-----

RoyBatty suggested an improvement for patcher behavior in the xEdit server, which I think is a great idea on it's own, but especially so given the atmosphere of the current modding community.

Rather than relying on default bash tags being parsed from the mod description, Wrye Bash could instead read from a _**text, json, or xml**_ file named the same as its associated plugin. Modifying the plugin for our own purposes is inefficient and unsafe as an update will remove any custom settings, but as well, using an external file would mean users can share their Bash tags. This would allow for similar functionality to saving and loading Bash profiles, but for single plugin instances.

Being able to share/provide an external configuration file is not only safer, it will help mod authors by potentially reducing the number of bad bug reports due to incorrect settings.

Functionality wise we obviously can't just remove the description-based method due to older unmaintained mods. We could however use a priority system: If an external configuration file of the same name exists use that, then use the mod description's included tags if they exist, then finally use the built in configurations we have currently defined.

In itself this probably wouldn't require complex/specific implementations for each game as Wrye Bash would be reading the file then setting valid tags it finds based on the game mode it's in currently. Of course, that's entirely based on where the behavior code for tags currently is.

**Comment by Infernio** [comment]
I would suggest a different layout.

Current Suggestion:
```
Data
|- MyMod.esp
|- MyMod.{json,txt,xml}
```

Problems with this approach:
 - It's not even slightly obvious what the JSON/TXT/XML file does.
 - It pollutes the Data folder even further - we already stick ESPs, BSAs, INIs and modgroups in there.

The first problem could be solved with a new file extension - for example, `MyMod.tags`. That doesn't help with the second one though.

I would suggest this:

```
Data
|- Bash Tags
|  |- MyMod.txt
|- MyMod.esp
```

This solves both problems. As for the format of the .txt file, I think a simple comma-separated list would be best - XML and JSON are overkill for something this simple:

```
# In 'Bash Tags/MyMod.tags'
# Adds these four tags to the plugin in WB
C.Water, Delev, Invenv, Relev
```

And it should probably have the ability to remove tags specified in the description too, just like the LOOT masterlist:

```
# In 'Bash Tags/BrokenMod.tags'
# Removes 'Delev', adds 'Keywords' to the plugin in WB
-Delev, Keywords
```

Anyways, assigned to 308, but might look into it sooner - depends on the health of the code that combines the LOOT info and tags from the description.

**Comment by Infernio** [comment]
Moving to 307, because I'm already finished with it :P
Pushing in a bit, just need to write some docs and a commit message

**Comment by Utumno** [comment]
Haha great - I would suggest to avoid the space in Bash Tags folder maybe?

**Comment by Infernio** [comment]
Yeah, that makes sense. Just BashTags then.

**Comment by Arthmoor** [comment]
Hopefully this will leave support for tags in descriptions in place as well so that thousands of old mods don't need to suddenly be updated :P

**Comment by FelesNoctis** [comment]
Holy crap that was fast!

Yeah, a key part of this is ensuring backwards compatability, which is why I suggested the priority system. We already have some predetermined tags for some plugins, but then description-based tags should override that (they may already do?) , and these files should override both.

@infernio How is the process of new tags or modifications handled right now? I figure by default the best way is if any changes are made through the UI, WB automatically builds that tag file instead of modifying the plugin description. It makes sense from the priority standpoint, and also passively encourages people to use them instead of it just being a somewhat hidden new feature.

**Comment by Infernio** [comment]
Yeah, I've thought about that too
I'll add another right click option to the Bash Tags field, `Copy to Data/BashTags`, which will save them to a file in there.

**Comment by Infernio** [comment]
@FelesNoctis Follow-up done in 360c6b6eea618405b13ee7ac3a821a223364c114.

**Comment by Infernio** [comment]
Not really related to the patcher, doesn't change anything about how the BP works. Mostly touches `mods_metadata.py`.
