### ISSUE TITLE
Update screenshots in docs

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#464]
They are pretty out of date by now, so taking some new ones would be nice. Additionally, we could use this as an opportunity to add some unused ones to the docs and remove redundant ones.

Follow-up to #432.

*(Opening only to have an issue to reference when I merge my `inf-new-screenshots` branch)*

**Comment by Infernio** [comment]
@Utumno `inf-new-screenshots` is done, I'd like to get it merged ASAP (so that I can start on the Enderal readme edits, see the feles merge for what happens if we have two sources of readme edits at the same time 😅). Should I do that as a single, squashed commit, or with a `no-ff` merge to preserve the commits?

**Comment by Utumno** [comment]
>  for what happens if we have two sources of readme edits at the same time 

Oh yes what a PITA that was - months and months of conflicts resolution.

You can do a no-ff if you prefer - thanks for taking care of this :+1:

**Comment by Infernio** [comment]
Seems to have chopped off ~600KB from the download, not bad

**Comment by Utumno** [comment]
Beautiful I must add - may ask who's Kylia? :P

**Comment by Infernio** [comment]
The character in this screenshot:
![](https://wrye-bash.github.io/bash/images/readme/screenshots-2.png)
