### ISSUE TITLE
Support non-standard compressions for SSE saves

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#466]
Skyrim SE's INI has a setting called `uiCompression`, which isn't there by default, but can be added and changed by users:
```ini
[SaveGame]
uiCompression=2
```

- If set to its default, 2, it generates LZ4-compressed saves.
- If set to 1, it generates zlib-compressed saves.
- If set to 0, it generates uncompressed saves, just like LE.

These use a flag in the header, which we already parse:
https://github.com/wrye-bash/wrye-bash/blob/c2d73965fba4d0a82bb95f7cbe13b7f5dbcc0155/Mopy/bash/bosh/save_headers.py#L220-L221

However, we then ignore the flag and always use LZ4. This seems to enter us into an infinite loop, **locking up the entire application and requiring it to be killed from the task manager**.
We should instead check the flag and decide what to do based on that.

Some saves from aers, showcasing all three save types: [SSE Saves.zip](https://github.com/wrye-bash/wrye-bash/files/3660354/SSE.Saves.zip)

**Comment by Utumno** [comment]
Well that's one of the tough nuts - we could ship with a fork of 7z that supports lz4 and zlib (methinks) but this decompresses files whereas we need to decompress binary blobs (this is for texture bsas too that are compressed). We have the code by nycz for lz4 we could add for zlib but python is slow for this kind of stuff. 

For now we should maybe add a warning and refuse to unpack the zlib ones, as the application freezing is a nono. But this is blocked by #338 really

**Comment by Infernio** [comment]
Python has native zlib support, so this was actually really easy: 2c53c3d57c9718022e73bf3dde8c2241e0113edf

**Comment by Utumno** [comment]
You're a scholar and a genteman
