### ISSUE TITLE
Port all patchers to Fallout 3/New Vegas

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#468]
### Patcher Status:
- [x] Alias Mod Names
- [x] Contents Checker
- [x] FormID Lists
- [x] Import Actors
- [x] Import Actors: AI Packages
- [x] Import Actors: Animations
- [x] Import Actors: Death Items
- [x] Import Actors: Faces
- [x] Import Actors: Factions
- [x] Import Actors: Spells
- [x] Import Cells
- [x] Import Destructible
- [x] Import Effect Stats
- [x] Import Enchantment Stats
- [x] Import Graphics
- [x] Import Inventory
- [x] Import Names
- [x] Import Object Bounds
- [x] Import Relations
- [x] Import Scripts
- [x] Import Sounds
- [x] Import Spell Stats
- [x] Import Stats
- [x] Import Text
- [x] Import Weapon Modifications
- [x] Leveled Lists
- [x] Merge Patches
- [x] Tweak Actors
- [x] Tweak Assorted
- [x] Tweak Names
- [x] Tweak Settings
- [x] Race Records

Assigned to 308, but some of these will definitely be done sooner than that.

**Comment by Utumno** [comment]
Congrats Inf!
