### ISSUE TITLE
Potential solution for Unicode raw strings

### ISSUE THREAD

**Issue by syntaxaire** [wrye-bash/wrye-bash#470]
Sub-issue of #460 

Further to the discussion [here](https://github.com/wrye-bash/wrye-bash/commit/ba2b0f33405ecce20afeca4c2120056d92992b05), I've looked into the conversion of `ur''` type Python 2 strings some more, and I think I've found a simple substitution to convert them all.

I don't think that passing the `re.U` flag to `re` along with a Python 2 bytestring is sufficient, because according to the documentation [here](https://docs.python.org/2/library/re.html#module-contents), the only thing the flag does is 'Make the \w, \W, \b, \B, \d, \D, \s and \S sequences dependent on the Unicode character properties database.'

So I propose the following instead: If a `ur''` string includes a backslash, instead of replacing `ur'long_\regex'` with `u'long' r'\regex'`, use `u'' r'long_\regex'`. This utilizes the concatenation feature without splitting the regex, and gives the intended result without modification in both Python 2 and 3.

**Comment by syntaxaire** [comment]
I believe the reason automated tools don't use this approach is:
```python
ur'(.*)([/\\:*?"<>|]+)(.*)' == u'' r'(.*)([/\\:*?"<>|]+)(.*)'
True

ur'\u0001(.*)([/\\:*?"<>|]+)(.*)' == u'' r'\u0001(.*)([/\\:*?"<>|]+)(.*)'
False
```

But you're not using Unicode literals anywhere.

**Comment by Utumno** [comment]
> use u'' r'long_\regex'

Good idea - please split your commit into one part with regexes that do not need this trick (include the `y\n -> y/n` fixup) and one that do and let's merge

Thanks!

**Comment by Infernio** [comment]
Related to #460.

**Comment by Infernio** [comment]
Merged it, thanks @syntaxaire 👍
