### ISSUE TITLE
Disable 'Empty Sublist Removal' by default

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#475]
The leveled list patcher has a feature that removes empty sublists from leveled lists.
This is intended to help with mods that accidentally added empty leveled lists to another leveled list, which can cause the leveled list to select nothing.

However, as Elminster pointed out on Discord, this can actually break mods. The problem is that some mods create empty leveled lists and fill them via scripts at runtime, and the patcher obviously can't distinguish between these two use cases.
For Skyrim and newer games, Papyrus exposes this functionality directly, while older games can do it via xSE (the `AddToLeveledList` function).
*Note: We're pretty much all in agreement that this is an absolutely awful idea that makes patching the mod in question a nightmare, but it's an established practice used by several very popular mods such as [Immersive Armors](https://www.nexusmods.com/skyrimspecialedition/mods/3479).*

The commit I made to fix this (65c75c852b790a8ac2cdfda6393f4295e594cfa1) currently disables it by default for all games and adds an option to enable it in the patcher GUI, but we might want to keep it enabled for Oblivion - I haven't really noticed any need for this part of the patcher with newer games, but Oblivion might be a different story.
Other options would be to enable the option by default or to remove the feature entirely.

**Comment by Utumno** [comment]
>  but we might want to keep it enabled for Oblivion

We should ask the users which would mean another game constant - too much of a hassle probably?

**Comment by Infernio** [comment]
I'm leaning towards just disabling it by default, I doubt it's very important these days.
Users who do want it can enable it, the checkbox is right there in the patcher GUI.

**Comment by Arthmoor** [comment]
I'd lean toward leaving it alone for Oblivion and do the new thing with newer games since Oblivion is primarily where this comes up as a problem. Yes, it may mean a new game constant or something but changing this is going to break expected behavior that's been ingrained for 12 years and counting.

**Comment by Infernio** [comment]
Left it enabled per default for Oblivion, disabled by default for everything else.
