### ISSUE TITLE
Feature Suggestion: Don't create "Mods" directories unless the installer tab is in use

### ISSUE THREAD

**Issue by Pickysaurus** [wrye-bash/wrye-bash#478]
Hey guys,

A bit of an OCD request here, but I'd prefer it if the app didn't create the "Skyrim Mods", "Skyrim SE Mods", etc folders in Steamapps\common unless I'm actually using Wyrebash as a mod manager (i.e. the Installer tab is active). 

It's by no means a priority or a "game breaking" problem, but it just bugs me to have to clean up those empty folders every so often.

Thanks for your time and all you do with Wyrebash :)

**Comment by Infernio** [comment]
Probably won't be considered until we're far into 308+, so placing on backburner for now.

**Comment by Utumno** [comment]
Yep - actually related to #178 - boot check for permissions create directories etc
