### ISSUE TITLE
CBash doesn't handle importing correctly when the NoMerge tag is involved

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#487]
Basically, if you have two or more `NoMerge`-tagged mods that are also tagged with another tag like `Stats`, the last override will not be considered *at all*.
For example, see this image (both mods are tagged `NoMerge, Stats`):

![CBash_NoMerge](https://user-images.githubusercontent.com/2845240/75285957-ddfc1a00-5817-11ea-8fc3-2321f522ea48.png)

PBash would not create an override in the BP here at all, which is the correct behavior. I'm not diving into CBash behavior until #312 is (at least close to) done though, so 308+. May also be the root cause of [these discrepancies](https://github.com/wrye-bash/wrye-bash/issues/400#issuecomment-591053279).

A few other random patcher issues to investigate - may or may not be linked: [SVN bug 216](https://sourceforge.net/p/oblivionworks/bugs/216/), [SVN bug 103](https://sourceforge.net/p/oblivionworks/bugs/103/) and [SVN bug 62](https://sourceforge.net/p/oblivionworks/bugs/62/).

[Originally from svn](https://sourceforge.net/p/oblivionworks/bugs/229/)

**Comment by Utumno** [comment]
Do you have a username in sourceforge @infernio? I could add you as an admin there :)

**Comment by Infernio** [comment]
I don't think I even have an account on sourceforge 😅

**Comment by Infernio** [comment]
Closing all CBash issues as `R-wont-fix` (#530).
