### ISSUE TITLE
A search bar on each tab

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#490]
Requested by @leandor [here](https://www.afkmods.com/index.php?/topic/4966-wrye-bash-all-games/page/83/&tab=comments#comment-176624).

Exactly what it says on the tin: a search bar that you can use to filter what appears on the tab, preferably with a small dropdown to the side of it you can use to filter out certain types of entries (some examples: only markers or hiding projects on the Installers Tab, only ESMs or no ESLs on the Mods tab, saves with no attached cosave on the Saves tab, etc.).

Prerequisites are #190 and at least enough BAIN refactoring to make it based on FileInfos (see #336).
Also not on 307, since I really don't want to bloat that milestone any more - we do have to release it at some point 😛.

**Comment by Infernio** [comment]
@Utumno If you hadn't seen it yet, @leandor posted on the AFK Mods thread, which is why I opened this issue: https://www.afkmods.com/index.php?/topic/4966-wrye-bash-all-games/page/83/&tab=comments#comment-176624

**Comment by Utumno** [comment]
See also https://discord.com/channels/537706885965676554/537708965942001685/974247707537469460

> we could add search switches like loose-files:yes - then rclick export package structure

**Comment by Infernio** [comment]
> preferably with a small dropdown to the side of it you can use to filter out certain types of entries (some examples: only markers or hiding projects on the Installers Tab, only ESMs or no ESLs on the Mods tab, saves with no attached cosave on the Saves tab, etc.).

From the issue description. I'd imagine those would end up just being aliases, so advanced users can type the filters directly while they remain discoverable in the dropdown for new users.

**Comment by suamor** [comment]
I asked https://www.afkmods.com/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=187236 about "space" key for unselecting a mod plugin. In the reply I was redirected to this page. When implementing this feature it would be great to have a shortcut to open the filter as I very often search for plugins or mod packages. Thank you.

**Comment by Infernio** [comment]
Sure, Ctrl+F should probably focus the search bar once it's added.

**Comment by Metallicow** [comment]
Yes, your request is actually possible, with enough work. Thank you for the inquiry.
