### ISSUE TITLE
Replace py2exe with PyInstaller

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#491]
Extracted from #415 so I can close that issue in the ganda-build-v2 merge.

Once we are on Python 3 - #460 - we should reconsider our options for building an EXE:

- [py2exe](https://github.com/py2exe/py2exe)
     - The unofficial fork with Python 3 support recently became official, py2exe now officially supports the latest py3 versions
     - API changed a lot and no up-to-date tutorials seem to exist
- PyInstaller
     - `pkgutils.iter_modules` ~~[is not supported](https://github.com/pyinstaller/pyinstaller/issues/1905)~~ **[is supported since 4.4 :tada:](https://github.com/pyinstaller/pyinstaller/pull/5959)**
     - Useful tool for inspecting PyInstaller archives: https://github.com/extremecoders-re/pyinstxtractor.git
- Nuitka
     - Nuitka compiles to a folder with many files, not appropriate
- cx_Freeze
     - This leaves the biggest mess I have ever seen in the output folder.
     - Has no option for single file output.
- [PyOxidizer](https://github.com/indygreg/PyOxidizer)
     - Still seems fairly immature and doesn't seem to have a onefile option(?)

Related to #460.

**Comment by Utumno** [comment]
300 stars wow - well py2exe seems like the best option still :)

**Comment by Infernio** [comment]
Okay, the new py2exe doesn't work at all with our `setup.py`. Looks like the entire API has changed - there's no more `py2exe.mf` and `py2exe.mf3` doesn't even have a `AddPackagePath`. Probably have to create a `ModuleFinder` object and call `add_packagepath` on it?

**Comment by Infernio** [comment]
Ganda's PyInstaller commit (5a00beefa941b33154e632459a66c79cf854dafb) builds a working EXE. Need to test if building a BP with it is still that slow.

**Comment by Infernio** [comment]
See 08947a8b968ebcdde4968ab70e45e6da3c1c3ab7.
