### ISSUE TITLE
Bash Tag to tell the BP to completely ignore a plugin for importing

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#495]
As it stands, the BP will import even from deactivated plugins, which sometimes surprises people. However, as I understand it, this is intended behavior - probably because doing it differently would complicate the merging / `Deactivate` / `Filter` handling too much?
A compromise might be to offer a bash tag that tells the BP to completely ignore a plugin's contents for importing, basically pretending that it doesn't even exist in the Data folder.

Needs thought as to how the details would work - e.g. what happens if another plugin has the ignored plugin as a master? Does it get imported, or will the ignore tag 'propagate' to all child plugins?
We should also do a thorough investigation of how each patcher reacts to disabled plugins and then decide what to do. In light of all these open questions, marking as a 308+ discussion rather than enhancement.

**Comment by Utumno** [comment]
It's the allowUnloaded for PBash essentially right?

**Comment by Infernio** [comment]
Something like that, my knowledge on this topic is too limited though, which is why I shoved it up to 308 :P

**Comment by Utumno** [comment]
I get eternally confused myself when I look at this one (unloaded mods and patch), but once the dust settles there shall be a bright light, where no bug can hide, config or patch phase, or otherwise, amen

I am still trying to wrap my brain around your tweaks refactoring :P

**Comment by Infernio** [comment]
> I am still trying to wrap my brain around your tweaks refactoring :P

Honestly, probably best to disregard the diff :P. Just read the new tweak files, starting from `MultiTweaker.scanModFile`, which implements pooling. Keep in mind also that refactoring isn't finished, the `buildPatch` overrides all essentially do the same thing now, so those will get replaced with a `tweak_record` method that just gets a record handed to it to implement the one line that is different in each tweak (the line that actually changes the record).

**Comment by Infernio** [comment]
Some preliminary investgation for another reported issue, this is PBash and `_SimpleImporter` only:
- Anything tagged counts as a source and the data that the tag wants will be gathered from it
- However, for the rest of the record to be forwarded, it must be active *or* merged

So in other words, an inactive mod with a tag results in something like this:

![BSGN](https://user-images.githubusercontent.com/2845240/78988831-48e88280-7b32-11ea-87fe-42a3dfcd0c61.png)

`New Mod.esp` is inactive. As you can see, the target of the `Text` I applied to it - the description - got forwarded, while the rest of the record was treated as if the plugin wasn't even there.

I *think* this is the intended behavior for disabled plugins. It makes the most sense at least - it allows tags like `Deactivate`/`Filter` to make sense and otherwise emulates the way the game does conflict resolution at runtime (i.e. ignoring inactive plugins).

**Comment by Infernio** [comment]
This is nonsense now that I actually understand the patcher. If you don't want a file included in the patch, simply deactivate it. If it has tags, imports will still happen - so just remove the tags in that case.
