### ISSUE TITLE
'Data Tab': View of data folder with source installers

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#50]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/203/)

Being able to browse Oblivion's whole data directory, with an indication for each file of which package it comes from, would be very useful for debugging an install with many mods. Ideally you'd be able to click on the package name and be taken to the correct one in the installers tab.
Use cases:
- you discover a huge texture in some overhaul that causes you memory issues, and you want to know which mod installed it.
- a menu xml file is giving you trouble; you know which one but you don't remember which of your 300 BAIN packages installed it.

Blocked on:
 - [ ] #529
 - [ ] #265

**Comment by Infernio** [comment]
On the backburner - great idea, but needs tons of work before it even becomes slightly viable (the #265 dependency is really a giant tree involving #336, #353 and BAIN refactoring).
