### ISSUE TITLE
NB

### ISSUE THREAD

**Issue by Metallicow** [wrye-bash/wrye-bash#505]
I shouldn't even be making this issue, but, some folks still don't know what an acronym is.
The problem lays where folk ask about this line lol "NB: the 32-bit version is required even if you are on a 64-bit operating system." on the frontpage README

The NB is in BOLD, but the rest is just a line statement.

To the noobs. just think of it as a kind away the internet censorship that happens everyday.
NB might be interpreted as "NO-BULLSHIT"
This simply means it is a rather strict rule for the following text.
"the 32-bit version is required even if you are on a 64-bit operating system."

... so in closing ... I'd like to say. GJKUTBD(That means 'Great Job Keep Up The Bad Work')

... continue on with acronyms which should be in wiki page or close this. Thanks.

**Comment by Infernio** [comment]
Added to `[dev] Acronyms` wiki page.
