### ISSUE TITLE
Remove Bloat in Savegame Oblivion

### ISSUE THREAD

**Issue by Gomstor** [wrye-bash/wrye-bash#506]
When I use the Remove Bloat option in a saved game I get this error window:

Traceback (most recent call last):
  File "bash\balt.pyo", line 1771, in __Execute
  File "bash\basher\saves_links.pyo", line 829, in Execute
  File "bash\bosh\_saves.pyo", line 305, in load
  File "bash\brec\mod_io.pyo", line 175, in unpack_header
AttributeError: 'file' object has no attribute 'unpack'

I am using version 307.202005011849 under the Oblivion game.

**Comment by Infernio** [comment]
Do you have a save with bloat you could upload? It always just spits out 'No bloating found' for all my saves.

**Comment by Utumno** [comment]
pushed a fix on nightly - 480-pt not even on dev yet

**Comment by Gomstor** [comment]
I just verified that this error only happens to me with saved games prior to the installation of this version of Wrye Bash. If I start a new game it does not report any error.

**Comment by Infernio** [comment]
@Gomstor Should be fixed in the new nightly (`307.202005012044`).

**Comment by Infernio** [comment]
@Utumno How do we even label this? Maybe we should have different regression labels, like `C-regression-dev` and `C-regression-nightly`?

**Comment by Utumno** [comment]
Yes was reluctant myself -and the winner is: invalid, as the change will disappear. A regression stays (unfortunately) in the dev's history, this kind of thing is better just be reported on the forums and be dealt with a fixup commit
