### ISSUE TITLE
Nehrim Support

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#514]
[The standalone release](https://store.steampowered.com/app/1014940/Nehrim_At_Fates_Edge/), that is. Should be straightforward.
May allow us to drop the terrible, half-baked support for the old version of Nehrim that we have right now.

**Comment by Infernio** [comment]
Nevermind, it's implemented in a really terrible way. The launcher takes your entire Oblivion installation and moves it to a backup folder, then moves the Nehrim files in there instead. If you want to play regular Oblivion again, you have to use the launcher and use a 'Switch to Oblivion' button, which will make it move the Nehrim files back into a Nehrim folder and the Oblivion backup files back into the Oblivion folder. Might be a workaround for some Oblivion bugs, who knows.

So if you want to manage this, you'll have to manually copy a Mopy folder into the `NehrimFiles` folder and manage it like any other Oblivion installation using the half-baked Nehrim support we have for the old total conversion version.

**Comment by Infernio** [comment]
Rejected, since I don't see a better way to manage this (doesn't even have a registry key).

**Comment by Arthmoor** [comment]
Shame this will only work on Steam copies too. Standard retail discs of the day and/or GoG copies are out of luck.

**Comment by XJDHDR** [comment]
I think the Steam version was just provided as a convenience for Steam users whereas non-Steam users can still use the original methods of installing it. It looks like achievements are the only addition for this release.

**Comment by Infernio** [comment]
Tentatively reopening, I think I've found a decent way to support this.

**Comment by Infernio** [comment]
Support is implemented on [inf-514-nehrim](https://github.com/wrye-bash/wrye-bash/tree/inf-514-nehrim), which is in nightly build `307.202006132332`.
Note that it does not let you manage both Oblivion and Nehrim at the same time (you *can* accomplish this, but only with command line arguments/manually moving the Mopy folder around), but instead 'hotswitches' the Bash Installers folder etc. that it uses, depending on whether it finds an `Oblivion.esm` or a `Nehrim.esm` in the Data folder.

**Comment by Infernio** [comment]
@Utumno got spooked after resolving all those conflicts and didn't want you to run through that without the necessary rereres, so insta-merged this.
