### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by Wolfstorm321** [wrye-bash/wrye-bash#517]
Is there a way to remove the splash screen? Perhaps some shortcut command? 
Wrye Bash is taking up to two minutes to load here, and I cant use my computer with the splash screen on top of everything.

**Comment by Infernio** [comment]
Make a copy of `bash_default.ini` called `bash.ini`. Then uncomment the `;bEnableSplashScreen=True` line and change it to False.

**Comment by Infernio** [comment]
> Wrye Bash is taking up to two minutes to load here

That reminds me, I should really polish up `xxx-inf-profile-sse-saves` and stick some of it on dev...

**Comment by Utumno** [comment]
> That reminds me, I should really polish up `xxx-inf-profile-sse-saves` and stick some of it on nightly...

Would be nice - I think we should reinstall @nycz 's method of parsing masters and use lz4 when we need to write those masters

**Comment by Wolfstorm321** [comment]
Thanks for the information.
