### ISSUE TITLE
Remove XML bbcode tag from various output.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#518]
In ancient times, before the war on BBCode began, various functions like "List Mods" or "List Bash Tags" would output their data along with spoiler and xml tags because it made the forum posts that use that data more readable.

Fast forward to 2020, and the XML tag being sent with this output is no longer useful anywhere, not even on Nexusmods. Most forum systems won't even parse the tag into anything. So it seems like it's probably time to remove that part of the output.

The spoiler tag can stay since most systems still recognize that one and it's useful to keep the lists from being insanely long.

**Comment by Infernio** [comment]
Was on my mind too :)
