### ISSUE TITLE
BAIN: Create a special package for vanilla files

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#52]
Basically, have BAIN setup a "Vanilla" package fixed at position 0 in the install order so it won't accidentally overwrite (and forever destroy) vanilla files.
Every time we are going to install a vanilla file, copy the original version into that package to preserve it. That way we don't have to break any BAIN rules to implement this (and can drop the Skip Bethsoft Content option).

Original svn issue description:
> If I'm not mistaken BAIN will happily overwrite vanilla Oblivion files, possibly leaving the user no choice but to reinstall Oblivion to say, go back to the vanilla music. Instead overwritten vanilla files should be moved to a special auto-managed installer (probably a folder, not a zip file) that always sits at position zero in the installers list. This way you can look at the conflicts tab to see which mods overwrite vanilla files, and annealing will restore vanilla files when overwriting mods are uninstalled.
>This package should work based on a fixed file list from a standard up-to-date Oblivion + all DLC install, to avoid copying random crap into it.
> When annealing, instead of copying files from the vanilla files package they should probably be moved out to save space, but provide an option to keep them for users that have loads of disk space and want to use the package as backup. Having them backed-up in there is useful in case you overwrite them manually or from OBMM and want to go back. Actually an option to import all vanilla files into the package would be interesting, maybe even as part of the Wrye Bash install process.

[Originally from svn](https://sourceforge.net/p/oblivionworks/enhancements/200/)

**Comment by Infernio** [comment]
On the backburner, BAIN is currently too much of a mess for this.
