### ISSUE TITLE
Deprecating CBash

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#520]
Since #516, PBash can now do everything CBash can - and thanks to #515 and #461, it can even do things CBash can't.

We're not planning to remove it, since
1. it is still faster
2. its Python-side code will probably come in handy if we ever get around to RBash (see https://github.com/wrye-bash/CBash/issues/27)

This issue is just here so it shows up in the final changelog for 307.

**Comment by Utumno** [comment]
> We're not planning to remove it

Well as it stands now probably not, although I would like to see it gone. If we could support a similar model for PBash and/or inject C or other C-speed code, and get as much inspiration from the CBash data model/business logic, then this has costed infinite maintenance, it's not linux friendly, causes code duplication, packs a dll that might cause even more problems if we move to another packaging solution and in general proved not a good idea

**Comment by Infernio** [comment]
One major source of pain is that we can't even update any record definitions without recompiling the DLL. Whatever we decide to go with as the successor to CBash, it should either be able to draw from our existing record definitions or should have autogenerated ones (either from ours or from xEdit's).

**Comment by Infernio** [comment]
Also, I'm not opposed to dropping CBash entirely if you feel that's a better solution. Again, its only advantage now is that it's faster (and removing it would *drastically* simplify patcher logic).

**Comment by Arthmoor** [comment]
Honestly I'm not sure we need to keep it around anymore. For reasons I can't recall now it was done solely to handle the complex records for merging purposes like LAND and PGRD in Oblivion. Since PBash is now handling this and patch generation time is somewhere between 90 seconds and 3 minutes I don't see much need to keep worrying about it.

Unless moving that code over to Rust ends up being significantly faster, the effort likely isn't worth it.

**Comment by Infernio** [comment]
I think we'll want a fresh start with an entirely different API if we do end up doing RBash. Namely, we want a runtime API that matches whatever we come up with after #312 and #480 are complete, plus maybe we'll eventually be rid of all that getattr/setattr nonsense and a much more pythonic and unified way of loading plugins (right now PBash has the whole LoadFactory/ModFile incantation, but CBash's ObCollection is even worse).

**Comment by XJDHDR** [comment]
Correct, one of the reasons behind CBash was because merging cell and worldspace edits using Python took a very long time.

**Comment by Infernio** [comment]
In any case, let's stash discussions of removing CBash until tweak pooling has landed. If we do want to go through with it, tweak pooling will make pulling out the CBash side of tweaks *much* easier.
Deprecating it is a quick 10-line change that we can do right now, and that's what this issue is about.

**Comment by LordNyriox** [comment]
@Infernio:  Well, you have successfully deprecated CBash in the more recent nightly builds. 

Any chance this issue will be closed (or relabeled for the next step of actual removal) soon?

**Comment by Infernio** [comment]
Issues are closed once the relevant commit lands on dev. 2c82b41efabff84b4b81f8fe2dd52616be3c232b is the commit that will close this issue, but it relies on `inf-509-510-usability`, which is mostly ready to merge except for the new settings menu not having any docs written yet.
