### ISSUE TITLE
Import Outfits

### ISSUE THREAD

**Issue by Wolfstorm321** [wrye-bash/wrye-bash#521]
I've made a mod which changes outfits for several npcs, but these outfits dont go into the bashed patch. 
I'm using the tags relev, delev, invent.add and invent.remove. But some outfits wont go into the bashed patch. According to xedit, only when there is a change in the name of the npc (made by another plugin, which uses the name and delev tags) is that the outfit is registered in the bashed patch. What am I doing wrong? Which are the correct tags for outfits? These outfits have two new levels of lists, so they need the relev and delev, but I'm not sure about the invent tags. Is a outfit considered as inventory? In CK they are in the same character tab.

**Comment by Infernio** [comment]
Import Inventory only patches inventories, i.e. `NPC_` and `CONT` records (plus `CREA` records in TES4/FO3/FNV). Expanding existing tags to cover new record types is generally not a great idea, I'd rather create a new Import Outfits patcher with its own dedicated tags.

**Comment by Wolfstorm321** [comment]
How do I create a import outfits patcher with Wrye Bash?

**Comment by Infernio** [comment]
You can't just create a new one, patchers are written in Python code. That comment was more of a note to myself, since I'm going to take this as a test to see how far I can refactor my new Import Inventory implementation.

**Comment by Infernio** [comment]
@Wolfstorm321 Try the [latest WIP build]( https://www.dropbox.com/sh/iazpayeexiyazeh/AAAbGeVHrlIksp2AFgI4w48Oa?dl=0&amp;lst=) (`307.202007232225`), it adds a new `Import Outfits` patcher with the tags `Outfits.Add` and `Outfits.Remove`.
