### ISSUE TITLE
Net.Framework run crash--Wyre Bash Oblivion

### ISSUE THREAD

**Issue by cesarcms** [wrye-bash/wrye-bash#523]
Hello, this error is similar to something that happened to other guys but in my case all the solutions that i tried didnt work for me.

**_Bug description_**
The problem started when i decided to unistall and reinstall Net.framework in my computer, becuase some problems that it had related to it. As result my wrye bash stopped to run and instead it showed this message:

![WryeIMG](https://user-images.githubusercontent.com/68985467/88888930-db598280-d204-11ea-86d7-00d014d2f938.JPG)

Idk if the image will upload because im new to this so i will put the text just in case:

```
Traceback (most recent call last):
  File "bash\bash.pyo", line 203, in main
  File "bash\bash.pyo", line 297, in _main
  File "bash\basher\__init__.pyo", line 4325, in InitSettings
  File "bash\bosh\__init__.pyo", line 3390, in initSettings
  File "bash\bosh\__init__.pyo", line 3374, in _load
  File "bash\bolt.pyo", line 1493, in __init__
  File "bash\bolt.pyo", line 1451, in load
AttributeError: 'str' object has no attribute 'append'
```

I tried to use the wip version and it dosent fix also i tried to unistall it and re install wyre bash and stills happening. Also i tried to install and unistall Net.framework and stills happening.

**_Wrye Bash Version_**

Standalone Wrye Bash exe ( WBSA ). (wip version for now, becuase i was trying to fix it).

**_Operating System_**

Windows 7 64 bits

My game is installed in  C:\Program Files (x86)\Bethesda Softworks\Oblivion (I know this may cause problems but i think its not because before having this bug wyre bash was running perfectly installed there)

**_Using bash ini?_**

No didnt knew that thing existed

Well i think thats all, i writed my issue on wrye bash discord and some guy said to put it here if i didnt find a solution, thing that happened.  I tried to follow the steps of bug reporting becuase so idk if i did it correctly because im new to this also i really want a solution to my wrye bash because it helped me a lot installing mods and not being able to use it makes me feel sad of how good it is.

Also i dont use MO2 only wyre bash :)

if its not understandable is because english is not my original langague.

**Comment by Infernio** [comment]
Please upload your `BashSettings.dat` file. You can find it in your `Documents\My Games\Oblivion` folder.

**Comment by Utumno** [comment]
Could you also produce a bugdump as described [here](https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug#the-bashbugdumplog)?

**Comment by cesarcms** [comment]
@Infernio sorry for the delay,  here is the BashSetings.dat: 

[BashSettings.zip](https://github.com/wrye-bash/wrye-bash/files/5003497/BashSettings.zip)

i made it a zip becuase i could not upload it normly, also i will paste all the content here just in case if the zip uploads incorrectly:

€UVDATA2q.€}q(U	boltPathsˆU_lords_pickle_versionKu.€}q(U_active_mods_lists}qU_current_list_indexK!U_saved_load_orders]q(cbash.load_order
lo_entry
qGA×¾Wf…cbash.load_order
LoadOrder
q)q}q(U
_loadOrderq(cbash.bolt
Path
q	)q
X   Oblivion.esmqbh	)qX   CM Partners.esmq
bh	)qX   CapesandCloaks.espqbh	)qX   DLCFrostcrag.espqbh	)qX   DLCSpellTomes.espqbh	)qX   DLCMehrunesRazor.espqbh	)qX   DLCShiveringIsles.espqbh	)qX
   DLCOrrery.espqbh	)qX   DLCThievesDen.espqbh	)qX   DLCVileLair.espqbh	)qX   DLCHorseArmor.espqbh	)q X   Knights.espq!bh	)q"X   CM Partners.espq#bh	)q$X   CM Partners NPC.espq%bh	)q&X   CM Partners NPC NE.espq'bh	)q(X   CM Partners More NPCs.espq)bh	)q*X   CM Partners More NPCs NE.espq+bh	)q,X   CM Partners Marker NPCs.espq-bh	)q.X   CM Partners Special NPCs.espq/bh	)q0X   DLCBattlehornCastle.espq1bh	)q2X   CM Partners Extra NPCs.espq3bh	)q4X   MidasSpells.espq5bh	)q6X   Immersive Interiors.espq7btq8U_activeOrderedq9(h
hhhhhhhhh h0tq:ub†q;hGA×¾Wj;÷Ïh)q<}q=(h(h
hhhhhhhhhhh h"h$h&h(h*h,h.h0h2h4h6h	)q>X   Bashed Patch, 0.espq?btq@h9(h
hhhhhhhhh h0tqAub†qBhGA×¾YfRJh)qC}qD(h(h	)qEX   Oblivion.esmqFbh	)qGX   CM Partners.esmqHbh	)qIX   CapesandCloaks.espqJbh	)qKX   DLCFrostcrag.espqLbh	)qMX   DLCSpellTomes.espqNbh	)qOX   DLCMehrunesRazor.espqPbh	)qQX   DLCShiveringIsles.espqRbh	)qSX
   DLCOrrery.espqTbh	)qUX   DLCThievesDen.espqVbh	)qWX   DLCVileLair.espqXbh	)qYX   DLCHorseArmor.espqZbh	)q[X   Knights.espq\bh	)q]X   CM Partners.espq^bh	)q_X   CM Partners NPC.espq`bh	)qaX   CM Partners NPC NE.espqbbh	)qcX   CM Partners More NPCs.espqdbh	)qeX   CM Partners More NPCs NE.espqfbh	)qgX   CM Partners Marker NPCs.espqhbh	)qiX   CM Partners Special NPCs.espqjbh	)qkX   DLCBattlehornCastle.espqlbh	)qmX   CM Partners Extra NPCs.espqnbh	)qoX   MidasSpells.espqpbh	)qqX   Immersive Interiors.espqrbh	)qsX   Bashed Patch, 0.espqtbtquh9(hEhKhMhOhQhShUhWhYh[hkhstqvub†qwhGA×¾Yf€  h)qx}qy(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstqzh9(hEhKhMhOhQhShUhWhYh[hktq{ub†q|hGA×¾Yh/²h)q}}q~(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstqh9(hEhKhMhOhQhShUhWhYh[hkhstq€ub†qhGA×¾Yh7Ph)q‚}qƒ(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq„h9(hEhKhMhOhQhShUhWhYh[hktq…ub†q†hGA×¾Yhº^5h)q‡}qˆ(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq‰h9(hEhKhMhOhQhShUhWhYh[hkhstqŠub†q‹hGA×¾Yj^5?h)qŒ}q(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstqŽh9(hEhKhMhOhQhShUhWhYh[hkhqhstqub†qhGA×¾YkÂ¬h)q‘}q’(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq“h9(hEhKhMhOhQhShUhWhYh[hkhohqhstq”ub†q•hGA×¾Yl	ë…h)q–}q—(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq˜h9(hEhGhKhMhOhQhShUhWhYh[hkhmhohqhstq™ub†qšhGA×¾Yn:\h)q›}qœ(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstqh9(hEhGhKhMhOhQhShUhWhYh[hihkhmhohqhstqžub†qŸhGA×¾Ynmh)q }q¡(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq¢h9(hEhGhKhMhOhQhShUhWhYh[hghihkhmhohqhstq£ub†q¤hGA×¾Yn”‹Dh)q¥}q¦(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq§h9(hEhGhKhMhOhQhShUhWhYh[hihkhmhohqhstq¨ub†q©hGA×¾YnÅ‘hh)qª}q«(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq¬h9(hEhGhKhMhOhQhShUhWhYh[hehihkhmhohqhstq­ub†q®hGA×¾YnïPh)q¯}q°(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq±h9(hEhGhKhMhOhQhShUhWhYh[hehghihkhmhohqhstq²ub†q³hGA×¾YoxÕh)q´}qµ(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq¶h9(hEhGhKhMhOhQhShUhWhYh[hchehghihkhmhohqhstq·ub†q¸hGA×¾Yo5ãTh)q¹}qº(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstq»h9(hEhGhKhMhOhQhShUhWhYh[hahchehghihkhmhohqhstq¼ub†q½hGA×¾YoZÐåh)q¾}q¿(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstqÀh9(hEhGhKhMhOhQhShUhWhYh[h_hahchehghihkhmhohqhstqÁub†qÂhGA×¾Yo|záh)qÃ}qÄ(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstqÅh9(hEhGhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstqÆub†qÇhGA×¾Yp*Ÿ¾h)qÈ}qÉ(h(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkhmhohqhstqÊh9(hEhGhIhKhMhOhQhShUhWhYh[h]h_hahchehghihkrter†q†h@X
   Launch Switch†q‡h@X   Launch Fraps†qˆh@X/   Interactive Map of Cyrodiil and Shivering Isles†q‰h@X   Launch LogitechKeyboard†qŠh@X   Launch MediaMonkey†q‹h@X   Launch Notepad++†qŒh@X   Launch Steam†qh@X   Launch EVGA Precision†qŽh@X   Launch WinMerge†qh@X   Launch FreeMind†qh@X   Launch Freeplane†q‘h@X   Launch FileZilla†q’h@X   Launch Egg Translator†q“h@X   Launch RAD Video Tools†q”h@X   Launch WinSnap†q•X
   DocBrowserq–X
   ModCheckerq—X   Settingsq˜X   Helpq™eX   bash.wizard.posMäK¿†qšX%   bash.saves.details.subSplitterSashPosKQUbash.mods.details.colReverse}q›(h)‰h,ˆuu.

**Comment by cesarcms** [comment]
@Utumno i did the installed version of bugdump and this window was shown:
![Wryebash Captura](https://user-images.githubusercontent.com/68985467/88968659-3d51d080-d275-11ea-972b-531cee273265.JPG)

i went to Wryebash Archives 
(Mopy files) and pressed the blocknote that said 
BashBugDump, idk which one is the usefull one but her it is:

[BashBugDump.log](https://github.com/wrye-bash/wrye-bash/files/5003577/BashBugDump.log)

This one has more code than the other one.

**Comment by Infernio** [comment]
@Utumno Error with the pure Python pickle instead of cPickle:
```
Traceback (most recent call last):
  File "bash\bash.py", line 249, in main
    _main(opts, wx_locale)
  File "bash\bash.py", line 343, in _main
    basher.InitSettings()
  File "bash\basher\__init__.py", line 4325, in InitSettings
    bosh.initSettings()
  File "bash\bosh\__init__.py", line 3390, in initSettings
    bass.settings = _load()
  File "bash\bosh\__init__.py", line 3374, in _load
    bolt.PickleDict(dirs[u'saveBase'].join(dat_file), readOnly))
  File "bash\bolt.py", line 1493, in __init__
    res = dictFile.load()
  File "bash\bolt.py", line 1451, in load
    self.data.update(pickle.load(ins))
  File "C:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 1195, in load_appends
    list.extend(stack[mark + 1:])
AttributeError: 'str' object has no attribute 'extend'
```

**Comment by cesarcms** [comment]
ok, any news about how to solve this issue?

**Comment by Infernio** [comment]
The settings file is definitely broken somehow. I'm not an expert on pickling by any means, so I'm waiting to see if @Utumno has any idea.

In the meantime, you can try to restore the backup. Delete `BashSettings.dat` and rename `BashSettings.dat.bak` to `BashSettings.dat`, then try launching again.

**Comment by cesarcms** [comment]
@Infernio i deleted the BashSettings.dat, replaced it and it worked. For the moment it runs perfectly if there is other issues related to this problem in the future i will post it here, also thanks for the help now i can install mods correctly.

**Comment by Infernio** [comment]
Glad to hear it. I'll close this issue then, feel free to reopen it if you can reproduce this again.
