### ISSUE TITLE
Problems with .CSV Files in Oblivion

### ISSUE THREAD

**Issue by Gomstor** [wrye-bash/wrye-bash#526]
I have a problem with the latest versions of Wrye Bash in Oblivion. When I use any .csv file in the Bash Patch I get this error:

MERGE / SCAN ERROR: Oblivion.esm
Traceback (most recent call last):
  File "bash \ gui \ events.pyo", line 166, in _post
  File "bash \ balt.pyo", line 890, in _conversation_wrapper
  File "bash \ basher \ patcher_dialog.pyo", line 201, in PatchExecute
  File "bash \ patcher \ patch_files.pyo", line 248, in scanLoadMods
  File "bash \ patcher \ base.pyo", line 79, in scan_mod_file
  File "bash \ patcher \ patchers \ preservers.pyo", line 240, in scanModFile
AttributeError: 'tuple' object has no attribute 'iteritems'

Assuming that the .csv file appears within its category, because in some it has disappeared as in the "Morph Factions" category for example. This is the BashBugDump.log file:

localize.pyo 85 setup_locale: No translation file for language 'Spanish', falling back to English
localize.pyo 88 setup_locale: Set wx locale to 'Spanish' (en_GB)
localize.pyo 96 setup_locale: Set Wrye Bash locale to 'English'
bash.pyo 223 dump_environment: Using Wrye Bash Version 307.202008041828 (Standalone)
bash.pyo 223 dump_environment: OS info: Windows-10-10.0.19041, running on Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
bash.pyo 223 dump_environment: Python version: 2.7.18 (v2.7.18: 8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]
bash.pyo 223 dump_environment: wxPython version: 4.0.7.post2 msw (phoenix) wxWidgets 3.0.5
bash.pyo 223 dump_environment: python-lz4 version: 2.2.1; bundled LZ4 version: 1.9.2
bash.pyo 223 dump_environment: pyyaml ​​version: 5.3.1
bash.pyo 223 dump_environment: Input encoding: None; output encoding: None
bash.pyo 223 dump_environment: Filesystem encoding: mbcs
bash.pyo 223 dump_environment: Command line: ['C: \\ Gomstor Go \\ Oblivion \\ Mopy \\ Wrye Bash.exe', '-d']
bash.pyo 223 dump_environment: Using scandir v1.10.0
bash.pyo 448 _import_bush_and_set_game: Searching for game to manage:
bush.pyo 80 _supportedGames: The following games are supported by this version of Wrye Bash:
bush.pyo 83 _supportedGames: Enderal, Fallout 3, Fallout 4, Fallout 4 VR, Fallout New Vegas,
bush.pyo 83 _supportedGames: Morrowind, Nehrim, Oblivion, Skyrim, Skyrim Special Edition, Skyrim VR
bush.pyo 85 _supportedGames: The following installed games were found via Windows Registry:
bush.pyo 87 _supportedGames: Oblivion: c: \ gomstor go \ oblivion
bush.pyo 144 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyo 150 _detectGames: Set game mode to Oblivion found in parent directory of Mopy: C: \ Gomstor Go \ Oblivion
bush.pyo 165 __setGame: Using Oblivion game: C: \ Gomstor Go \ Oblivion
loot_parser.pyo 46 <module>: Using LibYAML-based parser
mods_metadata.pyo 48 __init__: Initialized loot_parser, compatible with libloot v0.15.x
__init __. pyo 3353 initBosh: Looking for main game INI at C: \ Users \ Gomstor Go \ OneDrive \ Documents \ My Games \ Oblivion \ Oblivion.ini
testing UAC
__init __. pyo 1302 _initDB: Initializing BSAInfos
__init __. pyo 1303 _initDB: store_dir: C: \ Gomstor Go \ Oblivion \ Data
__init __. pyo 1304 _initDB: bash_dir: C: \ Gomstor Go \ Oblivion Mods \ Bash Mod Data \ BSA Data
__init __. pyo 1311 _initDB: Successfully initialized BSAInfos
__init __. pyo 1302 _initDB: Initializing ModInfos
__init __. pyo 1303 _initDB: store_dir: C: \ Gomstor Go \ Oblivion \ Data
__init __. pyo 1304 _initDB: bash_dir: C: \ Gomstor Go \ Oblivion Mods \ Bash Mod Data
__init __. pyo 1311 _initDB: Successfully initialized ModInfos
__init __. pyo 1302 _initDB: Initializing SaveInfos
__init __. pyo 1303 _initDB: store_dir: C: \ Users \ Gomstor Go \ OneDrive \ Documents \ My Games \ Oblivion \ Saves
__init __. pyo 1304 _initDB: bash_dir: C: \ Users \ Gomstor Go \ OneDrive \ Documents \ My Games \ Oblivion \ Saves \ Bash
__init __. pyo 1311 _initDB: Successfully initialized SaveInfos
__init __. pyo 1302 _initDB: Initializing INIInfos
__init __. pyo 1303 _initDB: store_dir: C: \ Gomstor Go \ Oblivion \ Data \ INI Tweaks
__init __. pyo 1304 _initDB: bash_dir: C: \ Gomstor Go \ Oblivion Mods \ Bash Mod Data \ INI Data
__init __. pyo 1311 _initDB: Successfully initialized INIInfos
__init __. pyo 1302 _initDB: Initializing ScreenInfos
__init __. pyo 1303 _initDB: store_dir: C: \ Gomstor Go \ Oblivion
__init __. pyo 1304 _initDB: bash_dir: C: \ Gomstor Go \ Oblivion Mods \ Bash Mod Data \ Screenshot Data
__init __. pyo 1311 _initDB: Successfully initialized ScreenInfos
MERGE / SCAN ERROR: Oblivion.esm
patcher_dialog.pyo 293 PatchExecute: Exception during Bashed Patch building:
Traceback (most recent call last):
  File "bash \ basher \ patcher_dialog.pyo", line 201, in PatchExecute
  File "bash \ patcher \ patch_files.pyo", line 248, in scanLoadMods
  File "bash \ patcher \ base.pyo", line 79, in scan_mod_file
  File "bash \ patcher \ patchers \ preservers.pyo", line 240, in scanModFile
AttributeError: 'tuple' object has no attribute 'iteritems'

Traceback (most recent call last):
  File "bas

**Comment by Infernio** [comment]
Which CSV files does this happen with? Try to reduce it down to just one file and provide a link.

**Comment by Gomstor** [comment]
Practically whenever I include a CSV file within the Bash Patch options. Specifically, the error happens to me when importing the names of the CSV files in the "Import Names" section, but the rest of the CSV files do not appear in their respective sections.

**Comment by Infernio** [comment]
Nightly-only regression, will be fixed in the next nightly.
