### ISSUE TITLE
Jump from Mod List to the Installer that installed a mod

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#53]
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/199/)

The names in the "installer" column in the mods tab should be hyperlinks that lead you to the corresponding BAIN package on the installers tab. If technically difficult, a context menu option that does the same would be useful as well.

**Comment by Utumno** [comment]
See: [wxPython: How to Programmatically Change wx.Notebook Pages](http://www.blog.pythonlibrary.org/2012/07/18/wxpython-how-to-programmatically-change-wx-notebook-pages/)

Hyperlinks would be grand but no clue how to go about that
