### ISSUE TITLE
Removing CBash

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#530]
The next step after #520. Blocked on at least `inf-312-tweak-pooling`, because I've already put the work in and am *not* going to resolve conflicts with all those CBash tweaks.

However, I'm concerned about releasing 307 without CBash. If we do that, the last CBash release that will be available in an archived WB release will be v0.6 in [306](https://github.com/wrye-bash/wrye-bash/releases/tag/v306). So marking as 308 and discussion for now, though I guess this is related to #260 as well.

**Comment by Arthmoor** [comment]
I agree that we should wait on the actual removal for 308. The usual process for deprecating anything is to do so in one release, which in our case would be 307 proper, and then proceed with removal in some following release later on. Probably 308 for us.

I don't think it would be correct procedure to both deprecate AND remove something as major as CBash within a single release cycle since we'd be giving the general userbase no fair warning that it's coming.

**Comment by Metallicow** [comment]
I just hope you all have optimized it enough in the refactorings that a pbash patch **doesn't take 15 min** compared to a **1 min cbash patch** lol.  That was kinda one of the big issues when cbash was originally written...

**Comment by Arthmoor** [comment]
I've been putting it through paces with my Oblivion install. I had it generate one in around 2 minutes. So it's definitely better than it was in the past. Although it does seem to vary in runtime for some reason. I've had it done in as little as 90 seconds and as long as 4 minutes. No idea why, but either way that's still not 15+

**Comment by Metallicow** [comment]
Usually as far as deprecating something goes, yes there should be a release stating it will be removed at some point in a future release. This statement should go into the main changelogs that **users** will see/read when updating.
So yea, removing cbash according to standard procedure would be in 308 or 309 at earliest.
Some projects update frequently and others don't... so it depends on how many features and testing is done in a version before RELz. 6mo-1yr is a normal stable standard, but projects like blender do one every 3 months nowadays and firefox and chrome have jumped off the stable standard and choose the bleeding edge standard now which is like every month.
... so it depends really. I think 3-6 month between releases is fine as long as they can maintain the stable standard with the manpower the project has for developers.
... and of course many projects just tell ya, "It'll be released when its ready"
