### ISSUE TITLE
Changing license to GPLv3 (or later)

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#531]
~~We're on GPLv2 right now~~ - Actually, the situation is more complex, see comments below - and several things we'd like to use are incompatible with that:
 - Ganda's [pynxm](https://github.com/GandaG/pynxm), which we're hoping to fork, edit and then merge into our codebase under #459, is licensed under Apache 2.0 - which is compatible with GPLv3, but [incompatible with GPLv2](https://www.gnu.org/licenses/license-list.html#apache2) (due to the patent termination clause).
 - [PyMuPDF](https://pypi.org/project/PyMuPDF/) is licensed under the GPLv3, and the library it wraps (MuPDF) is AGPLv3. See also their [license note](https://github.com/pymupdf/PyMuPDF#license).

Now, *technically* we would not actually be violating any licenses if we start using these, because thankfully our license is GPLv2 *or later* (see the `or (at your option) any later version.` notes in **all** our source files). This is also the only reason why we can even do this license change without having to contact every previous contributor to either ask them for permission or to strip out their contributions.

See this blog post for more information on the 'or later' clause: https://hritcu.wordpress.com/2007/01/06/gplv2-or-later/

**Comment by Infernio** [comment]
@Utumno Had another look, and we actually have to license under GPLv3 already. Reason is TaskDialog in windows.py:

https://github.com/wrye-bash/wrye-bash/blob/b25727b6ba2210289aa77a6c4ad288af74c55ae5/Mopy/bash/windows.py#L12-L17

So every release we distribute is effectively GPLv3 already because of that code. WB doesn't run without it, so it is a necessary dependency for us, which means we fall under the intersection of 'I want to license my code under: GPLv2 or later' and 'I want to copy code under: GPLv3' in the GPL compatibility matrix (https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility).
As that section shows, the result is 'OK: Combination is under GPLv3 [[3]](https://www.gnu.org/licenses/gpl-faq.en.html#compat-matrix-footnote-3)'.

So 'changing' the license to GPLv3 really isn't a change, just making it clear for users that they actually have to obey the GPLv3 (I doubt anyone dug this deep to look at WB's licensing before, which is exactly why we should make it clear that we're on GPLv3 and that users have to obey that license).

**Comment by Utumno** [comment]
Good catch - I leave this up to you :)

**Comment by Infernio** [comment]
`C-enhancement` so it shows up on the changelog. Maybe we should do this differently? Rust has a special `relnotes` tag which is what they use to decide which issues will get included in the release notes for a version.

**Comment by Utumno** [comment]
Could do - thanks for merging all this (and fixing the masterlist_dir typo in my rebase)

wow, a new codebase :)

**Comment by LordNyriox** [comment]
@Infernio:  While I was working on the "GBRPlus Patched ESM" support we were discussing over at [<https://github.com/wrye-bash/wrye-bash/issues/400#issuecomment-714537194>], I noticed an oversight in [<https://github.com/wrye-bash/wrye-bash/commit/372166874faa49ea1d4c0f3b473f7f3afbe068af>]. 

Specifically, the "license" badge in [Readme.md](https://github.com/wrye-bash/wrye-bash/blob/dev/Readme.md) still points to the old license version and file. 

I went ahead and created a [fixup commit](https://github.com/LordNyriox/wrye-bash/commit/fbbfd9fe790adb7d9c34cbb1770641ece08ab465) for you to merge into dev whenever you are ready. 

[<https://github.com/LordNyriox/wrye-bash/commit/fbbfd9fe790adb7d9c34cbb1770641ece08ab465>]
