### ISSUE TITLE
OBMM-style shader support

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#536]
More 'OBMM things WB can't do'.

Turns out OBMM was FOSS (GPL/LGPL), source code is available on the Nexus page: https://www.nexusmods.com/oblivion/mods/2097?tab=files
Should be something usable in there.

**Comment by lojack5** [comment]
At one point I had some python code that could edit Oblivion shader packages. I'll see if I can find it for reference if you like.

**Comment by Infernio** [comment]
Feel free to upload it to github or gist and link it here if you find it - more references can't hurt :)

**Comment by lojack5** [comment]
It was pretty messy, so I cleaned up variable names, commented, etc.  Put it in a repo for reference (python 3):
[oblivionsdp](https://github.com/lojack5/oblivionsdp)

**Comment by Infernio** [comment]
Thanks! I forked it into the wrye-bash repo, no worries.
