### ISSUE TITLE
Wyre bash error (wxpython stdout/stderr): Pulling out hair!

### ISSUE THREAD

**Issue by TheNaSMaX** [wrye-bash/wrye-bash#538]
Getting this message with wyrebash starting today. I've already reinstalled twice with no luck. I have zero experience with python so this is all greek to me. I can say that I uninstalled the heritage mod and ran it again and it just said something similar with another mod. I can also say that I've had heritage installed for several months now with no issue.

MERGE/SCAN ERROR: Heritage.esp

Traceback (most recent call last):

File "bash\gui\events.pyo", line 166, in _post

File "bash\balt.pyo", line 887, in _conversation_wrapper

File "bash\basher\patcher_dialog.pyo", line 201, in PatchExecute

File "bash\patcher\patch_files.pyo", line 248, in scanLoadMods

File "bash\patcher\base.pyo", line 79, in scan_mod_file

File "bash\patcher\patchers\special.pyo", line 578, in scanModFile

File "bash\brec\record_structs.pyo", line 344, in getTypeCopy

File "copy.pyo", line 190, in deepcopy

File "copy.pyo", line 334, in _reconstruct

File "copy.pyo", line 163, in deepcopy

File "copy.pyo", line 237, in _deepcopy_tuple

File "copy.pyo", line 163, in deepcopy

File "copy.pyo", line 257, in _deepcopy_dict

File "copy.pyo", line 193, in deepcopy

File "copy.pyo", line 278, in _keep_alive

MemoryError

Ok, I have recently installed a few new orc themed mods but I've done that before and I can't see them causing this issue.

**Comment by Metallicow** [comment]
Well the error says you ran out of memory. Does this mod have a ton of very large textures?

**Comment by Infernio** [comment]
@TheNaSMaX The error tells you what's wrong, you ran out of memory. Try using the WIP builds, which are 64bit: https://www.dropbox.com/sh/iazpayeexiyazeh/AAAbGeVHrlIksp2AFgI4w48Oa?dl=0

**Comment by TheNaSMaX** [comment]
It shouldn't, its basically a mod renaming enemies and giving them not "orders". Also I have about 32gb of RAM so how did I run out of memory?

**Comment by Infernio** [comment]
Because the Nexus version of Wrye Bash is a 32bit program. 32bit programs can only use ~2GB of RAM, no matter how much RAM you have.

**Comment by TheNaSMaX** [comment]
I'm going to try what you have suggested Infernio and try the 64bit version.

**Comment by Metallicow** [comment]
Well its actually somewhere inbetween 2-4GB with Oblivion on XP box. I think around 3ish was used but the excess can be used by other stuff. Sometimes there is a 4GB patch that allows it to access that much with certain 32bit games.
But yea if you have a 64 bit OS, then by all means use it, otherwise you will end up like all other players/modders and hit your limits real fast.

**Comment by XJDHDR** [comment]
> Well its actually somewhere inbetween 2-4GB with Oblivion on XP box. I think around 3ish was used but the excess can be used by other stuff. Sometimes there is a 4GB patch that allows it to access that much with certain 32bit games.

The limit for 32-bit programs is always 2GB unless they have been flagged as Large Address Aware, which I highly doubt is the case for either Python or WB's standalone EXEs. If the flag is set, the limit becomes 3GB on 32-bit OSs and 4GB on 64-bit.

**Comment by Metallicow** [comment]
Yes large address is 3-4 for program, I meant that XP32 would only use like 2.7 if you had 4gb but the large address patch for oblivion allowed more for that game. And yes, you can set the flag if you build your own exes with pyinstaller. I whipped up a utility a while ago but unless anyone here has maintained it then it is likely long out of date. I just maintain my own pyinstaller utility for my code editor nowadays. I click a single button and it builds live while the program is running.

**Comment by Infernio** [comment]
This has gotten off-topic - don't make me lock the issue 😉

**Comment by Infernio** [comment]
Obsolete as of 308 (64bit upgrade).
