### ISSUE TITLE
Central place for showing warnings

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#542]
Right now we just pop up `ListBoxes` whenever we want to display a warning.
This has some significant downsides:
 - Once the user clicks OK, it's gone for good. You often have to restart if you accidentally dismissed a warning.
 - The popup is buggy and often doesn't size correctly.
 - On the implementation side, there is no common framework for this. The warnings are all handled inside one giant method that gets called in random places.

A better idea might be having, say, a button with a notification bell icon in the GUI.
Once a warning comes in, we could change its icon to a warning sign (and maybe show a small notification bubble beneath it or even play a sound?).
Then once the user clicks the button, it expands into a dropdown listing all the warnings that they have not reacted to yet.

One risk might be users just ignoring this button though. Will have to do some prototyping here at some point.

**Comment by Infernio** [comment]
On the backburner, just a random idea I had.

**Comment by Utumno** [comment]
The internal part is addressed - the GUI part could be under discussion (for WB 400 given the number of devs) so I am removing this from the backburner
