### ISSUE TITLE
Skyrim VR INI file should be called SkyrimVR.ini

### ISSUE THREAD

**Issue by Timboman** [wrye-bash/wrye-bash#549]
Version: Wrye Bash 308.202011271602

Booted Wrye Bash through MO2 for Skyrim VR and selected Skyrim VR as the game during initial boot popup gets you this error.
![image](https://user-images.githubusercontent.com/36910038/100522081-3335d500-3176-11eb-871d-d1afdedbf079.png)

If I goto the location specified in the error and CREATE a "skyrim.ini" file by copying over my profile specific "skyrimvr.ini" file and then renaming it Wrye Bash boots correctly.

In situations where MO2 profile specific ini's are enabled the ini will NEVER be in this location, and specifically Skyrim VR will never create a "skyrim.ini" file but instead a "skyrimvr.ini" file either way. 

This should be addressed in the next Nightly Build

**Comment by Infernio** [comment]
Does the vanilla game launcher create the `SkyrimVR.ini`, or just MO2?

**Comment by Timboman** [comment]
Yes the vanilla version does create it as skyrimvr.ini

**Comment by Infernio** [comment]
Alright, thanks. We can't test Skyrim VR (which is why it's not documented anywhere yet), so people reporting issues like this is very important.

**Comment by Infernio** [comment]
Is there also a `SkyrimVRPrefs.ini` or `SkyrimPrefs.ini` in the My Games folder?

**Comment by Timboman** [comment]
That is just called SkyrimPrefs.ini even for VR

Tho like I said, in some cases neither may exist there if the game has only ever been fully booted via a profile specific MO2 instance.
Tho I'd have to ask the MO2 team how that's being handled exactly.

**Comment by Infernio** [comment]
That should be fine. One more thing - in the game folder, is there a `Skyrim_default.ini`? I looked over the SteamDB depots, and it seems like there should only be a `Skyrim.ini` there, is that correct?

**Comment by Timboman** [comment]
Here's a screenshot of my game folder, I obviously have files in there at this point beyond the scope of the vanilla install (SKSE, ENB, DLL Loaders etc) but it should otherwise be fairly representative.
![image](https://user-images.githubusercontent.com/36910038/100522985-d4bf2580-317a-11eb-8887-8d7960bfad6b.png)

**Comment by Infernio** [comment]
Thanks for the info, that was very helpful 👍

**Comment by Infernio** [comment]
Should be fixed in `308.202011281815`.

**Comment by Timboman** [comment]
Yup can confirm it's working now, with or without skyrim.ini skyrimvr.ini or skyrimprefs.ini at the \Documents\My Games\Skyrim VR\ location now.

Thanks!

**Comment by Infernio** [comment]
Great. I'll close this issue when I merge the fix.
