### ISSUE TITLE
More useful 'New Mod' menu

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#550]
It would be really nice if that command could become more powerful, e.g. being able to create not just ESPs but also ESLs. So:

- [ ] Replace the moldy old link with a new popup allowing you to:
  - [ ] Change the extension (.esp, .esm, etc. as supported by the game)
  - [ ] Change the name (not just 'New Mod')
  - [ ] Enable or disable the ESM and ESL flags (except for .esl and .esm files, obviously)
  - [ ] Pick any masters from the current load order (not just the game master or no masters)

Probably don't need text fields/areas for author/description, since one can easily adjust that on the Mods tab later.

**Comment by Utumno** [comment]
> Probably don't need text fields/areas for author/description, since one can easily adjust that on the Mods tab later.

Yep plus this code is about to change

**Comment by Infernio** [comment]
![image](https://user-images.githubusercontent.com/2845240/100904971-da44a480-34c7-11eb-9148-cc0f846b8d58.png)
