### ISSUE TITLE
Oblivion save game reload error

### ISSUE THREAD

**Issue by Gomstor** [wrye-bash/wrye-bash#559]
With version 308.202012021819 the error that I am going to explain does not occur, but in later versions it does.

When I generate the Bashpatch in Oblivion everything is fine, but when I reload a game, that is, I load a game after loading for the first time, the game does CTD. With the previously mentioned version it does not happen. No matter what options I choose in Bashpatch, my game does CTD when reloading a save game.

**Comment by Infernio** [comment]
We need more info than this, as the issue template that you deleted tells you.
Most notably a BashBugDump and a minimal reproducer (uncheck patchers until you can isolate the one that's causing it, then uncheck mods in that patcher until you figure out which mod(s) are causing it).

**Comment by Infernio** [comment]
Also, this should have gone on Discord/AFKMods first, as
1. the readme,
2. the github issue chooser and
3. the issue template

told you.
