### ISSUE TITLE
problems with mismatches bsa files

### ISSUE THREAD

**Issue by calielmax** [wrye-bash/wrye-bash#560]
i'm having some issues on trying to install mods on Skyrim Legendary edition. I download some mods on Nexusmod and i assured that it was the correct version but when i try to open it just dont open, i think it calls CTD. I openned the wrye bash and it says that the bsa arquives is mismatched. I dont know what to do. Just a couple of mods can open

**Comment by Infernio** [comment]
To fix the warning, unpack the BSA using something like [BAE](https://www.nexusmods.com/fallout4/mods/78/), then repack it using Archive.exe which comes with the CK.
There is no guarantee that this will fix your CTDs, and we can't help you with that anyways.

**Comment by Infernio** [comment]
Also, this should have gone on Discord/AFKMods first, as
1. the readme,
2. the github issue chooser and
3. the issue template

told you.
