### ISSUE TITLE
Add 'Mark All Water As Damaging' assorted tweak

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#564]
Useful for needs mods that make use of this flag. Instead of manually having to patch every single type of water to add this flag, we can do it with a simple tweak.
Thanks tweak pooling :)

**Comment by Infernio** [comment]
Closed in e1f77fb4333c4b7c60983d0bf8cb62fc410c02b2.

**Comment by VariableReferee** [comment]
Such a simple change with a HUGE impact for all of us RnD/iNEED users. Now I can get rid of my zedit patcher for that.
