### ISSUE TITLE
Don't restore scroll positions by default

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#566]
Takes up way too much of the boot process with even just semi-large load orders (>200 plugins/saves can take ~0.5s, >400 plugins/saves can take ~1.0s).

It's disabled by default now for a much faster boot, but if you want it back, the setting is in `Settings > Global Settings... > General > Restore Scroll Positions on Start`.

**Comment by Infernio** [comment]
*Issue is here so that it shows up on the version history, since it's a noticeable behavior change.*

**Comment by Utumno** [comment]
I remember this yes, from timings in revered wx2.7.12.smth - essentially the problem is the control (?) so probably boils down to #255

**Comment by Infernio** [comment]
It's because the way to scroll to a specific item is via [ScrollLines](https://wxpython.org/Phoenix/docs/html/wx.Window.html#wx.Window.ScrollLines), which literally visually scrolls down the ListCtrl. That can take >= 1s for large load orders/many saves.
If there was a way to just immediately jump to a position, that would probably fix the problem nicely - at that point we could simply change the default, so for now I think this is an acceptable workaround.
