### ISSUE TITLE
Add 'Troubleshoot Bashed Patch' command

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#568]
Bisecting seems to be a really hard concept to grasp for users. I think we can help here with an option to bisect the BP.
Overlaps with #554 and #312 since we'll basically need headless/programmatic BP building for this.

1. Untick half of all patchers, then rebuild the patch. Check if the issue still happens. If not, repeat with the other half instead.
2. Take the half that still causes the issue and split it in half, repeat step 1 with that half.
3. Repeat steps 1 and 2 until you've whittled it down to a single patcher.
4. Now do the same thing you just did with the sources on the right: uncheck half, rebuild, try ingame, etc. until you've got it down to a single mod that's causing the issue.

At each step, we'll launch the game and show the user a prompt with thumbs up/down buttons.
All 'unticking' will of course be done programmatically, the only interaction the user would have to do is check if the problem still occurs ingame and then click one of the buttons.

**Comment by Utumno** [comment]
Great idea - we should definitely not name it bisect though - maybe hmmm "Anneal" ? :D

"Troubleshoot patch"?

**Comment by Infernio** [comment]
Troubleshoot is a great name :)
