### ISSUE TITLE
Unified Package Creator

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#574]
A way to package a mod from within Wrye Bash, so that it ends up in a BAIN-friendly layout with both a BAIN wizard and an XML FOMOD that do the same things included.

This ensures maximum compatibility with mod managers:
- [Vortex](https://github.com/Nexus-Mods/Vortex): Supports both BAIN layouts and FOMODs
- [NMM](https://github.com/Nexus-Mods/Nexus-Mod-Manager): Supports FOMODs
- [MO2](https://github.com/ModOrganizer2/modorganizer): Supports all three types (wizards are still experimental though)
- [Kortex](https://github.com/KerberX/Kortex-Mod-Manager): Supports FOMODs
- Wrye Bash: Supports all three types

This is obviously a really far out goal, so put it on 310.

**Comment by lojack5** [comment]
Just curious, with a brief scan through MO2 source I wasn't sure where to find Wrye Bash wizard support.  Which source file should I start in to look at it?

Also, to get a *truely* unified installer format, I'm not sure how hard that would be with existing formats, but if it's not feasable then you could try getting devs of WB, MOD2, Vortex, etc together on a chat (like we did with `loadorder.txt` to agree on a common format to use.  Like agreeing that everyone would put installer scripts inside a subfolder called `install_script` or something, so if the installer supports BAIN it'd have a `install_script/wizard.txt`, if it supports FOMOD those files would be in `install_script` as well, etc.

**Comment by Infernio** [comment]
The hard (probably impossible) part would be getting mod authors to start using a new format. You would likely need something like a Nexus-side block on new uploads not in this format.
