### ISSUE TITLE
Move patch related structures to a GameInfo mixin

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#584]
GameInfo starts accumulating patcher related structures - this won't scale for other games especially non beth games. I suggest to:

- move patcher related constants out of constants and into patcher/ - keep constants for lists of files and the like (or eliminate depending on what remains)
- create a PatchGame(GameInfo) (?) class that takes care in its init to dynamically import the patcher module - remove this from GameInfo and indeed place a new file game/_patch_game.py
- have our current (beth) games inherit from PatchGame and call super init - move handling of per game patchers there

**Comment by Utumno** [comment]
Working on it

**Comment by Utumno** [comment]
Here @Infernio https://github.com/wrye-bash/wrye-bash/compare/1129f1bb2e4a1dccfcfe59e992c27d0e0d7f049f...4ebf5858466fb711d50a5aa66f7ccf0a674ccfa1 - kept separate to review. You have been working with patcher constants a lot as of late - so you might want to include some more (ex!) constants there. I think it's godd for squashing and next nightly - for one the game package was greatly simplified. One open TODO is dropping `supported_games`

**Comment by Infernio** [comment]
Re:
> _morrowind is maybe not a PatchGame at all?

Not yet, but it will be. We need at least the Leveled Lists patcher to match Wrye Mash, but I think we can port much more if we implement `isKeyedByEid` properly throughout the codebase (right now it's only implemented in a couple random places).
