### ISSUE TITLE
Show patchers that won't run because they lack sources in italics

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#587]
The idea is to indicate if a _ListPatcherPanel or _TweakPatcherPanel's patcher won't run because it lacks sources by showing the corresponding patcher label in italics.

**Comment by Infernio** [comment]
![image](https://user-images.githubusercontent.com/2845240/111628112-2229d600-87f0-11eb-823f-597bda1fd9a6.png)

**Comment by Infernio** [comment]
Not perfect yet, Tweak Races should also have italics (I don't check if the items are checked yet) and checking/unchecking the tweaks should then update it. Alias Mod Names should also check if it has any aliases defined and italicize itself otherwise.

**Comment by Infernio** [comment]
Assigned you because you had the idea :P

**Comment by Utumno** [comment]
Haha appreciated - be careful I have some other ideas (of the goal category) you may end up implementing :sweat_smile:
