### ISSUE TITLE
Wrye Bashnencountered an error

### ISSUE THREAD

**Issue by mafriwowo** [wrye-bash/wrye-bash#589]
### Latest Nightly

- [x] I have tried the latest nightly build and the issue still occurs.

### Asking on Discord/AFKMods

- [ ] I have asked on Discord/AFKMods and gotten the go-ahead to post this issue.

### BashBugDump

```
REPLACE THIS TEXT WITH THE CONTENTS OF THE BashBugDump.log
```

#### Description
Traceback (most recent call last):
  File "bash\bash.pyo", line 263, in main
  File "bash\bash.pyo", line 335, in _main
  File "bash\bash.pyo", line 460, in _detect_game
  File "bash\initialization.pyo", line 147, in init_dirs
  File "bash\initialization.pyo", line 54, in getPersonalPath
  File "bash\env\windows.pyo", line 626, in get_personal_path
  File "bash\env\windows.pyo", line 356, in _get_known_path
RuntimeError: Failed to retrieve known folder path 'UUID('fdd39ad0-238f-46af-adb4-6c85480369c7')'

#### Step-by-step reproduction
1. Include a step-by-step process to reproduce the issue here
1. Use lines starting with '1.', GitHub will automatically number them
   correctly when you submit the issue
1. If the steps require downloading mods, include links to them and the exact
   versions we have to download here
1. If the steps require activating certain Bashed Patch options, include
   information on your BP settings and mod tags. You can do this on the Mods
   tab as follows:
     * Your Load Order: 'View' > 'List Mods...'
     * Your Bashed Tags: 'View' > 'List Bash Tags...'
     * Your Bashed Patch config: Right click on the Bashed Patch > 'List Patch Config...'

**Comment by Infernio** [comment]
What that error means is that WB couldn't find your `My Documents` folder. Most likely the fault of OneDrive, you'll have to disable its management over the My Documents folder.

**Comment by lojack5** [comment]
Here's one of those "commonly asked issues with a known fix", perhaps we can add a special case error message pointing to the readme about OneDrive?

**Comment by Infernio** [comment]
Done in ba92f446e2ad96378ad9f33bf0af6d7f325b133d.
