### ISSUE TITLE
Split bolt to a package

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#590]
Though not a big as `bosh` still is, `bolt` is one of our bigger non-data source files.  I've also run into many situations where I've wondered "should this go in bolt?", but didn't put it there because bolt is so large.  I'd like to split bolt as something for me to work on in between bigger issues and while waiting on bigger bits of code changes to hit.  The end goal is to leave bolt in a better state overall, and give a clearer idea of what sorts of things belong in bolt: generic methods and classes that could be used in any project, not just Wrye Bash.  The "nuts and **bolt**s" used to build up an application.

See also [bolt.py](https://github.com/wrye-bash/wrye-bash/wiki/%5Bdev%5D-Deciphering-Source-Filenames#boltpy) and #368.

I plan on two phases of this:

- [ ] Part 1: Convert to a module.  Doing this should take no changes outside of bolt itself, and have no impact on pickling files using classes from bolt.  This will involve splitting into subpackages/submodules as well.  To keep the external API consistent with the current layout, at least one compromise must be made:
    - Module level attributes must stay in the top level of `bolt` (`pluginEncoding`, etc).  This is to avoid gotchas when doing `from .bolt import <attribute>` statements.

  There will be a little bit of work getting some of the pieces to work with each other, but for the most part this should also be fairly easy to accomplish.  A proposed layout, dividing bolt roughly into pieces that correspond to stdlib modules:
    - `bolt`
         - `path.py` - All path related operations (Path, GPath, etc)
         - `functional.py` - Functional programming related tools (similar to itertools, functools, etc).
         - `collection.py` - Container data types.
         - `encoding.py` - Utilities for encoding/decoding bytes to/from text.
         - `io.py` - I/O related classes and methods (so probably the `struct` related code in here as well for now).
         - `util.py` - All other things that don't fit into a largely shared type of concept.
         - `__init__.py` - Any glue code needed to get all these working together (should be minimal), like module level attributes.
- [ ] Part 2: General code cleanup and refactoring.  This is where changing the external facing API will come in, so put this off until after 309, as this will end up touching many places in general in the codebase.
 
 I've mostly assigned this to myself for something to work on while waiting on #460 and its blocking issues, and #178.

**Comment by lojack5** [comment]
I've opened this as a project for me to work on, now that WS games are mostly covered.  Suggestions on naming welcome, as well as code reviews.  I've set a goal of 2 parts to minimize interference with the PY3 upgrade.

**Comment by Infernio** [comment]
I tried this once before, you can find that branch here: https://github.com/Infernio/wrye-bash/tree/inf-bolt-module. Note that was before I had much experience with splitting a module, so the commits are a bit ugly.

Main problem that made me shelve the idea is that we save `Path`s into settings, which means that once people upgrade to the new 'module version', they won't be able to downgrade to previous versions anymore. For example, say we move `Path` into `bolt.paths.Path`. Then a saved `bolt.Path` instance becomes a `bolt.paths.Path` instance after saving the settings in the new version. That will work fine of course, but now you can't go back to the new version anymore. So it would need a VDATA bump.

Not sure if the plan is still to completely stop saving anything but builtins (ref @Utumno), but if so it would be best to wait on this until we've stopped pickling `Path`s so that we don't need to bump VDATA twice for this.

**Comment by Infernio** [comment]
The names I ended up with on that branch btw are:
```
collect.py - collections (duh), `collections.py` is taken by the stdlib
debugging.py - deprint and related infrastructure
localization.py - obsolete now that that's in localize.py at the top level
output.py - really stretching it here, but that contained Log, Progress, SubProgress and WryeText, i.e. anything that outputs text, plus `io,py` is taken by the stdlib
paths.py - self-explanatory
unicode_utils.py - decode/encode, now decoder/encode
```

**Comment by lojack5** [comment]
Sounds good, and yeah I'll take a look at your work.   Thanks for reminding me `collections` is taken, missed that one in my layout!  I don't see `encoding` (as a module/method) taken by stdlib though.

Hardest part is figuring out the module level attributes, got to have the internal/external view of them being consistent.

**Comment by Infernio** [comment]
Ah right, it's `encodings`. I guess `encoding` is fine then.

**Comment by Utumno** [comment]
I'd actually prefer bolt to remain a module. It's pretty well defined and
when something is moved there like AFile is a conscious design decision.
Thinning bolt is another thing and it's been worked on - but really the
effort now should go in other areas like 460 which will provide us the
tools for ps2 apis thinning

bolt is at the end of the day still too fluid and I see not much gain in
trying to split it

**Comment by Utumno** [comment]
A much more worthy goal is actually decoupling belt and its code box from
bolt - so move Wrye text out

**Comment by Infernio** [comment]
Agreed, that belt import in bash.py makes me squint every time :P

**Comment by lojack5** [comment]
Well, I guess the question is then: If I choose to work on this (since it's something I'm interested in), will it be considered a waste, will you prefer not to merge it?

**Comment by Utumno** [comment]
For now I would not want this yes - I would however very much like to see Wryetext moved out of there and the `codebox` hack be annihilated. Then (once on py3 land) I expect to see bolt seriously thinned - hard limit for a python file is ~800 loc and though I like packages we should not have a package for self contained stuff like the (thinned) bolt :)

**Comment by lojack5** [comment]
Ok, then.  If I find something that interests me, I'll show up again.

**Comment by Utumno** [comment]
Hey Lo sorry if I sounded harsh - I do hope you find 460 interesting cause it's happening soon I hope. I am blocked in the last 1% of this parsers merge which I find a huge and unabridged pain (with has some pleasure in it :)
