### ISSUE TITLE
Add 'Timescale Checker' patcher

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#591]
`GRAS\DATA\Wave Period` is specified relative to the timescale (the `TimeScale` global). If you halve the timescale, you also have to duplicate the wave periods of all grasses. If you duplicate the timescale, you have to halve the wave periods of all grasses, etc.

Right now, you can change the timescale via the BP, but wave periods are not adjusted. This checker takes care of that. It looks for the last override of the `TimeScale` global to find the final value for timescale ingame and adjusts wave periods to match if the found timescale does not match the vanilla timescale. It takes a timescale adjusted via the BP into account by simply running after the timescale BP tweak.

Note that Nehrim has a timescale of 10 (vs. the default timescale of 30 that Oblivion has), but the Nehrim devs did *not* adjust the wave periods of their grasses. So we have to build in an exception for Nehrim.

**Comment by Arthmoor** [comment]
Huh, after 15 years I"m still learning interesting things about OB. Never knew grass was tied to the timescale.
