### ISSUE TITLE
Fix all the counters in our definitions

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#592]
There are a ton of fields named something like 'count' or 'counter' with a similarly named list nearby. Should probably test in the CK if that counter gets updated. But not now, even xEdit doesn't do that yet - see e.g. https://github.com/TES5Edit/TES5Edit/issues/919.

**Comment by Infernio** [comment]
Not now. First #460, then #480, then #525, then this.

**Comment by Utumno** [comment]
Reopened as this has the bug label - cleaning up the backburner let's not have bugs in there
