### ISSUE TITLE
BAIN: Installer tab reports missing package assets after install

### ISSUE THREAD

**Issue by BeermotorWB** [wrye-bash/wrye-bash#598]
I've been experiencing an issue with BAIN in the recent nightlies, I'm guessing at least since a mid-April 21 build. I haven't reported it before now because I was trying unsuccessfully to build up some reliable reproduction steps, but in light of other reports this information might be useful.

The expected behavior is: BAIN remembers the state of assets after a package is installed.
Observed behavior:  After a new package is installed, BAIN will sometimes report that assets of a package are not installed (red box with plus).  This normally happens after another application reads or adds assets to the data folder, even if they're intentionally not tracked by BAIN.

Repro steps I have so far:
1. Install a package. In all of my cases it is a package with a BSA because I pack just about everything into a BSA.
2. Switch to the mods tab, tick the box. 
3. Leave Bash open and open xEdit **without** bypassing reference building.
4. Review the file in xEdit. Check for errors or whatever but do not save changes.  
5. Note this makes a <pluginname>.REFCACHE file in the Data folder under "SSEEdit Cache"
6. Close xEdit and return to Bash.
7. Switch to installers tab.
8. Note status of installed package.
9. If package is red, reinstall or anneal to correct.
10. Package will stay installed after the reinstall/anneal.

Other information:
Directories in Data not tracked by Bash/BAIN:
`./Tools/FNIS/*`  (Running FNIS is expected to affect installed state of the FNIS parent package as it replaces assets)
`./SSEEdit Cache` from xEdit
`./NetScriptFramework` from the .NETscript debugging tool.

No bugcheck experienced yet but I'll keep running debugmode to try to get something.

**Comment by Infernio** [comment]
I've noticed this too, but I'm sure it's been around for much longer than recent nightlies. I could swear I hit this even back in the 307 betas era.

In any case, it's not critical for now - Quick Refresh on the package has always fixed it for me (plus we're in the middle of 309/py3).

**Comment by Utumno** [comment]
Hey @BeermotorWB does this still occur?

**Comment by Infernio** [comment]
I'm going to close this for now. With all the refresh refactoring/reworking that's gone into 313, this will need retesting. Good chance it's fixed. If not, we can always reopen the issue (or make a new one).

**Comment by Utumno** [comment]
Thankjs Inf - I have in the works (in local ut-lab) a refactoring of BAIN refresh (irst part is the _Installer_Op link in the current nightly) that will simplify the whole picture - but will be 314, we need to release 313 :P
