### ISSUE TITLE
Validate FOMOD XML schema when running FOMOD installers

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#603]
Pickysaurus is working on getting mod managers to validate the FOMOD schema so that fewer authors will publish broken ones. See [this modding.wiki page](https://modding.wiki/en/vortex/developer/mod-installer-repair) for more information.

The main problem appears to be that there is no stdlib way to do this: https://stackoverflow.com/questions/299588/validating-with-an-xml-schema-in-python
So we'd have to add `lxml` as a dependency. Which may make this a no-go - @Utumno?
Edit: actually, [pyxb](https://github.com/pabigot/pyxb) may work as well, which would allow us to generate schema bindings AOT if I understand it correctly, so no new dependencies.
Edit 2: another option may be making `lxml` an optional dependency, which would mean you don't get the validation if you don't have it installed. Depends on how similar the API is to stdlib.

Ganda's repo with the schema can be found here: https://github.com/GandaG/fomod-schema

**Comment by Utumno** [comment]
@Infernio whatever you think - I would say avoiding the new dependency if pyxb can do that AOT then add lxml as an optional dependency (this won't affect the majority of users anyway) - but then if pyxb proves a pain go for lxml

**Comment by Infernio** [comment]
Thanks. I don't have much time right now anyways and finishing py3 takes priority, obviously.
