### ISSUE TITLE
Gracefully fail when parsing invalid LOOT masterlists

### ISSUE THREAD

**Issue by Vraccas24** [wrye-bash/wrye-bash#604]
### Latest Nightly

- [x] I have tried the latest nightly build and the issue still occurs.

### Asking on Discord/AFKMods

- [x] I have asked on Discord/AFKMods and gotten the go-ahead to post this issue.

### BashBugDump

```
localize.py  119 setup_locale: No translation file for language '', falling back to 'en_GB'
localize.py  122 setup_locale: Set wxPython language to 'en_GB'
localize.py  124 setup_locale: Set Wrye Bash language to 'en_GB'
doc_viewer.py   38 <module>: pdfviewer using PyMuPDF (GPL)
bash.py  222 dump_environment: Using Wrye Bash Version 310.202106231807 (Standalone)
bash.py  222 dump_environment: OS info: Windows-10-10.0.18362-SP0, running on Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
bash.py  222 dump_environment: Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
bash.py  222 dump_environment: wxPython version: 4.1.1 msw (phoenix) wxWidgets 3.1.5
bash.py  222 dump_environment: python-lz4 version: 3.1.3; bundled LZ4 version: 1.9.3
bash.py  222 dump_environment: pyyaml version: 5.4.1
bash.py  222 dump_environment: Input encoding: None; output encoding: utf-8
bash.py  222 dump_environment: Filesystem encoding: utf-8
bash.py  222 dump_environment: Command line: ['A:\\Games\\SteamLibrary\\steamapps\\common\\Skyrim Special Edition\\Mopy\\Wrye Bash.exe', '-d']
bash.py  471 _import_bush_and_set_game: Searching for game to manage:
bush.py  116 _supportedGames: The following games are supported by this version of Wrye Bash:
bush.py  119 _supportedGames:  Enderal, Enderal Special Edition, Fallout 3, Fallout 4, Fallout 4
bush.py  119 _supportedGames:  (WS), Fallout 4 VR, Fallout New Vegas, Morrowind, Morrowind (WS),
bush.py  119 _supportedGames:  Nehrim, Oblivion, Oblivion (WS), Skyrim, Skyrim Special Edition,
bush.py  119 _supportedGames:  Skyrim Special Edition (WS), Skyrim VR
bush.py  121 _supportedGames: Wrye Bash looked for games in the following places:
bush.py  122 _supportedGames:  1. Windows Registry:
bush.py  124 _supportedGames:   The following installed games were found via the registry:
bush.py   70 _print_found_games:  - Skyrim Special Edition: A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition
bush.py  133 _supportedGames:   Make sure to run the launcher of each game you installed through Steam
bush.py  133 _supportedGames:   once, otherwise Wrye Bash will not be able to find it.
bush.py  134 _supportedGames:  2. Windows Store:
bush.py  140 _supportedGames:   No installed games with modding enabled were found via the Windows Store.
bush.py  145 _supportedGames:   Make sure to enable mods for each Windows Store game you have
bush.py  145 _supportedGames:   installed, otherwise Wrye Bash will not be able to find it.
bush.py  208 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  215 _detectGames: Set game mode to Skyrim Special Edition found in parent directory of Mopy:  A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition
bush.py  231 __setGame: Using Skyrim Special Edition game: A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition
initialization.py  161 init_dirs: My Games location set to C:\Users\Shane\Dropbox\My PC (DESKTOP-9BKVF4N)\Documents\My Games\Skyrim Special Edition
initialization.py  174 init_dirs: LocalAppData location set to C:\Users\Shane\AppData\Local\Skyrim Special Edition
initialization.py  223 init_dirs: Game Mods location set to A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods
initialization.py  228 init_dirs: Bash Mod Data location set to A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data
initialization.py  232 init_dirs: Installers location set to A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers
initialization.py  241 init_dirs: Checking if WB directories exist and creating them if needed:
initialization.py  245 init_dirs:  - A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Mod Data
initialization.py  245 init_dirs:  - A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers
initialization.py  245 init_dirs:  - A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bain Converters
initialization.py  245 init_dirs:  - A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bain Converters\--Duplicates
initialization.py  245 init_dirs:  - A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bain Converters\--Corrupt
initialization.py  245 init_dirs:  - A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bash
initialization.py  245 init_dirs:  - A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition Mods\Bash Installers\Bash\BSA Cache
loot_parser.py   48 <module>: Using LibYAML-based parser
loot_parser.py   83 __init__: Using these LOOT paths:
loot_parser.py   84 __init__:  Masterlist: C:\Users\Shane\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
loot_parser.py   85 __init__:  Userlist: C:\Users\Shane\AppData\Local\LOOT\Skyrim Special Edition\userlist.yaml
loot_parser.py   86 __init__:  Taglist (fallback): A:\Games\SteamLibrary\steamapps\common\Skyrim Special Edition\Mopy\taglists\SkyrimSE\taglist.yaml
Wrye Bash encountered an error.
Please post the information below to the official thread at
https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games
or to the Wrye Bash Discord at
https://discord.gg/NwWvAFR

Traceback (most recent call last):
  File "bash\bash.py", line 258, in main
  File "bash\bash.py", line 350, in _main
  File "bash\bosh\__init__.py", line 3623, in initBosh
  File "bash\bosh\loot_parser.py", line 90, in __init__
  File "bash\bosh\loot_parser.py", line 102, in _refresh_tags_cache
  File "bash\bosh\loot_parser.py", line 166, in load_lists
  File "bash\bosh\loot_parser.py", line 690, in _parse_list
AttributeError: 'str' object has no attribute 'get'


```

#### Description
After following a STEP guide for SkyrimSE I wanted to create a Bashed patch but WB is not starting up. Tried reinstalling, the experimental wip-build, both standalone and installer versions. Ran it outside of the mod-manager, inside of it, on an empty modlist and the full one but it always ends up giving me the same error, right after running the .exe. The actual screen of WB does not even appear, instead the error-screen pops up right after the loading process.  

#### Step-by-step reproduction
1. Install Wrye-Bash, doesn't seem to matter which version.
1. Run the .exe as administrator, as normal user or from inside a mod-manager.
1. Wait for it to crash and produce an error message.

#### Additional information
1. This was tested with an empty modlist and only the DLCs of SkyrimSE installed, therefore I didn't add a modlist.
1. Operation System is Windows 10 (Version 1909 (OS Build 18363.1646)).
1. The current Wrye bash version is the wip-build 310.202106231807, I am using the installer version. 
1. Version 309.1 which I used before (tried in both installer and standalone) produced the same error.  
1. The bash_default.ini is being used without modifications

**Comment by Infernio** [comment]
That's not a BashBugDump, that's just the traceback. There's a link in the issue template, follow the steps listed in there: https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug#the-bashbugdumplog

**Comment by Utumno** [comment]
It was a fair try though :)

`yaml.load(ins, Loader=SafeLoader)` returns a (non empty) string (?)

@Vraccas24 - this is related to loot - have you hot the latest version? using some userlist? if using latest try deleting/redownloading the masterlists

**Comment by Utumno** [comment]
Added some debug prints for next iteration in 3b198f236a4e606c935446dd67b098cc8d91fa50

**Comment by Utumno** [comment]
Added some debug prints for next iteration in dfcf9b9ab3a2bdb7700403e7799d680fca8c5a1f (damn)

**Comment by Vraccas24** [comment]
@Infernio Sorry for that, missed the middle step (actually running the debuglog program). Updated the post.

@Utumno Thanks for the answer, that's good to know. Using Version 0.16.1 of LOOT which should be the latest one. Tried a reinstall (it was installed in a default directory) but that didn't help unfortunately. There does seem to be a problem with the userlist, I get an error telling me it wasn't a YAML map. This I can fix by updating the masterlist and sorting the plugins, though the error reappears once I restart loot so there might be a different issue here. Even while having loot uninstalled I could not load up Wrye Bash though. Not sure if I understood you correctly about posting the masterlist but if it helps I could share it. 
Going to try and sort out the loot issues tomorrow and see if that fixes it, thanks again for the help.

**Comment by Utumno** [comment]
Thanks - can you post us the userlist? Then backup it and remove it from where loot tries to find it - this should permit bash starting

**Comment by Vraccas24** [comment]
Alright that did the trick. Removed the userlist (turns out it was still using the one from when I last modded Skyrim back in 2019). WB started up but crashed with a different error. Reinstalled it, this time the release version instead of the nightly, and beware, it works now. As I had suspected the problems were at my end. 

Thanks a lot for pointing me into the right direction and sorry for the inconvenience, closing this. Have a great day!

**Comment by Utumno** [comment]
> Removed the userlist 

Still would like to see that one - so we can avoid errors like that in the future

> WB started up but crashed with a different error

We need as much tedting for newest nightly as possible - I would appreciate if you posted this error on discord

Thanks!

**Comment by Vraccas24** [comment]
Sadly I can't recreate the crash, even after installing the nightly again and didn't save the BugDump, sorry about that, should have thought of that.
I uploaded the userlist but as I said, it's 2 years old. Maybe it helps.
[userlist.txt](https://github.com/wrye-bash/wrye-bash/files/6791523/userlist.txt)

**Comment by Utumno** [comment]
Thanks a lot really appreciated - keep using the nightly :)

**Comment by Infernio** [comment]
That's... one weird file. I would love to know how a userlist ended up that way 🤔 
The traceback does make sense now, since parsing that as YAML would produce a string, not a dict (as all valid userlists would). I guess we could include a type check and fail parsing gracefully?

**Comment by pStyl3** [comment]
> That's... one weird file. I would love to know how a userlist ended up that way 🤔

In 2019 quite a bunch of LOOT versions were released.
> v0.14.0
v0.14.1
v0.14.2
v0.14.3
v0.14.4
v0.14.5
v0.14.6
v0.15.0
v0.15.1

So depending on when exactly in 2019 @Vraccas24's userlist was created, it could've be in conjuction with quite an outdated version of LOOT.

Maybe @Ortham knows more?

**Comment by Ortham** [comment]
> Maybe @Ortham knows more?

The userlist.txt shared above is base64-encoded, and when decoded it looks like a valid userlist (though I didn't try to load it in LOOT). I've got no idea how it ended up as base64 though.

**Comment by Infernio** [comment]
Huh, indeed. It comes out to this: [userlist_decoded.txt](https://github.com/wrye-bash/wrye-bash/files/6795748/userlist_decoded.txt)
