### ISSUE TITLE
Bug in 309.x

### ISSUE THREAD

**Issue by AndalayBay** [wrye-bash/wrye-bash#612]
### Latest Nightly

- [ ] I have tried the latest nightly build and the issue still occurs.

### Asking on Discord/AFKMods

- [ ] I have asked on Discord/AFKMods and gotten the go-ahead to post this issue.

### BashBugDump

```
REPLACE THIS TEXT WITH THE CONTENTS OF THE BashBugDump.log
```

There's no dump log. All I got was a simple error message:
![WB error](https://user-images.githubusercontent.com/1171156/139812052-7991fd20-0387-4b5f-8a87-0c399b491257.png)
I was trying to build my bashed patch. I'm just returning to Oblivion and I'm not happy with the changes 309 has made. I do not want to merge every mod I have and changing the settings is ridiculous. Thank you for busting WB. Going back to 307.

**Comment by Utumno** [comment]
Did you ask at the forums as the issue template suggests? Did you try the latest nightly as the issue template suggests? And of course, there **would** be  a log if you had followed the instructions in the issue template

So thank you for not being helpful and for being rude to people who offer you software for free, spending hours of their free time
