### ISSUE TITLE
Skyrim Anniversary Edition Support

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#616]
[Anniversary Edition](https://en.uesp.net/wiki/Skyrim:Anniversary_Edition) is basically just a DLC for SSE that bundles all Creation Club content released thus far (plus 26 newly released creations) together.

Shouldn't be much effort to support this - really just need to update the CCC fallback list and the vanilla files.

**Comment by Arthmoor** [comment]
One thing to note - the "Skyrim - Patch.bsa" file is no longer present after the core update to the game. Its contents were merged into the other archives.

**Comment by Infernio** [comment]
Should be fine, those sets are just there so BAIN doesn't remove vanilla files from the Data folder. So unless mods begin shipping a `Skyrim - Patch.bsa`, we're good :P
