### ISSUE TITLE
Allow customizing column auto-width per tab

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#625]
Right now we store auto-sizing information (Manual/Fit Contents/Fit Header) globally to the `bash.autoSizeListColumns` setting. I hadn't ever used that feature until today, when I realized how useful it is in sizing the Masters view on the Saves tab (while working on #624). Satisfied with how the Masters view was sized, I went back to the Mods tab - only to find all of my manually aligned columns on that tab had also been resized.
That this is global feels really unintuitive, and making it tab-local would make it more useful/powerful as well, letting you auto-resize only the tabs/views you want.

The only downside is that doing this will change the settings key used and so people will have to reenable it if they had it active previously.

**Comment by Utumno** [comment]
I had done this on purpose IIRC using a class keyPrefix variable - wouldn't
mind see this go - should simplify stuff internally
