### ISSUE TITLE
Improve doc browser usability

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#628]
If you want to associate a bunch of plugins with a bunch of different readmes right now, you need to:
 1. Double-click the first plugin
 1. Click `Set Doc`, then select the doc
 1. Alt-tab back to the main WB window
 1. Find and double-click the next plugin
 1. Repeat from step 2 until done

This can be improved significantly by:
 - [x] Replacing the (entirely useless) read-only plugin name field with a dropdown that lets you select any plugin in your load order directly and
 - [x] Adding a search bar that further lets you narrow the contents of the dropdown down

This way you no longer have to leave the doc browser to pick the next plugin and can search as much as you want (instead of having to look through your LO).
Of course the old workflow will still work as well, if you prefer that.

While we're touching the doc browser:
 - [x] Clicking 'Forget Doc' should select the next doc in line (simple QOL tweak)

Follow-up -> new issue: #631

**Comment by Utumno** [comment]
Not directly usability related but it would be _great_ if we got rid of Paths in there
