### ISSUE TITLE
Extensions API - UI refactoring

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#63]
Refactoring the UI when started should be done with the final goal of being able to provide an API for developers to extend Bash. This I suggest be done by providing an API for new _tabs_, ie the Wrye Bash extensions should add tabs to the main app. Our main tabs (Installers, Mods, Saves, Ini tweaks etc) should be refactored to such extensions.

**Comment by Utumno** [comment]
Under #163. Once Tank and list are unified and NotebookPanel and Sash[Tank...]Panel APIs interfaces are defined then reopen this.

**Comment by Infernio** [comment]
Note: I've edited this from 'plugins' to 'extensions' - if we ever do get around to doing this, then 'plugins' would be a very bad name, considering that .esp, .esm, .esl, etc. files are aleady called that.

**Comment by Utumno** [comment]
Great - where did the reaction button go?

**Comment by Infernio** [comment]
Seems to have disappeared. Github weirdness?

**Comment by Infernio** [comment]
That's where it went, locked issues don't allow reactions 😛

**Comment by Utumno** [comment]
Extending Bash is essential but should be gamewise instead of tabwise :P This issue here is rather a general API guideline (incorporated in #190 and #336) rather than a goal per se in the foreseeable (py2) future

**Comment by Infernio** [comment]
Honestly I think we want to reserve the term 'extensions' for real, third-party extensions - e.g. someone could create an 'extension' that adds a new tweak for use with their mod.
That is obviously absurdly far off - our APIs are in constant flux right now, freezing them is completely off the table at the moment. Like you mentioned above, we first need APIs *that we're happy with* - rock solid ones for game handling, new tabs, gui, files, etc.
