### ISSUE TITLE
Consider allowing BAIN to install into the base game folder

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#632]
To allow installation of ENBs, SKSE preloaders, etc. directly via BAIN. Should be done on a per-package basis by introducing a new link (similar to how 'Has Extra Directories' works right now) that changes the 'destination' from Data/Data Files to the base game folder.

Blockers:
 - [ ] #501
 - [ ] BAIN refactoring

**Comment by Utumno** [comment]
Reopening this - it's one of the most wanted features anyways. To properly address this we should probably add a new type of bain package (or easier some extra switch, for backwards compat) - start here: https://github.com/wrye-bash/wrye-bash/blob/59587e64715719610d1864b6055267526a6cb6f8/Mopy/bash/bosh/bain.py#L1015-L1074 then go to its caller `_reset_cache` then the beast that is `refreshDataCrcDate` and then up to InstallersData and track all the places we hard baked the assumption that the root dir is the Data dir. And then there would be backwards compat issues - so Installers saved in later versions should be compatible with newer bash versions. So this is frankly - tough.
