### ISSUE TITLE
Expand PROJ and HDPT tag coverage for Skyrim

### ISSUE THREAD

**Issue by Sabre142** [wrye-bash/wrye-bash#636]
Will PROJ -> DATA subrecords ever receive SSE tag support like it already has in FO3/FNV?

It would be good if SSE's Graphics tag could support (HDPT) Head Part: (MODL) Model and (TXST) Texture Set too as it already does with FO3/FNV.

**Comment by sibir-ine** [comment]
I've implemented the requested patcher expansion in [`sib-636-tag-coverage`](https://github.com/wrye-bash/wrye-bash/commits/sib-636-tag-coverage). @Infernio, did you have any plans for expanding patchers in FO3/FNV too, or did you just add labels for them because they were mentioned?

**Comment by Infernio** [comment]
Removed the labels 👍

**Comment by sibir-ine** [comment]
Okay, I'll merge this to nightly then.

**Comment by Infernio** [comment]
Future tip: you can use `git merge --squash` (on the command line - git clients should have an equivalent) followed by a `git commit`, that way the entire branch just ends up as a single commit on nightly.
