### ISSUE TITLE
Consolidating the Nexus pages

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#640]
I talked with the Nexus moderators/staff and I think we should maybe consolidate the Nexus pages into a single one in the 'Modding Tools' section (https://www.nexusmods.com/site). Opening this to group discussion and pinging @wrye-bash/bashers.

## Pros
- Only a single page to update. Right now updating all those pages takes between an hour and a day, what with needing to upload the files, edit the version and details, contact moderators to ensure all the files are released from the 'suspicious' detection, etc.
- There is no way we can keep creating pages as new games get added. Once we start supporting non-Bethesda games, this will balloon out of control.

## Cons
- We'd lose all our endorsements, downloads and views and would have to start over. This could hurt WB's discoverability massively (and it's already not that popular anymore - the Skyrim page has ~80K endorsements, the newer Skyrim SE page only has ~27K).

There are probably other pros and cons I'm forgetting.

## Nexus Responses
- Pickysaurus from Nexus said that he wouldn't be opposed to showing a popup or something similar to remind people to endorse WB (and once we have Nexus API integration (#459), that could even have a button which immediately endorses right there).
- Pickysaurus also said that Nexus staff can help us when we hide the pages so that when you visit one of the then-hidden pages, a link to the replacement page will be shown.

**Comment by XJDHDR** [comment]
> We'd lose all our endorsements, downloads and views and would have to start over.

You could at least partially negate this Con by archiving all downloads on the current pages, then edit the descriptions to say that they will no longer be updated while linking to the new page in Modding Tools.

**Comment by Infernio** [comment]
That does sound like a good idea :+1:

**Comment by Infernio** [comment]
The LOOT team (of which I'm a part) are also thinking about doing this (though in their case, it'd be moving from SkyrimSE to Modding Tools rather than consolidating). The discoverability problem is kind of a chicken and egg situation: more projects moving there would vastly help in the discoverability by boosting the category's ranking on the Nexus front page, but most projects are probably either content where they are or are concerned precisely about things like discoverability.

If the section becomes more popular, it could actually end up *helping* discoverability of tools, since we'd no longer have to compete with incredibly popular mods for search ranking etc.

**Comment by Infernio** [comment]
Another thing that would really help with this issue would be an update check on boot - that way we could do one more multi-page release, then consolidate to a single page for the release afterwards. Users would then see the update notification, along with a link to github/the new Nexus page. IIRC WB used to have an update check, but it was removed?

**Comment by Sabre142** [comment]
One potential problem with moving the Wrye Bash mod page to the Tools section would be that mod authors wouldn't be able to add Wrye Bash as a requirement for their mods (Nexus Mods only lets you add requirements from the same sub-site you are using):

![image](https://user-images.githubusercontent.com/26516348/217926486-a034ac1d-a185-4b45-a169-5e3671b4df59.png)

**Comment by Infernio** [comment]
There's nothing much we can do about that. We've requested Nexus add some kind of functionality to make cross-game tools appear on Nexus pages for games they support, but I don't know when (if ever) that will be implemented.

The current situation, with like 10 Nexus pages, simply isn't sustainable. Uploading a new version takes ages, plus all the antivirus detection hoops we have to jump through each time.

**Comment by sibir-ine** [comment]
@Sabre142, could you not add it as an "off-site" requirement at least?

**Comment by Metallicow** [comment]
I authorize you folks(Members of the Wrye Bash Organization) to upload my demo from TESNexus to the Organizations repository for further study and ado. (Original code and allow you to modify how it has progressed thru the years according to LoJacks wild idea of a script). (Or whatever monkeys are involved)

**Comment by Infernio** [comment]
Made a page for WB in the Modding Tools section: https://www.nexusmods.com/site/mods/591

We should probably add some newer images to this one, the only ones we have on the various pages are from 307 (or even older, like 307 beta days). I can't exactly do that since I'm on Linux now :P

**Comment by Infernio** [comment]
This is done. Only thing left to do is monitor the old pages to see if we should delete the old files there or not.
