### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by XLRT** [wrye-bash/wrye-bash#641]
How do I prevent Wrye Bash from creating new blank bashedpatch when I delete it?

**Comment by Infernio** [comment]
First: Make a copy of `bash_default.ini` in your Mopy folder, change its name to `bash.ini` and change the `;bEnsurePatchExists=True` line to `bEnsurePatchExists=False` (note the removal of the leading `;`, uncommenting the line).

Second: *Do not open issues in this repository.* From the Readme.md:
> We are currently monitoring [this thread](https://afkmods.com/index.php?/topic/4966-wrye-bash-all-games) at the AFK Mods forum and [the Wrye Bash Discord](https://discord.gg/NwWvAFR).
> Please be sure to ask there first before reporting an issue here.
