### ISSUE TITLE
Add support for the GOG version of Skyrim SE/AE

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#646]
Todd's done it again. Yet another rerelease of Skyrim on yet another platform.

Detailed information available here: https://github.com/loot/loot/issues/1802

Should be really easy to support, thankfully.

**Comment by Infernio** [comment]
See #648, if Beth start releasing other games on GOG as well soon I'll repurpose this issue to be about all of them.

**Comment by Infernio** [comment]
And just like that, renaming is needed since Nehrim and Enderal have been released on GOG.

**Comment by sibir-ine** [comment]
Not sure when this happened, but [FO3](https://www.gog.com/en/game/fallout_3_game_of_the_year_edition) & [FNV](https://www.gog.com/en/game/fallout_new_vegas_ultimate_edition) are on GOG, as is [Morrowind](https://www.gog.com/en/game/the_elder_scrolls_iii_morrowind_goty_edition), though I understand that support for it is limited at the moment. LOOT stores the GOG game IDs & registry keys [here](https://github.com/loot/loot/blob/master/src/gui/state/game/detection/gog.cpp), & the IDs can be used for unique icon files of the form `goggame-<GOG ID>.ico` to identify GOG installs as I'm not sure if they also have a `gog.ico` file. I believe they have the same AppData & My Games folders as their Steam variants. IIRC, @Ortham has them, so maybe they'd be able to confirm.

**Comment by Ortham** [comment]
> IIRC, @Ortham has them, so maybe they'd be able to confirm.

I've got Morrowind, Oblivion, Nehrim, Skyrim SE, Enderal, Fallout 3 and Fallout New Vegas on GOG. Not all the games on GOG have a `gog.ico` file (e.g. Morrowind doesn't), that's why I went for using the game-specific icon files to tell if an install is a GOG install.

**Comment by Utumno** [comment]
Thanks @Ortham @sibir-ine - do you think this is easily done @Infernio ?

**Comment by Infernio** [comment]
Should be straightforward, modulo some refactoring to support the different icons directly in `GOGMixin`.

**Comment by Utumno** [comment]
Thanks Inf - other than that I think from my side I have nothing else 311 related - 647 should be stable as far as loading is concerned, now that we parsed the WRLD children - in the patch API (keepRecords and co) there might be some buggy edge cases but this is (#)3112 so we'll have plenty of chances to revisit. I will have some time during the weekend - anything you want help with ping me

**Comment by Infernio** [comment]
Do the FO3/FNV games still have the different language directories in their GOG versions?

**Comment by Ortham** [comment]
No, they have separate installers for each language.
