### ISSUE TITLE
Add support for the EGS version of Skyrim SE/AE

### ISSUE THREAD

**Issue by sibir-ine** [wrye-bash/wrye-bash#648]
Looks like the GOG release was quickly followed by a release on the [Epic Games Store](https://store.epicgames.com/en-US/news/the-elder-scrolls-v-skyrim-has-landed-onto-epic-games-store) as well. It's the only TES/FO game available there at the moment.

More info can be found at loot/loot#1809.

**Comment by Infernio** [comment]
Oh *fantastic*, we'll need to add another new method for finding game locations according to the linked issue 🙄

I haven't even gotten around to #639 yet...

**Comment by Utumno** [comment]
> Oh _fantastic_, we'll need to add another new method for finding game locations according to the linked issue 🙄
> 
> I haven't even gotten around to #639 yet...

Whoops - that said don't do the reorganization just now let's do it the old way, as I am dropping the patcher import - simplifying game handling is ongoing :)

**Comment by Infernio** [comment]
Yeah, I'll open an issue to track that.

**Comment by Infernio** [comment]
@BeermotorWB I need the `CatalogItemId` of Skyrim SE on the Epic Games Store. It's in the manifest file, which is located somewhere in `C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests` (well, I actually check the registry to get this path, but that's the default). If you could post that ID (or just upload the entire manifest file), that would be very helpful.

**Comment by sibir-ine** [comment]
The `AppName` appears to be `ac82db5035584c7f8a2c548d98c86b2c` (Silarn accidentally labeled it `AppId`, an element that doesn't appear to exist in the manifest from cursory testing with other games). There also appears to be a separate `AppName` for the AE update, `5d600e4f59974aeba0259c7734134e27`, according to ModOrganizer2/modorganizer-game_skyrimSE@f1e3166e192a1c8ac206635a8f3596cab7756118.

**Comment by Infernio** [comment]
Alright, added support in `311.202210071332`. In the eternal words of Linus: Go Forth And Test. Because I'm sure as hell not going to :P

**Comment by BeermotorWB** [comment]
Related and for historical purposes:
https://github.com/loot/loot/issues/1809

**Comment by sibir-ine** [comment]
Looks like FO3 [will be on EGS](https://store.epicgames.com/en-US/p/fallout-3-game-of-the-year-edition) as well in a week. However, it'll be free to claim for a week, so that'll make testing easier at least.

**Comment by Infernio** [comment]
@wrye-bash/bashers I'm going to consolidate the EGS/GOG rereleases into the two issues we already have for them - we only need them to show up in the version history once anyway to inform users and this way we avoid a ton of extra open issues.

**Comment by Infernio** [comment]
Ref https://github.com/loot/loot/issues/1812 for FO3.

**Comment by sibir-ine** [comment]
Ref loot/loot#1867 for FNV Ultimate Edition. I'm working on adding support, & I think I've gotten it right. I'll push to nightly in a moment.
