### ISSUE TITLE
Update Tweak Settings for Fallout 4

### ISSUE THREAD

**Issue by BeermotorWB** [wrye-bash/wrye-bash#650]
### Fallout 4 - Tweak Settings tracking

Part of #482 effort

Most are GMST with room for any additional fix tweaks as identified. 

**Settings Tweaks**

- [x] Timescale
- [x] Strength / Encumbrance multiplier
- [x] Combat: Max Actors
- [x] Max Companions (Followers)
- [x] Vertical Object Detection
- [x] Player Max Jump Height
- [x] Fast Travel Time
- [x] Max Draggable Weight
- [x] Warning: Internal Distance to Hostiiles
- [x] Warning: External Distance to Hostiles
- [x] Disable Projectile Dodging (Matrix-like bullet dodging behavior by NPCs)
- [x] Merchant Restock Time
- [x] Player Fall Damage Threshold
- [x] Player Sprinting Cost
- [x] AI Bump Reaction Delay
- [x] Custom No Fast Travel Message
- [x] Custom Quicksave Message
- [x] Custom 'Carrying too much' Message
- [x] AI Conversation Chance
- [x] AI Conversation Chance - Interiors
- [x] Max Dead Actors
- [x] Hacking - Min Number of Words
- [x] Terminal Display Rate (lines per second?)
- [x] Gore: Combat Torso Explode Chance
- [x] Gore: Combat Dismemberment Chance

**Comment by BeermotorWB** [comment]
I've run through these after implementing and confirmed the ones I'm able to directly test via console and behavior.

**Comment by Infernio** [comment]
I've gone ahead and deleted `650-beer-f4-tweak-settings-01`, since it's merged now. Thanks 👍
