### ISSUE TITLE
Questions About Bashs Widgets

### ISSUE THREAD

**Issue by Metallicow** [wrye-bash/wrye-bash#66]
Just a question collection about some of the smaller widget related stuff.

Anywho...
Q1. Is there a reason ThinSplitterWindow was used? 
Graphically I see no difference between it and SplitterWindow. 
Plus gizmos is an oddball module.
If nothing useful is came up with specifically, I'll probably run the Q. by Robin and if nothing special(It may be dropped now and just lingering), the few instances where my 3Way-splitter or a 4-Way won't fit in, will be swapped to the standard widget class. It inherits from SplitterWindow, yet I see nothing special about it on windows XP. attach a small screenie if anyone sees a noticeable difference.
 
Edit: Added Tag for wxPyGUI.
sample app
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Test graphical difference in between ThinSplitterWindow and SplitterWindow.
"""

#-Imports-----------------------------------------------------------------------

#--Python Imports.
import os
import sys

#--wxPython Imports.
import wx
import wx.gizmos as gizmos

class TestPanel(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent, -1)

        self.splitter = wx.SplitterWindow(self, -1)

        splitterWin = wx.SplitterWindow(self.splitter, -1)
        sp2 = wx.Panel(splitterWin, -1)
        sp2.SetBackgroundColour(wx.GREEN)
        sp3 = wx.Panel(splitterWin, -1)
        sp3.SetBackgroundColour(wx.CYAN)
        splitterWin.SplitVertically(sp2, sp3, 150)

        thinSplitterWin = gizmos.ThinSplitterWindow(self.splitter, -1)
        tsp2 = wx.Panel(thinSplitterWin, -1)
        tsp2.SetBackgroundColour(wx.RED)
        tsp3 = wx.Panel(thinSplitterWin, -1)
        tsp3.SetBackgroundColour(wx.BLUE)
        thinSplitterWin.SplitVertically(tsp2, tsp3, 150)

        self.splitter.SplitHorizontally(splitterWin, thinSplitterWin, 150)

        vbSizer = wx.BoxSizer(wx.VERTICAL)
        vbSizer.Add(self.splitter, 1, wx.EXPAND | wx.ALL, 5)
        self.SetSizer(vbSizer)

class TestFrame(wx.Frame):
    def __init__(self, parent, id=wx.ID_ANY, title=wx.EmptyString,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.DEFAULT_FRAME_STYLE, name='frame'):
        wx.Frame.__init__(self, parent, id, title, pos, size, style, name)

        panel = TestPanel(self)
        self.Bind(wx.EVT_CLOSE, self.OnDestroy)

    def OnDestroy(self, event):
        self.Destroy()

class TestApp(wx.App):
    def OnInit(self):
        gMainWin = TestFrame(None)
        gMainWin.SetTitle('Test Demo')
        gMainWin.Show()

        return True

if __name__ == '__main__':
    import os
    import sys

    print('Python %s.%s.%s %s' % sys.version_info[0:4])
    print('wxPython %s' % wx.version())
    gApp = TestApp(redirect=False,
            filename=None,
            useBestVisual=False,
            clearSigInt=True)

    gApp.MainLoop()

```

**Comment by Utumno** [comment]
NO gui stuff till refactoring is done

**Comment by crazykilla15** [comment]
I need to know something about this, as i am doing work on the project using python 3 and wxpython phoenix .

wxpython phoenix doesnt have gizmos, i need an acceptable alternative.

**Comment by Metallicow** [comment]
Try asking Robin over at wxpython-dev mailing list.

I recall I had some issues attempting a clean switcheroo of the widgets with phoenix. I would just go ahead and use the standard wx splitter instead, unless there is a specific reason besides appearance. gizmos isnt hook'd/doc'd in for wxpy phoenix yet.

**Comment by crazykilla15** [comment]
What issues did you have?

**Comment by Metallicow** [comment]
@crazykilla15 A simple switch of subclassing from ThinSplitterWindow to SplitterWindow.
Ex: There is probably something specific being called(probably method or attrs) somewhere in thinsplitterwindow that may or not be in splitterwindow.
Phoenix aims to eliminate "cruft" and is a complete rewrite. One would have to look into the actual code for the two to iron out the differences. wxWidgets probably has docs for thinsplitterwindow for a start as it isn't present in phoenix docs yet.

**Comment by crazykilla15** [comment]
Thats what i've been doing, looking at what thinsplitterwindo does differently.

**Comment by Metallicow** [comment]
@crazykilla15 Apparently nothing bash was using... After some more work and testing, I can say that now that more refactoring has been done by the monkeys, that a simple switch of wx.gizmos.ThinSplitterWindow with wx.SplitterWindow does work now.

My metallicow-wx3-phoenix-compatability branch now works on wx28 Classic, wx30 Classic and Phoenix!!! :)

I stumbled across the splitterwindow fix again when ripping a Installers Details class for another branch that incorporates the same fix also.

**Comment by crazykilla15** [comment]
Thanks for feedback, but it's of no use to me anymore. I abandoned my work after it was put quite clearly to me that any talk of python before version 310(IIRC) is, and i quote, "trolling"

it wouldent have been worth it to port so many possible commits, i already had a hard time keeping up as it was.

**Comment by Utumno** [comment]
@crazykilla15:
Why did I even _have_ to put it clearly ? The _right thing_ to do would be to read the currently active issues and try to help with those - there are open issues tagged wx: https://github.com/wrye-bash/wrye-bash/labels/wx.
Instead - at a moment critical _and very tricky_ fixes were rolled - you turn up and start talking about moving to a new graphics library ! This can only mean you have _not an idea_ about the __state of the code__ ! And simply nor me nor _my users_ have time for that, hence trolling. If instead you had the stance I describe below you might by now have gotten write rights - a shame.

People, there is an etiquette in open source. And because I intend to go on working for Bash and I am _alone_ at the moment - nobody but me has written a good, _useful_ piece of code since 305 - I simply do not have time for people who don't _genuinely_ try to _help_. And help is asking me: _what needs to be done ?_ - no _let's move to P3_.

That goes for @Metallicow too - but at least you have set up your branches and working there - I would like you to stop posting to issues though. Rest assured I will turn the eye on your branches cause I am of course myself dissatisfied with the wx situation - but I think should be clear by now that there are more pressing matters like, say, ___the release___.

**Comment by crazykilla15** [comment]
Ok then, what needs to be done.

**Comment by Utumno** [comment]
#200, https://github.com/wrye-bash/wrye-bash/labels/wx
Here is a hard nut to crack for instance: https://github.com/wrye-bash/wrye-bash/issues/179

Metallic is already working on splitting the InstallersPanel to an InstallersPanel and an InstallersDetails - see my comments there:

https://github.com/wrye-bash/wrye-bash/commit/b67a680b30c712c2efda8b9d3963d2825edc07b6

This is a _top priority_ cause it will open the way for BAIN fixing/expanding - as it is now I have a 1k lines class responsible for everything - impossible situation (never mind the chaos in the data model). I want a blind split - but tested and documented in small _working_  individual commits. You could work together if you know git well enough - PM each other and set up a branch. Once ready let me do the final class API work and merge - ready means two classes but Bash working as before on user level _in every single commit in the branch_. Blind split means no unneeded changes (like formatting), not even needed ones - if you find bugs commit fixes separately. _Pure refactoring_ - splitting a class, intermediate level.

Welcome :)

PS: and let me concentrate on the release now - work among you - or if this is not possible tackle any of the issues you want from the ones I linked to on your own in dedicated branches in your fork and when ready post me a link to your branches and let me have a look. Just respect my (limited) time - or as Linus put it: " Words are cheap, let me see your code"

Talk in a couple weeks
