### ISSUE TITLE
Add Support for Overlay Plugins

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/wrye-bash#668]
Starfield introduces a new flag for plugins, which we've standardized on calling "Overlay". Current understanding is as follows:
- The flag's index is `0x200`, where the ESL flag used to be (which is now `0x100`).
- An overlay plugin cannot have the ESL flag set as well - if the game finds both, it ignores the ESL flag.
- An overlay plugin cannot have new records (well, technically it can, but it *really* shouldn't - they get injected into the the first master in the plugin's master list, which is not a desirable situation, obviously).
- An overlay plugin does not take up a load order slot at all.
- An overlay plugin must have at least one master - if the game does not find a master, it ignores the Overlay flag.

This makes them ideal for conflict resolution patches, for obvious reasons.

Wrye Bash should:
- [x] Parse the flag correctly.
- [x] Allow loading an unlimited number of overlay plugins.
- [x] Remove the ESL flag when we write a plugin that has the Overlay flag.
- [x] Not mark overlay plugins as ESL-capable.
- [x] Display the number of active overlay plugins in the status bar.
- [x] Warn about plugins (in the Plugin Checker) that have the Overlay flag set but include new records.
- [x] Warn about plugins (again, in the Plugin Checker) that have the Overlay flag set but also have the ESL flag set.
- [x] Warn about plugins (you guessed it, in the Plugin Checker) that have the Overlay flag set but have no masters.
- [x] Allow creating Overlay plugins via New Plugin...
  - [x] Also, New Plugin... should disable the ESL checkbox if the Overlay checkbox is selected (and vice versa).
  - [x] And the Overlay checkbox should also get disabled if no masters are selected.
- [x] Show a new color (and mouseover text) for overlay plugins - plus one mixed with the ESM color (no need for mixed overlay and ESL, obviously).
- [x] Check for Overlay-capable plugins and highlight them (time to refactor that system for good).
- [x] Feature an option to Overlay-flag a plugin, similar to how we ESL-flag.

**Comment by LordNyriox** [comment]
@Infernio: I find it interesting that these 'overlay' plugins sound similar to the 'mergeable' patch plugins from older Bethesda games. 

Once the Starfield plugin format has been fully decoded, perhaps you could implement the Starfield Bashed Patch as an 'overlay' plugin (instead of an ESL)?

**Comment by Infernio** [comment]
Potentially, but the BP can actually contain new records (GMSTs). Plus we already flag it as an ESL, so it's not going to take up a full slot anyways.

**Comment by LordNyriox** [comment]
> Potentially, but the BP can actually contain new records (GMSTs). 
Well, in pre-ESL games, those GMSTs are injected into the game master.  The same approach would apply to SF 'overlay' plugins.

**Comment by LordNyriox** [comment]
> Potentially, but the BP can actually contain new records (GMSTs). 

Well, in pre-ESL games, those GMSTs are injected into the game master.  The same approach would apply to Starfield 'overlay' plugins.

**Comment by LordNyriox** [comment]
> Potentially, but the BP can actually contain new records (GMSTs). 

In pre-ESL games, those GMSTs are injected into the game master.  My suggestion is to use the same approach in Starfield.

**Comment by LordNyriox** [comment]
> We don't inject them anymore 

Ah, right, I had forgotten that change.  Though I sure do remember when you removed those pickle files—you may not recall, but shortly afterwards I had asked for (and received) your help dumping the assigned GMST FormIDs from those, so that I could delete them with a clear conscience. 

Never mind my suggestion about changing the Bashed Patch, then.  👋

**Comment by Infernio** [comment]
We may still do it, but we'll see how the BP shakes out for Starfield first (which will obviously have to wait until SF1Edit is reliable and maybe even until the CK is released).

**Comment by Infernio** [comment]
Alright, should be done. Note that none of it will work in Starfield yet (except for the new color for Overlay-flagged plugins), because `canBash` is False for Starfield right now, which disables everything to do with plugin manipulation.
