### ISSUE TITLE
Manuel instruction where is it? 

### ISSUE THREAD

**Issue by 007chabp** [wrye-bash/wrye-bash#672]
how to use it?
Merci

**Comment by Infernio** [comment]
1. *Don't open issues here*, this is a technical bug tracker/development planner. Post on the Discord/forum instead. The issue template, readme and pre-filled issue description should have told you that.
2. See the [general readme](https://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html) and [advanced readme](https://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html).
