### ISSUE TITLE
FOMOD Error - Mod Author believes there is nothing wrong with the FOMOD script

### ISSUE THREAD

**Issue by m0lz** [wrye-bash/wrye-bash#674]
Fallout 4

Wrye Flash nightly build in use.

Try this Mod = https://www.nexusmods.com/fallout4/mods/61884

Download the main file, and try to install it using FOMOD

You will see scripting error issues.

The author however is happy that the script works fine in MO2 and Vortex, so he believes Wrye Bash is broken, and is stubbornly resisting trying to help with the issue (even to the point of burying the posts I made about it).

**Comment by m0lz** [comment]
Sorry should have posted this earlier, the error received is as follows ..

"The ModuleConfig.xml file used to specify the FOMOD installer for this package does not conform to the FOMOD specification. This should be reported to and fixed by the mod author. Please share the error log shown below with them as well. You can use the "Copy Log" button to easily copy it.

This warning can also be turned off globally via "Settings > Validate FOMODs", but be aware that by doing so, Wrye Bash may fail to install or incorrectly install invalid packages.

Line 63, column 0:
  Element 'typeDescriptor': This element is not expected. Expected is one of ( files, conditionFlags ).
  XML Path: /config/installSteps/installStep[2]/optionalFileGroups/group[1]/plugins/plugin[1]/typeDescriptor

Line 83, column 0:
  Element 'typeDescriptor': This element is not expected. Expected is one of ( files, conditionFlags ).
  XML Path: /config/installSteps/installStep[2]/optionalFileGroups/group[2]/plugins/plugin[1]/typeDescriptor"

Which led me to believe the author had not written the fomod script as per fomod specification.
However the author is adament that Wrye Bash is wrong.

**Comment by Utumno** [comment]
Well we might be erring but this needs to wait for 313 dev - thanks for the report!

**Comment by m0lz** [comment]
In case the author decides to stealth update the files with a change or two and the issue is lost due to not being able to reproduce it, here is the content of the ModuleConfig.xml

` 
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://qconsulting.ca/fo3/ModConfig5.0.xsd"> 
	<moduleName>Far Object LOD Improvement Project</moduleName> 
	<moduleImage path="images\banner.jpg" /> 
	<installSteps order="Explicit"> 
		<installStep name="Assets"> 
			<optionalFileGroups order="Explicit"> 
				<group name="Core Files" type="SelectExactlyOne"> 
					<plugins order="Explicit"> 
						<plugin name="Core Files"> 
							<description>Far Object LOD Improvement Project (FOLIP) adds missing LOD models for objects that don't currently have them. This improves visuals and eliminates pop-in of objects at very little performance cost.</description> 
							<image path="images\banner.jpg" /> 
							<files> 
								<folder source="000 Core Files" destination="" priority="0" /> 
							</files> 
							<typeDescriptor> 
								<type name="Required"/> 
							</typeDescriptor> 
						</plugin> 
					</plugins> 
				</group> 
				<group name="Generation" type="SelectExactlyOne"> 
					<plugins order="Explicit"> 
						<plugin name="I will generate LOD"> 
							<description>Select this option if you will be generating LOD.</description> 
							<image path="images\xLODGen Objects.png" /> 
							<conditionFlags> 
								<flag name="generate">On</flag> 
							</conditionFlags> 
							<files> 
								<folder source="001 Plugin" destination="" priority="0" /> 
							</files> 
							<typeDescriptor> 
								<type name="Optional"/> 
							</typeDescriptor> 
						</plugin> 
						<plugin name="I will NOT generate LOD"> 
							<description>Select this option if you are using pregenerated LOD that requires this mod as a dependency.</description> 
							<files> 
								<folder source="100 TexGen" destination="" priority="0" /> 
								<folder source="400 After Generation" destination="" priority="0" /> 
							</files> 
							<typeDescriptor> 
								<type name="Optional"/> 
							</typeDescriptor> 
						</plugin> 
					</plugins> 
				</group> 
			</optionalFileGroups> 
		</installStep> 
		<installStep name="Options"> 
			<visible> 
				<dependencies operator="And"> 
						<flagDependency flag="generate" value="On"/> 
				</dependencies> 
			</visible> 
			<optionalFileGroups order="Explicit"> 
				<group name="Textures" type="SelectExactlyOne"> 
					<plugins order="Explicit"> 
						<plugin name="I will use TexGen"> 
							<description>Select this option if you will use TexGen to generate the correct textures.</description> 
							<image path="images\TexGen.png" /> 
							<typeDescriptor> 
								<type name="Optional"/> 
							</typeDescriptor> 
						</plugin> 
						<plugin name="I will NOT use TexGen"> 
							<description></description> 
							<files> 
								<folder source="100 TexGen" destination="" priority="0" /> 
							</files> 
							<typeDescriptor> 
								<type name="Optional"/> 
							</typeDescriptor> 
						</plugin> 
					</plugins> 
				</group> 
				<group name="Synthesis" type="SelectExactlyOne"> 
					<plugins order="Explicit"> 
						<plugin name="I will use Synthesis"> 
							<description>I will use Synthesis FOLIP and HasDistantLOD patchers.</description> 
							<image path="images\Fallout4Guide_Synthesis5.png" /> 
							<typeDescriptor> 
								<type name="Optional"/> 
							</typeDescriptor> 
						</plugin> 
						<plugin name="I will NOT use Synthesis"> 
							<description>I will NOT use Synthesis.</description> 
							<conditionFlags> 
								<flag name="noSynthesis">On</flag> 
							</conditionFlags> 
							<typeDescriptor> 
								<type name="Optional"/> 
							</typeDescriptor> 
						</plugin> 
					</plugins> 
				</group> 
			</optionalFileGroups> 
		</installStep> 
		<installStep name="Special Plugins"> 
			<visible> 
				<dependencies operator="And"> 
						<flagDependency flag="noSynthesis" value="On"/> 
				</dependencies> 
			</visible> 
			<optionalFileGroups order="Explicit"> 
				<group name="Disable This When Done" type="SelectAny"> 
					<plugins order="Explicit"> 
						<plugin name="FOLIP - Before Generation"> 
							<description>Installs the FOLIP - Before Generation.esp plugin. It should be enabled for LOD generation, but disabled afterward. FAILURE TO HEED THESE WORDS WILL RESULT IN ISSUES.</description> 
							<files> 
								<folder source="300 Before Generation" destination="" priority="0" /> 
							</files> 
							<typeDescriptor> 
								<type name="Recommended"/> 
							</typeDescriptor> 
						</plugin> 
					</plugins> 
				</group> 
				<group name="Enable This When Done" type="SelectAny"> 
					<plugins order="Explicit"> 
						<plugin name="FOLIP - After Generation"> 
							<description>Installs the FOLIP - After Generation.esp plugin. It should be DISABLED for LOD generation, but enabled afterward. FAILURE TO HEED THESE WORDS WILL RESULT IN ISSUES.</description> 
							<files> 
								<folder source="400 After Generation" destination="" priority="0" /> 
							</files> 
							<typeDescriptor> 
								<type name="Optional"/> 
							</typeDescriptor> 
						</plugin> 
					</plugins> 
				</group> 
			</optionalFileGroups> 
		</installStep> 
	</installSteps> 
</config>`

**Comment by Infernio** [comment]
We are definitely not erring, if WB says the file does not conform to the FOMOD schema, then it doesn't conform to the schema. Doesn't matter if it works anyway (and it *will* probably work anyway, that typeDescriptor thing is quite common and is caused by some FOMOD generator not conforming to the schema IIRC), all WB is reporting is that that XML file fails to validate against the official FOMOD XML schema.

All this validation was added specifically because the Vortex guys requested it btw, so Vortex should definitely be complaining as well.

You can read more about this here: https://modding.wiki/en/vortex/developer/mod-installer-repair

**Comment by Infernio** [comment]
To elaborate, the exact problem is that the schema defines a `plugin` as having the following children:

1. Required: A `description` element of type `string`.
2. Optional: An `image` element of type `image`.
3. Required: A `files` element of type `fileList`.
4. Optional: A `conditionFlags` element of type `conditionFlagList` (this may also occur before the `files` element).
5. Required: A `typeDescriptor` element of type `pluginTypeDescriptor`.

Source: https://github.com/GandaG/fomod-schema/blob/dd86bbe2ada6f126378dea13d3ec29364da05c3f/ModuleConfig.xsd#L267

In the ModuleConfig you provided, the first three and last two plugins are correct:

```xml
<plugin name="Core Files"> 
	<description>Far Object LOD Improvement Project (FOLIP) adds missing LOD models for objects that don't currently have them. This improves visuals and eliminates pop-in of objects at very little performance cost.</description> 
	<image path="images\banner.jpg" /> 
	<files> 
		<folder source="000 Core Files" destination="" priority="0" /> 
	</files> 
	<typeDescriptor> 
		<type name="Required"/> 
	</typeDescriptor> 
</plugin> 
```

Note that the children match what I described above.

However, the fourth and fifth plugins are incorrect:

```xml
<plugin name="I will use TexGen"> 
	<description>Select this option if you will use TexGen to generate the correct textures.</description> 
	<image path="images\TexGen.png" /> 
	<typeDescriptor> 
		<type name="Optional"/> 
	</typeDescriptor> 
</plugin> 
```

Note the required `files` element being missing. That is why the validation fails and the warning is shown. One can fix it by simply adding an empty `files` element:

```xml
<plugin name="I will use TexGen"> 
	<description>Select this option if you will use TexGen to generate the correct textures.</description> 
	<image path="images\TexGen.png" />  
	<files /> 
	<typeDescriptor> 
		<type name="Optional"/> 
	</typeDescriptor> 
</plugin> 
```

**Comment by m0lz** [comment]
Thank you @Infernio 
Will give the author a link to your fix advice.
