### ISSUE TITLE
PopupMenu Items StatusBar StausText

### ISSUE THREAD

**Issue by Metallicow** [wrye-bash/wrye-bash#68]
I did all these at one time but seem like that went missing somewhere...

All popup menu links should have a descriptive StatusText that shows in the statusbar.
Ex: Export>NPC Levels... has StatusText Help
but a lot of the others are missing on mouse hover/enter.

Need to go though and add them all again. Docstrings had a lot of this infos. Add them to links so the user know what an item will do.

This is a smallish simple repetitive task most anyone with basic python/wxPython exp can do.

**Comment by Infernio** [comment]
Hey, it's the first thing I did :)
Closed in 1b4f254275ee4861d61cdb4a92103ce7908c54e5.
