### ISSUE TITLE
Wrong arguments passed to _AVariableContainer.map_fids

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#683]
`TypeError: _AVariableContainer.map_fids() missing 1 required positional argument: 'map_function'`

https://discord.com/channels/537706885965676554/537710082755133460/1253637464749379665

May be a broken mod but whatever it might be we should not pass the wrong args there rather check before calling
map_fids and act accordingly. Not sure if a regression or bug yet

**Comment by Infernio** [comment]
I've seen that error before, it's almost certainly a bug (i.e. me screwing up :P).

**Comment by Infernio** [comment]
I'll take a look at this one this weekend, FO4 stuff is probably something only I can do.

**Comment by Infernio** [comment]
Quick scan over the code, I'd say I typo'd here:
https://github.com/wrye-bash/wrye-bash/blob/079fae30377c9a226e409b27058c62af325a60f7/Mopy/bash/brec/complex_subrecords.py#L2201-L2204

Note the `map_struct(val_struct, map_struct, save_fids)`, where I pass `map_struct` into itself (and don't pass along the actual mapping function, `map_function`!)
