### ISSUE TITLE
Linux: Wrye Bash launched as OblivionLauncher fails to detect game path

### ISSUE THREAD

**Issue by PimpOfSune** [wrye-bash/wrye-bash#686]
### Latest Nightly

- [ ] I have tried the latest nightly build and the issue still occurs.
- [x] As a mere user I don't have much time (and maybe skill) for experimenting with bleeding-edge versions.

### Asking on Discord/AFKMods

- [ ] I have asked on Discord/AFKMods and gotten the go-ahead to post this issue.
- [x] Discord is out of questions. As of AFKMods, I'd prefer being here as reporting bugs for Linux version of Steam GitHub account is needed anyway.

### BashBugDump

```
https://gist.github.com/PimpOfSune/32fa2dd4a03d8062102b6455dff04441
```

#### Description
Ubuntu 24.04.1 x64, Linux version of Steam (non-Flatpak, non-Snap), Oblivion installed with default compatibility settings.
Original OblivionLauncher.exe , obse_loader launched as OblivionLauncher.exe and BOSS launched as OblivionLauncher.exe can detect game's folders just fine.
Wrye Bash can't.

#### Step-by-step reproduction
1. Install Steam.
2. Install Oblivion.
3. Run Oblivion from Steam Library once.
4. In launcher, flip few options.
5. Advance from launcher to starting actual game, see that flipped options work and the game works.
6. Grab Wrye Bash v312.1 Standalone Executable from NexusMods.
7. Extract it.
8. Move Mopy folder content to Oblivion's folder.
9. Rename Wrye Bash.exe to OblivionLauncher.exe
10. Run Oblivion from Steam Library once.

ER
as per #243 , it works.
As we're technically running same (same-named) executable w/ same runner, we're 100% sure that the very same runner, its set of options, WINE prefix with all its stuff including Registry imitation, etc-etc-etc is being used.

AR
"Wrye Bash could not find a game to manage."

NB:
Is there any verbose mode I could activate for a more informative .log file? This doesn't look sufficient to understand what actually happened.

**Comment by llde** [comment]
Are you sure you setting the same wine prefix Steam use to load Oblivion? If you are using Linux Steam it's possible that the rpefix is different.
I'm using WB a lot from Linux,  and it works for me

**Comment by Infernio** [comment]
> bush.py  246 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
Wrye Bash could not find a game to manage. Make sure to launch games you installed through Steam once and enable mods on games you installed through the Windows Store.
>
> You can also use the -o command line argument or bash.ini to specify the path manually.

That tells you what's wrong. Wrye Bash looks for a game in several places. Most of them aren't relevant toyou, because you're using the Wine version (so the native Linux support won't work), leaving only three:
- bash.ini, you don't seem to have one, so skipped;
- `-o` CLI argument, not given, so skipped;
- parent directory of the executable; there's no game there, so skipped.

That leaves nothing to manage. Easiest way to fix this, if you insist on launching WB this way, is to add `-o` as a CLI argument:
```
%command% -o 'Z:\home\ya-nou\.local\share\Steam\steamapps\common\Oblivion'
```

**Comment by PimpOfSune** [comment]
Oh. So it's hardcoded to be one level below Oblivion.exe ("relative path" is ambiguous even for me, somehow). Being side by side with game's executable does not work - and whatever game detection method BOSS uses do not work either.
I love the direction in which Elder Scrolls modding scene moves.
Well... good to know. I'll probably stick with symlinks since I'll have to do a metric ton of jumps between different executables.
