### ISSUE TITLE
wrye-bash-wizards repo

### ISSUE THREAD

**Issue by Metallicow** [wrye-bash/wrye-bash#73]
There was talk about making an online repo for install wizards back around when the refactor was originally brought up.
Basically now that we have everything moved to github, this should be real easy to do.
And github would be a great place for it anyway, since it's easy for folks to submit different types of stuff here.

This would provide a ideal spot for different mods with/without wizards for packages to have helpers write for mod authors/etc/create a nice goto database, and also be regulated by us generally for cleanliness(whitespace, optimized images, ugly code, etc) with what comes in/out, that way the user always gets a quality product.
This also would provide users/authors vastly unlimited examples to learn from also(a real example is always the easiest to learn from).

A small tool/plugin could be written that parses the page code and with a search filter, users would be able to look at what is available for a game/mod without too much hassle.

Make a repo suggested name(wrye-bash-wizards)
with the directory structure like this basically(I think this was all we really needed anyway) Does this look ok?

```
Oblivion(directory)
    ModName-NexusId(directory)
        wizard.txt
        screenshot.png or Wizard Images/images*.ext
EtcGameName(directory)
    ModName-NexusId(directory)
        archive basic contents
```

and maybe some other helper content, such as a package structure or something.

This is something that could be started easily now and added to bit by bit as we go(I know I will be writing some for new mods when I get back around to actually playing)

I'd just like to refresh myself on what exactly all might be needed before going ahead and creating a structure that might need change later because of hindsight. So lets decide on a futureproof structure first.
@lojack5: Basically the majority of the wizard stuff was mostly your code as I recall, so what do you think on this and If anything you might be planning on changing in this area, that might apply here...
I'd view this as a small side project that could be worked on here and there until It stabilizes as I am tooling though my backups atm.

**Comment by Utumno** [comment]
Definition of back burner
