### ISSUE TITLE
Add launcher for LOOT

### ISSUE THREAD

**Issue by Ortham** [wrye-bash/wrye-bash#81]
Since BOSSv3 is now LOOT, the BOSSv3-related changes to BOSS's launcher should be undone, and a new launcher added for LOOT. @lojack5, do you have any pointers of what would need to be added for a new launcher?

The BOSSv3 masterlist/userlist locations should also be updated to point to the LOOT locations. Replacement of the API isn't part of this issue, since it works well and IIRC there haven't been any relevant changes in LOOT since the API revision Bash has.

**Comment by WrinklyNinja** [comment]
Closing this as I think having a shortcut in Bash's apps directory is a better solution to adding code for specific launchers, and it works (you just need to manually disable Lock Load Order if it's enabled before running LOOT).

**Comment by Utumno** [comment]
Yep - although when dust settles I still find the idea appealing of having a BOSS like button that calls LOOT functions - without launching LOOT's UI - dunno if possible still but it would be a good idea. Especially setting the LO

**Comment by Utumno** [comment]
So marking as won't fix rather than rejecting - also interesting ideas by Loajack above - binning most of our tools will take some really ugly code with it apart from the pngs

**Comment by WrinklyNinja** [comment]
> Yep - although when dust settles I still find the idea appealing of having a BOSS like button that calls LOOT functions - without launching LOOT's UI - dunno if possible still but it would be a good idea. Especially setting the LO

That could be done using the LOOT API (which has grown a lot for the upcoming v0.11.0 release, now the LOOT application is built on top of it - I'll probably submit a PR updating it for Bash post-release).

**Comment by Utumno** [comment]
>  I'll probably submit a PR updating it for Bash post-release

That would be grand

**Comment by Infernio** [comment]
Has come up a few times now and the dust has long since settled, so reopening.
