### ISSUE TITLE
Rework the Plugin Checker to warn about more advanced types of problems

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#83]
The plugin checker (previously called 'mod checker', but we're trying to get away from terms like 'mod' and 'espm') is quite useful already. It includes a function to check for deleted references, which needs to load the plugins to do its thing. We can piggyback off of this and do more general analysis to check for more problems. In the end, the plugin checker should be able to check for:
- Corrupted plugins
- For SSE and games based on it, plugins with Form Version <=43
- Deleted references
- Deleted navmeshes
- Deleted base records
- HITMEs
- Record type collisions
- Probable injected collisions

While retaining all of its original analysis capability, i.e. being able to check for:
- ESL-capable plugins
- Incorrectly ESL-flagged plugins
- Mergeable plugins
- Deactivate-tagged plugins that are active
- MustBeActiveIfImported-tagged plugins that are imported, but inactive
- Plugins with missing masters
- Plugins with delinquent masters, i.e. masters that load after their dependents
- Cleaning information retrieved from LOOT

Original issue desciption:
> re: [this discussion](http://forums.bethsoft.com/topic/1482255-relz-wrye-bash-thread-99/page-4#entry23570417)
>
> Item Interchange had an NPC_ record with the same FormID as a masters's REFR record.  This caused a crash of CBash when building the Bashed Patch.
>
> Might be nice to have the ModChecker do record type checks against masters/children mods to detect this sort of thing.  Possibly have the check in the Bashed Patch building process, however that may add a lot of overhead.

**Comment by Infernio** [comment]
Scratch that, see https://github.com/wrye-bash/wrye-bash/issues/480#issuecomment-807548428 and https://github.com/wrye-bash/wrye-bash/issues/480#issuecomment-807588432.
Will be part of the Mod Checker instead of the BP.
