### ISSUE TITLE
BashMon is not launched via the Toolbar correctly.

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#84]
The command line switch to start BashMon is `--bashmon`.  However, when Bash is launched like this, it still needs to be able to find Oblivion.  Also,in the code for the button, it's specifically launched via `Wrye Bash Launcher.pyw`, which obviously won't work for the Standalone version.

So things that can cause the button to not work at all:
- Running Wrye Bash Standalone
- Having both Skyrim and Oblivion installed and automatically detected by Bash (it can't decide which game to manage at startup of BashMon).  This one is easily fixed by adding  `-g oblivion` to the code that launched BashMon
- Having Oblivion not detectable without extra command line arguements.  I.E, if you have to launch Wrye Bash with the `-o` argument to specify the path to the game to manage, this is not further passed on to BashMon, so BashMon cannot find the game.

Currently, I advised a user to create a custom shortcut that will handle this for him, until the issue is fixed in the code: [Error report](http://forums.bethsoft.com/topic/1482255-relz-wrye-bash-thread-99/page-6#entry23607085)

**Comment by Utumno** [comment]
@lojack5: could you take care of this one ?

**Comment by Utumno** [comment]
bashmon goes to backburner for now
