### ISSUE TITLE
BashMon has Unicode handling errors.

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#85]
Most likely introduced when the rest of Bash was updated to handle Unicode correctly, BashMon has Unicode encode/decode errors when attempting to swap faces (and most likely in other bashmon functions as well):

[Error report:](http://forums.bethsoft.com/topic/1482255-relz-wrye-bash-thread-99/page-6#entry23611360)

```
Traceback (most recent call last):
File "bash\bashmon.pyo", line 306, in monitor
File "bash\bashmon.pyo", line 233, in swapPlayer
File "bash\bosh.pyo", line 13877, in save_setPlayerFace
File "StringIO.pyo", line230, in write
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbe in position 0: ordinal not in range(128)
```

**Comment by Utumno** [comment]
Closing this as it is not a Bashmon thing - it is a face import thing and probably fixed in https://github.com/wrye-bash/wrye-bash/commit/6b63bbb2f1afed8aed2ed43e3efcecb68d9525a2 - see #196
