### ISSUE TITLE
Restriction On Executable

### ISSUE THREAD

**Issue by louy2** [wrye-bash/wrye-bash#86]
Wrye Bash refuses to install executable into the game folder, and also refuses to track folders other than the commonly used ones. Thus it cannot manage in my case, FNIS and Bodyslider, of which former is almost a universal prerequisite for any animation mods, and latter is a popular female body mesh and texture replacer generator. 

What's your opinion on this restriction?

**Comment by Infernio** [comment]
Superseded by #501.
