### ISSUE TITLE
BAIN is no longer auto-annealing even with the setting enabled (possibly resolved)

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#93]
[svn](https://sourceforge.net/p/oblivionworks/bugs/255/)

When updating a mod with a new version, it is standard practice to anneal it into place. This should be updating not only its own status, but the status of other mods above it in the package order.

The only time this should NOT happen is when auto-anneal is turned off.

However, the problem is that the setting is being completely ignored. Annealing a mod results in several mods above it in the package order changing their highlight colors. Hovering over them indicates Bash thinks they need to be annealed too.

This happened in a recent SVN update. Release version 303 does not exhibit this behavior.

**Comment by Utumno** [comment]
@Arthmoor found a reproducer for at least an anneal failure: install a mod from an installer, go to mods tab, edit its description, go to installers tab, refresh data, see the installer turn orange, right click Anneal does nothing.

Present at 305 - can you reproduce ?

**Comment by Arthmoor** [comment]
Would this not be expected behavior? You've caused the CRC of the file to change by doing this. BAIN is not supposed to overwrite something you've manually changed after installing it.

**Comment by Utumno** [comment]
@Arthmoor Thanks for clarifying - expect some more :)

**Comment by Arthmoor** [comment]
Just wanted to ping this again to mention it still happens, with less frequency than before, but it still comes up from time to time. Still not able to get a proper reproduction scenario up.

Since nobody else seems to be having the issue I'd say bump this to 307. There's no need for this to hold up 306.

**Comment by Utumno** [comment]
Well I have been shufflingg BAIN core for some time now and maybe its' time to revisit this - especailly after latest changes to override skips mechanics - give it a whirl: https://github.com/wrye-bash/wrye-bash/archive/utumno-refresh-checks-data.zip

**Comment by Utumno** [comment]
@Arthmoor I just pushed a fix commit that may be related, involving duplicating an installer (was buggy). Does this still occur ?

**Comment by Arthmoor** [comment]
Missed this back in May. Yes, it still happens, but I don't think holding up 307 for this is prudent.

**Comment by Utumno** [comment]
Any reproducer ? In particular are skip options involved ?

**Comment by Utumno** [comment]
@Arthmoor - next time you run into this please keep an eye open for skip options AND case sensitivity issues - that is if the package contains item sthat are in a different case inside the Data dir

**Comment by Arthmoor** [comment]
It still occasionally happens, but I've never been able to figure out how to properly reproduce it so it may as well stay closed until such time as that happens. Case sensitivity issues in the archive seem like the most likely candidate though.

**Comment by Utumno** [comment]
Well next time it happens (on the wip) please post me the exact files and rest of info (as in the case of the forum posts I linked above) :)
