### ISSUE TITLE
Ini Tweaks throw an Exception under Japanese Locale

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#97]
[svn](https://sourceforge.net/p/oblivionworks/bugs/264/)

OP - Daidalos:
Having the system locale set to Japanese causes an exception when creating a ini tweak and makes the ini tab disappear.

For details see [this post](http://forums.bethsoft.com/topic/1459790-relz-wrye-bash-thread-31/page-2#entry22783786).

Toxic:

> More information: http://forums.bethsoft.com/topic/1459790-relz-wrye-bash-thread-31/page-5#entry22796297

**Comment by Utumno** [comment]
Move to the backburner till a proper reproducer comes about

**Comment by Infernio** [comment]
Feel free to reopen and re-label if one ever does come along :P
